### ISSUE TITLE
Sudo Support for Notifications

### ISSUE THREAD

**Issue by TechIsCool** [jimsalterjrs/sanoid#10]
I would like to see sudo support added for the notifications section. The reason for this is ZFS on linux already supported the read only zfs commands with Sudo and my nagios user does not have access to zfs without sudo.

Line I have changed are
https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L488
https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L744
https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L792

Hope this make sense.

**Comment by jimsalterjrs** [comment]
The way I handle this is putting wrappers in the a "sudo" directory under Nagios' plugins directory, and then giving NOPASSWD access to that directory only to the Nagios user.

`nagios ALL=(ALL:ALL) NOPASSWD: /etc/nagios/nrpe.d/plugins/sudo/*`

    #!/bin/sh
    # /etc/nagios/nrpe.d/plugins/sudo/check_sanoid_pools
    #!/bin/sh
    
    /usr/local/bin/sanoid --monitor-health
    exit $?

and

    #!/bin/sh
    # /etc/nagios/nrpe.d/plugins/sudo/check_sanoid_snapshots
    
    /usr/local/bin/sanoid --monitor-snapshots
    exit $?

**Comment by TechIsCool** [comment]
Makes sense and is a good workaround to make the script updatable while still not requiring sudo to function.
