### ISSUE TITLE
Major engine redesign: Daemon mode?

### ISSUE THREAD

**Issue by jimsalterjrs** [jimsalterjrs/sanoid#100]
I'm opening this issue as a chance for the community to weigh in on possibly reimplementing Sanoid as a daemon rather than a process invoked repeatedly from cron.

Doing this would make it easier to implement arbitrary period frequencies from configs - for example some users want weekly intervals, others want *much* more frequent intervals.  It would also solve at a stroke the issue ( e.g. #75 ) some users of heavily loaded systems have where multiple Sanoid processes somehow managing to take the "same" periodic snapshot within a few seconds of one another.

Running as a daemon, Sanoid would be able to simply schedule new snapshots into the future, sleeping until a few milliseconds before the time to take the desired snapshot, then waking up to take the snapshot, checking its calendar to figure out when the next snapshot should be taken, then going back to sleep until it's time to take (or purge) the next snapshot. It wouldn't *ever* need to invoke the potentially heavy/IO operation of listing all snapshots on the system again after first being loaded, unless it needed to be reloaded due to a system reboot, crash, or possibly a sanoid.conf change.

There would also be a --watchdog mode, which could be invoked from cron as frequently or infrequently as desired, which basically just checked to make sure the Sanoid daemon was running, and restart it if it isn't.  --watchdog might also check to see if the most recent snapshots were fresh (within policy interval) or stale (not as recent as they should be) and additionally try to mail a user or otherwise generate an alarm if not.

The Nagios plugin functionality (--monitor-health and --monitor-snapshots) would remain unchanged, and would still be the most recommended method for monitoring Sanoid's functioning.

Tagging @STRML here since I know it's relevant to his interests. Also tagging @redmop, @tmlapp, and @0xFate as former contributors.

**Comment by STRML** [comment]
Regarding `--watchdog` (or perhaps `--check`, since watchdog implies a daemon to me), this seems like the kind of thing that could be helped via Monit or Nagios; however I do like the idea of an out-of-band verification step because, indeed, these are backups and I want to be sure.

Other comments in https://github.com/jimsalterjrs/sanoid/issues/8#issuecomment-313952768.

**Comment by jimsalterjrs** [comment]
Regarding your question about complexity: yeah, it's complex; I'd probably be rewriting half the codebase.

A cron-style config would probably be good for defining intervals, but would only be necessary for users who wanted to define their own custom intervals; most would still be using pre-defined intervals from the `defaults` file.

An "every 5 second" interval might look like:

````
[period_5000ms]
    snapshot_frequency = "*/12 * * * * *"
`````

Where, obviously, there's an extra place in there for seconds, not just minutes. Actually parsing it shouldn't be that hard; Perl has some pretty robust time-handling routines built in to abstract away the pain of figuring out how long it is between now and the next Monday at 08:00:05 Zulu time, or what have you. =)

We could even parse an entry with only five places instead of six by simply dropping the seconds entirely and beginning with minutes, like a "normal" crontab, to minimize the potential for user confusion.

I think the real issue here for you is how quickly you want your personal fix, vs how much you'd like to have everything all happen in one place (and all your features to be in mainline, rather than in a custom one-off). The real issues for the rest of the userbase are whether they're willing to trust a daemon mode, and whether they're willing to potentially have a config-breaking update in exchange for the pretty clear benefits we'd get out of the change.  (I'm not 100% sure I can make all this happen without breaking existing config specifications to some degree.  I *might* be able to, and I'd damn sure *like* to, but...)

**Comment by jimsalterjrs** [comment]
For your desired frequency, @STRML, I think you're still stuck with a daemon whether you like it or not, and whether it's Sanoid or a separate, simpler thing entirely.  The system load and potential for conflicts from firing up a new Sanoid process every five seconds are probably not going to be reasonable.

**Comment by STRML** [comment]
Understood re: the issues of running frequent-cron and starting up so many Sanoid processes. In a high-frequency snapshotting mode there may not be a better way.

Eventually, the goal would be for this to interact with Syncoid in such a way that we could keep a persistent tunnel open and essentially stream live fs updates to a remote host, snapshots and all, like the Oracle ZFS appliance.

Also - it appears znapzend does a daemon in a similar fashion: https://github.com/oetiker/znapzend/blob/master/doc/znapzend.pod

**Comment by ewwhite** [comment]
For what it’s worth, I use Monit and Syncoid to run 15-second replication intervals between local and remote appliances.

Please see: https://serverfault.com/a/842740/13325

--
Edmund White
ed@ewwhite.net
847-530-1605

**Comment by jimsalterjrs** [comment]
@ewwhite Syncoid is considerably lighter-weight to fire up, partly because it doesn't need to parse every single snapshot on a system. =)

I'm really glad you've published your results with the frequent replication, though! It's something I've been "interested in but unwilling to devote time to experimentation with personally, at least yet" for quite a while, so seeing your results is much appreciated.

**Comment by STRML** [comment]
I've given znapzend a try - so far it fits our needs quite well and in combination with a long-lived SSH session (autossh + ControlMaster) we're able to replicate 5-second snapshots with minimal CPU usage or latency. Quite impressive.

Given that znapzend exists, I am not sure if rewriting sanoid makes sense. It is a simpler project, and in that sense it fills a unique niche.

**Comment by testbird** [comment]
It may be easier to let sanoid/pyznap keep a table of scheduled snaps to work around the problems (like small time deltas and transmissions taking longer than the interval) than to implement a deamon mode. Especially if you also consider machines that are not running 24x7 and use the anacron daily/hourly mechanism.
https://github.com/cythoning/pyznap/issues/3
