### ISSUE TITLE
RPM spec file is stale

### ISSUE THREAD

**Issue by thirtythreeforty** [jimsalterjrs/sanoid#101]
I'm not sure how to use the provided spec file to build an RPM package. It seems to be maintained, but it looks like it's referring to patches that don't exist and a nonexistent `https://github.com/jimsalterjrs/sanoid/archive/sanoid-master.zip`.

How can I build correctly versioned RPM packages?

**Comment by jimsalterjrs** [comment]
I wish I could help, but I'm not a RHEL/CentOS/Fedora person and don't know anything about building RPMs.  If you look at the authorship of the spec file, you might try tagging whoever contributed it by username to see if they'll come to the rescue.

**Comment by thirtythreeforty** [comment]
Gotcha; I'm no expert either.  Seems that @tmlapp originally wrote it.

**Comment by tmlapp** [comment]
I have neglected the spec file for quite a while. I updated it and pushed a new branch to my fork. https://github.com/tmlapp/sanoid/tree/rpmdev

- Go ahead and clone that
- Copy the sanoid.spec file to your SPEC dir
- run `spectool -g -R /path/to/your/SPEC/sanoid.spec` to download the source file
- run `rpmbuild -bb /path/to/your/SPEC/sanoid.spec` to build the rpm

This should build fine on Fedora >20 and RHEL/CentOS

I'll put in a pull request shortly.

Thanks

**Comment by jimsalterjrs** [comment]
@tmlapp don't know if it changes things any, but I pushed some new updates to syncoid since your comment here.

**Comment by tmlapp** [comment]
@jimsalterjrs 

It doesn't really affect things too much, but when you bump a version can you be sure to include tagging it? That way it can be downloaded via the version tag.

I'll bump the version in the spec file to 1.4.11 and then submit a pull request.

Thanks

**Comment by thirtythreeforty** [comment]
Thank you both for the attention to this! @tmlapp I didn't see the branch on your fork, but I'm content to wait if you're planning to PR it soon.

**Comment by jimsalterjrs** [comment]
@tmlapp I am trying to get better about that, I swear!

I didn't tag yet because, well, I wasn't done bumping versions yet; today saw a whole bunch of commits.  I think things are going to die down for the evening, so I'll go do a new release now.  Please let me know if making the release doesn't actually accomplish what you're looking for; I'm still not exactly the world's foremost github expert! =)

**Comment by tmlapp** [comment]
@jimsalterjrs  No problem. I fight with git/github everytime I use it.

@thirtythreeforty  I was trying to keep up with the multiple releases and things just started getting messy. I'll get it pushed up soon and a pull request to Jim.

Thanks guys.

**Comment by tmlapp** [comment]
@thirtythreeforty - I pushed my branch and created a pull request. The build process above should work with any tagged release in the repository (currently at 1.4.13)

Thanks.

**Comment by jimsalterjrs** [comment]
@tmlapp - I appreciate your efforts to make life easier for people in RH-land. =)
