### ISSUE TITLE
[syncoid] feature request: use guid property to identify matching snapshots instead of creation

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#103]
Yes I know, this is just a caprice and maybe nobody will run into issues because of this.
Just bringing it for the sake of correctness.

As far as I understand from looking at the syncoid code (I don't know perl and I find it's semantic very ugly to understand) it uses the `creation` property to check if a snapshot from source is the same with a snapshot in target.
The `creation` property is relative to the local system time (it is not set in UTC). This could lead to issues with snapshot creation during DST shifting.

I have stumbled upon this paragraph in the zfs manual:

> Native  Properties
> [...]
>      guid                  The 64 bit GUID of this dataset or bookmark which does not change over its entire  lifetime. When a snapshot is sent to
>                           another pool, the received snapshot has the same GUID. **Thus, the guid is suitable to identify a snapshot across pools**.

If I start to learn this bloody language, would a PR be accepted?

Thanks again for syncoid!

**Comment by jimsalterjrs** [comment]
I was unaware of the GUID property and I would _absolutely_ accept a PR that switched to using it instead of creation time to identify snapshots.  I've never been entirely comfortable with the way it's set up now; it just seemed like a good idea to use that in addition to the snapshot name, in case somebody got weird with things!

**Comment by jimsalterjrs** [comment]
You don't need to create a PR; I've already implemented this fix, and committed to master in 1.4.11. Thank you for the idea!
