### ISSUE TITLE
Feature Request: Pre/Post scripting

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#105]
With pre/post scripting, I can quince filesystems of VMs, rsync something, or pauses databases before the snapshots.

**Comment by redmop** [comment]
If the pre/post scripting are in the config sanoid.conf file, separate scripts can be made for each dataset, while using a wrapper around sanoid makes this very difficult as there isn't a way to "sanoid --dataset data/home" without making separate config directories.

**Comment by jimsalterjrs** [comment]
I'd like more detail on this, please.  I'm sympathetic to the desire for it, but not sure how - for example - such a pre/post scripting option would handle recursion into child datasets.  Would it run once on the parent only, would it run for the parent and for each child, or would it need its _own_ recursion to be configurable separately from the overall recursion policy for the parent dataset?

I'm blocking on this until I get some workable pseudo-config-code from you, along with explanations of what it would do.  I don't need actual programmatic stuff, and you don't have to be perfect or pretty with names of directives or arguments, I'd just like to see a mocked up `sanoid.conf` that includes the kind of thing you'd like to do, with explanations of what your mocked-up `sanoid.conf` is doing and how.

I don't think _I'll_ ever use this, for any number of reasons, but it would probably be a fairly popular option, so if you can come up with a logical syntax for this, I'm willing to implement it.

**Comment by redmop** [comment]
Using [BackupPC](http://backuppc.sourceforge.net/faq/BackupPC.html#_conf_dumppreusercmd_) as an example, why not do both?

sanoid.conf entry
```
[data/home]
     presnap=(run before any snapshots on this dataset)
     prechildsnap=(run before each child snapshot of that dataset)
     postchildsnap=(run after any snapshots on this dataset)
     postsnap=(run after any snapshots on this dataset)
```

Sanoid-run
```
process data/home
run presnap
run prechildsnap if recursive
take snapshot(s)
run postchildsnap if recursive
run postsnap
```

**Comment by jimsalterjrs** [comment]
This looks doable.  Might want to ping me if you don't see something on this in a few days (or, take a stab at it yourself and give me a PR to review).

**Comment by redmop** [comment]
I'll try to work something up this weekend.

**Comment by dkruyt** [comment]
Give for the postchildsnap the volume as an parameter back to the script. This way each cild can run a script with it own options.

volumes for recursion

/zfspool/container/nameserver
/zfspool/container/mailserver
/zfspool/container/webserver

```
[/zfspool/containers]
	use_template = containers
	recursive = yes
	process_children_only = yes
        prescript = /opt/scripts/prescript.sh <- will take the volumename as an argument and executed for each child.
        postscript =  /opt/scripts/postscript.sh <- will take the volumename as an argument and executed for each child.
```

**Comment by discostur** [comment]
anything new here when the feature will be merged into main? ;)

**Comment by benyanke** [comment]
Would also find this very useful for pausing VMs / stopping containers, etc.
