### ISSUE TITLE
Feature Request: Syncoid Compression

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#107]
Parallel compression for slow links is sexy. lzop is awesome for LAN. pigz for WAN links because more compression will speed the transfer rate, especially during the day when I limit bandwidth to 5 mbps. My [sanoid repo](https://github.com/redmop/sanoid/blob/redmop-patch-1/syncoid) has MANY compression types in it, but it's pretty ugly and I've not tried to do it a better way yet. Soon. I may just aim for adding pigz (which I will use) and then switches for custom ones.

**Comment by jimsalterjrs** [comment]
Implemented in 1.4.10 in master as `--compress=pigz-fast` for `pigz -3` and `--compress=pigz-slow` for `pigz -9`.

How useful that is will depend wildly on the available link speed and CPU types for an individual user.  Default compression remains `lzop` for remote replication and (forced) `none` for local replication.
