### ISSUE TITLE
Feature Request: Separating expiring and taking of snapshots

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#109]
Freeing up snapshot space takes IO. Soemtimes, I want that after hours. Sanoid can do it with some monkey business, znapzend can't do it at all. zfsnap does this very well.

**Comment by redmop** [comment]
Actually, this one isn't needed, I'm going to close it.

**Comment by jimsalterjrs** [comment]
What's the difference between "monkey business" and "very well" here?  Is the difference a code change, or merely a documentation enhancement?

**Comment by redmop** [comment]
Monkey business is doing this is cron
```
* * * * sanoid --cron --take-snapshots
0 0 * * sanoid --cron --purge-snapshots
```
aka separating them out. zfsnap does this by design as taking and purging snapshots are different commandlines.

**Comment by jimsalterjrs** [comment]
So how would you change that to make it "not monkey business"?  Seems fairly straightforward to me.

**Comment by redmop** [comment]
I might stick it in the config file.
