### ISSUE TITLE
SSH -o option needs multiple option expansion

### ISSUE THREAD

**Issue by jimsalterjrs** [jimsalterjrs/sanoid#117]
@hrast01's new `-o` argument in syncoid to pass options through to SSH only supports a single option.

SSH itself unfortunately requires multiple options to be specified `-o option1 -o option2`, not a more sensible `-o option2,option2`. We should accept `-o option1,option2` in syncoid, parsing them out to the format SSH requires along the way.

Current code needing patching begins at line 42 in v1.4.15.

~~~~
my $sshoption;
if (defined $args{'o'}) {
	$sshoption = "-o $args{'o'}";
	if ($sshoption eq "NoneSwitch=yes"){
		$sshcipher = ""
	}
} else {
	$sshoption = "";
}
~~~~

If anybody else wants to tackle this, I will accept clean pull requests.  Otherwise it goes into a fairly low priority "I'll get to this eventually" bucket.

**Comment by hrast01** [comment]
And because I can't leave well enough alone, #118 .

**Comment by jimsalterjrs** [comment]
thank you @hrast01, this looks good and worked well with both single and multiple options passed to SSH when I tested it.  accepted #118 into master.
