### ISSUE TITLE
Multiple Destinations

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#12]
Is it possible to have Sanoid send snapshots to different servers/locations on separate schedules? Say, every 15 min to an onsite server, and nightly to an offsite server.

**Comment by jimsalterjrs** [comment]
Sure - replication scheduling isn't actually handled within Sanoid itself; you just schedule it in cron.  Example:

````
*/15 * * * * /usr/local/bin/syncoid -r data/images root@onsitespare:data/images
0 1 * * * /usr/local/bin/syncoid -r data/images root@offsitedr:data/images
````

**Comment by redmop** [comment]
Awesome. Thanks for the help. :)
