### ISSUE TITLE
Syncoid Incremental Hangs at End

### ISSUE THREAD

**Issue by aberg83** [jimsalterjrs/sanoid#120]
I'm having an issue using Syncoid for incremental replications. Initial replication of all my datasets to another local pool on the same machine worked flawlessly. 20TB moved in about 12 hours (Wow!). However, trying to perform a second incremental replication on any of the datasets hangs at 99% or 100% complete. The console locks up and I have to reboot to kill the receive process. If I try to sync in a new SSH session while it is still hung, I get the following error:

Cannot sync now: XXXX is already target of a zfs receive process.

I'd really love to be able to rely on syncoid as it is a great piece of software. Any help is appreciated.

**Comment by jimsalterjrs** [comment]
How long did you give it before you started killing things? What you're seeing isn't a Sanoid issue, it's just what the tail end of zfs replication looks like sometimes. Until the last txg syncs, the receive (and the send piping into it) aren't going to go away, and syncoid can't exit. Depending on the receiving system and the size of the replication, this can sometimes be as long as several minutes of nothing seeming to happen at 100% as described.

IME *typical* hang times at the end are usually more in the 5-10 second range - if you get one at all - but like I said, you're just waiting for the last txg to sync before the process exits.

**Comment by aberg83** [comment]
It is hanging for significantly longer than 5-10 seconds. I've left it sit upwards of an hour and still no change.

**Comment by jimsalterjrs** [comment]
"Upwards of an hour" sounds buggy. You're going to need to look upstream to find answers, though - syncoid just wraps native ZFS replication and makes it command-line usable; all the heavy lifting happens inside the zfsonlinux project itself. Once replication actually *begins*, Sanoid's job is done - it's just `zfs send` on the source piped to `zfs receive` on the target.

I would definitely advise taking a look at `iotop` on the target before you start killing things next time, and maybe going ahead and opening a bug report at zfsonlinux while you can still pull the kinds of data they may be looking for.

FWIW, this is not a scale problem. 20T is a little larger than my most frequent replication tasks, but it's by no means the largest I've worked with, and it's not *much* bigger than my typical (usually anywhere from 5T-15T or thereabouts).
