### ISSUE TITLE
adding lz4 compression? 

### ISSUE THREAD

**Issue by devZer0** [jimsalterjrs/sanoid#123]
have a look at:
https://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO

seems that lz4 compression is slightly faster and decompression is MUCH faster than lzop.

zrep does have support for lz4, btw

**Comment by jimsalterjrs** [comment]
Have a look at the code, and implement a pipe through lz4 rather than lzop using --compression=lz4. (This should be really, really easy - take a look and you'll see how gzip, lzop, and pigz are currently handled.) Then issue a pull request. If your patch looks clean, I'll accept it into master.

**Comment by hrast01** [comment]
I've implemented this in PR #136.
