### ISSUE TITLE
After Syncoid ZFS volumes seem to take up more space on destination

### ISSUE THREAD

**Issue by deanroker123** [jimsalterjrs/sanoid#125]
Hi,
I am very impressed with sanoid and syncoid. They seem to work brilliantly.
I am a little confused though. My source pool shows 479GB used but the destination shows 650Gb used. The logicalused value for both is the same. Where has my missing space gone?
Both ends are set up the same with compression on at the root and a 4k record size.

Any ideas?

Thanks

Dean

**Comment by jimsalterjrs** [comment]
Are you removing older snapshots from the target? If you're not running 
Sanoid on the target, there's nothing there to prone old snapshots.


----------------

(Sent from my tablet - please blame any weird errors on autocorrect)

**Comment by deanroker123** [comment]
This is the first sync (but I am running sanoid in backup config). 

If i run zfs list -t snapshot each of the snapshots seems to take up more space than the related snapshot at the source.
The compressraio is 1.00 on the destination and 1.4 on the source. I think this could be why. The destination pool has compression set to on and shows it as being set for the dataset, should this be the same as the source?

**Comment by jimsalterjrs** [comment]
> The compressraio is 1.00 on the destination and 1.4 on the source.

That would certainly explain it.

> The destination pool has compression set to on and shows it as being set for the dataset, should this be the same as the source?

Syncoid will not set or unset any flags on the target; they remain the same as they were when last set directly (or inherited from the parent).

With that said, the compression flag does not affect data that's *already* been written - so if compression had been set on the target after several replications had already occurred, the data which had already written would *not* be compressed, even though the dataset showed compression being on.  *Further* writes to that dataset would be compressed.

Another possibility is if you have clones on the source. Syncoid's replication does not recreate parent/clone relationships from the source on the target; each dataset is replicated independently.  So if you had source/parent with snapshot @1, and source/child which was cloned from source/parent@1, on target you would have target/parent and target/child which were each 100% independent of one another, and would therefore take up more space.

**Comment by deanroker123** [comment]
Hi Jim,

I have deleted and resynced a few times and compression is definitely on
before the sync, and I haven't cloned anything.

I think there are 2 things going on. One of which makes sense but not the
other.

I have different ashift=9 on the source and ashift=12 on the destination so
i think when the blocks are replicated they only take up a small portion of
the actual target block?

But what I can't understand is if I rsync the file to a new dataset that
had compression set to on I still dont get any compression, but the same
dataset on the source gets 1.4x

Its driving me mad lol.

Thanks for the suggestions though.

Thanks
Dean

**Comment by valeech** [comment]
I can confirm this issue. Doing an initial sync the destination receives full data for clones and the origin is broken. 

So if you have clones chained off of each other, all clones on the destination will be full size and not linked!

SOURCE POOL:
https://pastebin.com/7dqX0qks

After running `./syncoid -r testpool root@desthost:testpool/testclient`

DESTINATION POOL:
https://pastebin.com/yHtrpy69

**Comment by ionutz22** [comment]
@deanroker123 this might be related to ashift=9 and ashift=12 and also depends on your pools layout (how many drives, is raidz, raidz2, mirrors, etc) as this can add the extra overhead.

see more: http://schalwad.blogspot.ro/2015/09/understanding-how-zfs-calculates-used.html

**Comment by phreaker0** [comment]
@deanroker123 It's the ashift values for sure, you said you have used a recordsize of 4k. With ashift 9 on the source the smallest block of data which can be written to disk is 512 bytes. So compression can be usefull here and apparently is with a factor of 1.4. On the target you have ashift 12 which means that the minimal block of data is 4k. So compression can't do anything here, therefore the 1.00 compression factor.
