### ISSUE TITLE
Feature request: Help text for the commands

### ISSUE THREAD

**Issue by LordAro** [jimsalterjrs/sanoid#128]
Having to go back to the readme to find which flags each command supports is a bit tiresome, especially when it's incorrect (syncoid doesn't have a --verbose flag) or missing entirely (findoid)

Be good to have a -h/--help flag for all of the commands

**Comment by jimsalterjrs** [comment]
If you implement one that's clean and relatively easy to maintain, I'll accept a PR.

**Comment by LordAro** [comment]
I'll see what I can come up with. Are you opposed to GetOpt::Std/Long ?

**Comment by jimsalterjrs** [comment]
I kinda prefer to avoid pulling in more CPAN dependencies than I absolutely have to, because it makes installation that much more of a pain. Can you make a brief case for it with examples? If it saves enough work / makes the code enough more maintainable, I'll consider it.

**Comment by LordAro** [comment]
well, GetOpt::Std/Long are in the standard library, (as i understand it, I'm not a huge perler)
If I wanted to go outside the STL, I'd want something like ArgParse or DocOpt :)

**Comment by jimsalterjrs** [comment]
Oh! If they're in the standard library and don't require installation from CPAN, then yes, I'll almost certainly accept them.

Can you please figure out how to neuter your editor's aggressive cosmetic changes, though? I really don't want to accept a PR that appears to modify several hundred lines of code that have nothing to do with the actual patch being made.
