### ISSUE TITLE
Separate scheduling of snapshot cleanup

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#13]
Is it possible to schedule removing of snapshots at a later time, such as after hours, instead of doing them during the day?

I'm using zfSnap and I have it making snapshots every 15 min, hourly, daily, and weekly, and I have it only removing snapshots at 12:05a daily.

**Comment by jimsalterjrs** [comment]
It's not possible the way Sanoid is currently set up, and honestly I don't see a good reason to do it - removing snapshots does not impact the system noticeably when they're removed on a regular schedule, even on relatively lightweight systems with low RAM and slow rust drives.

If this is something you're dead set on, we could discuss it as a commissioned feature.  If implemented, it would basically just mean an argument to cause Sanoid to skip thinning, so you'd end up with a crontab like this:

~~~~
*  7-17 * * * /usr/local/bin/sanoid --cron --no-thinning
*   0-6 * * * /usr/local/bin/sanoid --cron
* 18-23 * * * /usr/local/bin/sanoid --cron
~~~~

**Comment by redmop** [comment]
I've had issues with it before, though it has been a while, 0.62, I think. I'll try it this weekend.
I look at the code, and it is almost there. Would you be open to a patch, should I decide to work on it?

**Comment by jimsalterjrs** [comment]
Always. :-)

----------

(Sent from my phone - please blame any weird errors on autocorrect)

**Comment by redmop** [comment]
Actually, this already exists, it just needs a little massaging.
* * * * * sanoid --take-snapshots
0 0 * * * sanoid --prune-snapshots

**Comment by jimsalterjrs** [comment]
closing - if you want to make a pull request, you can reopen.
