### ISSUE TITLE
syncoid --no-sync-snap --quiet not quiet

### ISSUE THREAD

**Issue by jasonblewis** [jimsalterjrs/sanoid#132]
`syncoid --no-sync-snap --quiet` is not quiet and outputs something to stdout.

```
root@quartz:~# syncoid --no-sync-snap --quiet tank/home root@backup:tank/backup-quartz-tank-home
NEWEST SNAPSHOT: autosnap_2017-08-11_14:00:01_hourly
root@quartz:~# 
```

I expect that `--quiet` shouldn't output anything unless there is an error.

**Comment by jasonblewis** [comment]
Syncoid version: 1.4.16

**Comment by jimsalterjrs** [comment]
Thank you for the report! I'll add an if check in there to make sure it doesn't run its mouth if --quiet is set soon.
