### ISSUE TITLE
Feature Request: Option to bypass root check in Syncoid

### ISSUE THREAD

**Issue by lopsided98** [jimsalterjrs/sanoid#139]
It is possible to allow syncoid to operate without running as root or using sudo by using ZFS delegated permissions.

If you are using the `--no-sync-snap` option, this requires the `hold` and `send` permissions to be delegated to the syncoid's user for the source dataset, and the `create` , `mount`, `receive` and `rollback` for the destination dataset,  Without that option, you might need a few more, such as `destroy`.

The problem is that syncoid tries to run commands with sudo if it is run as a non root user. I would like an option that bypasses the root check and makes syncoid assume it has the permissions it needs.

**Comment by phreaker0** [comment]
linked PR was merged, will be in the next release
