### ISSUE TITLE
Having trouble with syncoid error on line 787

### ISSUE THREAD

**Issue by ledoktre** [jimsalterjrs/sanoid#143]
I have 2 servers in this little lab.  I run KVM on both servers, have raid-z (3 x SSD) and mirror (2 x 4TB) on each.  I have each configured with sanoid to create snapshots as well.

My intended use case is to syncoid all of rpool0 on vserver1 to rpool1/backup/vserver1 on both boxes, and likewise all of rpool0 on vserver2 to rpool1/backup/vserver2 on both boxes.

Two issues with my little plan thus far.

1. When I issue syncoid "recursively", I end up with errors on subsequent runs :

**_could not find any snapshots to destroy; check snapshot names.

CRITICAL ERROR: Target rpool1/backup/vserver1/pool0 exists but has no snapshots matching with rpool0/pool0!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target._**

I figured out that this is because rpool0/pool0 are not included in sanoid, but subfolders are.  This is where I create folders for the virtual machines and store the qcow2 files.  This behaviour also happens on /var/tmp, which I am not including in sanoid either.  For now, I just wrote a little bash script to syncoid just the folders that have snapshots.  The error went away, but optimally I would like to just use recursive?

2. I am now getting a different error, and it appears to be when using syncoid to transfer to the opposite box, though I am not sure if that part is pertinent.  Error :

_**WARNING: /usr/bin/ssh  -c chacha20-poly1305@openssh.com,arcfour -p 11022 -S /tmp/syncoid-root-root@10.4.8.12-1504656237 root@10.4.8.12 " /sbin/zfs destroy rpool1/backup/vserver1/var@syncoid_vserver1_2017-09-05:19:03:42;  /sbin/zfs destroy rpool1/backup/vserver1/var@syncoid_vserver1_2017-09-05:18:57:44" failed: 256 at /opt/apps/sanoid/syncoid line 787.**_

I probably get 6 of them every time I run the script.    I have no idea what is causing that.  

Any help would be most appreciated.

Thanks,

**Comment by ledoktre** [comment]
Appears on issue 2 above it is not just over SSH.  Here is another error but local :

_**WARNING:   /sbin/zfs destroy rpool1/backup/vserver1/var/spool@syncoid_vserver1_2017-09-05:19:04:03;  /sbin/zfs destroy rpool1/backup/vserver1/var/spool@syncoid_vserver1_2017-09-05:19:03:47 failed: 256 at /opt/apps/sanoid/syncoid line 787.**_

**Comment by jimsalterjrs** [comment]
First things first: if you're getting an error 256, I believe you're using an older version of Syncoid.  Update that first, and then let's try again, please.

Also, when pasting in errors, please paste the actual command being run as well as the error message.

**Comment by ledoktre** [comment]
For the error 256, I cloned maybe about a week ago, a tad longer.  According to VERSION on both boxes, both are 1.4.16?  I'll check to see if there is a recent update.

On the other, the command I am using is one of these two : 

/opt/apps/sanoid/syncoid --recursive rpool0 rpool1/backup/vserver2
/opt/apps/sanoid/syncoid --recursive rpool0 -sshport=11022 root@10.24.28.11:rpool1/backup/vserver2

This is run from vserver2, first line intending to sync to a second pool locally, second intending to backup same datasets to a secondary pool on the opposite box. 

Thanks,

**Comment by phreaker0** [comment]
@yilmazn please post the output of "sanoid -r --cron --debug"

**Comment by yilmazn** [comment]
[root@rdsski01 zfs_scripts]# zfs snapshot pool/ski@autosnap_2018-09-03_17:17:04_daily
[root@rdsski01 zfs_scripts]# 

[root@rdsski01 zfs_scripts]# zfs list -t snapshot pool/ski
cannot open 'pool/ski': missing '@' delimiter in snapshot name
[root@rdsski01 zfs_scripts]# 

[root@rdsski01 zfs_scripts]# zfs list -t snapshot pool/ski@autosnap_2018-09-03_17:17:04_daily 
NAME                                          USED  AVAIL  REFER  MOUNTPOINT
pool/ski@autosnap_2018-09-03_17:17:04_daily     0B      -   205K  -
[root@rdsski01 zfs_scripts]#

**Comment by phreaker0** [comment]
sry, the last command missed the "-r" flag, but you figured it out. This is weird, sanoid doesn't report any error on taking the snapshots but they aren't there? Which sanoid version are you using?

**Comment by phreaker0** [comment]
:-D just noticed you used "-r" option for sanoid, which probably translates to "--readonly" which explains the behaviour. Remove the flag and it will take snapshots :-)

**Comment by phreaker0** [comment]
I guess this is resolved? If not feel free to reopen.
