### ISSUE TITLE
critical error when receiving stream from 2 different sources at the same time

### ISSUE THREAD

**Issue by ionutz22** [jimsalterjrs/sanoid#145]
Hi,

I have the following situation:
nasA replicates data using syncoid from nasB and nasC via 2 different cron jobs at 30 minutes difference.
When first job takes longer (high amount of data to transfer or is an initial full sync as in example below) and the second starts while first is running I'm getting the following error, and the first job stops.

```
lzop: Inappropriate ioctl for device: <stdin>
cannot receive incremental stream: invalid backup stream
CRITICAL ERROR: /usr/bin/ssh -c chacha20-poly1305@openssh.com,arcfour -p 22 -i /root/.ssh/syncoid_id_rsa -S /tmp/syncoid-root-root@nasB-1504772734 root@nasB ' /sbin/zfs send -I tank/mydataset@autosnap_2017-06-12_10:35:01_monthly tank/nasB/mydataset@syncoid_nasA_2017-09-07:08:25:37 | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 1867556846592 |  /sbin/zfs receive -F tank/nasB/mydataset  failed: 256 at /usr/sbin/syncoid line 206.
```

I'm using syncoid 1.4.7 on CentOS 7, and cronjobs looks like:

```
jobb:
syncoid -r root@nasB:tank/mydataset tank/nasB -sshkey=/root/.ssh/syncoid_id_rsa
jobc:
syncoid -r root@nasC:tank/mydataset tank/nasC -sshkey=/root/.ssh/syncoid_id_rsa
```

Any idea how to fix this ?

**Comment by jimsalterjrs** [comment]
I'm not sure I'm following.  Where does nasC enter the equation? I just see two identical jobs doing a pull replication from nasB.

Also... did you type those in by hand, or are those the actual cron jobs?  Because they're bugged: you've got the source as `root@nasB:/tank/mydataset`, which won't work because there's a leading slash before `tank`.  ZFS paths (as opposed to filesystem paths) do not start with a leading slash.  So it should be `syncoid -r root@nasB:tank/mydataset tank/nasB` etc.

**Comment by ionutz22** [comment]
I've updated them; I've done some manual work as I replaced the real hostnames/datasets.
Both are cron jobs (basically a small shell script containing that command, and beside the command there is also a redirect to a log file: >> mylogfile  2>&1 ) .

**Comment by ionutz22** [comment]
Hi Jim,

Any thoughts on this ? this is annoying as I cannot run 2 syncoid jobs in parallel, even the source is 2 different servers.

Thank you.

**Comment by jimsalterjrs** [comment]
I don't know what's going on in your case; ZFS and syncoid both are perfectly fine with multiple receives to *separate* datasets; they only refuse to run with multiple receives to a *single* dataset.  Proof:

````
root@banshee:~/git/sanoid# zfs list -r banshee | egrep 'source|target'
banshee/source1                  523M  48.1G   523M  /banshee/source1
banshee/source2                  523M  48.1G   523M  /banshee/source2

root@banshee:~/git/sanoid# whenits -d now+5s syncoid root@localhost:banshee/source1 banshee/target1 ; whenits -d now+5s syncoid root@localhost:banshee/source2 banshee/target2

root@banshee:~/git/sanoid# zfs list -r banshee | egrep 'source|target'banshee/source1                  523M  47.1G   523M  /banshee/source1
banshee/source2                  523M  47.1G   523M  /banshee/source2
banshee/target1                  523M  47.1G   523M  /banshee/target1
banshee/target2                  523M  47.1G   523M  /banshee/target2

root@banshee:~/git/sanoid# cp /banshee/source1/512M.bin /banshee/source1/512M-1.bin ; cp /banshee/source2/512M.bin /banshee/source2/512M-1.bin

root@banshee:~/git/sanoid# whenits -d now+5s syncoid root@localhost:banshee/source1 banshee/target1 ; whenits -d now+5s syncoid root@localhost:banshee/source2 banshee/target2

root@banshee:~/git/sanoid# zfs list -r banshee | egrep 'source|target'banshee/source1                 1.02G  45.1G  1.02G  /banshee/source1
banshee/source2                 1.02G  45.1G  1.02G  /banshee/source2
banshee/target1                 1.02G  45.1G  1.02G  /banshee/target1
banshee/target2                 1.02G  45.1G  1.02G  /banshee/target2
````

**Comment by phreaker0** [comment]
@ionutz22 can you send debug output of a parallel run which fails?

**Comment by phreaker0** [comment]
@ionutz22 I guess your problem was resolved, if you still have the problem fell free to reopen and pls provide more debug information.
