### ISSUE TITLE
error at /usr/bin/sanoid line 335

### ISSUE THREAD

**Issue by emacsomancer** [jimsalterjrs/sanoid#147]
When I run `sudo sanoid --take-snapshots --verbose` I get:

`taking snapshot dozer/USERS@autosnap_2017-09-12_22:47:34_daily
CRITICAL ERROR: /sbin/zfs snapshot dozer/USERS@autosnap_2017-09-12_22:47:34_daily failed, -1 at /usr/bin/sanoid line 335.`

But if I run `/sbin/zfs snapshot dozer/USERS@autosnap_2017-09-12_22:47:34_daily` directly, the snapshot is created as expected.

**Comment by redmop** [comment]
You should post your sanoid.conf. I'm sure it will be asked for.



Shawn T Perry
Red Mop Computing Services
phone: 303-881-2623
email: shawn@redmop.com

**Comment by emacsomancer** [comment]
sanoid.conf:
```
[dozer/USERS]                                                                                                                                                  
        use_template = standard                                                                                                                                
[tank/ROOT/voidmusl]                                                                                                                                           
        use_template = standard                                                                                                                                
                                                                                                                                                               
                                                                                                                                                               
#############################                                                                                                                                  
# templates below this line #                                                                                                                                  
#############################                                                                                                                                  
                                                                                                                                                               
[template_standard]                                                                                                                                            
        recursive = yes                                                                                                                                        
        hourly = 24                                                                                                                                            
        daily = 10                                                                                                                                             
        monthly = 3                                                                                                                                            
        yearly = 0                                                                                                                                             
        autosnap = yes                                                                                                                                         
        autoprune = yes       
```

**Comment by vphan13** [comment]
I have the same issue. . slight different error message but it references the same line in the sanoid file

root@serverA agomez2]# /opt/software/sanoid/sanoid --take-snapshots --verbose
INFO: taking snapshots...
taking snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_12:47:57_daily
cannot create snapshot 'zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_12:47:57_daily': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_scale/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_12:47:57_daily failed, 256 at /opt/software/sanoid/sanoid line 335.


sanoid.conf

[zfs_A/archdata]
        recursive = yes
        hourly = 24
        daily = 14
        monthly = 3
        yearly = 1
        autosnap = yes
        autoprune = yes


[zfs_A/home]
        recursive = yes
        hourly = 0
        daily = 1
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes

**Comment by jimsalterjrs** [comment]
Whoa, that's weird - in yours it's trying to put a monthly and a daily 
tag on the same snapshot, so it's failing.

I can see you're using an older version of Sanoid since it's trying to 
exit 256; can you please update to today's latest and try again?

**Comment by vphan13** [comment]
I believe this is already the latest

[root@serverA /]# /opt/software/sanoid/sanoid --version
INFO: Sanoid version: 1.4.15

Was there any other logging you wanted?  I know if I removed the following snapshot it will probably work but I'd like a less disruptive option

zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly.  

Also this error prevents all snapshots of all datasets under zfs_A/archdata from being created

**Comment by jimsalterjrs** [comment]
Latest is 1.4.17.

**Comment by vphan13** [comment]
Newest version creates new snapshots but the majority of snapshot creation for datasets under zfs_A/archdata fails. . its trying to create snapshots from snapshots.  It seems to be random as far as what snapshots its trying to create new snapshots from

[root@ceres tmp]# /opt/src/sanoid/sanoid --cron
INFO: taking snapshots...
taking snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_daily
cannot create snapshot 'zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_daily': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_daily failed, 256 at /opt/src/sanoid/sanoid line 335.
taking snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_hourly
cannot create snapshot 'zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_hourly': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_hourly failed, 256 at /opt/src/sanoid/sanoid line 335.
taking snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_yearly
cannot create snapshot 'zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_yearly': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_yearly failed, 256 at /opt/src/sanoid/sanoid line 335.
taking snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_monthly
cannot create snapshot 'zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_monthly': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/0577@autosnap_2017-09-11_20:00:01_hourly@autosnap_2017-09-14_14:58:26_monthly failed, 256 at /opt/src/sanoid/sanoid line 335.
taking snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily
cannot create snapshot 'zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily failed, 256 at /opt/src/sanoid/sanoid line 335.
taking snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_hourly

**Comment by jimsalterjrs** [comment]
I wonder if it's getting confused by the underscore in your dataset name.

Would you be willing to temporarily rename the dataset to something 
without an underscore, to help isolate the problem?

**Comment by jimsalterjrs** [comment]
Oh lord, that's not a dataset, that's the /pool/ name. Still wonder if 
that could be the issue.

Would you be willing to export it and re-import it under an 
underscore-free name, for testing purposes?  I'm not suggesting you need 
to leave it that way to make Sanoid work, I'd just love to conclusively 
demonstrate whether that's what's causing the bug or not, so I know what 
I'm trying to fix.

````
zpool export zfs_A ; zpool import zfs_A zfsA
````

**Comment by vphan13** [comment]
Its been working since March with that name. . and I can create snapshots manually with zfs commands so I don't think that is it.  

I have an identical zfs host that receives snapshots from this one, I will see if I can replicate the issue on that host by enabling snapshot creation on it.

**Comment by jimsalterjrs** [comment]
Of course you can manually create snapshots... but you can't manually do it as pool/dataset@snap1@snap2, which is what's happening in Sanoid.  The question here is exactly what's screwing up Sanoid's internal logic to make it try to cram two names onto one snapshot, and I was asking if you'd mind temporarily changing the name to omit the underscore to see if that's it.

**Comment by vphan13** [comment]
That is going to be a very disruptive change at the moment. . I can tell you that this was working up until 9/12 at 5PM.  That was the last successful email in root's mailbox about the cronjob, and also the reason why I don't think the underscore in the pool name is the issue.  

Removing the source snapshots fixes the issue ie

zfs destroy zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly

takes care of the error below . . .

cannot create snapshot 'zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily failed, 256 at /opt/src/sanoid/sanoid line 335.

taking snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily
cannot create snapshot 'zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily': multiple '@' delimiters in name
CRITICAL ERROR: /sbin/zfs snapshot zfs_A/archdata/700040@autosnap_2017-07-01_00:00:03_monthly@autosnap_2017-09-14_14:58:26_daily failed, 256 at /opt/src/sanoid/sanoid line 335.


The problem is I have hundreds of errors like this. . I'd really like to know the root cause

**Comment by jimsalterjrs** [comment]
Pretty much got to be a regex issue, which is why I'm suspecting the 
underscore (since I've never seen this error before in years of operation 
on hundreds of machines... None of which had underscores in pool names).

It's ok I'll try to recreate on my end when I get a moment.

**Comment by vphan13** [comment]
so removing the problematic source snapshots allows for new snapshots to be created, but it breaks syncoid. . .as syncoid refuses to transfer snapshots to an existing dataset

I obviously cannot destroy the destination datasets. . I just want to copy all new snaps to it


[root@serverA tmp]# /opt/src/sanoid/syncoid --debug -r --compress=pigz-fast -c arcfour zfs_scale/archdata/0161 root@serverB:zfs_sdsc/archdata/0161
DEBUG: checking availability of /usr/bin/pigz on source...
DEBUG: checking availability of /usr/bin/pigz on target...
DEBUG: checking availability of /usr/bin/pigz on local machine...
DEBUG: checking availability of /usr/bin/mbuffer on source...
DEBUG: checking availability of /usr/bin/mbuffer on target...
DEBUG: checking availability of /usr/bin/pv on local machine...
DEBUG: recursive sync of zfs_scale/archdata/0161.
DEBUG: getting list of child datasets on zfs_scale/archdata/0161 using   /sbin/zfs list -o name -t filesystem,volume -Hr zfs_scale/archdata/0161 |...
DEBUG: syncing source zfs_scale/archdata/0161 to target zfs_sdsc/archdata/0161.
DEBUG: checking to see if zfs_sdsc/archdata/0161 on /usr/bin/ssh  -c arcfour -p 22 -S /tmp/syncoid-root-root@serverB-1505437193 root@serverB is already in zfs receive using /usr/bin/ssh  -c arcfour -p 22 -S /tmp/syncoid-root-root@serverB-1505437193 root@serverB /bin/ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "/usr/bin/ssh  -c arcfour -p 22 -S /tmp/syncoid-root-root@serverB-1505437193 root@serverB  /sbin/zfs get -H name zfs_sdsc/archdata/0161 2>&1 |"...
DEBUG: getting list of snapshots on zfs_scale/archdata/0161 using   /sbin/zfs get -Hpd 1 -t snapshot guid,creation zfs_scale/archdata/0161 |...
DEBUG: getting list of snapshots on zfs_sdsc/archdata/0161 using /usr/bin/ssh  -c arcfour -p 22 -S /tmp/syncoid-root-root@serverB-1505437193 root@serverB  /sbin/zfs get -Hpd 1 -t snapshot guid,creation zfs_sdsc/archdata/0161 |...
DEBUG: getting current value of -p used on zfs_sdsc/archdata/0161...
/usr/bin/ssh  -c arcfour -p 22 -S /tmp/syncoid-root-root@serverB-1505437193 root@serverB  /sbin/zfs get -H -p used zfs_sdsc/archdata/0161

CRITICAL ERROR: Target zfs_sdsc/archdata/0161 exists but has no snapshots matching with zfs_scale/archdata/0161!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

**Comment by emacsomancer** [comment]
@jimsalterjrs - do you have any thoughts on my original error?  I don't think it's the same issue as vphan's.

**Comment by jimsalterjrs** [comment]
Did you figure anything out, @emacsomancer?

**Comment by emacsomancer** [comment]
I'm not certain exactly, but I'm guessing it's an issue with Bedrock Linux and installing it in a non-root stratum.  So I don't think it's an issue directly with Sanoid.  (I've managed to install it in the root stratum in Bedrock and it seems to be working.)

**Comment by jimsalterjrs** [comment]
Interesting. Never even heard of your distro! :)

**Comment by emacsomancer** [comment]
https://bedrocklinux.org/ - it's essentially a 'meta-distro'.
