### ISSUE TITLE
Feature Request: raw sync (-w) for zfs send of encrypted at rest data

### ISSUE THREAD

**Issue by Laeeth** [jimsalterjrs/sanoid#150]
Raw sync enables sending zfs on linux encrypted at rest data to be kept in encrypted form when sending (the default is to unencrypt before sending).  This is enabled with the -w flag to zfs send (which I believe is harmless when sending unencrypted data sets).  It would be very helpful to have this feature as an option.  I'm experimenting now with hacking this into syncoid, but I don't really know perl.

**Comment by rcproam** [comment]
As of ZoL v0.7.3 I cannot tell if this feature has been implemented as the 'raw send' feature is not mentioned in any of the release notes?
https://github.com/zfsonlinux/zfs/releases

Also the command syntax / usage output of the zfs command in ZoL v0.7.3 does not list any "-w" option:
        send [-DnPpRvLec] [-[i|I] snapshot] <snapshot>
        send [-Lec] [-i snapshot|bookmark] <filesystem|volume|snapshot>
        send [-nvPe] -t <receive_resume_token>

The 'raw zfs send' feature should be amazing but it seems really poorly documented at present... which is maybe why it's not included in sanoid yet?

**Comment by phreaker0** [comment]
@rcproam encryption and raw send feature are not in any tagged release yet, only in the master branch for now.

**Comment by ronnyegner** [comment]
Raw send/receive is now in a tagged release:

https://github.com/zfsonlinux/zfs/releases

Would love to see support. I can also help with testing. Documentation is also improved a lot.

**Comment by phreaker0** [comment]
@ronnyegner i guess you mean the pre release 0.8.0-rc1 version?
It should be possible with this PR: #273

**Comment by ronnyegner** [comment]
@phreaker0 Yes, i meant 0.8.0-rc1. And the PR looks good. Altough it would be good to have a command line switch for it. But as long as it works...

**Comment by phreaker0** [comment]
follow up PR #295

**Comment by phreaker0** [comment]
#295 and (#343) were merged, so raw sends are possible now.

**Comment by geudrik** [comment]
Readme page doesn't include these changes, <3
