### ISSUE TITLE
Syncoid breaks with OpenSSH 7.6 due to full removal of arcfour cipher

### ISSUE THREAD

**Issue by lopsided98** [jimsalterjrs/sanoid#152]
OpenSSH 7.6 removes all support for the arcfour cipher, which causes it to die because arcfour is an unknown cipher. It seems like arcfour was disabled in the past, but it was still recognized, so it didn't cause a crash, but now it does because the code for arcfour was completely eliminated.

This can be worked around be specifying a new cipher list using the undocumented `-c` option, but it might be good to automatically handle this.

Possibly, arcfour could be dropped from the cipher list. Chacha20 support was added in OpenSSH 6.5, and all currently supported Ubuntu releases have at least 6.6. I don't know if there other older systems that need to be supported.

**Comment by jimsalterjrs** [comment]
#131 merged; this is fixed now. Thanks!
