### ISSUE TITLE
occasionally get lots of messages from cron about not finding snapshots

### ISSUE THREAD

**Issue by jasonblewis** [jimsalterjrs/sanoid#154]
Hi,

Occasionally I get 10-20 emails fron cron, all in the space of about 10 minutes about how sanoid could not find any snapshots to destroy.

I suspect this is happening when for some reason sanoid takes ages to finish, and the next cron run calls sanoid again while its still running.

errors like this:

```
could not find any snapshots to destroy; check snapshot names.
could not remove tank/home@autosnap_2017-10-22_04:00:01_hourly : 256 at /usr/sbin/sanoid line 227.
```
and
```
INFO: deferring pruning of tank/home@autosnap_2017-10-22_04:00:01_hourly - tank/home is currently in zfs send or receive.
```

I've switched to using systemd to run sanoid. I'll report back later if that seems to mitigate the problem. Systemd timer units i believe won't be allowed to run while a previous one is still running.

**Comment by jimsalterjrs** [comment]
You're correct, this is going to happen when two sanoid instances are running at once - particularly on a rather heavily loaded system; sanoid should update its cache each time snapshots are created or destroyed, but on a system with lots and lots of snapshots and not enough RAM to hold them all in memory, it can take a very significant amount of time to rebuild the cache.

Sanoid maintains multiple separate locks; one process won't try to remove snapshots while another one is removing snapshots, and one process won't try to rebuild the cache while another one is - but if one removes snapshots then starts rebuilding the cache, then a second process can start, and try to remove snapshots it sees in the (existing, stale) cache which aren't actually there.

**Comment by jasonblewis** [comment]
fwiw, after switching to using systemd timers to run sanoid, I've had no recurrences of this issue.

**Comment by gregorydlogan** [comment]
I'm experiencing this in an ongoing fashion.  As far as I know I'm only running one instance of Sanoid via cron.  This is on a very lightly loaded Proxmox host.  Any idea where to start debugging?  I'm exclusively seeing things like

> could not find any snapshots to destroy; check snapshot names.
could not remove data/files/images@autosnap_2018-03-25_23:00:01_hourly : 256 at /root/sanoid/sanoid line 240.

but there are snapshots on that dataset.

**Comment by jimsalterjrs** [comment]
1. sanoid instance fires up at 18:00:00, begins deleting old
snapshots 

2. another sanoid instance fires up at 18:00:01, also begins
deleting old snapshots - but it's working from the same cache file that
the first instance is, so in some cases the snapshots are already gone
when this instance tries to delete them 

3. first sanoid instance
finishes its run, and updates the cache at 18"02 

4. second sanoid
instance finishes its run at 18:00:03, and updates the cache again


Basically, if this bugs you schedule sanoid --cron to run less
frequently. I don't really care about this sort of overlap, so I
generally run it every minute; if you want to avoid these messages, try
running it every five minutes, or fifteen, or even every half hour. 

On
2018-03-27 18:36, Greg Logan wrote: 

> I'm experiencing this in an
ongoing fashion. As far as I know I'm only running one instance of
Sanoid via cron. This is on a very lightly loaded Proxmox host. Any idea
where to start debugging? I'm exclusively seeing things like 
> 
>>
could not find any snapshots to destroy; check snapshot names.
>> could
not remove data/files/images@autosnap_2018-03-25_23:00:01_hourly : 256
at /root/sanoid/sanoid line 240.
> 
> but there are snapshots on that
dataset. 
> 
> --
> You are receiving this because you commented.
>
Reply to this email directly, view it on GitHub [1], or mute the thread
[2].

 

Links:
------
[1]
https://github.com/jimsalterjrs/sanoid/issues/154#issuecomment-376698328
[2]

**Comment by gregorydlogan** [comment]
I'll double check, but I'm seeing this when running things on a 15 minute interval.  I would be very surprised if it's taking that long to run, but I suppose it's possible.

**Comment by phreaker0** [comment]
@gregorydlogan 
if you have a huge amount of dataset/snapshots the runtime can be pretty high, see #202.

I would recommend to checkout systemd timers which will make sure that sanoid is only started if the last run completed. But if you like to keep cron you can take a look at "run-one" which makes sure that only one instance is ran.

**Comment by jasonblewis** [comment]
another way to ensure it only runs once is to use flock
`flock -n /run/sanoid-lock sanoid` or similar

**Comment by phreaker0** [comment]
to sum up the solutions to prevent parallel sanoid runs (and therefore prevent the errors):
- use systemd timers instead of cron
- prepend the cron command line with flock as suggested by @jasonblewis
