### ISSUE TITLE
snapshots are not being pruned in production template

### ISSUE THREAD

**Issue by covici** [jimsalterjrs/sanoid#159]
I am using a production template similar to the one you have in sanoid.conf except for hourly = 24 etc.  I will insert below.

Datasets using this template are not pruning anything.  When I use the backup template it seems things are being pruned.

I will attach them below.

[templates.conf.txt](https://github.com/jimsalterjrs/sanoid/files/1451149/templates.conf.txt)

**Comment by jimsalterjrs** [comment]
That template as pasted will absolutely prune old snapshots. Maybe you'd misspelled a reference to it when you tried to apply it to your datasets?

````
root@banshee:/tmp/sanoid# syncoid data/demo banshee/pruneme
INFO: Sending oldest full snapshot data/demo@autosnap_2017-09-01_00:00:01_monthly (~ 583.5 MB) to new target filesystem:
 597MiB 0:00:12 [46.7MiB/s] [================================>] 102%            
INFO: Updating new target filesystem with incremental data/demo@autosnap_2017-09-01_00:00:01_monthly ... syncoid_banshee_2017-11-07:13:35:54 (~ 439 KB):
 357KiB 0:00:00 [ 667KiB/s] [==========================>       ] 81%            
root@banshee:/tmp/sanoid# zfs list -rt snap banshee/pruneme | grep hourly | wc -l
36
root@banshee:/tmp/sanoid# sanoid --cron --configdir /tmp/sanoid --force-update --verbose
INFO: cache forcibly expired - updating from zfs list.
INFO: taking snapshots...
INFO: pruning snapshots...
INFO: pruning banshee/pruneme@autosnap_2017-11-06_02:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_03:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_04:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_05:00:02_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_06:00:02_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_07:00:02_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_08:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_09:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_10:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_11:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_12:00:01_hourly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-06_13:00:01_hourly ... 
INFO: cache forcibly expired - updating from zfs list.
INFO: pruning banshee/pruneme@autosnap_2017-11-01_00:00:02_monthly ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-01_00:01:02_monthly ... 
INFO: cache forcibly expired - updating from zfs list.
INFO: pruning banshee/pruneme@autosnap_2017-10-08_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-09_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-10_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-11_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-12_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-13_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-14_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-15_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-16_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-17_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-18_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-19_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-20_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-21_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-22_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-25_15:59:03_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-25_16:00:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-25_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-26_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-27_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-28_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-29_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-30_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-10-31_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-01_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-02_23:59:01_daily ... 
INFO: pruning banshee/pruneme@autosnap_2017-11-03_23:59:01_daily ... 
INFO: cache forcibly expired - updating from zfs list.
````

I placed your config file exactly as written in /tmp/sanoid/sanoid.conf, along with a fresh copy of sanoid.confs.default, and a dataset referencing it:

````
root@banshee:/tmp/sanoid# cat /tmp/sanoid/sanoid.conf
[banshee/pruneme]
	use_template = production

[template_production]
	hourly = 24
	daily = 3
	monthly = 0
	yearly = 0
	autosnap = yes
	autoprune = yes
````

**Comment by covici** [comment]
OK, it looks like its pruning the hourlys, but only up to 09:00 at the 12:00 run, so its more than 24 hours.  I still have daily from 11/04, so its not pruning those.

**Comment by jimsalterjrs** [comment]
Keep in mind that Sanoid is extremely conservative. If you've specified hourly=24, a snapshot must be > 24 hours old AND you must have > 24 total hourly snapshots, or nothing's getting pruned.

Six hourly snapshots, all a week old? No pruning.

99 hourly snapshots, all taken today? No pruning.

**Comment by covici** [comment]
OK, I put debug mode on and discovered that in all but one file, the
overrides with template_production are not taking place.  Even when
the overrides do take place some of the values are still using the
template in /etc/sanoid/sanoid_defaults.conf.

I attach my complete sanoid.conf so maybe you can see why this has
gone wrong.


On Tue, 07 Nov 2017 14:06:02 -0500,
Jim Salter wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
> Keep in mind that Sanoid is extremely conservative. If you've specified hourly=24, a snapshot must be > 24 hours old AND you must have > 24 total hourly snapshots, or nothing's getting pruned.
> 
> Six hourly snapshots, all a week old? No pruning.
> 
> 99 hourly snapshots, all taken today? No pruning.
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by jimsalterjrs** [comment]
You didn't attach either the sanoid.conf, or the results of sanoid --cron --debug.

**Comment by covici** [comment]
Here itis again.
Its right below this line unless github removes attachments.



On Wed, 08 Nov 2017 09:52:56 -0500,
Jim Salter wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> You didn't attach either the sanoid.conf, or the results of sanoid --cron --debug.
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by covici** [comment]
Here are the first two lines from the debug output
DEBUG: initializing $config{rpool/home} with default values from
/etc/sanoid/sanoid.defaults.conf.
DEBUG: initializing $config{rpool/root} with default values from /etc/sanoid/sanoid.defaults.conf.

As you can see, nothing is overridden.  If github has removed the
attachment, give meanother address so I can send it.

Thanks.

On Wed, 08 Nov 2017 09:52:56 -0500,
Jim Salter wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> You didn't attach either the sanoid.conf, or the results of sanoid --cron --debug.
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com
