### ISSUE TITLE
Syncoid doesn't exit on error and cannot be terminated by Keyboard Interrupt

### ISSUE THREAD

**Issue by alecz20** [jimsalterjrs/sanoid#164]
I noticed that if syncoid encounters an error it will get stuck at that error.
Pressinc Ctrl+C displays some sort of stuck progress but does not exit the program.

The workaround is to kill the process:

`syncoid --recursive storage/set1 root@server2:set1`
`INFO: Sending oldest full snapshot  storage/set1@syncoid_server_2017-11-13:10:19:46 (~ 356.6 GB) to new target filesystem:`
`cannot receive new filesystem stream: destination 'set1' does not exist`
`^C24.6MiB 0:00:08 [2.98MiB/s] [>                                              ]  0% ETA 1:09:02:08`
`^C`

Either the program should exit on error or be terminated by Ctrl+C

**Comment by attie** [comment]
Have you tried `^\` (sends SIGQUIT)?

**Comment by phreaker0** [comment]
I encountered the same issue once, in this case mbuffer was using 100% cpu. But unfortunately I failed to reproduce the issue for analysis.

**Comment by phreaker0** [comment]
I can't reproduce the problem on the current master. Please reopen if the problem still occurs (a proper reproducer would also be nice)
