### ISSUE TITLE
Issues with 'ps' on SmartOS

### ISSUE THREAD

**Issue by jjlawren** [jimsalterjrs/sanoid#17]
It seems the assumptions for `ps` arguments don't work well on SmartOS or perhaps other Solaris-ish / Illumos-based systems.

When using the BSD-style options (grouped arguments without '-' preceding them), it falls back to the compatibility `/usr/ucb/ps` binary, which doesn't support the '-o' argument.

It looks like this can be solved (for SmartOS) by always using the UNIX-style options with a preceding hyphen and the '-Ao' flag instead of 'axo' for checking ZFS activity.

**Comment by jimsalterjrs** [comment]
Any interest in creating a pull request with sanity-checking of the 
underlying OS?

I did my best to create a set of options for ps that would work on 
either Linux or BSD, but one that works on Linux AND BSD AND 
Solaris-like OSes looks basically impossible.  I'm happy to support it, 
but I don't have any Solaris to test on and am probably not going to set 
up a test environment for that platform any time soon, so some help 
would be appreciated.

Does uname work predictably on Solaris as on Linux/BSD?  Or can you 
think of a better way to test for host environment?
