### ISSUE TITLE
Solaris11.3 - syncoid fails

### ISSUE THREAD

**Issue by brendon0** [jimsalterjrs/sanoid#172]
Looks like failure on the zfs get snapshot commands:

root@SolarisZFS:/opt/csw/bin# syncoid --debug bigstore/smb/archive flash/temp/archive
DEBUG: SSHCMD: /usr/bin/ssh
DEBUG: checking availability of /usr/bin/lzop on source...
DEBUG: checking availability of /usr/bin/lzop on target...
DEBUG: checking availability of /usr/bin/lzop on local machine...
DEBUG: checking availability of /usr/bin/mbuffer on source...
DEBUG: checking availability of /usr/bin/mbuffer on target...
DEBUG: checking availability of /usr/bin/pv on local machine...
DEBUG: syncing source bigstore/smb/archive to target flash/temp/archive.
DEBUG: checking to see if flash/temp/archive on  is already in zfs receive using  /bin/ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "  /sbin/zfs get -H name flash/temp/archive 2>&1 |"...
DEBUG: getting list of snapshots on bigstore/smb/archive using   /sbin/zfs get -Hpd 1 -t snapshot guid,creation bigstore/smb/archive |...
invalid option 't'
For more info, run: zfs help get
DEBUG: getting list of snapshots on flash/temp/archive using   /sbin/zfs get -Hpd 1 -t snapshot guid,creation flash/temp/archive |...
invalid option 't'
For more info, run: zfs help get
DEBUG: getting current value of -p used on flash/temp/archive...
  /sbin/zfs get -H -p used flash/temp/archive

CRITICAL ERROR: Target flash/temp/archive exists but has no snapshots matching with bigstore/smb/archive!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

          NOTE: Target flash/temp/archive dataset is < 64MB used - did you mistakenly run
                `zfs create flash/temp/archive` on the target? ZFS initial
                replication must be to a NON EXISTENT DATASET, which will
                then be CREATED BY the initial replication process.

FYI in Solaris 11.3 I use "zfs list -t snapshot xxxxx" get a list of snapshots.

**Comment by jimsalterjrs** [comment]
I don't have a Solaris box to test on, so you'll need to work with me here. =)

Please try ` /sbin/zfs get -Hpd 1 -t snapshot guid,creation bigstore/smb/archive` from the command line. Record output.

Assuming it fails, then please try ` /sbin/zfs get -t snapshot guid,creation bigstore/smb/archive`. If that one works, you'll need to step through and try the `-H`, `-p`, and `-d 1` options independently until you figure out what's throwing Solaris for a loop.

**Comment by brendon0** [comment]
root@SolarisZFS:/opt/csw/bin# /sbin/zfs get -Hpd 1 -t snapshot guid,creation bigstore/smb/archive
invalid option 't'
For more info, run: zfs help get

**Comment by brendon0** [comment]
More info:

root@SolarisZFS:/opt/csw/bin# zfs help get
usage:
        get [-rHpe] [-d max] [-o "all" | field[,...]] [-s source[,...]]
            <"all" | property[,...]> [filesystem|volume|snapshot|share] ...

**Comment by brendon0** [comment]
Removing the "-t snapshot" gets this output

root@SolarisZFS:/opt/csw/bin# /sbin/zfs get -Hpd 1 guid,creation bigstore/smb/archive
bigstore/smb/archive    guid    5910988941821281768     -
bigstore/smb/archive    creation        1500157685      -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:10     guid    3953010774284668191     -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:10     creation        1512079930      -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:57     guid    5292856628667940414     -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:57     creation        1512079977      -
bigstore/smb/archive%archive    guid    18245244681948268328    -
bigstore/smb/archive%archive    creation        1500157760      -

**Comment by jimsalterjrs** [comment]
Ugh. Well, that's gross.

Without `-t snapshot` you get all datasets themselves, not just their snapshots. I suppose we could filter that list with a regex requiring the presence of `@`, assuming that it's not possible to create a dataset with an `@` in the name (hopefully it isn't!).

I also hate to commit that to production for everybody, given how inelegant it is. I'm a little more inclined to something along the lines of a `--solaris` flag on the command line or similar to cause the use of the less-elegant code with the regex filter.

Thoughts?

**Comment by brendon0** [comment]
Im cool with the --solaris command, seems logical. Or you could just grep for @
No Grep:
root@SolarisZFS:/opt/csw/bin# /sbin/zfs get -Hpd 1 guid,creation bigstore/smb/archivebigstore/smb/archive    guid    5910988941821281768     -
bigstore/smb/archive    creation        1500157685      -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:10     guid    3953010774284668191     -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:10     creation        1512079930      -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:57     guid    5292856628667940414     -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:57     creation        1512079977      -
bigstore/smb/archive%archive    guid    18245244681948268328    -
bigstore/smb/archive%archive    creation        1500157760      -


With Grep:
root@SolarisZFS:/opt/csw/bin# /sbin/zfs get -Hpd 1 guid,creation bigstore/smb/archive | grep @bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:10     guid    3953010774284668191     -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:10     creation        1512079930      -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:57     guid    5292856628667940414     -
bigstore/smb/archive@syncoid_SolarisZFS_2017-11-30:17:12:57     creation        1512079977      -


 

    On Thursday, November 30, 2017, 6:08:25 PM EST, Jim Salter <notifications@github.com> wrote:  
 
 
Ugh. Well, that's gross.

Without -t snapshot you get all datasets themselves, not just their snapshots. I suppose we could filter that list with a regex requiring the presence of @, assuming that it's not possible to create a dataset with an @ in the name (hopefully it isn't!).

I also hate to commit that to production for everybody, given how inelegant it is. I'm a little more inclined to something along the lines of a --solaris flag on the command line or similar to cause the use of the less-elegant code with the regex filter.

Thoughts?

**Comment by brendon0** [comment]
New thoughts:

--solaris may not work -

What if I am sending data from my Solaris host to my OmniOS host? The commands on each end would
be different for the "zfs get" - How would you differentiate which side is which if you use a single catchall for "--solaris"

It may make more sense to " | grep @" the zfs get all command to catch all the snapshots only.

**Comment by jimsalterjrs** [comment]
Honestly, figuring out a reliable way to auto-detect Solaris hosts is 
probably the best way forward.

I still don't want to replace actually identifying snapshots directly 
with a clumsy regex for all hosts in prod going forward.

**Comment by brendon0** [comment]
Solaris:
root@SolarisZFS:/opt/csw/bin# cat /etc/release
                             Oracle Solaris 11.3 X86
  Copyright (c) 1983, 2016, Oracle and/or its affiliates.  All rights reserved.
                            Assembled 03 August 2016
OmniOS:
root@omnios:~# cat /etc/release
  OmniOS v11 r151022
  Copyright 2017 OmniTI Computer Consulting, Inc. All rights reserved.
  Use is subject to license terms.

**Comment by brendon0** [comment]
Solaris:
root@SolarisZFS:/opt/csw/bin# uname -a
SunOS SolarisZFS 5.11 11.3 i86pc i386 i86pc

OmniOS:
root@omnios:~# uname -a
SunOS omnios 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc

**Comment by phreaker0** [comment]
@brendon0 seems like the current version supports the -t flag: https://docs.oracle.com/cd/E19253-01/816-5166/6mbb1kqo8/index.html

**Comment by phreaker0** [comment]
Seems like the only solution is to upgrade Solaris.

**Comment by Will-Moshe** [comment]
Am I mistaken that the `-t` flag is for `list`, not `get`?  Testing latest `syncoid` with Solaris 11.4 and still receive the `invalid option 't'` error.

**Comment by Will-Moshe** [comment]
Requesting to re-open this ticket.  I can do any required testing.

**Comment by phreaker0** [comment]
You are right, different option :-(
