### ISSUE TITLE
Can I run syncoid every 1 minute?

### ISSUE THREAD

**Issue by mwacgi** [jimsalterjrs/sanoid#177]
Can I run syncoid every 1 minute like this:
`* * * * * /usr/sbin/syncoid --recursive --quiet pool/data root@192.168.1.100:pool/data`

**Comment by phreaker0** [comment]
yes, but cron doesn't check if the last command finished. So if the syncoid process takes longer than a minute you will end up with two sanoid processes, the second one will check and see that the pool is already busy sending/receiving and will error out and you will probably get an error mail from cron if configured.
If available you can use systemd timers, they will only be scheduled if the old one finished.

**Comment by mwacgi** [comment]
@phreaker0 
Thank you very much.
