### ISSUE TITLE
Log syncoid transfer information to file

### ISSUE THREAD

**Issue by Guillaume00** [jimsalterjrs/sanoid#179]
Is there a way to log the list of snapshots, amount of data and transfer time to a file?

**Comment by phreaker0** [comment]
you can redirect the "--debug" output to a file.

**Comment by Ryushin** [comment]
In case this helps anyone.  I wanted to log to syslog.  I don't use systemd so this is run from /etc/cron.d/sanoid
`
*/15 * * * * root bash -c '[ -f /etc/sanoid/sanoid.conf ] && TZ=MST /usr/sbin/sanoid --cron --verbose | /usr/bin/logger --tag=sanoid'
*/15 * * * * root bash -c '/bin/sleep 30; syncoid --recursive --skip-parent --compress=lz4 --no-sync-snap rpool root@myserver.mydomain.com:netshares/zfs_server_backups/laptop_backup | /usr/bin/logger --tag=syncoid'
`
