### ISSUE TITLE
Excluding certain datasets from recursive syncoid call

### ISSUE THREAD

**Issue by AndrewJDR** [jimsalterjrs/sanoid#187]
Hello, thanks for your work on syncoid/sanoid.

I'd really like to be able to exclude certain datasets from being synced with a recursive syncoid call.
While I could not use `-r` and call syncoid individually for each dataset that i wish to replicate, this increases the chance that I'll forget to add a corresponding syncoid command after creating a new dataset and accidentally miss out on backing up some data.

Currently, I managed to accomplish this by creating an empty dataset on the target  with the same name as the dataset I wish to exclude on the source. This "blocks" replication of that particular dataset to the target. For example, assuming I want to exclude 'zpool/scratch', this causes the following error during replication (`/usr/local/bin/syncoid -r zpool root@1.2.3.4:backups/zpool`):
```
CRITICAL ERROR: Target backups/zpool/scratch exists but has no snapshots matching with zpool/scratch!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

          NOTE: Target backups/zpool/scratch is < 64MB used - did you mistakenly run
                `zfs create root@1.2.3.4:backups/zpool/scratch` on the target? ZFS initial
                replication must be to a NON EXISTENT DATASET, which will
                then be CREATED BY the initial replication process.
```
The rest of the syncoid process executes fine, so this message isn't seemingly a problem. So this accomplishes my goal of not replicating that particular dataset.

However, I also have to add the following crontab entry on the source side, otherwise unnecessary syncoid snapshots from the failed attempts will accumulate there:
```/sbin/zfs destroy 'zpool/scratch@%'```
(Note I explicitly don't want to do snapshotting on that dataset, so the wildcard destroy is fine in my situation)

I do believe I could use `--no-sync-snap`, but I'd really prefer not to, as I generally like syncoid's behavior of creating and removing the temporary snapshots to prevent any snapshot expiration mishaps from occurring.

Ideally, This `zfs destroy` crontab wouldn't be necessary, as it's just another thing I need to remember to update every time I exclude a dataset.

This brings me to my questions:

* When syncoid reaches the error condition mentioned above, would it be okay to immediately destroy the autosnap that was created (or just not create it in the first place -- whichever is applicable given the ordering of the code)? This would avoid needing to create the crontab, but I'm not sure if it would cause some other issue. It seems to me that if a given syncoid run creates an autosnap and is immediately unable to replicate said autosnap, there's no point in keeping said autosnap around. If this sounds like a benign enough change, I could submit a PR with it.
* Do you have any thoughts on some kind of `--exclude` or `--exclude-pattern` flag for syncoid that allows one to exclude certain datasets from recursive replication based on a pattern match against the dataset name? So in my case I'd use something like ``--exclude=zpool/scratch*`` on the source. The benefit here is that I'd neither have to create an empty dataset on the target nor create a `zfs destroy` crontab.
* I could alternatively write a small wrapper script around syncoid that accepts the ```--exclude``` parameter, then calls `zfs list` or similar and runs a syncoid command for each dataset, minus any excluded ones. This is not hard for me to do, but would become yet another thing I have to maintain on different systems, so I'd prefer it just be handled by syncoid proper.
* Any other suggestions for how to handle this better?

**Comment by AndrewJDR** [comment]
Slightly related - https://github.com/jimsalterjrs/sanoid/issues/127
But they are using `--no-sync-snap`, which I don't really want to do.

**Comment by attie** [comment]
I think that my PR (#189) addresses this use case.

**Comment by AndrewJDR** [comment]
@attie That looks great!

**Comment by phreaker0** [comment]
there are now two solutions to your problem
- using the no sync property from #189
- using one or more exclude regular expressions #239 

so I think this can be closed
@AndrewJDR if not feel free to reopen the issue
