### ISSUE TITLE
migrating from zrep to syncoid

### ISSUE THREAD

**Issue by toddpfaff** [jimsalterjrs/sanoid#194]
I realize that documentation states that syncoid doesn't allow the replica target to exist, but I don't understand why this shouldn't be possible if the source and target have been created using some other zfs send-recv tool.

I want to migrate from zrep to syncoid and I'm wondering if anyone has done this while being able to preserve an existing target.  Perhaps there is a way to convert the last zrep snapshot meta data to a format that syncoid can start with?

**Comment by jimsalterjrs** [comment]
The target can exist as long as it's actually a replica in the first place. What you can't do is zfs create pool/target and then expect syncoid pool/source pool/target to work.

**Comment by toddpfaff** [comment]
Thanks, Jim, that's great to know.  I missed that subtlety in the 
documentation I'd read.  I'll follow up after I've made the move.

**Comment by toddpfaff** [comment]
Where is the Right Place for discussion and questions about sanoid/syncoid?

**Comment by jimsalterjrs** [comment]
I'd generally recommend a thread on Reddit in /r/zfs. I'm pretty active there, and it lends itself to discussion better than GitHub threads. I keep Reddit Gold up on my account there, so if you want to make sure to get my attention, tag me by typing **/u/mercenary_sysadmin** (my Reddit username) in the body of your message; that makes sure I get a direct message alerting me to the thread.

**Comment by toddpfaff** [comment]
Ok, I'll consider that route.  After finding some other discussion threads 
today in the zfs-disuss@list.zfsonlinux.org, I subscribed to that list and 
was composing a message to that list to ask for some sanoid/syncoid 
advice.  Is that another forum that may get your attention?

Thanks,
Todd

**Comment by jimsalterjrs** [comment]
I am not active on zfs-discuss. I won't see any messages there unless 
somebody brings them to my attention somewhere else.

Mailing lists are a giant PITA for me, because my email is already 
overflowing and then some. You may very well get good sanoid/syncoid 
advice there, I dunno; but it's unlikely to be from me. =)  I /do/ know 
there are quite a lot of sanoid/syncoid users on /r/zfs, but I have no 
idea how frequently it's used by users of the zfs-discuss list.

**Comment by toddpfaff** [comment]
Jim,

Further to what you wrote above, I've tried a syncoid run and I get:

CRITICAL ERROR: Target pool/host/host1 exists but has no snapshots matching with pool/host/host1!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

Yes, the target does exist, but it's a replica, so how can I get syncoid to work with this existing target replica?  How do I prime the syncoid pump?

**Comment by jimsalterjrs** [comment]
You can't. You don't have matching snapshots on source and target. No matching snapshots means no incremental replication; you'd need to destroy the target and start over with a full.

**Comment by toddpfaff** [comment]
To tie up this thread, I just want to confirm that it worked just fine in the case where I had a zfs replica created and maintained with zrep.  I simply stopped my zrep replication, left all existing zrep snapshots in place on source and target, and then started running syncoid.  Syncoid picked up where zrep had left off and began syncing my new sanoid snapshots.  I haven't done so yet but I will eventually just remove the old zrep properties and snapshots with a 'zrep clear'.

Thanks, Jim, for your guidance.

**Comment by phreaker0** [comment]
no issue here, just a happy user :-)
