### ISSUE TITLE
syncoid --no-sync-snap still tries (and fails) to purge old sync snapshots

### ISSUE THREAD

**Issue by flo82** [jimsalterjrs/sanoid#196]
I'm using sanoid for atleast 2 years now without any problems (local zpool backup). Thanks for the great work :-) Now i'm trying to add a remote backup zpool. i got 3 zpools:

* source and target are located on sourcehostname
* remote ist located on remotehostname

The following should be achieved (see commands in "Steps to reproduce"):

at first source/a dataset is synced to target/a (local backup).
the next command syncs source/a dataset to remote/a with the special option "--nosync-snap" (remote backup).

The 2nd command causes errors (see current behaviour). Please give advice to fix the issue on my site.

## Expected Behavior

both commands run without problems and no logging output (because of --quiet).

## Current Behavior

first command runs without problems
the second command produces the following output:

`NEWEST SNAPSHOT: syncoid_sourcehostname_2018-02-09:04:15:00`
`could not find any snapshots to destroy; check snapshot names.`
`WARNING: /usr/bin/ssh -c chacha20-poly1305@openssh.com,arcfour -p 22 -S /tmp/syncoid-root-root@sourcehostname-1518146187 root@remotehostname " /sbin/zfs destroy remote/a@syncoid_sourcehostname_2018-02-08:04:15:01" failed: 256 at /opt/sanoid/syncoid line 769.
`
## Possible Solution

the message with NEWST SNAPSHOT is adressed in #132 -> waiting for new release
the warning seems similiar to the problem described in #143 -> have no idea how to fix this

## Steps to Reproduce (commands issued)

`syncoid source/a target/a --quiet`
`syncoid source/a user@remotehostname:remote/a --no-sync-snap --quiet`

## Context (Environment)

Ubuntu 16.04. LTS with latest updates on both machine.
sanoid v1.4.14 on both machines

**Comment by flo82** [comment]
to give some more input:

it seems that this issue has something to do with sanoid taking snapshots.
here is the sanoid config on the sourcehost:

>[source/a]
>        use_template = production
>
>[target]
>        use_template = backup
>        process_children_only = yes
>        recursive = yes
>
>[template_production]
>        hourly = 0
>        daily = 30
>        monthly = 2
>        yearly = 0
>        autosnap = yes
>        autoprune = yes
>
>[template_backup]
>        autoprune = yes
>        hourly = 0
>        daily = 90
>        monthly = 12
>        yearly = 0
>autosnap = no
>        hourly_warn = 2880
>        hourly_crit = 3600
>        daily_warn = 48
>        daily_crit = 60

on targethost sanoid will not run.
if i'm running

> syncoid source/a user@remotehostname:remote/a --no-sync-snap --quiet
a 2nd time BEFORE sanoid runs - then the only output i got is:

> NEWEST SNAPSHOT: syncoid_sourcehostname_2018-02-09:04:15:00

so it definetily has something todo with sanoid running in between.

**Comment by jimsalterjrs** [comment]
You can't have Sanoid TAKING snapshots on the target. You need to be using a hotspare or backup template on the target - one that prunes old snapshots but does not take new ones.

**Comment by flo82** [comment]
> You can't have Sanoid TAKING snapshots on the target. You need to be using a hotspare or backup template on the target - one that prunes old snapshots but does not take new ones.

i don't want to use sanoid for taking snapshots on the target (autosnap = no).
i just want to use syncoid with source -> target, and source -> remote.
but this gives the described warning.

how can i better describe my problem :-) ?

**Comment by jimsalterjrs** [comment]
I'm not sure. I'm having trouble following because while you're very verbose here, you're a little inconsistent with pseudo-naming conventions between your two machines, and with whether you do or don't show actual commands being run.

In particular, you aren't showing the actual command that you ran when receiving this error, which seems to be the real meat of your report:

```
NEWEST SNAPSHOT: syncoid_sourcehostname_2018-02-09:04:15:00
could not find any snapshots to destroy; check snapshot names.
WARNING: /usr/bin/ssh -c chacha20-poly1305@openssh.com,arcfour -p 22 -S /tmp/syncoid-root-root@sourcehostname-1518146187 root@remotehostname " /sbin/zfs destroy remote/a@syncoid_sourcehostname_2018-02-08:04:15:01" failed: 256 at /opt/sanoid/syncoid line 769.
```
Can you please show the exact command being used when you see this error?

Also, can you please update to the latest version of syncoid first? I can see that you are using an older version due to the output string including the chacha20-poly1305 cipher, which has been removed from the current version.

**Comment by flo82** [comment]
Last time I used the latest official release (1.4.14). I now updated to git.master.

First i run this command:

`syncoid source/a target/a --quiet`

and it produces no output.

Second i run this command:
`syncoid source/a user@remotehostname:remote/a --no-sync-snap --quiet`
and it produces the following output:

> NEWEST SNAPSHOT: syncoid_sourcehostname_2018-02-10:21:01:45
> could not find any snapshots to destroy; check snapshot names.
> WARNING: /usr/bin/ssh     -S /tmp/syncoid-root-user@remotehostname-1518292939 user@remotehostname " /sbin/zfs remote/a@syncoid_remotehostname_2018-02-10:04:15:01" failed: 256 at /opt/sanoid/syncoid line 727.

if i run the 2nd command again:

`syncoid source/a user@remotehostname:remote/a --no-sync-snap --quiet`

it will produce the following output:
> NEWEST SNAPSHOT: syncoid_sourcehostname_2018-02-10:21:01:45

Can you now understand my problem? I think it has something todo with the snapshots created by the first command.

Thank you for your patience and support.

**Comment by jimsalterjrs** [comment]
Yep. The real problem here is that it's trying to purge old sync snapshots when it's being invoked with --no-sync-snap. It shouldn't be trying to purge them, since it's not being asked to create them either.

**Comment by jimsalterjrs** [comment]
I don't have the time to tackle this right now, but I updated your title so I'll know wtf I'm looking at when I do. =)

**Comment by flo82** [comment]
perfect. if you need s/o to test a new release I can give it a try.
unfortunately i can't propose a merge request because i don't understand the source code entirely.
keep up the great work! :-)

**Comment by flo82** [comment]
now (after upgrading sanoid-repository to head) **-no-sync-snap** is completely broken for me.

First command works:
`syncoid source/a user@remotehostname:remote/a --no-sync-snap`

After second run:
`syncoid source/a user@remotehostname:remote/a --no-sync-snap`

The following error is produced:

```
WARN: ZFS resume feature not available on target machine - sync will continue without resume support.
NEWEST SNAPSHOT: syncoid_sourcehostname_2018-04-30:01:15:09
INFO: Sending oldest full snapshot source/a@autosnap_2018-04-28_21:20:03_monthly (~ 292.7 MB) to new target filesystem:
cannot receive new filesystem stream: destination has snapshots (eg. remote/a@syncoid_sourcehostname_2018-04-30:01:15:09)
must destroy them to overwrite it
mbuffer: error: outputThread: error writing to <stdout> at offset 0x268000: Broken pipe                                                                                                                                                                                                                     ]  8% ETA 0:00:10
mbuffer: warning: error during output to <stdout>: Broken pipe
25,8MiB 0:00:01 [17,1MiB/s] [====================>                                                                                                                                                                                                                                                          ]  8%
CRITICAL ERROR:  /sbin/zfs send 'source/a'@'autosnap_2018-04-28_21:20:03_monthly' | /usr/bin/pv -s 306902752 | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/ssh     -S /tmp/syncoid-root-root@remotehostname-1525077183 root@remotehostname ' /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc |  /sbin/zfs receive  -F '"'"'remote/a'"'"'' failed: 256 at /opt/sanoid/syncoid line 267.

```

**Comment by phreaker0** [comment]
@flo82 
which os and zfs version are you using? The second run should do an incremental send but instead does a full one. The latests master contains fixes for special char handling and it required to change the snapshot parsing code, maybe your zfs output looks different and it can't correctly parse the snapshot list.
Can you rerun your commands with --debug and --dumpsnaps?

**Comment by phreaker0** [comment]
I tested the same scenario, Ubuntu 18.04 with zfs 0.7.x replicating to Ubuntu 16.04 with zfs 0.6.x:

```
$ sudo zfs create storage/test
$ sudo zfs snapshot storage/test@'first snapshot'
$ sudo zfs snapshot storage/test@'second snapshot'
$ ./syncoid --no-sync-snap storage/test root@craig:storage/test
WARN: ZFS resume feature not available on target machine - sync will continue without resume support.
NEWEST SNAPSHOT: second snapshot
INFO: Sending oldest full snapshot storage/test@first snapshot (~ 40 KB) to new target filesystem:      
INFO: Updating new target filesystem with incremental storage/test@first snapshot ... second snapshot                                                                                                                                                                            
$ sudo zfs snapshot storage/test@'third snapshot'
$ ./syncoid --no-sync-snap storage/test root@craig:storage/test
WARN: ZFS resume feature not available on target machine - sync will continue without resume support.
NEWEST SNAPSHOT: third snapshot
Sending incremental storage/test@second snapshot ... third snapshot (~ 4 KB):
```

With mixed english/german locales:
```
source$ sudo locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE:en
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME=de_AT.UTF-8
LC_ADDRESS=de_AT.UTF-8
LC_TELEPHONE=de_AT.UTF-8
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION=de_AT.UTF-8
LC_ALL=

remote$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME=de_AT.UTF-8
LC_ADDRESS=de_AT.UTF-8
LC_TELEPHONE=de_AT.UTF-8
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION=de_AT.UTF-8
LC_ALL=
```
So i don't think the locales are at fault here, but I can be wrong of course :)

**Comment by flo82** [comment]
thanks for testing that @phreaker0 . this is strange. at least i could use the --no-sync-snap again :-)
the strange warning (described above) is still present. so bug is not closed yet.

```
NEWEST SNAPSHOT: syncoid_sourcehostname_2018-02-10:21:01:45
could not find any snapshots to destroy; check snapshot names.
WARNING: /usr/bin/ssh -S /tmp/syncoid-root-user@remotehostname-1518292939 user@remotehostname " /sbin/zfs remote/a@syncoid_sourcehostname_2018-02-10:04:15:01" failed: 256 at /opt/sanoid/syncoid line 727.
```
I would help if I knew how

**Comment by jimsalterjrs** [comment]
approved and merged.

**Comment by flo82** [comment]
thank you @phreaker0.
works as intended.

**Comment by Phillipip** [comment]
general different language settings are not the problem, but different language entries in .bashrc file on remote server like
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
are responsible for this error.
