### ISSUE TITLE
syncoid --verbose: Unknown option

### ISSUE THREAD

**Issue by jasonblewis** [jimsalterjrs/sanoid#198]
In the help for syncoid it says:

```
--verbose             Prints the version number
```
I think it probably should be --version

https://github.com/jimsalterjrs/sanoid/blob/f6519c0aea4c624161f92a1304943d1c60e714bc/syncoid#L959

**Comment by jsavikko** [comment]
I've made an pull request #205  to fix option verbose to version in helptext.

**Comment by phreaker0** [comment]
resolved by #205
