### ISSUE TITLE
Override config file locations with argument

### ISSUE THREAD

**Issue by jjlawren** [jimsalterjrs/sanoid#20]
On some distros the default config directory is not in `/etc`. This means the script must be edited directly and will cause conflicts with future git pulls. Would be cleaner if the individual config files or the base config directory (or both!) could be overridden by a runtime argument, leaving the values in the script as the defaults.

**Comment by jimsalterjrs** [comment]
added --configdir=/path/to/configs option to sanoid for all of your non-standard config dir needs.
