### ISSUE TITLE
Should the snapshopts on the remote/backup host be removed?

### ISSUE THREAD

**Issue by flyemsafe** [jimsalterjrs/sanoid#200]
I want to use syncoid to keep a backup server in sync with the primary. But i notice i cannot just run syncoid without first deleting the existing snapshops. Does this mean in order to keep the backup server in sync, i should have a pre task that deletes the snapshots received from the last syncoid run? 

I also have saniod setup on the backup server using the backup template, i thought it would purge the snapshots. Allowing syncoid to run without error. This does not seem to be the intended use of syncoid backup template.

Ideally, i would like to have sanoid taking regular snapshots, then have syncoid sending them to the backup server on a regular scheduled/ Is this possible?

```
cannot receive new filesystem stream: destination has snapshots (eg. backuppool/virtimages)
must destroy them to overwrite it
CRITICAL ERROR:  /sbin/zfs send datapool/virtimages@autosnap_2018-02-17_19:35:37_daily | /usr/bin/pv -s 41584 | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/ssh     -S /tmp/syncoid-root-root@192.168.12.2-1518919889 root@192.168.12.2 ' /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc |  /sbin/zfs receive -F backuppool/virtimages' failed: 256 at /usr/sbin/syncoid line 236.
```

### Local
```
zfs list -H -o name -t snapshot | grep virt
datapool/virtimages@autosnap_2018-02-17_19:35:37_daily
datapool/virtimages@autosnap_2018-02-17_19:35:37_monthly
datapool/virtimages@autosnap_2018-02-17_19:35:37_hourly
datapool/virtimages@autosnap_2018-02-17_20:31:43_hourly
datapool/virtimages@autosnap_2018-02-17_21:02:22_hourly
```

### Remote
```
backuppool/virtimages@autosnap_2018-02-17_19:35:37_daily
backuppool/virtimages@autosnap_2018-02-17_19:35:37_monthly
backuppool/virtimages@autosnap_2018-02-17_19:35:37_hourly
```

**Comment by redmop** [comment]
Sanoid needs to be run locally and separately on the remote host as well. Neither sanoid, nor syncoid cleanup snapshots on the remote host.

**Comment by monkiki** [comment]
According to my tests, If I run sanoid id both servers and use syncoid to copy snapshot to the remote one, the syncoid execution replace the remote sanoid snapshots. So I don't know how to purge the expired snapshots in the remote server :-/

**Comment by jimsalterjrs** [comment]
Use a backup template. The sample provided in sanoid.defaults.conf is a 
working example - it iTunes snapshots but does not take them.

On May 1, 2018 5:34:04 AM Paco Avila <notifications@github.com> wrote:
According to my tests, If I run sanoid id both servers and use syncoid to 
copy snapshot to the remote one, the syncoid execution replace the remote 
sanoid snapshots. So I don't know how to purge the expired snapshots in the 
remote server :-/
