### ISSUE TITLE
Have events on operations done.

### ISSUE THREAD

**Issue by gfriloux** [jimsalterjrs/sanoid#209]
Based on PR#193: https://github.com/jimsalterjrs/sanoid/pull/193
I think it would be nice if we could get events when sanoid is doing a thing.

we could add `--event|e=s` in getopt to specify a program or script to be called when snapshots are created/deleted.

The idea comes from the fact that:
- I am studying removing an internal script that does the same thing than syncoid, by syncoid itself (so I dont have to maintain my script alone).
- My actual script sends notifications when it finishes to send a snapshot (we also grab snapshot size and time it took to transfer it).

Am I alone thinking it would be a good thing, or everyone thinks parsing syncoid's stdout is enough ?

**Comment by phreaker0** [comment]
So in contrast to #193 the event callback should be called asynchronously without blocking?

**Comment by gfriloux** [comment]
This is a very interesting question.
I believe it should be blocking to avoid possible flooding in case the script called is slower than the sync itself.
In case of uncontrollable latencies, and for example a script that does send notifications by mail/mattermost/whatever, we might end up with events arriving without respecting the order of actions.
In this particular case, i would prefer to risk a slowdown than inverting the order of actions on monitoring

**Comment by phreaker0** [comment]
so whats the difference to #193?

**Comment by gfriloux** [comment]
It is a little hard for me to really remember the context, as it was months ago and my memory fails me (im actually working on a project that does not involve ZFS).

I believe that the main idea was to get an event system, as #193 only cares about events for created snapshots, which is only part of the stuff done.

Does it also calls the script when deleting snapshots ?

**Comment by gfriloux** [comment]
Then i believe you already resolved the issue i created.
If i later find out something missing, i would create another issue and try to be more verbose/clear on what i need.

**Comment by phreaker0** [comment]
yeah :-)
