### ISSUE TITLE
"recursive = false" in sanoid.conf taken as true

### ISSUE THREAD

**Issue by wyoung** [jimsalterjrs/sanoid#219]
It seems that any non-empty value given to `recursive` is taken as a true value.

Also related, according to [the TOML docs](https://github.com/toml-lang/toml#user-content-boolean), you're supposed to be using `true` in Boolean values, not `yes`. I'm filing it here instead of as a separate bug because I suspect it's a symptom of the same problem, not handling TOML Booleans correctly.

**Comment by sparky3387** [comment]
FYI, The verbose and readonly options combined create this
