### ISSUE TITLE
syncoid: --no-stream question

### ISSUE THREAD

**Issue by ionutz22** [jimsalterjrs/sanoid#222]
Hi,

I'm transferring a dataset from nasA to nasB (syncoid command runs on B) using the following command:

`syncoid -r root@nasA:data/web datab/web -sshkey=mykey --no-stream`

It skips all snapshots and uses the latest snapshot, also it creates semi-ephemeral syncoid snapshot on source (nasA), but it looks this is not present/transferred on target (nasB) after sync is finished.
In the meanwhile newer snapshots are created on nasA and when I'm running another syncoid on nasB it refuses to work (see bellow error) ... and I suspect that's related to semi-ephemeral snapshot missing on target (nasB).

```
CRITICAL ERROR: Target datab/web exists but has no snapshots matching with data/web!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

```
Is this the normal behavior for --no-stream options in syncoid ?

I'm using sanoid-1.4.18.

Thanks.

**Comment by phreaker0** [comment]
No. It should work by having the syncoid snapshot on the target too. I guess something on the target removes the syncoid snapshot. Can you run your command with the --debug flag and post the output to see whats exactly happens?

**Comment by ionutz22** [comment]
Thanks ... I figured it out, it works as expected.
In this particular case I had another syncoid job (on nasC) syncing data from the same server every hour ... and when that run again the last ephemeral snapshots was deleted ...
