### ISSUE TITLE
Support for multiple targets

### ISSUE THREAD

**Issue by apiening** [jimsalterjrs/sanoid#225]
I want to replicate my zpool to three different targets (usb drives).
That means I need to keep three sync states for syncoid to be able to sync against a drive that has not been connected for the last couple of sync runs.
I can see, that syncoid creates snapshots with the name syncoid-<hostname>_<datetime>.
Is it possible to use another label (like disk1, disk2 and disk3 for example) instead of the hostname or append a suffix to the snapshot label?

**Comment by phreaker0** [comment]
this was an surprising easy one, this needs some testing, can you try the linked PR?
