### ISSUE TITLE
Syncoid does not check for root properly.

### ISSUE THREAD

**Issue by MikeBellerue** [jimsalterjrs/sanoid#23]
It looks like Syncoid is supposed to check to see if the script is running with root privileges, and if not, use sudo to escalate.

When installed on a distribution that does not have sudo installed, Syncoid fails to check properly, and despite being run as root, it fails to send the snapshots to their destination. I was using Proxmox 4.0 when I encountered this. A quick apt-get install sudo fixes the issue. I was ssh'd in as root rather than su'ing to root, if that makes a difference.

**Comment by silviuvulcan** [comment]
Same happens with a FreeNAS remote - sudo is not in the *hardcoded* path

**Comment by silviuvulcan** [comment]
Also I checked the code and it initially checks properly and sets $isroot correctly, but then it fails to do the same inside functions.

**Comment by jimsalterjrs** [comment]
Looks like this was fixed at some point and I just forgot to close this issue - while testing @hrast01's #118, I ran with `--debug` and saw that `sudo` is no longer being called unnecessarily.
