### ISSUE TITLE
--quiet to suppress ZFS warning?

### ISSUE THREAD

**Issue by candlerb** [jimsalterjrs/sanoid#234]
Running syncoid from cron with `--quiet` under Ubuntu 16.04, the following warning still appears:

```
WARN: ZFS resume feature not available on source and target machine - sync will continue without resume support.
```

and therefore cron sends mail.

Should perhaps `--quiet` should suppress such warnings?  Or I could just run it under `cronic`.

**Comment by phreaker0** [comment]
@candlerb 
you could add --no-resume flag, so resume support is disabled completely

**Comment by candlerb** [comment]
Good point! (As long as I remember to remove it after moving to Ubuntu 18.04, which has ZOL 0.7+)
