### ISSUE TITLE
Running syncoid more than once causes replication to disappear

### ISSUE THREAD

**Issue by rjsears** [jimsalterjrs/sanoid#237]
I am running the latest versions of both sanoid and syncoid. I have sanoid set like this:

    /etc/sanoid.conf

    [rpool]
        use_template = production
        recursive = yes

    [template_production]
            hourly = 36
            daily = 31
            monthly = 12
            yearly = 6
            autosnap = yes
            autoprune = yes

When I initiall run sanoid it creates all of the snapshots that have been requested. When issuing the command `zfs list -t snap` I can see all of the snapshots. I am able to clones these snapshots, they work fine.

Once I had that all setup, I tried to impliment syncoid with the commad `syncoid -r rpool spinning/backups` where `spinning/backups` is a separate pool on the same system. On the initial run of syncoid it behaved exactly as expected, and I was able to see the replicated filesystem and all files, etc as expected. I was able to jump over to the backup pool and see everything as if it were the actual pool.

    root@pve:~# df -h
    Filesystem                   Size  Used Avail Use% Mounted on
    udev                          63G     0   63G   0% /dev
    rpool/ROOT/pve-1             914G  869M  913G   1% /
    rpool                        913G  128K  913G   1% /rpool
    rpool/ROOT                   913G  128K  913G   1% /rpool/ROOT
    rpool/data                   913G  128K  913G   1% /rpool/data
    spinning                     8.8T     0  8.8T   0% /spinning
    spinning/backups             8.8T     0  8.8T   0% /spinning/backups
    spinning/backups/ROOT        8.8T     0  8.8T   0% /spinning/backups/ROOT
    spinning/backups/ROOT/pve-1  8.8T  1.6G  8.8T   1% /spinning/backups/ROOT/pve-1
    spinning/backups/data        8.8T     0  8.8T   0% /spinning/backups/data
    root@pve:~#

    root@pve:~# ls -al /spinning/backups/ROOT/pve-1/
    total 124
    drwxr-xr-x 23 root root  23 Jun 19 13:18 .
    drwxr-xr-x  3 root root   3 Jun 19 14:47 ..
    drwxr-xr-x  2 root root 155 Jun 19 13:06 bin
    drwxr-xr-x  5 root root  11 Jun 19 12:32 boot
    drwxr-xr-x  5 root root  16 May 16 01:13 dev
    drwxr-xr-x 93 root root 181 Jun 19 14:03 etc
    drwxr-xr-x  2 root root   2 Feb 23 15:23 home
    drwxr-xr-x 19 root root  33 Jun 19 12:31 lib
    drwxr-xr-x  2 root root   3 May 16 01:12 lib64
    drwxr-xr-x  2 root root   2 May 16 01:12 media
    drwxr-xr-x  2 root root   2 May 16 01:12 mnt
    drwxr-xr-x  2 root root   2 May 16 01:12 opt
    drwxr-xr-x  2 root root   2 Feb 23 15:23 proc
    drwx------  4 root root  14 Jun 19 14:33 root
    drwxr-xr-x  2 root root   2 Jun 19 12:36 rpool
    drwxr-xr-x 15 root root  18 Jun 19 12:32 run
    drwxr-xr-x  2 root root 223 Jun 19 13:06 sbin
    drwxr-xr-x  2 root root   2 Jun 19 13:18 spinning
    drwxr-xr-x  2 root root   2 May 16 01:12 srv
    drwxr-xr-x  2 root root   2 Feb 23 15:23 sys
    drwxrwxrwt  8 root root   8 Jun 19 14:18 tmp
    drwxr-xr-x 10 root root  10 May 16 01:12 usr
    drwxr-xr-x 11 root root  13 May 16 01:12 var
    root@pve:~# 

However, as soon as I run it a second time, I am no longer able to get to any replicated data and it simply appears to disappear from the filesystem:

    root@pve:~# syncoid -r rpool spinning/backups
    Sending incremental rpool@syncoid_pve_2018-06-19:14:47:28 ... syncoid_pve_2018-06- 
    19:14:57:25 (~ 4 KB):
    1.52KiB 0:00:00 [87.8KiB/s]             
    Sending incremental rpool/ROOT@syncoid_pve_2018-06-19:14:47:30 ... syncoid_pve_2018-06- 
    19:14:57:26 (~ 4 KB):
    1.52KiB 0:00:00 [90.9KiB/s]             
    Sending incremental rpool/ROOT/pve-1@syncoid_pve_2018-06-19:14:47:32 ... syncoid_pve_2018- 
    06-19:14:57:26 (~ 4.1 MB):
    4.19MiB 0:00:00 [21.7MiB/s]           
    Sending incremental rpool/data@syncoid_pve_2018-06-19:14:47:43 ... syncoid_pve_2018-06- 
    19:14:57:27 (~ 4 KB):
    1.52KiB 0:00:00 [74.2KiB/s]        
    Sending incremental rpool/swap@syncoid_pve_2018-06-19:14:47:45 ... syncoid_pve_2018-06- 
    19:14:57:28 (~ 4 KB):
    1.52KiB 0:00:00 [88.6KiB/s]         
    root@pve:~# 

    root@pve:~# ls -al /spinning/backups/ROOT/pve-1/
    ls: cannot access '/spinning/backups/ROOT/pve-1/': No such file or directory
    root@pve:~# 

    root@pve:~# df -h
    Filesystem        Size  Used Avail Use% Mounted on
    rpool/ROOT/pve-1  914G  869M  913G   1% /
    rpool             913G  128K  913G   1% /rpool
    rpool/ROOT        913G  128K  913G   1% /rpool/ROOT
    rpool/data        913G  128K  913G   1% /rpool/data
    spinning          8.8T  128K  8.8T   1% /spinning
    spinning/backups  8.8T  128K  8.8T   1% /spinning/backups
    root@pve:~# 

Perhaps I am not running it correctly, or maybe there is some other issue. Any help would be greatly appreciated.

**Comment by jimsalterjrs** [comment]
Looks like some of your datasets are not mounted. `zfs mount spinning/backups/ROOT ; zfs mount spinning/backups/ROOT/pve-1` should sort you out.

I'd recommend using `zfs list` to look for datasets rather than `df`, for exactly this reason. `df` only shows you currently *mounted* filesystems, not all *available* filesystems (in this case, datasets count as filesystems).

**Comment by rjsears** [comment]
Jim - 

Thank you for your quick reply. 

I do use zfs list and see that it is there, but maybe I don't understand the operation of syncoid (or maybe the underlying zfs). 

Why would syncoid unmount a mounted system? The first time I run snycoid it replicates the pool AND mounts it as shown above. The second time I run it is replicates (I assume based on the debug) but then does not mount it? 

Is this the intended way it operates?

Thanks!

**Comment by rjsears** [comment]
Well, now that I know what is happening I know what to look for and its not a problem! Thanks again for your quick reply and fantastic toolset!
