### ISSUE TITLE
FreeBSD and SmartOS support

### ISSUE THREAD

**Issue by cahukS** [jimsalterjrs/sanoid#24]
Could you please add FreeBSD and SmartOS support? Sanoid works for me on FreeBSD 10.2 after I changed the paths for the external commands sanoid/syncoid is using but it would be great if Sanoid would support these OSs by default.

**Comment by cedrictineo** [comment]
Is there a doc somewhere for installing, configuring and runing sanoid + syncoid on FreeBSD (9.3 or 10.2) - I see notes around here about changing the source to make it compatible with freebsd's path, any recap of what needs to be done for FreeBSD?

**Comment by cahukS** [comment]
I don't know if there is a documentation for Sanoid + FreeBSD. 

I only changed the path for Perl in the shebang of the `sanoid`/`syncoid` commands (to #!/usr/local/bin/perl) and the path for `pv`, `mbuffer`, `sudo` and`lzop` in the `sanoid`/`syncoid` commands.

**Comment by jimsalterjrs** [comment]
Changing shebang path for FreeBSD is no longer necessary, as of 1.4.5.

Working on path detection issues for `pv`, `lzop` and friends.

Install documentation needs to happen too.  Will work on that as well.
