### ISSUE TITLE
Cannot mount: filename too long (FreeBSD)

### ISSUE THREAD

**Issue by caliston** [jimsalterjrs/sanoid#240]
Using syncoid from an Ubuntu 18.04 machine to a FreeBSD 11.0 machine, the latter pulling:

` syncoid -r --dumpsnaps root@ceno.example.com:ceno/lxc pool/servers_zfs/ceno/lxc`

Fails with:

```
INFO: Sending oldest full snapshot ceno/lxc/images/db70d8bca321fe3fbf4b40606d5c863a649c21b4b1a02b72ecb98c1ccfa3990b@readonly (~ 261.9 MB) to new target filesystem:
 271MiB 0:00:30 [9.04MiB/s] [===================================================================================================================================] 103%            
cannot mount 'pool/servers_zfs/ceno/lxc/images/db70d8bca321fe3fbf4b40606d5c863a649c21b4b1a02b72ecb98c1ccfa3990b': File name too long
CRITICAL ERROR: /usr/bin/ssh     -S /tmp/syncoid-root-root@ceno.example.com-1530724219 root@ceno.example.com ' /sbin/zfs send '"'"'ceno/lxc/images/db70d8bca321fe3fbf4b40606d5c863a649c21b4b1a02b72ecb98c1ccfa3990b'"'"'@'"'"'readonly'"'"' | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 274659344 |  /sbin/zfs receive  -F 'pool/servers_zfs/ceno/lxc/images/db70d8bca321fe3fbf4b40606d5c863a649c21b4b1a02b72ecb98c1ccfa3990b' failed: 256 at /usr/bin/syncoid line 281.
```

[I think ](https://serverfault.com/questions/660588/file-name-too-long-mount-nfs) this might be a mount point length issue fixed by FreeBSD commit [r318736](https://svnweb.freebsd.org/base/head/?view=log&pathrev=318736) but that's not going to land until FreeBSD 12 comes out in 6 months.  

Even if this volume fails, it doesn't try and transfer the other volumes that come after it.

**Comment by phreaker0** [comment]
So the actually issue is that syncoid stops replicating at this point, because the actual issue is with FreeBSD, syncoid can't do much here, except using the "-u" flag, so received datasets aren't mounted.
