### ISSUE TITLE
Recursive doesn't work in template

### ISSUE THREAD

**Issue by NastyEbilPiwate** [jimsalterjrs/sanoid#257]
Config:

[tank/backup]
        use_template = 6month

[template_6month]
        hourly = 0
        daily = 0
        monthly = 6
        yearly = 0
        autosnap = yes
        autoprune = yes
        recursive = yes

I would expect this to take snapshots of tank/backup and all child datasets, but it only snapshots tank/backup itself. Moving the 'recursive = yes' line out of the template and into the tank/backup block then makes it work as expected. No error is generated to say that recursive doesn't work in a template - it simply does nothing. Using commit eeedf38d57217388330dc4aad17f867b4e265958.

**Comment by phreaker0** [comment]
@jimsalterjrs the "recursive" key is specially excluded to be used in templates, any specific reason for that?

**Comment by phreaker0** [comment]
that makes sense, thx. A warning would be good.

**Comment by zig** [comment]
Hi all,

sorry to comment in such an old closed issue, but I was surprised by this decision to disallow having `recursive` in a template, I have I think a legitimate use case, consider this example 

```
[rpool/VDISKS/n2ivm1]
        use_template = production

[bpool/BOOT]
        use_template = production,recursive
        # recursive can't be in template !!
        recursive = yes
        process_children_only = yes

[rpool/ROOT]
        use_template = production,recursive
        recursive = yes
        process_children_only = yes

[rpool/USERDATA]
        use_template = production,recursive
        recursive = yes
        process_children_only = yes

[template_production]
        frequently = 0
        hourly = 1
        daily = 30
        monthly = 1
        yearly = 1
        autosnap = yes
        autoprune = yes
        post_snapshot_script = /etc/sanoid/send.sh

[template_recursive]
        post_snapshot_script = /etc/sanoid/send.sh -r --skip-parent

```

If `recursive` was allowed in a template, I could have written this in a safer and shorter way like this :
```
[rpool/VDISKS/n2ivm1]
        use_template = production

[bpool/BOOT]
        use_template = production,recursive

[rpool/ROOT]
        use_template = production,recursive

[rpool/USERDATA]
        use_template = production,recursive

[template_production]
        frequently = 1
        hourly = 1
        daily = 30
        monthly = 1
        yearly = 1
        autosnap = yes
        autoprune = yes
        post_snapshot_script = /etc/sanoid/send.sh

[template_recursive]
        recursive = yes
        process_children_only = yes
        post_snapshot_script = /etc/sanoid/send.sh -r --skip-parent
```

What do you think about it ?
