### ISSUE TITLE
15 minute snapshots?

### ISSUE THREAD

**Issue by Anderath** [jimsalterjrs/sanoid#27]
It's not clear to me if I can do 15 minute snapshots with this or not.

My thinking is this:

I want to be able to provide a "psuedo-HA" environment where 2 hosts have enough storage for 2 different sets of VMs to replicate to each other as a "backup + DR" recovery solution.

So to illustrate:

Host A --Replicates VMs to Host B in the event this host goes down
VM1(Home server)
VM2(Home server)
VM3(Cold storage but ready for activation)
VM4(Cold storage but ready for activation)

Host B --Replicates VMs to Host A in the event this host goes down
VM3(Home server)
VM4(Home server)
VM1(Cold storage but ready for activation)
VM2(Cold storage but ready for activation)

In this scenario, I believe hourly snapshots may be going too far back when replicating with a syncoid cron running every hour to make sure each host holds each other hosts' VMs.

Edit: Made example a little bit clearer.

**Comment by jimsalterjrs** [comment]
Syncoid can do replication whenever you ask it to, and 15 minutes is not 
going to be too much overhead for the vast majority of environments.

Sanoid isn't currently set up to manage a 15 minute interval, but I'm 
willing to write the code if you want to commission that as a new 
feature.  Wouldn't be too expensive.  Once you commission it and I write 
it, it would go into the public codebase, and be maintained along with 
the rest of the code.

**Comment by Anderath** [comment]
I hereby commission this as a new feature(Or enhancement... either/or)!

To be honest, I'm fairly new to the open source world(Or github in general). Is there anything apart from testing it that I would need to do? If not, code on and I will vet the code! I've set this up on my work laptop running through a tinc VPN using syncoid every hour. I was thinking about doing some craft pipes through notify-send so I know when a replication fails or the snapshots aren't syncing up for some reason so Sanoid can be run more on a desktop rather than strictly server to server.

I imagine since Sanoid runs every minute, it'll just look at the config file every quarter hour and scoop up another snapshot. With the beautfy of copy on write, it'll just leave down a marker at that point and, wallah, I have my psuedo poor-man's HA failover. As long as 15 minutes in a business day is an acceptable loss(Plus the boot time of whatever VM you're running) then this would be a fairly optimal solution based around ZFS.

**Comment by jimsalterjrs** [comment]
OK, this is awkward.

"Commission" means "offer to pay for development of".  I'm probably not 
going to spontaneously write 15-minute interval code anytime soon.  I'm 
willing to review your code if you write it and merge it if it meets 
standards, or write it myself if paid to. Sorry!

Another option would be to leave sanoid the way it is, and simply 
syncoid more frequently.  You'd lose the last 15-minute snapshot every 
time you successfully replicated, but your "most recent snapshot" would 
always be the syncoid snapshot from the last replication, which would be 
inside the window you're looking for.

*/4 * * * * syncoid -r data/images root@otherbox:data/images

That line in your crontab would get you your normal list of 
sanoid-maintained snapshots as per policy, plus your most recent 
snapshot being the syncoid snapshot from your most recent replication, 
with a new replication happening at x:0, x:15, x:30, and x:45.

**Comment by jimsalterjrs** [comment]
no further activity since March, so I'm closing this one #wontfix.  If anybody wants to commission it, let me know and we can reopen.  Also open to pull requests implementing this, but until then, closing.

**Comment by andymarigold** [comment]
Can you give an indication of how much it will be to implement this "minute based" feature ?

I am happy with the "syncoid -r" way of doing less than one hour backups, but I don't mind contributing financially if it is not too expensive.

**Comment by ondratra** [comment]
For anyone encountering this topic, sub-hour backups can nowadays be achieved via `frequently` and `frequent_period` settings.
