### ISSUE TITLE
syncoid -> file on ext4

### ISSUE THREAD

**Issue by mac-linux-free** [jimsalterjrs/sanoid#278]
Could I use syncoid to send to a file...perhaps gziped?

Thank you.

**Comment by redmop** [comment]
You COULD do it by creating a loopback file and making ZFS in it, but that is terribly messy.  Don't do that.

Otherwise, no.

**Comment by mac-linux-free** [comment]
like this here https://unix.stackexchange.com/questions/113743/zfs-snapshot-to-file-as-backup-with-rotation just for archiving purposes

**Comment by redmop** [comment]
No. Sanoid does not do that. It is ZFS send to ZFS receive only.

**Comment by jimsalterjrs** [comment]
The question is, what would syncoid be accomplishing for you that a simple zfs send would not?

If you're just dumping snapshots to a file, I'm not sure why you need syncoid - or even something *like* syncoid - at all.

**Comment by redmop** [comment]
ZFS send to tape... That's all I have.

**Comment by mac-linux-free** [comment]
ok thank you all...I´m doing rsync to an external hdd for now...though zfs isn´t good for removable hdd

**Comment by redmop** [comment]
zfs send <snapshot> | borg --stdin might be a better solution for you. Note the lack of -I or -i in the zfs send. Borg does good dedup, compression, and encryption.

**Comment by mac-linux-free** [comment]
thanks redmop...trying this here https://github.com/scotte/borgsnap

**Comment by jimsalterjrs** [comment]
Or if you want lightweight and simple, `zfs send poolname/datasetname | gzip -3 > poolname-datasetname.gz` is really all it takes. Stick a datestamp on the filename if you want to get fancy; rely on the mtime of the file to figure out when it was made otherwise.
