### ISSUE TITLE
UNEXPECTED ERROR: target exists but has no matching snapshots 

### ISSUE THREAD

**Issue by c0mputerking** [jimsalterjrs/sanoid#28]
I am having the same problem as closed issue number 16 https://github.com/jimsalterjrs/sanoid/issues/16 see below ... hope im not missing something obvious ... there was mention of creating symlinks but i am just trying to do this locally for now. 

root@pve-2:/bpool/backups/openoid/home# /usr/local/bin/syncoid --debug apool/home bpool/backups/openoid/home
DEBUG: checking availability of /usr/bin/lzop on source...
DEBUG: checking availability of /usr/bin/lzop on target...
DEBUG: checking availability of /usr/bin/lzop on local machine...
DEBUG: checking availability of /usr/bin/mbuffer on source...
DEBUG: checking availability of /usr/bin/mbuffer on target...
DEBUG: checking availability of /usr/bin/pv on local machine...
DEBUG: syncing source apool/home to target bpool/backups/openoid/home.
DEBUG: checking to see if bpool/backups/openoid/home on  is already in zfs receive using  /bin/ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "  /sbin/zfs get -H name bpool/backups/openoid/home 2>&1 |"...
DEBUG: getting list of snapshots on apool/home using  /usr/bin/sudo /sbin/zfs get -Hpd 1 creation apool/home |...
DEBUG: getting list of snapshots on bpool/backups/openoid/home using  /usr/bin/sudo /sbin/zfs get -Hpd 1 creation bpool/backups/openoid/home |...
DEBUG: getting current value of readonly on bpool/backups/openoid/home...
  /sbin/zfs get -H readonly bpool/backups/openoid/home
DEBUG: setting readonly to on on bpool/backups/openoid/home...
  /sbin/zfs set readonly=on bpool/backups/openoid/home
UNEXPECTED ERROR: target exists but has no matching snapshots!

**Comment by jimsalterjrs** [comment]
You created bpool/backups/openoid/home before trying to replicate **to** it from apool/home.  So, just like the error says... it exists, but has no matching snapshots.

You need to _zfs destroy bpool/backups/openoid/home_, **then** _syncoid apool/home bpool/backups/openoid/home_.  It will create the dataset initially in a full replication from apool/home's oldest snapshot, then do an incremental replication to bring in the rest of apool/home's available snapshots.  From then on out, when you _syncoid apool/home bpool/backups/openoid/home_, it will do incremental replication only.

**Comment by jimsalterjrs** [comment]
added mollyguard to help newbies with this mistake in 1.4.6
