### ISSUE TITLE
Error trying to resume stream if snapshot deleted

### ISSUE THREAD

**Issue by fewenuga** [jimsalterjrs/sanoid#281]
I was forced to delete a snapshot due to a space constraint which I have no resolved, but when I go back to try to sync the folder, I am getting an error that I have no idea how to get around.  Any help would be appreciated.

syncoid -r storage/xcluster/home/mzhibo root@sn2:storage/xcluster/home/mzhibo
Resuming interrupted zfs send/receive from storage/xcluster/home/mzhibo to storage/xcluster/home/mzhibo (~ UNKNOWN remaining):
cannot resume send: 'storage/xcluster/home/mzhibo@syncoid_sn1.gacrc.uga.edu_2018-10-15:09:56:18' used in the initial send no longer exists
   0 B 0:00:28 [   0 B/s] [<=>                                                                                                     ]
cannot receive: failed to read from stream
CRITICAL ERROR:  /sbin/zfs send -t 1-1587db4a35-120-789c636064000310a501c49c50360710a715e5e7a69766a63040c1049eb233a5da0de10a40363b92bafca4acd4e412068699db98c0ea30e4d3d28a534b40327c70793624f9a4ca92d46220bda2dd451a9bfe927c882ba6beb338a9f96db14706923c27583e2f31379581a1b824bf28313d55bf2239a7b4b824b5483f233f37553fb72a233329dfa1b8322f393f3325be38cf502f3d31b92859af343d512f35a534dec8c0d042d7d040d7d0d4cac0d2cad4cccad082010e00e95a34ea | /usr/bin/pv -s 0 | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/ssh     -S /tmp/syncoid-root-root@sn2-1539869176 root@sn2 ' /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc |  /sbin/zfs receive -s -F '"'"'storage/xcluster/home/mzhibo'"'"'' failed: 256 at /usr/local/bin/syncoid line 354.

**Comment by fewenuga** [comment]
When I try the --no-stream I also get a critical error.

cannot receive: failed to read from stream
CRITICAL ERROR:  /sbin/zfs send -t 1-1587db4a35-120-789c636064000310a501c49c50360710a715e5e7a69766a63040c1049eb233a5da0de10a40363b92bafca4acd4e412068699db98c0ea30e4d3d28a534b40327c70793624f9a4ca92d46220bda2dd451a9bfe927c882ba6beb338a9f96db14706923c27583e2f31379581a1b824bf28313d55bf2239a7b4b824b5483f233f37553fb72a233329dfa1b8322f393f3325be38cf502f3d31b92859af343d512f35a534dec8c0d042d7d040d7d0d4cac0d2cad4cccad082010e00e95a34ea | /usr/bin/pv -s 0 | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/ssh     -S /tmp/syncoid-root-root@sn2-1539869592 root@sn2 ' /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc |  /sbin/zfs receive -s -F '"'"'storage/xcluster/home/mzhibo'"'"'' failed: 256 at /usr/local/bin/syncoid line 354.

**Comment by phreaker0** [comment]
@fewenuga you need to abort the resumed send. On the receiving side you have the state of an interrupted replication. Because you deleted the snapshots which was used for that it can't be resumed anymore. You need to execute:

zfs receive -A storage/xcluster/home/mzhibo

on the target host and it will work again.
I'm planning to handle those types of failure automatically but as of now I haven't figured out how to reliable capture the output of the zfs commands and parse them for those types of errors.

**Comment by fewenuga** [comment]
Now I an getting the 
CRITICAL ERROR: Target storage/xcluster/home/mzhibo exists but has no snapshots matching with storage/xcluster/home/mzhibo!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.
which I have never figured out how to get past.

**Comment by phreaker0** [comment]
@fewenuga In this case you removed all common snapshots of the src and dst dataset and can't replicate anymore. Did you delete the syncoid snapshot manually?

**Comment by fewenuga** [comment]
The user ran out of space in their home directory so I was forced to nuke all their snapshots, syncoid included to give them back space.  I hadn't expected this issue when I ran our deletion script.

**Comment by phreaker0** [comment]
You should adapt your deletion script to exclude the syncoid snapshots, those shouldn't consume much space if syncoid is run regularly. Those snapshot are specially to guarantee matching snapshots for replication unless one manually destroys them. You have to start over with your replication now (i would rename the target dataset as backup, run the initial replication again and delete the renamed dataset after it finished sucessfully).

In the future one can also take advantage of bookmarks in this cases #247

**Comment by fewenuga** [comment]
I'm an idiot when it comes to this error, what command would I use to get past this?  Sorry for asking.




________________________________

**Comment by redmop** [comment]
@fewenuga You're not an idiot. You've just encountered a new experience. It happens. I still find gotchas after 4 years of ZFS.
