### ISSUE TITLE
Wrong ZFS Free Value showed by sanoid --monitor-health

### ISSUE THREAD

**Issue by gbonazzoli** [jimsalterjrs/sanoid#282]
On every Ubuntu 18.10 Server we managed, the following command:

```
root@srv-dr1:~# /usr/local/bin/sanoid --monitor-health
OK ZPOOL vgraid : ONLINE {Size:10.8T Free:7.48T Cap:30%} 
```
is reporting a wrong ZFS Free value. As you can see

```
root@srv-dr1:~# zfs list
NAME                                          USED  AVAIL  REFER  MOUNTPOINT
vgraid                                       2.68T  4.89T   140K  /vgraid
vgraid/apt-cacher-ng                         6.87G  4.89T  6.87G  /var/cache/apt-cacher-ng
vgraid/oraback                                615G  4.89T   615G  /oraback
vgraid/samba                                 1.77T  4.89T  4.00G  /vgraid/samba
vgraid/samba/SeaFile                         1.76T  4.89T  1.73T  /vgraid/samba/SeaFile
```
sanoid 1.4.18 says 7.48T instead of 4.89T

Regards

**Comment by phreaker0** [comment]
sanoid checks the pool properties (raid parity space is also considered as storage space there):

`zpool list`

**Comment by bforpc** [comment]
so what is the different between the 2 outputs (and how it can be used in real)?

**Comment by phreaker0** [comment]
@bforpc 
zfs list shows you the usable space for datasets/..., zpool list shows you the physically usable space. From the manpage:
```
used                Amount of storage space used within the pool.

   The  space  usage properties report actual physical space available to the storage pool. The physical
   space can be different from the total amount of space that any contained datasets can  actually  use.
   The  amount  of  space used in a raidz configuration depends on the characteristics of the data being
   written. In addition, ZFS reserves some space for internal accounting that the zfs(8)  command  takes
   into  account, but the zpool command does not. For non-full pools of a reasonable size, these effects
   should be invisible. For small pools, or pools that are close to being completely  full,  these  dis-
   crepancies may become more noticeable.
```

**Comment by gbonazzoli** [comment]
Ok, 

It's now crystal clear !

But, in my opinion, the Physical Free Disk Space can be misleading because it is not directly comparable between hosts due to different disk's parity, different redundant hot spares etc.

It would be better yo have metrics that show values (such as logical free space, number of sanoid snapshots, last taken snapshot) of each and only each dataset managed by sanoid.

But this is out of scope the current issue.

**Comment by phreaker0** [comment]
@gbonazzoli monitor-health isn't really for checking space usage but for errors. There is another flag for that "--monitor-capacity", they actual used/available space could be integrated there.
