### ISSUE TITLE
--quiet doesn't supress (all) non-error output

### ISSUE THREAD

**Issue by hillsy** [jimsalterjrs/sanoid#283]
I run sanoid from cron like so: `*/15 * * * * TZ=UTC /usr/local/sbin/sanoid --cron --quiet`

Running code from master as of commit 22160deb8ec300a9ef5e4c1c61e5133c46b1f2cc.

It seems to work fine, except we get the occasional message "INFO: deferring pruning of `<ZFS details redacted>` is currently in zfs send or receive".

This isn't **really** an error condition; it's a consequence of the amount of data we occasionally sync (using syncoid) and is expected behaviour. But it's a bit annoying as cron job errors are automatically emailed to our whole team.

I was going to log this as a feature request, but looking around line 297 it seems like $args{'verbose'} is checked prior to printing this message, and $args{'verbose'} **ought** to be 0 if --cron and --quiet flags are passed (AFAICT - not a Perl guy here). So maybe it's a bug? Of course it's also possible I'm doing something wrong...

**Comment by phreaker0** [comment]
@hillsy Make really sure that you are running the version you stated. The line in question was hidden behind verbose after that commit 742db32e686520dc22ea11a8f831ed15618fdf9c.
Maybe /usr/local/sbin/sanoid was overwritten by a package manager upgrade or something?

**Comment by hillsy** [comment]
Hmm. We have it on several boxes; I didn't actually take a note of which box the message came from and it's possible one of them had an old version.

I've redeployed on all machines now so they should definitely **all** be on that version. Will give it a day or so's running to see if the messages keep appearing.
