### ISSUE TITLE
Workaround for "Corwardly refusing" error.

### ISSUE THREAD

**Issue by spadazz** [jimsalterjrs/sanoid#285]
Hello,
I'm no expert in syncoid / zfs so, I ask forgiveness if I'm missing something obvious, But...
I'm using syncoid 1.4.18 in a proxmox server with openzfs only to send snapshot to a backup server.
Not using sanoid to take snapshot, but a script in crontab.
Usually it works, but last night the receiving server had problems and backup activity was stuck.
After reboot, I was not able to restart the backup of a dataset via syncoid because of the error "Cowardly refusing to destroy your existing target".

The last snapshot in backup server is:
tank/syncoid/subvol-216-disk-1@2018-10-25_00:15

While in the the source server I have the following snapshot but not the same:
tank/subvol-216-disk-1@2018-10-25_00:30

(snapshot are take every 15 min.)

I tried to match both sides before rerun syncoid, doing something like this : 
zfs send tank/subvol-216-disk-1@2018-10-25_00:30 | pv | ssh xxx@backup zfs recv -n -F tank/syncoid/subvol-216-disk-1@2018-10-25_00:30

But it gives the error:
cannot receive new filesystem stream: destination has snapshot, must destroy the to overwrite.

But destroy all backup snapshots isn't an option to me, also due to the large amount of data to backup everything.

How can I fix this and restart only from 00:30 --> forward ?

Thanks a lot

**Comment by spadazz** [comment]
P.S: I'm running syncoid with the --no-sync-snap option, since I'm using existing snapshot to do the incremental backup.

**Comment by phreaker0** [comment]
The full error message states that there are no matching snapshots between the two datasets any more so zfs replication won't work here. You need to retransmit the whole zfs dataset again and make sure that you don't remove the last matching snapshot in the future (Either by fixing your wrapper scripts or by using the syncoid managed snapshots).

**Comment by carrchr** [comment]
hi @phreaker0 pardon my ignorance but I am in the same exact situation as spadazz.  
What is the easiest way to "retransmit the whole zfs dataset again"? Just `destroy` the datasets on the remote? or is there a command in `syncoid` that can do a one-time "force re-sync"?

**Comment by jimsalterjrs** [comment]
Destroy the datasets on the remote side.
