### ISSUE TITLE
How can I make --exclude to work ?

### ISSUE THREAD

**Issue by peter-held** [jimsalterjrs/sanoid#288]
Hi,

I'm using this command line for syncoid and the --exclude is not working:
SYNCOID_COMMON_OPTS="--sshport=2222 --recursive --no-sync-snap --exclude='hourly'"

Thanks.

**Comment by phreaker0** [comment]
@peter-held the --exclude option works for excluding datasets but not snapshots, based on your exclude option I guess you expected it to work for snapshots.

**Comment by peter-held** [comment]
I understand.
Is it possible to exclude snapshots ?

**Comment by phreaker0** [comment]
not yet, but there is already a feature request here: #153

**Comment by peter-held** [comment]
Thanks.
