### ISSUE TITLE
Create newer release

### ISSUE THREAD

**Issue by fryfrog** [jimsalterjrs/sanoid#29]
Hey, I made https://aur.archlinux.org/packages/sanoid/ and noticed that the 1.0.8 release is a bit old. Any chance there is a stable point between now and it that is worth releasing? :)

**Comment by jimsalterjrs** [comment]
All code in main should be considered release quality. If I haven't tested 
it, it doesn't push to main.

----------

(Sent from my phone - please blame any weird errors on autocorrect)

**Comment by jimsalterjrs** [comment]
v1.4.4 pushed to new release.  I still don't promise to remember to do this every time I push to main though. =)
