### ISSUE TITLE
snapshots not removed

### ISSUE THREAD

**Issue by peter-held** [jimsalterjrs/sanoid#293]
Hi,

Because I need pull mode for backups, I switched from znapzend to sanoid.
I created a script to rename the snapshots from znapzend format to sanoid.
The problem is that sanoid doesn't want to clean the renamed snapshots:

Filesystem rpool/ROOT/ubuntu has:
     71 total snapshots (newest: 18.1 hours old)
          7 daily
              desired: 7
              newest: 42.1 hours old, named autosnap_2018-11-21_00:00:00_daily
          63 monthly
              desired: 3
              newest: 738.1 hours old, named autosnap_2018-10-23_00:00:00_monthly
          1 hourly
              desired: 24
              newest: 18.1 hours old, named autosnap_2018-11-22_00:00:00_hourly

Do you have any idea why ?

Thanks.

**Comment by phreaker0** [comment]
@peter-held please post the used sanoid command and please run:

`sanoid --debug --prune-snapshots`

and post the output please.

**Comment by peter-held** [comment]
# sanoid --debug --prune-snapshots
DEBUG: initializing $config{rpool/ROOT/ubuntu} with default values from /etc/sanoid/sanoid.defaults.conf.
DEBUG: overriding autosnap on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding autoprune on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding hourly on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding daily on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding monthly on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding yearly on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: getting list of child datasets on rpool/ROOT/ubuntu using  /sbin/zfs list -o name -Hr rpool/ROOT/ubuntu |...
DEBUG: recursively setting yearly_mon from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting autoprune from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting path from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting min_percent_free from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting capacity_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_hour from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_mday from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting capacity_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting autosnap from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_mday from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_hour from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monitor_dont_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monitor_dont_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monitor from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_hour from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
****** CONFIGS ******
$VAR1 = {
          'rpool/ROOT/ubuntu' => {
                                   'autoprune' => 1,
                                   'autosnap' => 1,
                                   'capacity_crit' => '95',
                                   'capacity_warn' => '80',
                                   'daily' => '7',
                                   'daily_crit' => '32',
                                   'daily_hour' => '23',
                                   'daily_min' => '59',
                                   'daily_warn' => '28',
                                   'hourly' => '24',
                                   'hourly_crit' => '360',
                                   'hourly_min' => '0',
                                   'hourly_warn' => '90',
                                   'initialized' => 1,
                                   'min_percent_free' => '10',
                                   'monitor' => 1,
                                   'monitor_dont_crit' => 0,
                                   'monitor_dont_warn' => 0,
                                   'monthly' => '3',
                                   'monthly_crit' => '35',
                                   'monthly_hour' => '0',
                                   'monthly_mday' => '1',
                                   'monthly_min' => '0',
                                   'monthly_warn' => '32',
                                   'path' => 'rpool/ROOT/ubuntu',
                                   'yearly' => '0',
                                   'yearly_crit' => '0',
                                   'yearly_hour' => '0',
                                   'yearly_mday' => '1',
                                   'yearly_min' => '0',
                                   'yearly_mon' => '1',
                                   'yearly_warn' => '0'
                                 }
        };

Filesystem rpool/ROOT/ubuntu has:
     71 total snapshots (newest: 18.4 hours old)
          63 monthly
              desired: 3
              newest: 738.4 hours old, named autosnap_2018-10-23_00:00:00_monthly
          7 daily
              desired: 7
              newest: 42.4 hours old, named autosnap_2018-11-21_00:00:00_daily
          1 hourly
              desired: 24
              newest: 18.4 hours old, named autosnap_2018-11-22_00:00:00_hourly


INFO: pruning snapshots...

**Comment by peter-held** [comment]
Latest commit from master.

**Comment by peter-held** [comment]
# zfs get -r -Hpt snapshot creation rpool/ROOT/ubuntu | grep monthly
rpool/ROOT/ubuntu@autosnap_2018-08-23_00:00:00_monthly  creation        1534982400      -
rpool/ROOT/ubuntu@autosnap_2018-08-24_00:00:00_monthly  creation        1535068800      -
rpool/ROOT/ubuntu@autosnap_2018-08-25_00:00:00_monthly  creation        1535155200      -
rpool/ROOT/ubuntu@autosnap_2018-08-26_00:00:00_monthly  creation        1535241600      -
rpool/ROOT/ubuntu@autosnap_2018-08-27_00:00:00_monthly  creation        1535328000      -
rpool/ROOT/ubuntu@autosnap_2018-08-28_00:00:00_monthly  creation        1535414400      -
rpool/ROOT/ubuntu@autosnap_2018-08-29_00:00:00_monthly  creation        1535500800      -
rpool/ROOT/ubuntu@autosnap_2018-08-30_00:00:00_monthly  creation        1535587200      -
rpool/ROOT/ubuntu@autosnap_2018-08-31_00:00:00_monthly  creation        1535673601      -
rpool/ROOT/ubuntu@autosnap_2018-09-01_00:00:00_monthly  creation        1535760000      -
rpool/ROOT/ubuntu@autosnap_2018-09-02_00:00:00_monthly  creation        1535846400      -
rpool/ROOT/ubuntu@autosnap_2018-09-03_00:00:00_monthly  creation        1535932800      -
rpool/ROOT/ubuntu@autosnap_2018-09-04_00:00:00_monthly  creation        1536019200      -
rpool/ROOT/ubuntu@autosnap_2018-09-05_00:00:00_monthly  creation        1536105600      -
rpool/ROOT/ubuntu@autosnap_2018-09-06_00:00:00_monthly  creation        1536192000      -
rpool/ROOT/ubuntu@autosnap_2018-09-07_00:00:00_monthly  creation        1536278400      -
rpool/ROOT/ubuntu@autosnap_2018-09-08_00:00:00_monthly  creation        1536364800      -
rpool/ROOT/ubuntu@autosnap_2018-09-09_00:00:00_monthly  creation        1536451200      -
rpool/ROOT/ubuntu@autosnap_2018-09-10_00:00:00_monthly  creation        1536537600      -
rpool/ROOT/ubuntu@autosnap_2018-09-11_00:00:00_monthly  creation        1536624000      -
rpool/ROOT/ubuntu@autosnap_2018-09-12_00:00:00_monthly  creation        1536710400      -
rpool/ROOT/ubuntu@autosnap_2018-09-13_00:00:00_monthly  creation        1536796800      -
rpool/ROOT/ubuntu@autosnap_2018-09-14_00:00:00_monthly  creation        1536883200      -
rpool/ROOT/ubuntu@autosnap_2018-09-15_00:00:00_monthly  creation        1536969600      -
rpool/ROOT/ubuntu@autosnap_2018-09-16_00:00:00_monthly  creation        1537056000      -
rpool/ROOT/ubuntu@autosnap_2018-09-17_00:00:00_monthly  creation        1537142400      -
rpool/ROOT/ubuntu@autosnap_2018-09-18_00:00:00_monthly  creation        1537228800      -
rpool/ROOT/ubuntu@autosnap_2018-09-19_00:00:00_monthly  creation        1537315200      -
rpool/ROOT/ubuntu@autosnap_2018-09-20_00:00:00_monthly  creation        1537401600      -
rpool/ROOT/ubuntu@autosnap_2018-09-21_00:00:00_monthly  creation        1537488000      -
rpool/ROOT/ubuntu@autosnap_2018-09-22_00:00:00_monthly  creation        1537574400      -
rpool/ROOT/ubuntu@autosnap_2018-09-23_00:00:00_monthly  creation        1537660800      -
rpool/ROOT/ubuntu@autosnap_2018-09-24_00:00:00_monthly  creation        1537747200      -
rpool/ROOT/ubuntu@autosnap_2018-09-25_00:00:00_monthly  creation        1537833600      -
rpool/ROOT/ubuntu@autosnap_2018-09-26_00:00:00_monthly  creation        1537920000      -
rpool/ROOT/ubuntu@autosnap_2018-09-27_00:00:00_monthly  creation        1538006400      -
rpool/ROOT/ubuntu@autosnap_2018-09-28_00:00:00_monthly  creation        1538092800      -
rpool/ROOT/ubuntu@autosnap_2018-09-29_00:00:00_monthly  creation        1538179200      -
rpool/ROOT/ubuntu@autosnap_2018-09-30_00:00:00_monthly  creation        1538265600      -
rpool/ROOT/ubuntu@autosnap_2018-10-01_00:00:00_monthly  creation        1538352000      -
rpool/ROOT/ubuntu@autosnap_2018-10-02_00:00:00_monthly  creation        1538438400      -
rpool/ROOT/ubuntu@autosnap_2018-10-03_00:00:00_monthly  creation        1538524800      -
rpool/ROOT/ubuntu@autosnap_2018-10-04_00:00:00_monthly  creation        1538611200      -
rpool/ROOT/ubuntu@autosnap_2018-10-05_00:00:00_monthly  creation        1538697600      -
rpool/ROOT/ubuntu@autosnap_2018-10-06_00:00:00_monthly  creation        1538784000      -
rpool/ROOT/ubuntu@autosnap_2018-10-07_00:00:00_monthly  creation        1538870400      -
rpool/ROOT/ubuntu@autosnap_2018-10-08_00:00:00_monthly  creation        1538956800      -
rpool/ROOT/ubuntu@autosnap_2018-10-09_00:00:00_monthly  creation        1539043200      -
rpool/ROOT/ubuntu@autosnap_2018-10-10_00:00:00_monthly  creation        1539129600      -
rpool/ROOT/ubuntu@autosnap_2018-10-11_00:00:00_monthly  creation        1539216000      -
rpool/ROOT/ubuntu@autosnap_2018-10-12_00:00:00_monthly  creation        1539302400      -
rpool/ROOT/ubuntu@autosnap_2018-10-13_00:00:00_monthly  creation        1539388800      -
rpool/ROOT/ubuntu@autosnap_2018-10-14_00:00:00_monthly  creation        1539475200      -
rpool/ROOT/ubuntu@autosnap_2018-10-15_00:00:00_monthly  creation        1539561600      -
rpool/ROOT/ubuntu@autosnap_2018-10-16_00:00:00_monthly  creation        1539648000      -
rpool/ROOT/ubuntu@autosnap_2018-10-17_00:00:00_monthly  creation        1539734400      -
rpool/ROOT/ubuntu@autosnap_2018-10-18_00:00:00_monthly  creation        1539820800      -
rpool/ROOT/ubuntu@autosnap_2018-10-19_00:00:00_monthly  creation        1539907200      -
rpool/ROOT/ubuntu@autosnap_2018-10-20_00:00:00_monthly  creation        1539993600      -
rpool/ROOT/ubuntu@autosnap_2018-10-21_00:00:00_monthly  creation        1540080000      -
rpool/ROOT/ubuntu@autosnap_2018-10-22_00:00:00_monthly  creation        1540166400      -
rpool/ROOT/ubuntu@autosnap_2018-10-23_00:00:00_monthly  creation        1540252800      -
rpool/ROOT/ubuntu@autosnap_2018-11-22_18:30:02_monthly  creation        1542911405      -

**Comment by phreaker0** [comment]
okay, so create time is also correct, so I need more debugging information as I don't really now whats wrong, can you patch sanoid to provide more info for me by running the following command in the directory where sanoid is located. After that please run the prune command again and post the output:

```
bind "set disable-completion on"
cat << 'EOF' | patch -p1
diff --git a/sanoid b/sanoid
index 7ae1b5b..dff8d34 100755
--- a/sanoid
+++ b/sanoid
@@ -247,12 +247,15 @@ sub prune_snapshots {
 	my $forcecacheupdate = 0;
 
 	foreach my $section (keys %config) {
+		if ($args{'verbose'}) { print "DEBUG1: $section\n"; }
 		if ($section =~ /^template/) { next; }
 		if (! $config{$section}{'autoprune'}) { next; }
 		if ($config{$section}{'process_children_only'}) { next; }
 
 		my $path = $config{$section}{'path'};
 
+		if ($args{'verbose'}) { print "DEBUG2: $path\n"; }
+
 		my $period = 0;
 
 		foreach my $type (keys %{ $config{$section} }){
@@ -264,6 +267,8 @@ sub prune_snapshots {
 			elsif ($type eq 'monthly') { $period = 60*60*24*31; }
 			elsif ($type eq 'yearly') { $period = 60*60*24*365.25; }
 
+			if ($args{'verbose'}) { print "DEBUG3: $type $period\n"; }
+
 			# avoid pissing off use warnings by not executing this block if no matching snaps exist
 			if (defined $snapsbytype{$path}{$type}{'sorted'}) {
 				my @sorted = split (/\|/,$snapsbytype{$path}{$type}{'sorted'});
@@ -276,9 +281,12 @@ sub prune_snapshots {
 				# how many total snaps of this type do we currently have?
 				my $numsnapsthistype = scalar (@sorted);
 
+				if ($args{'verbose'}) { print "DEBUG4: $maxage $minsnapsthistype $numsnapsthistype\n"; }
+
 				my @prunesnaps;
 				foreach my $snap( @sorted ){
 					# print "snap $path\@$snap has age $snaps{$path}{$snap}{'ctime'}, maxage is $maxage.\n";
+					if ($args{'verbose'}) { print "DEBUG5: $snaps{$path}{$snap}{'ctime'}\n"; }
 					if ( ($snaps{$path}{$snap}{'ctime'} < $maxage) && ($numsnapsthistype > $minsnapsthistype) ) {
 						my $fullpath = $path . '@' . $snap;
 						push(@prunesnaps,$fullpath);

EOF
bind "set disable-completion off"

```

**Comment by peter-held** [comment]
# sanoid --debug --prune-snapshots
DEBUG: initializing $config{rpool/ROOT/ubuntu} with default values from /etc/sanoid/sanoid.defaults.conf.
DEBUG: overriding autosnap on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding autoprune on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding hourly on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding daily on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding monthly on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: overriding yearly on rpool/ROOT/ubuntu with value from user-defined template template_common.
DEBUG: getting list of child datasets on rpool/ROOT/ubuntu using  /sbin/zfs list -o name -Hr rpool/ROOT/ubuntu |...
DEBUG: recursively setting monthly_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monitor_dont_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting autosnap from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting capacity_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monitor from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting capacity_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_hour from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_mday from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_hour from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_hour from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting path from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monitor_dont_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_mday from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting yearly_mon from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly_min from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting monthly_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting autoprune from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting daily_warn from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting hourly_crit from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
DEBUG: recursively setting min_percent_free from rpool/ROOT/ubuntu to rpool/ROOT/ubuntu.
****** CONFIGS ******
$VAR1 = {
          'rpool/ROOT/ubuntu' => {
                                   'autoprune' => 1,
                                   'autosnap' => 1,
                                   'capacity_crit' => '95',
                                   'capacity_warn' => '80',
                                   'daily' => '7',
                                   'daily_crit' => '32',
                                   'daily_hour' => '23',
                                   'daily_min' => '59',
                                   'daily_warn' => '28',
                                   'hourly' => '24',
                                   'hourly_crit' => '360',
                                   'hourly_min' => '0',
                                   'hourly_warn' => '90',
                                   'initialized' => 1,
                                   'min_percent_free' => '10',
                                   'monitor' => 1,
                                   'monitor_dont_crit' => 0,
                                   'monitor_dont_warn' => 0,
                                   'monthly' => '3',
                                   'monthly_crit' => '35',
                                   'monthly_hour' => '0',
                                   'monthly_mday' => '1',
                                   'monthly_min' => '0',
                                   'monthly_warn' => '32',
                                   'path' => 'rpool/ROOT/ubuntu',
                                   'yearly' => '0',
                                   'yearly_crit' => '0',
                                   'yearly_hour' => '0',
                                   'yearly_mday' => '1',
                                   'yearly_min' => '0',
                                   'yearly_mon' => '1',
                                   'yearly_warn' => '0'
                                 }
        };

Filesystem rpool/ROOT/ubuntu has:
     92 total snapshots (newest: 1.0 hours old)
          22 hourly
              desired: 24
              newest: 1.0 hours old, named autosnap_2018-11-23_14:00:16_hourly
          7 daily
              desired: 7
              newest: 15.0 hours old, named autosnap_2018-11-23_00:00:01_daily
          63 monthly
              desired: 3
              newest: 20.5 hours old, named autosnap_2018-11-22_18:30:02_monthly


INFO: pruning snapshots...
DEBUG1: rpool/ROOT/ubuntu
DEBUG2: rpool/ROOT/ubuntu
DEBUG3: yearly 31557600
DEBUG3: monthly 2678400
DEBUG4: 1534949855 3 63
DEBUG5: 1534982400
DEBUG5: 1535068800
DEBUG5: 1535155200
DEBUG5: 1535241600
DEBUG5: 1535328000
DEBUG5: 1535414400
DEBUG5: 1535500800
DEBUG5: 1535587200
DEBUG5: 1535673601
DEBUG5: 1535760000
DEBUG5: 1535846400
DEBUG5: 1535932800
DEBUG5: 1536019200
DEBUG5: 1536105600
DEBUG5: 1536192000
DEBUG5: 1536278400
DEBUG5: 1536364800
DEBUG5: 1536451200
DEBUG5: 1536537600
DEBUG5: 1536624000
DEBUG5: 1536710400
DEBUG5: 1536796800
DEBUG5: 1536883200
DEBUG5: 1536969600
DEBUG5: 1537056000
DEBUG5: 1537142400
DEBUG5: 1537228800
DEBUG5: 1537315200
DEBUG5: 1537401600
DEBUG5: 1537488000
DEBUG5: 1537574400
DEBUG5: 1537660800
DEBUG5: 1537747200
DEBUG5: 1537833600
DEBUG5: 1537920000
DEBUG5: 1538006400
DEBUG5: 1538092800
DEBUG5: 1538179200
DEBUG5: 1538265600
DEBUG5: 1538352000
DEBUG5: 1538438400
DEBUG5: 1538524800
DEBUG5: 1538611200
DEBUG5: 1538697600
DEBUG5: 1538784000
DEBUG5: 1538870400
DEBUG5: 1538956800
DEBUG5: 1539043200
DEBUG5: 1539129600
DEBUG5: 1539216000
DEBUG5: 1539302400
DEBUG5: 1539388800
DEBUG5: 1539475200
DEBUG5: 1539561600
DEBUG5: 1539648000
DEBUG5: 1539734400
DEBUG5: 1539820800
DEBUG5: 1539907200
DEBUG5: 1539993600
DEBUG5: 1540080000
DEBUG5: 1540166400
DEBUG5: 1540252800
DEBUG5: 1542911405
DEBUG3: daily 86400
DEBUG4: 1542380255 7 7
DEBUG5: 1542412800
DEBUG5: 1542499200
DEBUG5: 1542585600
DEBUG5: 1542672000
DEBUG5: 1542758400
DEBUG5: 1542911404
DEBUG5: 1542931204
DEBUG3: hourly 3600
DEBUG4: 1542898655 24 22
DEBUG5: 1542844800
DEBUG5: 1542911402
DEBUG5: 1542913202
DEBUG5: 1542916803
DEBUG5: 1542920402
DEBUG5: 1542924017
DEBUG5: 1542927603
DEBUG5: 1542931205
DEBUG5: 1542934802
DEBUG5: 1542938418
DEBUG5: 1542942002
DEBUG5: 1542945602
DEBUG5: 1542949218
DEBUG5: 1542952818
DEBUG5: 1542956403
DEBUG5: 1542960017
DEBUG5: 1542963616
DEBUG5: 1542967202
DEBUG5: 1542970804
DEBUG5: 1542974401
DEBUG5: 1542978018
DEBUG5: 1542981616

**Comment by phreaker0** [comment]
It makes sense now, didn't see it before without the extra debugging info: it seems you migrated/renamed you daily snapshots from before to monthly snapshots now. All your monthly snapshots are one day apart and are not older than 3 months's. You asked sanoid to keep at least 3 monthlies which for sanoid means:
* don't delete any snapshots if there are less or equal to 3 snapshots for this type
* don't delete any monthly snapshots which aren't older than 3 months (<--- this is the reason why nothing is pruned for your monthlies)
