### ISSUE TITLE
turn recursive off feature

### ISSUE THREAD

**Issue by chesty** [jimsalterjrs/sanoid#296]
Hi, Thanks for sanoid and synoid. I love you work.

I would like to turn on recursive for [rpool] and then turn it off for [rpool/var/lib/docker]

docker with the zfs driver creates temporary data sets with random names under rpool/var/lib/docker, ie rpool/var/lib/docker/0ef628b3cd1...., I  would like rpool/var/lib/docker to have snapshots, and rpool/var/lib/docker/volumes but not all the random temporary ones like rpool/var/lib/docker/0ef628b3cd1.... 

Eventually those random named data sets will be deleted, I don't really need them to be snapshot. I can't work out how to stop it after turning recursion on in [rpool].

If it's not an easy feature to add or doesn't seem needed by most people, no worries. I might be able to configure docker to create those temporary data sets somewhere else, I'm not sure yet, right now I'm not using recursive and listing the data sets explicitly. I'm just worried I might create a new data set and forget to update the sanoid config.

The another way I thought might work would be if I could use regular expression when listing data set names in the config, like [rpool/var/lib/docker/[0-9a-f]{64}] and turn off snapshots for matching data sets, but I don't think that's supported either.

**Comment by phreaker0** [comment]
@chesty 
you can try the linked PR I made, it implements what you need. Please test (a example configuration is in the PR description):-)

**Comment by chesty** [comment]
oh wow, cheers.
works perfectly. 
thanks.
