### ISSUE TITLE
Offset Snapshot Time

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#299]
Is there any way to add taking snapshots at a offset time?

For example, taking the hourly snapshots on X:05, dailies at 7:15a, and weeklies on Friday at 6:00p?

**Comment by phreaker0** [comment]
@redmop this is already possible look at the "sanoid.defaults.conf", for example for weeklies:

```
# weekly -at 23:30 each Monday
weekly_wday = 1
weekly_hour = 23
weekly_min = 30
```

**Comment by redmop** [comment]
Awesome. I must have missed that. Thanks for pointing that out.
