### ISSUE TITLE
Why do i get at source @syncoid and @autosnap

### ISSUE THREAD

**Issue by bforpc** [jimsalterjrs/sanoid#302]
Hi,

i run sanoid every hour on the source system. Why do i get @syncoid and @autosnap snapshots ?
Whats the difference?

bfo

**Comment by phreaker0** [comment]
sanoid takes snapshots with "autosnap" prefix and syncoid the replication tools creates "syncoid" prefixed snapshots to make sure that the replication always works (unless you use the --no-sync-snap option)

**Comment by bforpc** [comment]
Sorry for answer on this closed issue:
On the source machine is no syncoid running. So why there are being snaphots created?

bfo

**Comment by phreaker0** [comment]
syncoid creates the snapshot on both the target and the source, with ZFS you need a common snapshots to do incremental replication. If you just wan't to rely on your existing snapshots you can pass the no sync snap option but then you are in charge of making sure that there is a common snapshots between the source and target at all time.

**Comment by phreaker0** [comment]
This is just how ZFS incremental send/receive works. If there are no common snapshots on source and target anymore, an incremental send/receive doesn't work anymore. This is the reason why syncoid by default creates up to date snapshots on both source and target. After a successful replication it will remove the old onces, so at most there is one syncoid snapshot per dataset at all times (assuming replication succeeds each time).
