### ISSUE TITLE
sanoid v2.0.1 self-reports as v2.0.0

### ISSUE THREAD

**Issue by sysmray** [jimsalterjrs/sanoid#307]
The source package at https://github.com/jimsalterjrs/sanoid/archive/v2.0.1.tar.gz incorrectly has a version of "2.0.0" and reports that version on `sanoid --version`.

**Comment by jimsalterjrs** [comment]
Good point. Hmmm. I don't know of any way to fix it other than making ANOTHER release that's 2.0.2 which fixes literally nothing but the version string, though. Not sure that's worth it...

**Comment by sysmray** [comment]
I agree that it's not worth it by itself -- the next actual release seems completely reasonable
