### ISSUE TITLE
Don't hardcode perl path

### ISSUE THREAD

**Issue by fhriley** [jimsalterjrs/sanoid#31]
Syncoid hardcodes the path to perl:

#!/usr/bin/perl

Which doesn't work on some systems, e.g. freenas. Instead, use env:

#!/usr/bin/env perl

**Comment by jimsalterjrs** [comment]
Thank you for the bug report.  Fixed in 1.4.5.

**Comment by jimsalterjrs** [comment]
Reverted to original shebang in 1.4.7.  PATH is not set in environment for cron by default on any systems I'm aware of; setting the shebang to **#!/usr/bin/env perl** resulted in cron jobs not running at all on ANY system.

Added a FREEBSD.readme file in the root outlining options for FreeBSD users; you can either edit the shebang locally to #!/usr/local/bin/perl OR you can drop a symlink with **ln -s /usr/local/bin/perl /usr/bin/perl** as a workaround for this and any other Perl scripts written on a non-BSD operating system.
