### ISSUE TITLE
source-bwlimit too bursty

### ISSUE THREAD

**Issue by electricOzone** [jimsalterjrs/sanoid#310]
I'm attempting to send ZFS syncs from behind an extremely slow DSL circuit. I'm using `--source-bwlimit=30k` to limit the speed to what I assume is 30kB/s (250kb/s) (per another issue that was opened; this could be a little better documented).

Using iftop, I'm able to see traffic between these servers bursting over 520kb/s. The running average is also over 250kb/s.

I'm not sure if this is due to the rate-limiting mechanism of mbuffer not being intended to run at these low speeds, or something else. I need to ensure that traffic does not burst over 250kb/s as this causes heavy packet loss on this circuit, which impacts monitoring of the site.

**Comment by jimsalterjrs** [comment]
No matter how you slice it, this is an `mbuffer` bug. We're passing the arguments directly to `mbuffer`; if it isn't then doing the right thing with it, that's not something we can directly fix.

You're welcome to try a different stream limiting solution and see if it meets your needs; modern versions of `pv` also include a stream bandwidth limiting function. If you find that another one works better for your use case, you're welcome to tell us about it here. Or even better, submit a PR which allows for the use of the alternate limiter, along with some good documentation demonstrating how and why it's better. =)

**Comment by electricOzone** [comment]
Thanks for the suggestion, I'll try out the "--tcpbuffer" option. However, I don't see this documented in syncoid; is this a mbuffer argument?

**Comment by electricOzone** [comment]
Hm, I gave this a try, but am seeing the same behavior. I think for now, I will attempt to reimplement a shaper on our Ubiquiti ERL. I started out with this, but turns out there's a bug on that platform with implementing shapers on IPSEC interfaces :)

Thanks for all your help here.
