### ISSUE TITLE
Snapshots should be taken in fixed order

### ISSUE THREAD

**Issue by matveevandrey** [jimsalterjrs/sanoid#311]
Currently sanoid creates snapshot in the random order ([daily, frequently, hourly, monthly, weekly, yearly] - sorted by alphabet)
However logically snapshots should always be taken in fixed order from yearly to frequently
  
Example for the first run

now:
00:00:01 snap_daily
00:00:02 snap_frequently
00:00:03 snap_hourly
00:00:04 snap_monthly
00:00:05 snap_weakly
00:00:06 snap_yearly

should be fixed order in order to have most frequent (read as "resent") snapshot the last

**Comment by phreaker0** [comment]
There is no fixed order currently, for me it's random on each run. I agree with you having a fixed order would be nice.

**Comment by matveevandrey** [comment]
#312 patch provided

**Comment by phreaker0** [comment]
PR was merged.
