### ISSUE TITLE
ZFS 6.5.x: CRITICAL ERROR: bookmarks couldn't be listed for <volume> (exit code 256) cannot open 'tank/vm-229-disk-1': operation not applicable to datasets of  this type

### ISSUE THREAD

**Issue by pquan** [jimsalterjrs/sanoid#316]
I'm running a fairly "ancient" ZFS 6.5.1 in production. Syncoid has issues when replicating volumes because on this version bookmarks are only availble on filesystems and not volumes.

The relevant error is "CRITICAL ERROR: bookmarks couldn't be listed for tank/vm-229-disk-1 (exit code 256) cannot open '<volume>': operation not applicable to datasets of  this type

This is an easy fix on line 1324. I'll submit a PR in a few minutes.

**Comment by phreaker0** [comment]
wasn't aware of that, thanks for the fix!
