### ISSUE TITLE
please consider simple error checking

### ISSUE THREAD

**Issue by borkd** [jimsalterjrs/sanoid#32]
When dealing with backups and data replication it usually pays to fail early and/or at least be loud about it. Acting on non zero exit codes from system() calls and setting overall exit code to non-zero vaue would be a preferred way to do it. 

Simple snapshot creation failure encountered in [syncoid, sub newsyncsnap, L668](https://github.com/jimsalterjrs/sanoid/blob/50b258cad125f3cd759418679250cdfaf6848ba8/syncoid#L668) results in no clear warning message, failed sync, and program still exits with code 0.

[sanoid, sub take_snapshots, L335](https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L335) also doesn't seem to care whether the operation failed or not.

If session cleanup and die() seem too harsh, please consider issuing a BIG FAT WARNING instead.

Thanks!

**Comment by jimsalterjrs** [comment]
Thank you for the report.  I will be working on this in the next few days.

**Comment by jimsalterjrs** [comment]
Added ==0 or die to all system calls that didn't already have it in sanoid and syncoid.
