### ISSUE TITLE
recursive clones can fail on the first replication attempts

### ISSUE THREAD

**Issue by phreaker0** [jimsalterjrs/sanoid#323]
Depending on the order of recursive clones they will fail on the first attempts because the origin datasets weren't replicated before. Syncoid should order the datasets for replication so the origin of all cones are replicated before recreating them.

**Comment by TerraTech** [comment]
Please do, as this can be rather frustrating especially when your just doing an initial prime with ```--no-stream``` option.  I just literally hit this problem a few minutes ago with a 3TB send.  The result is a half baked mess that needs to be sorted out manually.

zfs send/receive ability is a really nice feature, however the peaceful dataset ecosystem and transfer of power can be mercilessly decimated by an attack of the clones.  Even zfs send/receive native ```-R``` replication stream package can get it wrong, depending on ordering.  What I've learned (the hard way) is when your zfs pool has clones, zfs send/receive can become frustratingly fragile.

**Comment by TerraTech** [comment]
FWIW, if you use docker + ZFS storage driver, its whole storage tree is a landmine filled field of clones.
