### ISSUE TITLE
Slowness in sync

### ISSUE THREAD

**Issue by fewenuga** [jimsalterjrs/sanoid#324]
I have been running the sync on two of my boxes every day for the last month and a half.  It appears the each sync has gotten progressively slower and slower.  I know it isn't a memory leak since the program completes, but is there a cache or something that could be slowing this down? I've gone from a sync taking 45 minutes to a sync taking 5 hours.

**Comment by fewenuga** [comment]
The sanoid version hasn't changed to the best of my knowledge.  I do not have a large number of snapshots, but I do have a lot of volumes.  ZFS is less than half full on both machines.  The only other thing that has changed is that my boss has added a sanoid cron job to run every hour, but I should be seeing gaps in speed, not a constant slowness, at least I assume so.

**Comment by fewenuga** [comment]
A while, but stopping the sanoid process does not increase the speed.

**Comment by fewenuga** [comment]
It looks like it does the zfs send receive and then just sits there for a minute or more and then does the next send receive

**Comment by jimsalterjrs** [comment]
note that this is going to be an issue upstream pretty much no matter what. sounds like the system is probably more heavily loaded than it should be and has more metadata than fits in ARC more likely than not; I see this behavior in machines with a lot of snapshots (and/or a lot of datasets) and not a lot of memory allocated to ARC.

To the extent that this can be reported as a bug, it should be reported upstream to OpenZFS. All syncoid does is automate the generation of the ZFS send and receive commands; if they run slowly, that's a function of network / hardware / OpenZFS itself.

**Comment by shodanshok** [comment]
@fewenuga This is probably caused by default setting for `zfs_per_txg_dirty_frees_percent`. Try issuing `echo 0 > /sys/module/zfs/parameters/zfs_per_txg_dirty_frees_percent` on the *receiving* side. Does it change anything?

For reference: https://github.com/zfsonlinux/zfs/issues/7725

**Comment by fewenuga** [comment]
That didn't seem to have any affect.  Turning off sanoid got me some speed back, but what was taking 45 minutes is down from 5 hours to 3 hours.  I still see the transmit, followed by a long pause, 30 to 60 seconds, then the next transmit.

**Comment by shodanshok** [comment]
OK. At this point I really think you should try some manual `zfs send/recv` to see if the situation improve compared on `syncoid` transfers.
