### ISSUE TITLE
pv in wrong place

### ISSUE THREAD

**Issue by gordan-bobic** [jimsalterjrs/sanoid#330]
pv is used in the wrong place in the pipe. It should either be used before compressing on the sending side, or after decompressing on the receiving side.

Otherwise the expected transfer size will be wrong, possibly by a LOT.

Affects 2.0.1, not checked previous versions.

**Comment by phreaker0** [comment]
I think you are mistaken, as far as I can see pv is uses either before compression or after decompression. Can you post an built command where it isn't?

**Comment by gordan-bobic** [comment]
Will paste the --debug output when I'm in front of a full size keyboard, but something is clearly off because pv output regularly completes far from 100%.

**Comment by phreaker0** [comment]
zfs send size estimation is wrong/not exact for smaller sizes, this is the reason why it goes beyond 100% sometimes. This would be an upstream issue.

**Comment by gordan-bobic** [comment]
Perhaps, but I was seeing things be out by a factor of 2x.

**Comment by gordan-bobic** [comment]
Apologies for the noise, you're right - pv is in the right place:
```
# /usr/bin/ssh     -S /tmp/syncoid-root-root@sourceserver-1547758795 root@sourceserver ' /sbin/zfs send '"'"'data/mysql'"'"'@'"'"'xfer'"'"' | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 13541767136 |  /sbin/zfs receive -F 'data/mysql'
39.1GiB 0:05:14 [ 126MiB/s] [=====================================================================================] 309%
```

It actually looks like the problem might be to do with the data source being compressed on ZFS. I note that send doesn't use -cp, and there appears to be no option for syncoid to enable this. This would be quite helpful to avoid decompression and recompression.
