### ISSUE TITLE
--no-resume should be either disabled by default or auto-detected

### ISSUE THREAD

**Issue by gordan-bobic** [jimsalterjrs/sanoid#331]
At the moment, resume defaults to on, even if neither the sender nor the receiver have the feature enabled on the pool.

It should either be disabled by default or auto-detected. Otherwise an opaque error "pool has to be upgraded to receive this stream" is thrown.

**Comment by phreaker0** [comment]
@gordan-bobic it's already auto detected. syncoid should only use resumeable send if both the sender and receiver supports it. Doesn't it for you?

**Comment by gordan-bobic** [comment]
Clearly not, because I was getting the mentioned error and I only figured out what was wrong when I enabled --debug and dropped parts of what it was doing until finally removing -s from receive made it work.

**Comment by phreaker0** [comment]
Please post the debug output (--debug) of the syncoid run. Which ZFS version are you using on source and target?

**Comment by gordan-bobic** [comment]
ZFS 0.7.5 on Ubuntu 18.04. Will paste --debug shortly.

**Comment by phreaker0** [comment]
okay, now I get it, syncoid only checks if your zfs version supports resumeable send, which it does but I wasn't aware that this was dependent on a pool feature. Can you run zpool upgrade and post the list of available features which are missing from the pool?

**Comment by gordan-bobic** [comment]
The feature is listed but disabled. I don't want to enable it because it's my root/boot file system and grub doesn't understand that feature flag.

**Comment by phreaker0** [comment]
What is it called? But i guess checking for that is not feasible, it may be better to catch the exact error from the above, so it will be like #309

**Comment by gordan-bobic** [comment]
Pool flag:
```
# zpool get all data | grep extensible
data  feature@extensible_dataset     disabled                         local
```

Error:
```
# /usr/sbin/syncoid --force-delete --recursive --no-sync-snap root@sourceserver:data/mysql data/mysql
NEWEST SNAPSHOT: autosnap_2019-01-17_20:42:38_monthly
Removing data/mysql because no matching snapshots were found
NEWEST SNAPSHOT: autosnap_2019-01-17_20:42:38_daily
INFO: Sending oldest full snapshot data/mysql@xfer (~ 38.9 GB) to new target filesystem:
cannot receive new filesystem stream: pool must be upgraded to receive this stream.
 512KiB 0:00:00 [25.8MiB/s] [>                                                                                     ]  0%            
mbuffer: error: outputThread: error writing to <stdout> at offset 0x40000: Broken pipe
mbuffer: warning: error during output to <stdout>: Broken pipe
CRITICAL ERROR: /usr/bin/ssh     -S /tmp/syncoid-root-root@sourceserver-1547758776 root@sourceserver ' /sbin/zfs send '"'"'data/mysql'"'"'@'"'"'xfer'"'"' | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 41724779224 |  /sbin/zfs receive -s -F 'data/mysql' failed: 256 at /usr/sbin/syncoid line 405.
NEWEST SNAPSHOT: autosnap_2019-01-17_20:42:38_daily
INFO: Sending oldest full snapshot data/mysql/.log@xfer (~ 4.7 GB) to new target filesystem:
cannot receive new filesystem stream: pool must be upgraded to receive this stream.
```
