### ISSUE TITLE
Feature Request: Preserve Compression and Attributes

### ISSUE THREAD

**Issue by gordan-bobic** [jimsalterjrs/sanoid#332]
It would be really handy to have an option for syncoid to send with the -cp options to avoid decompressing and re-compressing the data. It would also result in more accurate transfer size estimates for already compressed data sets when used.

**Comment by phreaker0** [comment]
Should be possible with #295. The send size estimation should be correct despite the compression as zfs hopefully calculates it differently depending on the case.

**Comment by gordan-bobic** [comment]
Ah, I guess --sendoptions isn't in 2.0.1 yet.

**Comment by phreaker0** [comment]
#295 is merged now and will end up in the next release.

**Comment by phreaker0** [comment]
@redmop yes, with #295 you can specify custom send/recv properties like preserving compression
