### ISSUE TITLE
Does Sanoid/syncoid convert hourly's to daily's/monthly's etc?

### ISSUE THREAD

**Issue by yanky83** [jimsalterjrs/sanoid#354]
Source (sanoid only hourly snaps, no monthly etc) / target (syncoid to pull snaps, sanoid to prune) setup.

I had assume sanoid on the target might convert hourly's to monthly's etc, but this does not seem to be the case.

Is there a way to have only hourly snaps on source (to preserve space) and keep more snaps (hourly, daily, monthly, yearly) on the target backup system?

Thanks.

**Comment by jimsalterjrs** [comment]
Prune dailies and monthlies after the first one on the source. Replicate 
daily (or more often). You'll only have a single monthly and single daily 
on source, but can keep more on target - they don't disappear on target 
when pruned on source.

**Comment by yanky83** [comment]
Thanks for the advice, that seems feasible for daily/maybe monthly, but I think I'd rather not keep a snap on a live system for a year?

I guess manually renaming the snaps would be an option? And maybe a feature request for the future? Other suggestions?

**Comment by jimsalterjrs** [comment]
If you keep twelve monthlies on the target, you don't specifically need a 
yearly. If you want to keep a January until the next January no matter 
what, keep 24 monthlies.

Hourlies tend to have a lot of ephemeral trash in them, but there usually 
isn't much difference in space consumed by twelve monthlies or by one 
yearly, for most workloads.

**Comment by yanky83** [comment]
Could be worth a try, I am just a bit worried about the additional storage usage on the source system.

Could you think of any side-effects of renaming a daily snap to a say a monthly snap?

**Comment by jimsalterjrs** [comment]
None, as long as you get the rename correct so that sanoid's monthly policy 
handling will expire it on time. If you typo it sanoid will treat it as a 
manually created snapshot and never expire it.
