### ISSUE TITLE
docs: "bwlimit" options miss the unit (bytes? bits? per second?)

### ISSUE THREAD

**Issue by klemens-u** [jimsalterjrs/sanoid#355]
Please add documentation regarding the unit (bits? bytes?) for the bwlimit options:

```
--source-bwlimit <limit t|g|m|k>
--target-bw-limit <limit t|g|m|k>
```

I've only found one reference here, but it is still not clear:
https://github.com/jimsalterjrs/sanoid/issues/310

Furthermore: what is the background/reasoning about having two bwlimit settings? I mean in effect the throughput is one number, isn't it?

Thank you!

**Comment by phreaker0** [comment]
I think this is already documented in the README.md:
```
--source-bwlimit <limit t|g|m|k>

This is the bandwidth limit imposed upon the source. This is mainly used if the target does not have mbuffer installed, but bandwidth limites are desired.

--target-bw-limit <limit t|g|m|k>

This is the bandwidth limit imposed upon the target. This is mainly used if the source does not have mbuffer installed, but bandwidth limites are desired.
```

So there are two options in case one of the involved hosts doesn't have mbuffer installed.
@jimsalter what does the 't' unit suffix mean, in my manpage it isn't listed.

**Comment by klemens-u** [comment]
To clarify the question: is it bits or bytes per second?

I'v updated the original post accordingly.

**Comment by phreaker0** [comment]
From the manpage of mbuffer:
`...<rate> can be given in either Bytes, kBytes, MBytes, or GBytes per second....`
And you are right, this should be included for clarification (while also removing the wrong dash for the target limit)

**Comment by klemens-u** [comment]
Ok thanks, I created pull request for readme and syncoid.
