### ISSUE TITLE
What happens if pre_snapshot_script fails?

### ISSUE THREAD

**Issue by saurabhnanda** [jimsalterjrs/sanoid#358]
Context: https://github.com/jimsalterjrs/sanoid/issues/108#issuecomment-471178140

I'm trying to make sure a daily snapshot is taken only after the DB backup is complete. However, I want the snapshot to fail loudly if the DB backup script fails. Unfortunately, it seems that sanoid ignores errors of pre/post scripts. I simply tried this...

```
   pre_snapshot_script = /bin/false
```

...and it didn't seem to deter the snapshotting process in any way.

**Comment by jimsalterjrs** [comment]
And it never will. I don't ever want taking a snapshot to fail. Better a 
snapshot without whatever quiescing process you've cooked up than no snapshot.

If you really, really want this, you can make it happen in your own script 
by trapping errors and killing the parent sanoid process if you have 
errors. But I don't recommend it.

**Comment by saurabhnanda** [comment]
> I don't ever want taking a snapshot to fail. Better a snapshot without whatever quiescing process you've cooked up than no snapshot.

I can understand that there would be setups where taking a snapshot is more important that the pre-snapshot script. However, in my setup, taking a snapshot makes sense only if the pre-script (taking a database backup) has been successful. Else it will just be a no-op snapshot.

If the design decision in this case is very clear, is there a way to do this the other way around? i.e. DB backup script calls sanoid at the end to take a snapshot of a specific ZFS dataset on-demand?

**Comment by phreaker0** [comment]
@saurabhnanda @jimsalterjrs  actually there is an option which will abort snapshot taking if the pre snapshot scripts fails: "no_inconsistent_snapshot". By default it's empty and a snapshot will be taken but the post snapshot script won't be executed. But with the option set to "yes" it will also skip the snapshot taking.

**Comment by jimsalterjrs** [comment]
Logic is pretty simple to take a snapshot that sanoid will recognize as its 
own. You might be better served just taking the snapshot in your 
"pre-snapshot" script, IDK.

I suppose we could consider an optional argument to wait for the pre script 
to complete.

**Comment by jimsalterjrs** [comment]
Thanks Christoph - I wasn't 100% on how the pre script was implemented :)

**Comment by phreaker0** [comment]
I guess the question was answered :-)
