### ISSUE TITLE
Recursive prune on target?

### ISSUE THREAD

**Issue by ste7677** [jimsalterjrs/sanoid#364]
I run 2 instances on sanoid. 1) on my production server, 2) on my backup server

1) production server: Snapshotting works fine with recursive datasets

2) backup server: syncoid receive works fine

great, but:

On my backup server, I want more (longer lasting) snapshots than on my production machine - . However, running sanoid on my backup machine (destination) for cleaning up expired snapshots won't clean them up (prune) **recursively** into datasets. Manually adding a module to each child dataset seems to prune correctly.

Also notable: When putting recursive=yes in a backup template, I get an "ignore recursive" warning.

1. Is this expected behavior?

2. Are there workarounds or do I have to specify a module for each child dataset on the destination machine's sanoid.conf?

attachement: zfs listing & sanoid config
[sanoid.txt](https://github.com/jimsalterjrs/sanoid/files/3023249/sanoid.txt)

**Comment by jimsalterjrs** [comment]
No, what you describe is not expected behavior; when specifying **recursive=yes** Sanoid will descend into all child datasets and apply policies (including pruning) there as well.

**Comment by ste7677** [comment]
For whatever reason, it seems to work after a couple runs. Really strange, no config changed. I suggest issue close.

btw: recursive=yes can not be specified in a template, right (throws an ignore error here)? That should be documented somewhere.

Thank you for that great piece of software :-) !
