### ISSUE TITLE
Behavior of "zfs list -t snapshot" in ZFSonLinux Changed

### ISSUE THREAD

**Issue by ahouts** [jimsalterjrs/sanoid#372]
Not sure if the latest git version of ZFS is supported, but the behavior of `zfs list -t snapshot` has changed to only include the root dataset. This means you must manually specify every dataset you want to list the snapshots for (ie. `zfs list -t snapshot zroot/dataset1`).

https://github.com/zfsonlinux/zfs/issues/8591

I currently have over 20000 snapshots on my system (usually have around 100), so this issue can spiral out of control pretty quickly. Not sure if ZOL or you guys should fix this issue, but until it is resolved somewhere I won't be able to use sanoid.

**Comment by jimsalterjrs** [comment]
Are you 100% sure this affects sanoid? AFAICT it's a change in behavior when you actually specify a dataset as a target, which we don't. This is the command Sanoid uses to get snapshots:

~~~~
zfs get -Hpt snapshot creation
~~~~

Can you try that on your system, please - and if you only get snapshots on the root dataset, try again with:

~~~~
zfs get -rHpt snapshot creation
~~~~

(Adding the -r(ecursive) flag) and see if that changes things?

**Comment by ahouts** [comment]
Just tried it, `zfs get -Hpt snapshot creation` does only get snapshots for the root dataset. 
`zfs get -rHpt snapshot creation` seems to hang, but I assume that has something to do with the number of snapshots on my system. I'll leave it running and let you know if it does finish.

**Comment by jimsalterjrs** [comment]
If you've got over 20,000 snapshots, that will likely take a while to finish. Sounds like we just need to patch in the `-r` flag and we'll be golden.

**Comment by ahouts** [comment]
Sounds good to me. I have a feeling it might only recursively list snapshots for the root volume, but I guess we will see.

**Comment by ahouts** [comment]
Nevermind, `zfs get -rHpt snapshot creation` appears to have the original functionality, listing all snapshots across all volumes.

**Comment by jimsalterjrs** [comment]
OK, patched both sanoid and syncoid to explicitly request recursion when retrieving snapshots. Closed; let me know if you have problems.

**Comment by ahouts** [comment]
Just tried running the latest git version of sanoid (8d8df7e533b7d72c8f99683dd1f87dc2b758b2ad), ran into a different problem.

```
cannot open 'zpoolname/parent': dataset does not exist
INFO: taking snapshots...
taking snapshot zpoolname/parent/child@autosnap_2019-04-07_17:12:08_monthly
cannot open 'zpoolname/parent/child': dataset does not exist
usage:
        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR: /sbin/zfs snapshot zpoolname/parent/child@autosnap_2019-04-07_17:12:08_monthly failed, 512 at /usr/bin/s
anoid line 555.
taking snapshot zpoolname/parent/child@autosnap_2019-04-07_17:12:08_daily
cannot open 'zpoolname/parent/child': dataset does not exist
usage:
        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR: /sbin/zfs snapshot zpoolname/parent/child@autosnap_2019-04-07_17:12:08_daily failed, 512 at /usr/bin/san
oid line 555.
taking snapshot zpoolname/parent/child@autosnap_2019-04-07_17:12:08_hourly
cannot open 'zpoolname/parent/child': dataset does not exist
usage:
        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR: /sbin/zfs snapshot zpoolname/parent/child@autosnap_2019-04-07_17:12:08_hourly failed, 512 at /usr/bin/sa
noid line 555.
taking snapshot zpoolname/datasetname@autosnap_2019-04-07_17:12:08_monthly
cannot open 'zpoolname/datasetname': dataset does not exist
usage:
        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR: /sbin/zfs snapshot zpoolname/datasetname@autosnap_2019-04-07_17:12:08_monthly failed, 512 at /usr/bin/sa
noid line 555.
taking snapshot zpoolname/datasetname@autosnap_2019-04-07_17:12:08_daily
cannot open 'zpoolname/datasetname': dataset does not exist
usage:
        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR: /sbin/zfs snapshot zpoolname/datasetname@autosnap_2019-04-07_17:12:08_daily failed, 512 at /usr/bin/sano
id line 555.
taking snapshot zpoolname/datasetname@autosnap_2019-04-07_17:12:08_hourly
cannot open 'zpoolname/datasetname': dataset does not exist
usage:
        snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR: /sbin/zfs snapshot zpoolname/datasetname@autosnap_2019-04-07_17:12:08_hourly failed, 512 at /usr/bin/san
oid line 555.
INFO: deferring cache update - valid cache update lock held by another sanoid process.
INFO: pruning snapshots...
```

Interestingly, `zfs get -Hpd 1 -rt snapshot guid,creation <dataset>` does not recurse into child datasets.

**Comment by jimsalterjrs** [comment]
It looks like you're using a stock sanoid.conf you haven't configured for 
your actual system?

**Comment by ahouts** [comment]
Whoops, my package manager overwrote my configuration file when I installed the latest version. It is deleting snapshots now, so it appears to be working as intended. Thanks!

**Comment by phreaker0** [comment]
FYI, this change is being reverted soon: https://github.com/zfsonlinux/zfs/pull/8594

**Comment by ahouts** [comment]
Good to know. Seems like a change like this would break all sorts of bash
scripts, so it's probably for the best.

**Comment by jimsalterjrs** [comment]
I see no reason not to leave in the explicit **-r** argument in syncoid and sanoid, though. Truth be told, I distinctly remember having it in my original releas code, but I think I eventually took it out myself for the dubious reason of not wanting to "look dumb" by having an "unnecessary" argument in place.
