### ISSUE TITLE
Critical Error in ZFS Send (line 667)

### ISSUE THREAD

**Issue by electricOzone** [jimsalterjrs/sanoid#373]
When running syncoid from cron, I find that one of my datasets frequently fails with the following error. I have been unable to replicate this error when running the same syncoid command from the teminal. I'm running the command as:
`/usr/local/bin/syncoid -r orion/kvm/images root@server.domain.com:orion/kvm/images`

Please let me know if further information is needed.

`CRITICAL ERROR: /sbin/zfs send -I 'orion/kvm/images/dns'@'autosnap_2019-03-24_23:59:16_daily' 'orion/kvm/images/dns'@'syncoid_kvm_2019-04-09:00:08:30' | /usr/bin/pv -s 4207527776 | /usr/bin/lzop | /usr/bin/mbuffer -q -s 128k -m 16M 2>/dev/null | /usr/bin/ssh -S /tmp/syncoid-root-root@server.domain.com-1554786301 root@server.domain.com ' /usr/bin/mbuffer -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /sbin/zfs receive -s -F '"'"'orion/kvm/images/dns'"'"'' failed: 65280 at /usr/local/bin/syncoid line 667.`

**Comment by electricOzone** [comment]
It may also be important to note, I run three syncoid operations at the same time:
`  5     0       *       *       *       /usr/local/bin/syncoid -r orion/sshfs root@server.domain.com:orion/sshfs >/dev/null
  5     0       *       *       *       /usr/local/bin/syncoid -r orion/kvm/images root@server.domain.com:orion/kvm/images >/dev/null
  5     0       *       *       *       /usr/local/bin/syncoid -r root@server.domain.com:orion/benton-backup orion/benton-backup >/dev/null`

**Comment by phreaker0** [comment]
@electricOzone the error code '65280' needs to be shifted by 8 bits to the right to get the exit code of the command, which is 255 and this indicates an ssh error, from the manual:

```
 EXIT STATUS

     ssh exits with the exit status of the remote command or
     with 255 if an error occurred.
```

So I guess you internet connections drop out for a short time in that case or something. As you cron job is in the early morning, maybe you have an ISP which resets the connection each day and it only happens when the replication runs longer?

**Comment by electricOzone** [comment]
Thanks for the info @phreaker0. Can you help me understand which process this error code comes from? I.e., is this an ssh error code (and were you referring to the ssh man page?).

I don't think this is due to the ISP going down in the evening, however, I am seeing ipsec errors on the tunnel between these two sites (the remote end is on a fixed wireless link), so it could be that is throwing a wrench into things.

However, it seems to be the same one dataset that is failing on a more regular basis, and it's one of the smaller ones. Also, for the most part, packet loss is below 1%. In fact, when I manually ran the backup this morning, packet loss crept up to 5%, but the backups completed successfully.

Among my ideas for a solution here, I had considered running syncoid more frequently throughout the day in case some of the datasets fail. However, I'm still only wanting to sync my dailies. If I'm running _sanoid_ once per day, could I then run syncoid with `--no-sync-snap` to **only** sync sanoid snapshots? Is this best practice?

**Comment by electricOzone** [comment]
Thanks for the suggestion. I'll start with doing hourly syncoid in cron with --no-sync-snap and daily sanoid snapshots. If that fails me, I'll try building a simple retry script.

**Comment by electricOzone** [comment]
Last bit of info: I was a doof and failed to check the basics. This turned out to be caused by incorrectly configured MTU on the IPSEC tunnel.
