### ISSUE TITLE
Consider running read-only commands as non-privileged user

### ISSUE THREAD

**Issue by tomposmiko** [jimsalterjrs/sanoid#377]
Since ZFS 0.7.0 non-privileged users are allowed to run non-destructive zfs commands without sudo, like list and some others.

It might make sense to consider running these commands without sudo.

**Comment by phreaker0** [comment]
But it would need extra effort to support 0.6.x users then, so I would just leave it as is.

**Comment by redmop** [comment]
I agree with @phreaker0. That said, once Ubuntu 16.04 falls out of support, we should consider it.

We'll need to watch the path on Debian. zfs is not in user paths.

**Comment by tomposmiko** [comment]
Actually, I agree, it was rather just a heads up.
Should I close this issue for now or leave it alive until it is more actual?

**Comment by phreaker0** [comment]
Let's close this for now, maybe we will reconsider this on a later date.
