### ISSUE TITLE
Shell wrapper lock down does not work properly

### ISSUE THREAD

**Issue by tomposmiko** [jimsalterjrs/sanoid#378]
I use a bash script as the remote syncoid user's shell.
I am almost 100% sure it was working properly in the past.

The script is basically a list of `if` statments and checks for valid commands sent by syncoid through ssh to the remote server.

The end of the script looks like this:
```
if [ "$@" ]; then
    echoerr "!!! WARNING !!! UNKNOWN zrep command sent to remote !!!"
    echoerr "command: $@"
fi

exit 1
#eval $@
```
So if there is still something to be validated, it is printed to `stderr` (more suitable than stdout in this case).
Also at the very end the script exits so unknown (invalid) command cannot run (that would be the point of the script).

The problem is that the syncoid command throws errors in this way:

```
WARN: lzop not available on source ssh:-S /tmp/syncoid-syncoid-syncoid@<sourceserver>-1556478192 syncoid@<sourceserver>- sync will continue without compression.
WARN: mbuffer not available on source ssh:-S /tmp/syncoid-syncoid-syncoid@<sourceserver>-1556478192 syncoid@<sourceserver>- sync will continue without source buffering.
WARN: ZFS resume feature not available on source machine - sync will continue without resume support.
Sending incremental <zfs filesystem>@syncoid_<backupserver>_2019-04-28:21:01:12 ... syncoid_<backupserver>_2019-04-28:21:03:15 (~ UNKNOWN):
 133KiB 0:00:00 [ 759KiB/s] [    <=>                                                                                                                         
```

So it looks like there is no other command sent to the server.

If `exit 1` is changed to `set -x;eval $@`, it is working properly:

```
Sending incremental <zfs filesystem>@syncoid_<backupserver>_2019-04-28:21:03:15 ... syncoid_<backupserver>_2019-04-28:21:05:40 (~ 5.0 MB):
4.81MiB 0:00:02 [1.84MiB/s] [=====================================================================================================================================================================================>          ] 95%            
```
So it looks like there is still no other command sent to the server (`set -x` should indicate that).

I don't find the reason for this behavior. Any thoughts or suggestions?

**Comment by phreaker0** [comment]
syncoid doesn't forward the output of every remote command to the local stdout/stderr. So for debugging in your case it would be best to redirect the error output of your check script to a local debug log file.

The command checking in syncoid changed some time ago to use the bash builtin 'command' instruction instead of using external commands like which/ls, which is probably the reason why you need some adaptions.
