### ISSUE TITLE
syncoid not always getting oldest snapshot

### ISSUE THREAD

**Issue by jimsalterjrs** [jimsalterjrs/sanoid#381]
Discovered a bug today in which a full replication isn't actually beginning with the very oldest snapshot present:

    root@SAP0:~# zfs list -rt snap data/images | grep images\@
    data/images@autosnap_2019-05-08_13:13:56_monthly               0B      -    96K  -
    data/images@autosnap_2019-05-08_13:13:56_daily                 0B      -    96K  -
    data/images@autosnap_2019-05-08_13:13:56_hourly                0B      -    96K  -
    data/images@autosnap_2019-05-08_14:00:02_hourly                0B      -    96K  -
    data/images@autosnap_2019-05-08_15:00:01_hourly                0B      -    96K  -
    data/images@autosnap_2019-05-08_16:00:02_hourly                0B      -    96K  -
    data/images@syncoid_usp-hs0_2019-05-08:16:51:28                0B      -    96K  -

Replicating in full to hotspare misses the monthly snapshot:

    root@hs0:~# syncoid root@sap0:data/images data/sap0/data/images
    WARN: ZFS resume feature not available on target machine - sync will continue without resume support.
    INFO: Sending oldest full snapshot data/images@autosnap_2019-05-08_13:13:56_hourly (~ 40 KB) to new target filesystem:
      48.3KiB 0:00:00 [1.64MiB/s] [=================================] 118%
    INFO: Updating new target filesystem with incremental data/images@autosnap_2019-05-08_13:13:56_hourly ... syncoid_usp-hs0_2019-05-08:16:54:09 (~ 33 KB):
      14KiB 0:00:00 [ 321KiB/s] [=============>                    ] 42%

Note that it incorrectly identified the hourly, not the monthly, as "oldest snapshot" on the source. This means that we miss the monthly on the target:

    root@hs0:~# zfs list -rt snap data/sap0
    NAME                                                            USED  AVAIL  REFER  MOUNTPOINT
    data/sap0/data/images@autosnap_2019-05-08_13:13:56_hourly   144K      -   208K  -
    data/sap0/data/images@autosnap_2019-05-08_14:00:02_hourly    16K      -   208K  -
    data/sap0/data/images@autosnap_2019-05-08_15:00:01_hourly    16K      -   208K  -
    data/sap0/data/images@autosnap_2019-05-08_16:00:02_hourly    16K      -   208K  -
    data/sap0/data/images@syncoid_usp-hs0_2019-05-08:16:51:28    16K      -   208K  -
    data/sap0/data/images@syncoid_usp-hs0_2019-05-08:16:54:09      0      -   208K  -

Hey @phreaker0 , remember how I used to have `sanoid` sleep for one second between snapshots? *This* is why I was doing it. I remembered I had problems not being able to identify the oldest snapshot but I couldn't dredge up the details; now the details have re-bitten me in the arse and I remember why I was doing that. =)

When several snapshots of the same dataset are all the same age, it seems to be basically random which one gets pulled up as "oldest". I'm not sure if we're currently sorting age by the actual zfs creation property, or just using the text datestamp in the snapshot name itself. But neither one has a granularity smaller than one second, so it's easy to get order screwed up if you have multiples with the exact same creation time (to a granularity of one second). Suggestions that are less crude than my old one of "just sleep a second between taking snapshots, so this crap doesn't happen"? =)

**Comment by jimsalterjrs** [comment]
It looks like this is also creating occasional problems where an incremental `syncoid` run isn't always picking up the *newest* snapshot from source when `--no-sync-snap` is set, also, and for the same reasons.

**Comment by phreaker0** [comment]
Yeah I remember :-) Currently the snapshots are ordered by the creation timestamp, if it's the same the ordering is done by the snapshot name I think or random. The creation timestamp is only has second precision but the zfs list command always lists them in the correct order so internally the original ordering is known. I used that knowledge by extending the creation timestamp by a three digit running number so ordering is always correct. This should fix both problem, at least I couldn't reproduce the original issue anymore after my linked PR.
