### ISSUE TITLE
Syncoid has an undocumented dependency on Perl module Capture::Tiny

### ISSUE THREAD

**Issue by rasschaert** [jimsalterjrs/sanoid#386]
I upgraded from v2.0.1 to latest master so I could use the --create-bookmark syncoid option.

I got this error message when running syncoid:

`Can't locate Capture/Tiny.pm in @INC (you may need to install the Capture::Tiny module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/bin/syncoid line 16.`

Which is due to [syncoid](https://github.com/jimsalterjrs/sanoid/blob/837711a7417b453bb8ee376a3bb15315f53fa1b3/syncoid#L16)'s use of the Perl module Capture::Tiny, which was not installed on my system.

Fixing it was easy enough: just had to install the libcapture-tiny-perl package from the Ubuntu repositories.

The documentation should probably be updated to reflect this dependency and how to install them on the various supported distros.

**Comment by phreaker0** [comment]
PR is already there :-) #385

**Comment by phreaker0** [comment]
pr was merged and therefore documentation update is in place, @rasschaert thx.
