### ISSUE TITLE
Issues with starting initial syncoid replication.

### ISSUE THREAD

**Issue by tonymmm1** [jimsalterjrs/sanoid#387]
I am running the latest CentOS 7.6 on two of my server boxes and am trying to setup replication between them using syncoid but the operation fails. Sometimes the syncoid binary works and sometimes it does not. I am using root users and have proper ssh keys established so it must be on either zfs or syncoid side. I am managing my snapshots with sanoid and am using --no-sync-snap option with syncoid binary. I really appreciate the time put into this project but I am unable to run this program without experiencing bugs. 

The terminal printout:

 
[root@servert1 ~]# time syncoid --no-sync-snap --compress=none --no-resume RaidZ2T1/Photos root@10.0.10.2:Mirror1/replicationbeta1/servert1/Photos | mail -s "servert1 syncoid Photos to servert2 complete" root
Ambiguous output redirect.
mbuffer: error: outputThread: error writing to <stdout> at offset 0x0: Broken pipe
mbuffer: warning: error during output to <stdout>: Broken pipe
 270kiB 0:00:00 [2.77MiB/s] [>                                                                                                                                                                                               ]  0%            
CRITICAL ERROR:  zfs send  'RaidZ2T1/Photos'@'autosnap_2019-05-18_14:47:31_weekly' | pv -s 567449234024 | mbuffer  -q -s 128k -m 16M 2>/dev/null | ssh     -S /tmp/syncoid-root-root@10.0.10.2-1558604301 root@10.0.10.2 ' mbuffer  -q -s 128k -m 16M 2>/dev/null |  zfs receive   -F '"'"'Mirror1/replicationbeta1/servert1/Photos'"'"'' failed: 256 at /usr/local/sbin/syncoid line 460.

real    0m0.685s
user    0m0.144s
sys     0m0.124s

**Comment by tonymmm1** [comment]
The error seems to affect both CentOS and freenas/freebsd. I have not extensively tested Debian or other distros. I might just revert back to standard zfs send but I would need to find a way to script it to work with sanoid automated snapshots.

**Comment by tonymmm1** [comment]
Are there any issues running multiple zfs send/recv streams on one machine or even on one zfs pool.

**Comment by tonymmm1** [comment]
Is the issue because of syncoid not being able to determine snapshot to choose from sanoid such as to pick from hourly, daily, or weekly snapshots from the same generated time.

**Comment by phreaker0** [comment]
@tonymmm1 I guess you are using the (t)csh shell based on the error output "Ambiguous output redirect.". Switch to bash or sh and it should work.

**Comment by tonymmm1** [comment]
So I am trying it out on a different machine with zfs 0.7.13 with only local disks and am getting an error. Failure to read from stream and this is also a dataset snapshot created with sanoid. I wonder if sanoid snapshots are unable to be properly utilized by syncoid.


![Screenshot_2019-05-23_20-50-50](https://user-images.githubusercontent.com/20303853/58297206-8b7b6200-7d9c-11e9-8fbb-f274b6982499.png)

**Comment by redmop** [comment]
Syncoid and Sanoid work together just fine.

The problem you're having is explained in the CRITICAL ERROR section. It appears that you already created external/Photos. You should not do that. Syncoid takes care of that for you. Please delete external/Photos, then try running your first syncoid command.

If that doesn't fix it, please post the output of the following:
zfs list -t all -r external1
zfs list -t all -r external
zpool list

**Comment by tonymmm1** [comment]
Yeah sorry I am still presented with a bug even after I delete the dataset from external pool. I get the same repeatable error on my CentOS machines.

![Screenshot_2019-05-23_21-50-47](https://user-images.githubusercontent.com/20303853/58299497-ea44d980-7da4-11e9-8ca8-68e244273663.png)

**Comment by redmop** [comment]
Try it without no-sync-snap

**Comment by tonymmm1** [comment]
The first command is with a --no-sync-snap flag.

**Comment by redmop** [comment]
Right. Does it work without that flag?

**Comment by tonymmm1** [comment]
Yeah sorry again still nothing, I do not know if this is an inherit problem with zfs-on-linux or if there is some sort of dependency bug. 

![Screenshot_2019-05-23_21-55-57](https://user-images.githubusercontent.com/20303853/58299725-b5855200-7da5-11e9-9a37-22ed57fcb7be.png)

**Comment by redmop** [comment]
Are pv and mbuffer installed?

next up:, please run these:
which pv
which mbuffer

**Comment by tonymmm1** [comment]
Here is the command with debug enabled, I have pv and mbuffer installed and am using Manjaro latest version. 
![Screenshot_2019-05-23_22-00-29](https://user-images.githubusercontent.com/20303853/58299896-35abb780-7da6-11e9-8ae1-90dfc8c853ae.png)

**Comment by redmop** [comment]
The last line is telling. Install mbuffer.

**Comment by tonymmm1** [comment]
Yeah i guess maybe I dont have mbuffer installed

**Comment by redmop** [comment]
That said, it should have noticed mbuffer isn't there and skipped it.

**Comment by tonymmm1** [comment]
So should i try running the command with normal zfs send and see if that works.

**Comment by redmop** [comment]
Can you install mbuffer and test?

**Comment by tonymmm1** [comment]
Yeah I am trying to compile it because I am unable to download it from aur repo.

**Comment by redmop** [comment]
It really makes a speed improvement.

**Comment by tonymmm1** [comment]
But if its local does it really matter or over lan.

**Comment by redmop** [comment]
it still really helps, even locally. Because of how zfs streams the data. It also helps smooth out seeks. I usually run with a 1G buffer.

**Comment by tonymmm1** [comment]
Ok I compiled the latest mbuffer from the official site. So let me try running commands again

**Comment by redmop** [comment]
I see mbuffer in aur in Arch. 
https://aur.archlinux.org/packages/mbuffer/

**Comment by tonymmm1** [comment]
Yeah now its working, so mbuffer is a mandatory dependency at least in this iteration of the software. 
![Screenshot_2019-05-23_22-09-30](https://user-images.githubusercontent.com/20303853/58300274-7fe16880-7da7-11e9-999c-ae97f7db8421.png)

**Comment by tonymmm1** [comment]
I wonder if on centos the version of mbuffer is too old, is that a possibility.

**Comment by redmop** [comment]
I use syncoid on centos 5, 6, and 7. works fine. Your syncoid problem with centos is different than the one we just troubleshooted.

**Comment by tonymmm1** [comment]
May I ask you for some more of your time for that problem as well?

**Comment by tonymmm1** [comment]
Thanks very much for you help though, I'll try to be more mindful in the future.

**Comment by redmop** [comment]
Some. Can you file a new bug for mbuffer detection not working?

**Comment by tonymmm1** [comment]
Sure sounds good.

**Comment by redmop** [comment]
I'm testing on centos 7.6. It turns out, I was running an old version of sanoid/syncoid.

**Comment by tonymmm1** [comment]
Yeah I guess mbuffer is required for it to work so that means ill have to find a way to compile it for freenas as well.

**Comment by tonymmm1** [comment]
Thanks very much for your help and feedback. Should I close this bug?

**Comment by redmop** [comment]
centos 7.6 works fine locally. mbuffer probably is the problem.

**Comment by redmop** [comment]
Verify mbuffer fixes the problem first. If it does. close away.

**Comment by tonymmm1** [comment]
Okay

**Comment by redmop** [comment]
And, I'm happy to help. :)

**Comment by phreaker0** [comment]
related to #388
