### ISSUE TITLE
Mbuffer detection not working for syncoid

### ISSUE THREAD

**Issue by tonymmm1** [jimsalterjrs/sanoid#388]
Systems that do not have mbuffer installed fail to run syncoid and break with an error.

![Screenshot_2019-05-23_21-55-57](https://user-images.githubusercontent.com/20303853/58300548-9936e480-7da8-11e9-9e82-2638aa8f5fd4.png)

**Comment by redmop** [comment]
It's not detecting that mbuffer is missing, and is trying to use it anyway.

**Comment by phreaker0** [comment]
@tonymmm1 you are using an old version (your output shows the binaries with full paths), can you test with the current master?
Please also run the following (syncoid checks command existence that way in the latest version):
`command -v mbuffer; echo $?`

**Comment by phreaker0** [comment]
should be solved with updating to the latest version, if not please provide more information
