### ISSUE TITLE
sanoid_cacheupdate.lock breaking due to likely race condition

### ISSUE THREAD

**Issue by zhimsel** [jimsalterjrs/sanoid#391]
```
$ sanoid --version
/usr/sbin/sanoid version 2.0.1
(Getopt::Long::GetOptions version 2.50; Perl version 5.28.1)

$ cat /sys/module/zfs/version
0.7.12-2

$ uname -a
Linux hithaeglir 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
```

---

I have 2 recurring crons that run on my machine that use `sanoid`:

1. The "default" systemd `timer`/`service` unit that comes with sanoid that runs `--take-snapshots` every 15 minutes
1. A zfs monitoring script that runs every ~30 seconds via `monit` that runs `--verbose --readonly --monitor-snapshots`

Note: neither of these commands use the `--force-update` option.

I've been seeing an intermittent issue (that be as long as a day or so between occurrences, to back-to-back occurrences):

```
$ monit status zfs
Monit 5.25.2 uptime: 13h 16m

Program 'zfs'
  status                       Status failed
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  last exit value              1
  last output                  ERROR: /var/run/sanoid_cacheupdate.lock is invalid.
  data collected               Fri, 24 May 2019 07:46:00
```

When this error appears, the `/var/run/sanoid_cacheupdate.lock` file contains

```
30842
/usr/bin/perl /usr/sbin/sanoid --take-snapshots
nly --monitor-snapshots
```

[As far as I can tell from `sanoid`'s source code, it expects 2 lines in that file](https://github.com/jasonblewis/sanoid/blob/4a3e93372c3502a7a4d9e2202d147ab00fd23559/sanoid#L942-L948): the first, I'm guessing, is the PID of the process holding the lock; the second is the full command of the process holding the lock.

Between run of either of these crons, I can see that the lockfile should _normally_ be non-present. I imagine it's only created when sanoid is updating its cache and then it's removed. The problem is that one of these processes is leaving the lockfile around after it's done, and in a bad state (note the broken third line).

I'm guessing that, from time to time, these two crons are running at exactly the same moment and simultaneously trying to write the lockfile. One of them fails, and thus leaves the broken lockfile in place. Deleting the lockfile allows both crons to run until the issue occurs again.

---

I'm not really sure what could be done on `sanoid`'s side to fix this. Maybe some kind of timeout and retry? If the race condition is occurring outside of the `sanoid` process itself... ¯\_(ツ)_/¯

In the meantime, I think I've mitigated the issue on my system by using `flock -w <secs> /tmp/sanoid.lock` on both crons. That way, if any automatic sanoid process is running, the another will wait for it to finish before doing its thing.

However, this is mildly clunky, and if there's a way for `sanoid` to handle this internally, that'd be preferred. If nothing can be done (which is understandable), maybe a note can be added to the README or manpage indicating the issue and the possible solution? If that's the route we end up going, I'm happy to write up a PR for it.

---

Anyway, this is a fantastic tool otherwise and it's been incredibly useful for keeping my ZFS-based system(s) automated. Thanks for writing this and keep up the good work 👍

**Comment by phreaker0** [comment]
I just hit the same problem as you on one of my production servers, will look into it.

**Comment by jefft** [comment]
I hit what appears to be the same problem. I have two crons for two apps, each running 'sanoid --monitor-snapshots' on the hour. 12 days after setting this up, `sanoid --monitor-snapshots` has started to fail with `ERROR: /var/run/sanoid_cacheupdate.lock is invalid.`.

**Comment by ChESch** [comment]
/usr/sbin/sanoid version 2.0.3
(Getopt::Long::GetOptions version 2.50; Perl version 5.28.1)

Linux proxmox02 5.3.13-1-pve #1 SMP PVE 5.3.13-1 (Thu, 05 Dec 2019 07:18:14 +0100) x86_64 GNU/Linux

I have the same problem (ERROR: /var/run/sanoid_cacheupdate.lock is invalid.), but I have only one cronjob (* * * * * TZ=UTC /root/sanoid/sanoid --cron)

When this ERROR occurs, sanoid stops working completely and no more snapshots are taken. That kind of defeats the purpose of autosnapshots, and if this is not fixed, I am forced to search for a different solution, which I would really like to avoid.

**Comment by jefft** [comment]
e5c998c is slightly broken. I get:

```
# /usr/sbin/sanoid --take-snapshots --verbose
syntax error at /usr/sbin/sanoid line 1406, near "unlink"
Execution of /usr/sbin/sanoid aborted due to compilation errors.
```
it's just missing a comma.

**Comment by phreaker0** [comment]
thx, see #478
