### ISSUE TITLE
Syncoid multiple errors

### ISSUE THREAD

**Issue by Hr46ph** [jimsalterjrs/sanoid#392]
I've setup sanoid and now that's working for a few days I am trying to get Syncoid to send snaps to a backup server. However, on the command line I can't get it to work.

`# syncoid dolphin:zroot/home@autosnap_2019-05-26_23:59:09_daily backup/zfs-sends/dolphin_zroot_home`
I run the command on the server that has 'backup/zfs-sends' locally available. It should pull over ssh from the remote host 'dolphin'. The pool/dataset@snapshot is a literal copy/paste from that host. I run the command as root, ssh to dolphin works with ssh keys without a passphrase.

The messages it throws out:
```
ssh: Could not resolve hostname autosnap_2019-05-26_23:59: Name or service not known
WARN: /usr/bin/lzop not available on source ssh:-S /tmp/syncoid-dolphin:zroot/home-dolphin:zroot/home@autosnap_2019-05-26_23:59-1558976880 dolphin:zroot/home@autosnap_2019-05-26_23:59- sync will continue without compression.
WARN: /usr/bin/mbuffer not available on source ssh:-S /tmp/syncoid-dolphin:zroot/home-dolphin:zroot/home@autosnap_2019-05-26_23:59-1558976880 dolphin:zroot/home@autosnap_2019-05-26_23:59 - sync will continue without source buffering.
WARN: ZFS resume feature not available on source machine - sync will continue without resume support.
ssh: Could not resolve hostname autosnap_2019-05-26_23:59: Name or service not known
Use of uninitialized value $value in split at /usr/bin/syncoid line 967.
Use of uninitialized value $sync in string eq at /usr/bin/syncoid line 252.
Use of uninitialized value $sync in string eq at /usr/bin/syncoid line 252.
Use of uninitialized value $sync in string eq at /usr/bin/syncoid line 252.
ssh: Could not resolve hostname autosnap_2019-05-26_23:59: Name or service not known
CRITICAL ERROR: snapshots couldn't be listed for 09_daily (exit code 65280) at /usr/bin/syncoid line 1267.
```
The packages lzop and mbuffer are available on both the backup and the remote host.

I did try different notations of hostname:snapshot and hostname:dataset.

Thanks.

**Comment by phreaker0** [comment]
You can't specify a snapshot to send. Everything after an @ is considered an ssh host.

**Comment by Hr46ph** [comment]
Sorry I didn't finish that last line, I'll edit it. I tried with and without the snapshot, and I tried quoting to prevent ssh from interpreting the '@'.

Here's the output:
`# syncoid dolphin:zroot/home backup/zfs-sends/dolphin_zroot_home
cannot open 'dolphin:zroot/home': dataset does not exist`
or:
`# syncoid dolphin:/zroot/home backup/zfs-sends/dolphin_zroot_home
cannot open 'dolphin:zroot/home': dataset does not exist`

**Comment by phreaker0** [comment]
that's the fault of syncoid, currently you always have to provide a username with an ssh host:
`syncoid root@dolphin:zroot/home backup/zfs-sends/dolphin_zroot_home`

There is a PR #374 dealing with this.

**Comment by Hr46ph** [comment]
Ah that works, thanks!
