### ISSUE TITLE
Don't hardcode paths in sanoid

### ISSUE THREAD

**Issue by Nekroze** [jimsalterjrs/sanoid#393]
Hello, I am very interested in using Sanoid however on NixOS almost no command is in the standard location which presents a problem as commands like `ps`, `zfs`, and `zpool` are all defined as variables with a hard coded path to their assumed locations.

It would be great if it could just use `$PATH` to find them but failing that some way to override their locations is a must IMO. And not just for NixOS as I imagine some other weird distro has these in non standard paths too.s

**Comment by phreaker0** [comment]
is already in master :-) #270

**Comment by Nekroze** [comment]
oh, cool. Sorry I mised that @phreaker0 as I was only on the latest release tag v2.0.1. Any release planned or is master kept stable enough to try use that?

**Comment by Nekroze** [comment]
Additonally, while #270 merged, it seems to have gone back as https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L34 is still hard coded

**Comment by Nekroze** [comment]
Ah it seems #270 was only for syncoid. the same will need to be done for sanoid. Please re-open this issue @phreaker0

**Comment by phreaker0** [comment]
sry!

**Comment by Nekroze** [comment]
Thanks mate, nice work on the syncoid patch. Sadly, I don't think I will have any time available any time soon to try replicate it on sanoid.

**Comment by deliciouslytyped** [comment]
Oh funny, I was about to open an issue like this, turns out GitHub's related issue suggestions are quite handy. @Nekroze do you have a nix expression you want to upstream yet?

**Comment by deliciouslytyped** [comment]
@phreaker0 findoid also needs to be patched.

**Comment by Nekroze** [comment]
@deliciouslytyped I haven't got something I would consider upstreaming yet, as usual with my personal system I went just far enough to get what I needed working and was shuffled on to other things.

Here is the nix expression I am currently using https://gist.github.com/Nekroze/9a879200fb5a3cddc7a99127af9ae888 if that helps. I see you opened https://github.com/NixOS/nixpkgs/issues/71423 cheers for the mention, maybe we can merge the two and clean it up to make something worth PR'ing.
