### ISSUE TITLE
syncoid not showing progress bar

### ISSUE THREAD

**Issue by jimsalterjrs** [jimsalterjrs/sanoid#396]
Since applying the last set of PRs, it appears something's broken syncoid's pv progress bar. I still see `pv` in the output when I ctrl-C out of a run, but during the run, no progress bar is displayed.

I *think* the problem is in @phreaker0 's latest patchset requiring Capture::Tiny, but I'm not positive; I haven't thoroughly bisected. I just know reverting the box I installed the new version on back to the version prior restores the progress bar.

@phreaker0 can you test on one of your own boxes also?

**Comment by phreaker0** [comment]
@jimsalterjrs can confirm. The problem is that stderr is redirected to capture it and therefore pv doesn't detect a terminal, damn. But I have a possible workaround in my head and will report back later.
