### ISSUE TITLE
Total snapshot cost (refer amount) for syncoid destinations increasing rapidly

### ISSUE THREAD

**Issue by rwarren** [jimsalterjrs/sanoid#397]
Back on May 17 I updated our sanoid and syncoid scripts to the latest github version. Since then, the total "refer" amount (recorded as "snapshot cost per dataset" in the charts below) on all of my backed up datasets immediately started increasing _dramatically_ in size with every snapshot, while the snapshot cost at the source did not change.

This snapshot cost is happening at syncoid destinations (i.e. the backup server) even for source datasets that are fixed size, and continue to have zero snapshot cost at the data source!!

**Why would syncoid destinations have a per-snapshot refer cost (a significant one!) when the source side does not have this cost? Where is it coming from?**

As an example, below is the trend chart showing total snapshot cost for a fixed size image (dataset of some iso files). Note that the cost (total refer value) stays at zero at the source, while the destination is rising steadily (at an exact rate of 16 kB per snapshot in this clean case).

![image](https://user-images.githubusercontent.com/2751728/58998852-e7001380-87d0-11e9-82b2-dffe08dd9d42.png)

That snapshot cost increase is puny compared to the cost increase on larger datasets. 

![image](https://user-images.githubusercontent.com/2751728/58998890-1ca4fc80-87d1-11e9-8459-d0f6b8282462.png)

In the example above, in the first 3 days since the sanoid change, the total source snapshot cost remained the same, while the snapshot cost on the backup server increased by 12 GB! With hourly snapshots this is a rate of approximately 170 MB per snapshot!

Every other backed up image has done the exact same thing.  Why?

Needless to say, but this has resulted in a dramatic increase in the hard-drive-eating rate on the backup server. Note the obvious corner point in the 60 day chart below (and ignore the unrelated reporting gap):

![image](https://user-images.githubusercontent.com/2751728/58999195-84a81280-87d2-11e9-9b3f-731cad3b8f34.png)

Did sanoid change something, or did the underlying zfs-on-linux change something?

**Comment by jimsalterjrs** [comment]
I don't see how either sanoid or syncoid could have changed anything. We can rule out sanoid entirely, regardless, since you say the problem only exhibits on a backup target, not the source.

Can you revert syncoid to last stable, and see if your problem persists? (I don't see how it *wouldn't*, given that all syncoid is doing is ZFS replication, but hey. Bisection is bisection.)

**Comment by rwarren** [comment]
I don't see how syncoid could be doing it, either. But if it isn't syncoid, what is it? It isn't the underlying zfs snapshot storage schema that changed, since the extra refer space is not happening on the source system.

If not syncoid, I suppose it could be a change to how `zfs send` behaves... but that also seems odd, and I can't find any record of this.

It is definitely *something*, since the effect is obvious (and huge).

Anyway, I've reverted syncoid to around a year ago to start the bisection. FWIW, the entirely arbitrary start commit is:

```
commit e65879d1f8c4a1304ee0d16d4393645b5e07de1e
Author: Lucas Salibian <lucas.salibian@gmail.com>
Date:   Fri Jun 8 11:52:52 2018 -0400

    Fix --help typo
```

We'll see what happens.

**Comment by jimsalterjrs** [comment]
Ultimately the only thing syncoid even *could* be doing to impact the target size is preserving or not preserving clones. And if this were the key factor, the newer syncoid would be using massively *less* space, since it would likely be preserving clones rather than replicating them separately as independent datasets/zvols. (Note: I am not personally a user of this functionality; I don't find ZFS clones a very useful feature over the long run, only in short-term testing and restoration.)

Aside from that, it would pretty much have to be either something you changed in the underlying ZFS properties on the source side (ie changing recordsize to something smaller than the ashift value on the target), or something in the zfs receive code having changed.

**Comment by rwarren** [comment]
Just to make it more obvious what is happening, here is the a current comparison of the `zfs list -t snapshot` state for the _exact same snapshots_ between syncoid src and dst for a static dataset (containing some iso files):

```
Source system:
-------------
NAME                                                  USED  AVAIL  REFER  MOUNTPOINT
data/images/iso@autosnap_2019-06-06_12:00:01_hourly      0      -  4.63G  -
data/images/iso@autosnap_2019-06-06_13:00:01_hourly      0      -  4.63G  -
data/images/iso@autosnap_2019-06-06_14:00:01_hourly      0      -  4.63G  -
data/images/iso@autosnap_2019-06-06_15:00:01_hourly      0      -  4.63G  -
data/images/iso@autosnap_2019-06-06_16:00:01_hourly      0      -  4.63G  -
data/images/iso@autosnap_2019-06-06_17:00:01_hourly      0      -  4.63G  -
data/images/iso@autosnap_2019-06-06_18:00:01_hourly      0      -  4.63G  -
data/images/iso@syncoid_pth-hs0_2019-06-06:18:09:43      0      -  4.63G  -

Destination system:
------------------
NAME                                                  USED  AVAIL  REFER  MOUNTPOINT
data/images/iso@autosnap_2019-06-06_12:00:01_hourly    16K      -  4.63G  -
data/images/iso@autosnap_2019-06-06_13:00:01_hourly    16K      -  4.63G  -
data/images/iso@autosnap_2019-06-06_14:00:01_hourly    16K      -  4.63G  -
data/images/iso@autosnap_2019-06-06_15:00:01_hourly    16K      -  4.63G  -
data/images/iso@autosnap_2019-06-06_16:00:01_hourly    16K      -  4.63G  -
data/images/iso@autosnap_2019-06-06_17:00:01_hourly    16K      -  4.63G  -
data/images/iso@autosnap_2019-06-06_18:00:01_hourly    16K      -  4.63G  -
data/images/iso@syncoid_pth-hs0_2019-06-06:18:09:43      0      -  4.63G  -
```

This clearly shows the 16K that appears from _somewhere_.  As in my initial post, for larger datasets this magical amount can be significantly bigger (e.g. ~170 MB for the other chart I posted), although harder to isolate due to a changing source dataset.

Also curious (a clue?) is that the instantaneous syncoid snapshot takes zero space at the destination.

**Comment by jimsalterjrs** [comment]
I think you may be misunderstanding what some of these numbers mean. The USED on a snapshot is the amount of data unique to that specific snapshot, not shared by the working set or by any other snapshot on the system.

If you have more snapshots on one side than the other, the side that has more snapshots may easily show lower values for USED on the same snapshot vs the other system, because even though it's the same snapshot with the same data, less of that data is shared with some other snapshot.

I notice that REFER is precisely the same on both sides. Is that the case for all your datasets?

**Comment by rwarren** [comment]
Ok. This error report was off base.

The main problem _appears_ to have been a bunch of spurious monthly sanoid snapshots on the backup (syncoid pulling side) with messed up timestamps that sanoid didn't clean up. I don't know what caused them, but I just went on a big cleaning run of abnormal sanoid snapshots and all my storage is now back to expected levels. I'm unclear why the timing worked like it did for everything (fan being hit on May 17), but if it is all fixed now I'm not going to investigate much further.

Example snapshot timings I sniped (note that the first one was at the root):

```
sudo zfs destroy data/images@autosnap_2018-09-18_20:01:01_monthly
sudo zfs destroy data/images/etc-libvirt-qemu@autosnap_2018-09-18_20:01:01_monthly
sudo zfs destroy data/images/jarvis@autosnap_2018-10-17_17:14:01_monthly
sudo zfs destroy data/images/jarvis@autosnap_2018-10-17_17:15:01_monthly
sudo zfs destroy data/images/lite-import@autosnap_2018-09-18_20:01:01_monthly
sudo zfs destroy data/images/lite-jira@autosnap_2018-09-18_20:01:01_monthly
sudo zfs destroy data/images/lite-s0@autosnap_2018-09-18_20:01:01_monthly
sudo zfs destroy data/images/lite-s0@autosnap_2019-05-29_20:33:01_monthly
<etc>
```

I don't know what caused those spurious snapshots. Monthly snapshots are normally closer to the hour like this:

```
data/images/jarvis@autosnap_2019-06-01_00:00:01_monthly
```

The oddly timed ones were extras for the hour, not delayed snapshots (grepping for "monthly" snapshots yielding > 13 snapshots). No clue why. Like this double snapshot for 2018-10-17:

```
data/images/jarvis@autosnap_2018-10-17_01:00:01_monthly
data/images/jarvis@autosnap_2018-10-17_17:14:01_monthly
```

Removing all of those put me back to pre-hockey-stick storage levels, so it may have just been that, with the 16K-per-static-dataset-snapshot thing being a TOTAL red herring (which is still happening).

![image](https://user-images.githubusercontent.com/2751728/59067700-436e3c00-8880-11e9-8cbe-892982ef1af5.png)

fwiw, ashift=13 and recordsize=8k on both servers.

This issue can probably be closed.... but is one needed for the weird off-time sanoid snapshots? Odds are that was a known issue and is fixed. Servers are now running tip github versions, so we'll see.

---

Regarding comments on what snapshot costs mean, I do understand that. However, what I don't understand is the new baseline 16K-per-snapshot that now seems to exist for a static dataset. That appears to be a separate issue I may move to the zfs github (`#zfs` didn't know).

> I notice that REFER is precisely the same on both sides. Is that the case for all your datasets?

No. That was only for the clean example dataset with a fixed set of ISOs that was unchanged over the life of all snapshots (both sides). Other datasets vary more normally.

**Comment by jimsalterjrs** [comment]
OK. I'm going to go ahead and close this. It sounds like you're just retaining more snapshots on the target than the source, so the source had already pruned snapshots that the target had not yet.

**Comment by jimsalterjrs** [comment]
Regarding the 16K-per-snapshot - at a guess, metadata is just being accounted for more accurately in the new version of zfs list. On ashift=13 systems, 16K is two blocks; it seems entirely likely that the metadata for an otherwise "empty" snapshot would eat two blocks.
