### ISSUE TITLE
syncoid error with dataset containing spaces in recursive mode

### ISSUE THREAD

**Issue by mals** [jimsalterjrs/sanoid#40]
When trying to sync a child dataset containing spaces, syncoid fails as the space is not being escaped.

Steps to reproduce:
1) zfs create pool/test
2) zfs create "pool/test/Hello World"
3) syncoid -r pool/test remote_user@remotehost:pool/test

Output:
root@hostname:~# syncoid -r data5tb/test root@hostname2:data5tb_backup/test
Sending incremental data5tb/test@syncoid_hostname_2016-06-05:10:09:53 ... syncoid_hostname_2016-06-05:10:11:32 (~ 4 KB):
1.52KiB 0:00:00 [5.38KiB/s] [==================================================================>                                                                                                              ] 38%  
cannot open 'data5tb/test/Hello': dataset does not exist
cannot open 'World': dataset does not exist
usage:
        snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR:  /usr/bin/sudo /sbin/zfs snapshot data5tb/test/Hello World@syncoid_hostname_2016-06-05:10:11:41
 failed: 512 at /usr/local/bin/syncoid line 697.

**Comment by jimsalterjrs** [comment]
hell, I didn't realize you COULD create a dataset with a space in the name.

will tackle this for the next release. look for it to be fixed by early July.

**Comment by mals** [comment]
Just wondering if there were any updates on this issue. Again, many thanks for the awesome tool!

**Comment by jimsalterjrs** [comment]
Sorry, still on the "to-do" list. =\

**Comment by jimsalterjrs** [comment]
This *should* be fairly easy to fix; I just keep not getting around to tackling it. If anybody else wants to take a crack at automatically backslash-escaping spaces in dataset names, I'd be more than happy to review a PR and accept if it's clean.

**Comment by mals** [comment]
I did some work on this a while ago and sent a PR, however, it's probably a number of months out of sync from your repo now. I won't have a chance to merge and test your changes for at least a few weeks, however, my repo is here in case you wanted to have a look: https://github.com/mals/sanoid/

**Comment by jamesyoungman** [comment]
Any progress?   I just waited 10h for my snapshots to sync, only to find syncoid fell over with this error.   I think it's too late to change my dataset names, but not being able to use syncoid would be a pain.

**Comment by jamesyoungman** [comment]
Also on the subject of quoting, this line worries me a bit:

		$dataset =~ s/$sourcefs//;

If sourcefs contains any regex metacharacter (i.e. character that does anything but match itself) you're  probably going to get the wrong result.
