### ISSUE TITLE
Syncoid: Properties do not update when changed on source (ex: refquota)

### ISSUE THREAD

**Issue by pquan** [jimsalterjrs/sanoid#400]
I noticed that changes in the refquota (perhaps others too) property is not reflected from the source to the dest.
This creates an issue (rollback errors) on some replications when the source dataset if full. 
In this occasion I'd just increase the quota on the source dataset, but this is never propagated to the destination. The destination then cannot be rolled back and this prevents remote backups.
You can say it's easy to update the remote by hand, but put yourself in a pool of say vm and recursive replication and the thing quickly gets out of control (and becomes possible issue and liability).
Perhaps the best thing to do would be to just replicate (some) properties from the source to the target dataset.

**Comment by phreaker0** [comment]
@pquan you can probably use the '--sendoptions' and '--recvoptions' arguments to apply properties while replication.

**Comment by pquan** [comment]
@phreadker0 

I think this is still an issue.

If I "syncoid" one fs to another pool, I'd expect all transferable attributes to be migrated. refquota is not migrated or created on the destination fs even when that fs does not exist (i.e. on the initial sync).
This behavior should be default and not require special options.

**Comment by phreaker0** [comment]
@pquan the ordinary behaviour of zfs send is to exclude properties. I would expect the same from syncoid without extra options. If you want to include properties you need to specify it.

**Comment by pquan** [comment]
I think you're focusing on "changing" the property when it changes on the source. But it's not even copied from the source on fs creation time. 

My point is zfs send/receive is not enough, so you make syncoid which does more, including creating the fs on the new node. It only makes sense to mirror as many properties from the source as possible. 

it's called "syncoid" after all ;)

**Comment by phreaker0** [comment]
@pquan You can do that by providing the correct send option, it's just not the default.

**Comment by pquan** [comment]
It's more complicated than that. I use syncoid to sync vm images between hosts. All vm images are hosted under the same fs, say pool/vm/vm1, pool/vm/vm2 etc. These are dynamic meaning you can create/remove vm, and also change the VM parameters like refquota. 
When using syncoid to sync the root directory pool/vm recursively, It will create the necessary filesystems under rpool/vm on the target host. I expect ALL attributes from any underlying system to be copied. Not just a subset. And refquota is a fairly important attribute.
There might be workarounds in the form of specific options to the low-level sync commands, but then I can drop syncoid and use plain zfs send/receive then instead.
I think my point is clear and obvious.

**Comment by phreaker0** [comment]
@pquan syncoid with no options given will work like zfs send/recv but will take care of snapshot taking/removing, figuring out matching snapshots, handling clones, handling resume send features and stuff like that.
We are just in disagreement what should be the default, but you can just use the correct flags to replicate also the metadata exactly as is. If this is not possible with zfs provided flags one can try to implement a feature/flag which does this.
