### ISSUE TITLE
monitor-snapshots with recursive and process_children_only complains about no snapshots on parent

### ISSUE THREAD

**Issue by pquan** [jimsalterjrs/sanoid#401]
When using a recursive snapshot management, where the parent is never snapshot and is excluded with process_children_only=yes I would expect that sanoid --monitor-snapshots will not complain about the missing snapshots on the parent:

However, we still get the errors out of sanoid --monitor-snapshots

A sample config is:

```
[tank/share]
  recursive=yes
  process_children=yes
```

**Comment by phreaker0** [comment]
@pquan You have a typo in your config :-) 'process_children' -> 'process_children_only'. Just looked at the code, it's handled the same for monitor as for taking snapshots so it should work the same.
