### ISSUE TITLE
Adding support for zfs 0.8.0 and raw encryption send and in-line compression send

### ISSUE THREAD

**Issue by tonymmm1** [jimsalterjrs/sanoid#402]
Feature request for new release of zfs with zfs send -w for raw encrypted snapshots send as well as zfs send -c for in-line compression with existing lz4 on dataset.

**Comment by phreaker0** [comment]
@tonymmm1 already implemented in master:
`syncoid --sendoptions=w src dst`
`syncoid --sendoptions=c src dst`
