### ISSUE TITLE
syncoid should warn and/or strip replication stream "-R" in sendoptions for root dataset

### ISSUE THREAD

**Issue by gdevenyi** [jimsalterjrs/sanoid#411]
If I use syncoid to replicate an entire dataset such as:
```
> syncoid --sendoptions="R" --recursive data root@remotehost:data
```
The root dataset "data" is sent with the "-R" option, resulting in the entire pool being sent with this configuration. This means that syncoid:sync is ignored, and all the lovely recursive features of syncoid are wasted.

I suggest that "-R" should either be stripped for the root dataset, or a big warning be displayed regarding this sub-optimal configuration.

**Comment by phreaker0** [comment]
With introducing the send/recv options there are now a huge amount of complex cases, which I think syncoid can't properly handle. So my opinion is that the user is soley responsible for the power options. Using -R the user should know that recursion (and all properties) are handled solely by zfs and the --recursive flag doesn't make much sense. Prohibiting -R isn't a solution either as it's the only way to replicate a complete encrypted dataset root with inherited keys for example.

**Comment by gdevenyi** [comment]
Thanks @phreaker0 I wasn't aware of the restriction on -R.

I would be happy on a warning in the documentation or a warning in the code, I'll investigate how difficult it would be to check for the root in the code, and be sure to add the details you noted.

**Comment by phreaker0** [comment]
It would be pretty easy to catch the case in the code, I'm just not sure if we should do that.

**Comment by skrenes** [comment]
I think a warning would be very helpful. I was having all kinds of problems because of this very issue. A warning would have saved me a considerable amount of time.

**Comment by Sieboldianus** [comment]
Just adding a note here: I think `--sendoptions="R"` is critical, but I was still missing some coordinated way to pull all my datasets with syncoid in a coordinated manner.

I wrote a little [gist](https://gist.github.com/Sieboldianus/1bf84dcdaf1b845bbc8155d757ec6fe5) that shows how to pull datasets based on a file with a list of key:value pairs (dataset sources and targets).
