### ISSUE TITLE
I've submitted a FreeBSD port, but can you make a release w/ {send,recv}options?

### ISSUE THREAD

**Issue by hartzell** [jimsalterjrs/sanoid#412]
Hi All,

I've created and submitted a FreeBSD port.  I need to fix a few things, but it's nearly done.

BUT, for my use case I need to use `recvoptions`.

Is it possible that you can cut a new release (the port uses `2.0.1`) in the next little while, so that I can update the port before it gets merged?

The bug (new port) report is here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238584

My ports tree, which you can layer over the standard ports tree using portshaker) is here: https://github.com/hartzell/freebsd-ports

Thanks!

**Comment by hartzell** [comment]
The port that I've submitted is ready to go and if/when someone reviews it, it should be merged as is.

I'd love to see a new release that includes the newer features.

Are there any particular blockers?

Thanks!

**Comment by hartzell** [comment]
I've added a second port, `sanoid-devel`, which points at a commit on the master branch, and updated the FreeBSD bugzilla "bug" report.

**Comment by jdrch** [comment]
Thanks for this. Definitely helps with getting it set up on Project Trident; I was planning on looking for ports in AppCafe.

**Comment by phreaker0** [comment]
v2.0.3 is out and the send/recv options are available since v2.0.2

**Comment by hartzell** [comment]
Great.  I've submitted a [bug to update the port](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241771) to 2.0.3 (and the current devel commit).

**Thanks!**
