### ISSUE TITLE
Regression on v2.0.1 '$getsendsizecmd' vs FreeBSD 12 stable (r349133)

### ISSUE THREAD

**Issue by 9845e2e188ff377d** [jimsalterjrs/sanoid#414]
https://github.com/jimsalterjrs/sanoid/blob/master/syncoid
line 1607:
my $getsendsizecmd = "$sourcessh $mysudocmd $zfscmd send $sendoptions -nP $snaps";

this '-nP' generate the same output on ubuntu 19.04 (zol) and Freebsd 12 release, but on Freebsd stable (r349133) to get the same output, '-nvP' must be used:

`# zfs create tank/qq`
`# zfs snapshot tank/qq@baseline`
`# zfs send -nP tank/qq@baseline`
`full    tank/qq@baseline`
`# zfs send -nvP tank/qq@baseline`
`full    tank/qq@baseline        38000`
`size    38000`

tested that additional '-v' parameter on ubuntu and FreeBSD 12 release output the same expected result (with size). zfs man page says that -v report sizes ... Is it possible to push that change '-nvP' on 'getsendsizecmd'?.

my $getsendsizecmd = "$sourcessh $mysudocmd $zfscmd send $sendoptions -nvP $snaps";

**Comment by hartzell** [comment]
FWIW, both `-nP` and `--nvP` generate the same output on a FreeBSD-Release system that's been updated with freebsd-update:

```
hartzell@corvid:~ % uname -a
FreeBSD corvid.alerce.com 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
hartzell@corvid:~ % sudo zfs send -nP zroot/usr/home@hourly-2019-06-17-08
full	zroot/usr/home@hourly-2019-06-17-08	29487181256
size	29487181256
hartzell@corvid:~ % sudo zfs send -nvP zroot/usr/home@hourly-2019-06-17-08
full	zroot/usr/home@hourly-2019-06-17-08	29487181256
size	29487181256
hartzell@corvid:~ %
```

**Comment by hartzell** [comment]
@9845e2e188ff377d  -- Are you saying that you confirmed that on Ubuntu the addition `v` in the option string does not change the output?

> tested that additional '-v' parameter on ubuntu and FreeBSD 12 release output the same expected result (with size)

**Comment by 9845e2e188ff377d** [comment]
> @9845e2e188ff377d -- Are you saying that you confirmed that on Ubuntu the addition `v` in the option string does not change the output?

Yes, I do.
No changes, even on incremental
```
zol:~$ cat /etc/issue
Ubuntu 19.04 \n \l
zol:~$ sudo zfs create test/qq
zol:~$ sudo zfs snapshot test/qq@snap1
zol:~$ sudo dd if=/dev/zero of=/test/qq/dd bs=1M count=1             
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.000690701 s, 1.5 GB/s
zol:~$ sudo zfs snapshot test/qq@snap2
zol:~$ sudo zfs send -nP -I test/qq@snap1 test/qq@snap2              
incremental     snap1   test/qq@snap2   1058864
size    1058864
zol:~$ sudo zfs send -nvP -I test/qq@snap1 test/qq@snap2             
incremental     snap1   test/qq@snap2   1058864
size    1058864
```
