### ISSUE TITLE
skip_children information

### ISSUE THREAD

**Issue by Side2005** [jimsalterjrs/sanoid#417]
how does **skip_children** work? is it a boolean or can i specify a child of a certain dataset to be skipped?

My use case: i do power off a vm with a prescript, snapshot the dataset, and start the vm again with a post script. However, i do want to skip this process for a certain dataset (each vm has its own dataset).

lets say i got a dataset 'vm' with its child datasets **vm/child1** and **vm/child2**

I do want to process vm/child1, but not vm/child2. 
Can i skip vm/child 2 with skip_children = vm/child2?
_________
according to sanoid
`if ($skipChildren) {
						if ($args{'debug'}) { print "DEBUG: ignoring $dataset.\n"; }
						delete $config{$dataset};
						next DATASETS;
}`

it should be based on the defined dataset, correct? Do i define it with parentdataset/childdataset or just childdataset?
 I cannot test it since we do not have a test environment for it.

**Comment by redmop** [comment]
skip_children is boolean. It is either on or off. 

If you want to start/stop only certain VMs during the snapshot, you would need to put that in a script that is called by sanoid.

**Comment by Side2005** [comment]
Thanks for your post.

I do not want to snapshot certain VMs at all. My workaround for now is to have the VMs Disk in the parent directory instead inside of its own dataset, so "process_children_only = yes" can make it work.

However:
It would still be useful to skip certain datasets from beeing processed at all.

**Comment by phreaker0** [comment]
@Side2005 
To exclude a specific dataset from snapshotting you just need to override the autosnap option:

```
[vm/child2]
    autosnap = no
    monitor = no
```
