### ISSUE TITLE
Pass dataset to pre/post snapshot script

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#419]
This can let the script know what datasets are going to be snapshotted, so it can react accordingly. This lets us reuse scripts instead of having a script for each dataset.

Something like this would be particularly handy:
pre_snapshot_script = /path/to/script.sh --snapshot-dataset **$sanoid-snapshot-dataset** --some-other-sexy-argument

**Comment by tiedotguy** [comment]
The env vars `SANOID_TARGET` and `SANOID_SNAPNAME` are passed to pre, post, and prune snapshot scripts.  You need to be careful when using `recursive=zfs` with pre and post, as the script is only invoked for the base, not for each child.

It's not greatly documented, but it's mentioned briefly [here](https://github.com/jimsalterjrs/sanoid/blob/master/sanoid.conf#L94-L95).

**Comment by redmop** [comment]
Thanks for noticing that, Do you know how snapname will handle multiple snapshots to be taken at the same time (such as freq, and hourly at the same time)

**Comment by tiedotguy** [comment]
Unfortunately, they are all distinct snapshots.  If you're putting a database in to hot backup mode for instance, it will be put in and taken out multiple times.

It **looks** like they go in scale order (yearly, monthly, etc), so you could detect the first one, but I'm not 100% certain you can tell which is the last one.

**Comment by redmop** [comment]
I'm just wanting to know the contents of that variable when multiple snapshots are going to be taken, and how the snapshots are delimited. I think can grep/awk my way to what I need from that.

**Comment by tiedotguy** [comment]
Right - I mean it's not exposed like that.  Every snapshot, even for the same dataset, has its own pre/post script executed:

```
SANOID_TARGET=tank/dataset SANOID_SNAPNAME=autosnap_date_yearly /your/pre-script.sh
zfs snapshot tank/dataset@autosnap_date_yearly
SANOID_TARGET=tank/dataset SANOID_SNAPNAME=autosnap_date_yearly /your/post-script.sh

SANOID_TARGET=tank/dataset SANOID_SNAPNAME=autosnap_date_monthly /your/pre-script.sh
zfs snapshot tank/dataset@autosnap_date_yearly
SANOID_TARGET=tank/dataset SANOID_SNAPNAME=autosnap_date_monthly /your/post-script.sh

SANOID_TARGET=tank/dataset SANOID_SNAPNAME=autosnap_date_weekly /your/pre-script.sh
zfs snapshot tank/dataset@autosnap_date_yearly
SANOID_TARGET=tank/dataset SANOID_SNAPNAME=autosnap_date_weekly /your/post-script.sh
...
```

I don't really know Perl, but I'll see if I can cobble together a viable solution, exposing both current type and planned types (where a "type" is yearly, monthly, etc)

**Comment by redmop** [comment]
That is actually enough. I can get the type out of the variable, and only run the meat of the script on the daily|weekly|monthly|yearly snapshot, ignoring the frequently|hourly snapshots. Getting all the times at once would help efficiency, though.

Your example only shows it taking the yearly snapshot though. I assume the monthly and weekly sections would take the monthly and weekly respectively.

**Comment by tiedotguy** [comment]
/facepalm

Sorry, it was a bad copy and paste, I'll update it in a second.

I think I've got the code working, it has a lot more information generally, I'm writing up the documentation now before I PR it, but here's roughly what the interface looks like:

```
* pre_snapshot_script

        This script will be executed before a snapshot is taken.  The following environment variables with be passed:

| SANOID_TARGET   | The dataset about to be snapshot |
| SANOID_SNAPNAME | The name of the snapshot that will be taken (does not include the dataset name) |
| SANOID_TYPE     | The type of snapshot to be taken (yearly, monthly, weekly, daily, hourly, frequently) |
| SANOID_BATCH    | All the snapshots which will be taken against this dataset (does not include the dataset name), joined by commas.  Note that not all of the snapshots will have been taken.  For example, monthly is taken before weekly, but weekly is still included when SANOID_TYPE is monthly. |
| SANOID_SCRIPT   | The type of script being executed, one of pre, post, or prune.  Allows for one script to be used. |

        If the script returns a non-zero exit code, the snapshot will not be taken ... more docs about no_inconsistent_snapshot ...

* post_snapshot_script

        This script will be executed after a snapshot is taken.  The following environment variables with be passed:

| SANOID_TARGET   | The dataset about to be snapshot |
| SANOID_SNAPNAME | The name of the snapshot that will be taken (does not include the dataset name) |
| SANOID_TYPE     | The type of snapshot to be taken (yearly, monthly, weekly, daily, hourly, frequently) |
| SANOID_BATCH    | All the snapshots which will be taken against this dataset (does not include the dataset name), joined by commas.  Note that not all of the snapshots will have been taken.  For example, monthly is taken before weekly, but weekly is still included when SANOID_TYPE is monthly. |
| SANOID_SCRIPT   | The type of script being executed, one of pre, post, or prune.  Allows for one script to be used. |
| SANOID_FORCD    | ... no_inconsistent_snapshot vs force_post_snapshot_script ... |

* pruning_script

...
```
