### ISSUE TITLE
Syncoid failing on FreeBSD 11.3-R

### ISSUE THREAD

**Issue by dwrobison** [jimsalterjrs/sanoid#422]
I have other sends working but this one is failing. I only have lzop and pv installed.

WARN: mbuffer not available on source [local machine] - sync will continue without source buffering.
WARN: mbuffer not available on target ssh:-S /tmp/syncoid-root-root@phoenix-1563222551 root@phoenix - sync will continue without target buffering.
WARN: ZFS resume feature not available on target machine - sync will continue without resume support.
INFO: Sending oldest full snapshot raid1/BACKUPS/LBXRICH@syncoid_backup.vicor.com_2019-07-15:13:09:58 (~ UNKNOWN) to new target filesystem:
59.7KiB 0:00:00 [1.51MiB/s] [   <=>                                                                                                                                                         ]
cannot receive: invalid name
CRITICAL ERROR:  zfs send  'raid1/BACKUPS/LBXRICH'@'syncoid_backup.vicor.com_2019-07-15:13:09:58' | pv -s 0 | lzop  | ssh     -S /tmp/syncoid-root-root@phoenix-1563222551 root@phoenix ' lzop -dfc |  zfs receive   -F '"'"'/raid1/BACKUPS/LBXRICH'"'"'' failed: 256 at /usr/local/sbin/syncoid line 460.
INFO: Sending oldest full snapshot raid1/BACKUPS/LBXRICH/84@syncoid_backup.vicor.com_2019-07-15:13:09:59 (~ UNKNOWN) to new target filesystem:
cannot receive: invalid name

Trailing before "failed: 256 at..." is tick quote tick quote tick tick

**Comment by dwrobison** [comment]
Got it. My mistake. Sorry for the white noise.

**Comment by redmop** [comment]
What was the mistake in case someone else makes it?
