### ISSUE TITLE
Feature Request: syncoid: a way to nice and ionice zfs

### ISSUE THREAD

**Issue by chesty** [jimsalterjrs/sanoid#425]
It would be handy to be able to nice and ionice zfs via a command line argument. 

maybe a command to run infront of $zfscmd

my $recvcmd = "$targetprecmd $targetsudocmd $zfscmd receive $recvoptions $receiveextraargs $forcedrecv $targetfsescaped";

`syncoid --target-precmd="nice -n 19 ionice -c 2 -n 7" ...`

I'm not sure if that would make it harder or impossible to lock down syncoid for some people. alternatively.

or `syncoid --target-nice="-n 19" --target-ionice="-c 2 -n 7" ...`

I guess if security is an concern those arguments should be processed to stop shell injection. ie
`syncoid --target-nice="-n 19; rm -rf /;" --target-ionice="-c 2 -n 7" ...`

Cheers. I'm a big fan of sanoid and syncoid and many thanks to the developers and community.

**Comment by phreaker0** [comment]
@chesty As most of the processing power and disk activity is used by the zfs kernel module it doesn't have much benefit nicing the user space control tools.

**Comment by chesty** [comment]
OK. I thought the data was passing through a bunch of userspace processes where the kernel could schedule the IO of those processes (and cpu which might not be significant).

**Comment by phreaker0** [comment]
I just tested if the decompressing and recompression while sending a compressed dataset to another is handled by the user space tools but this is also handled by the kernel module, so there is no real advantage in implementing that.
