### ISSUE TITLE
systemd timer for prune is missing

### ISSUE THREAD

**Issue by segler-alex** [jimsalterjrs/sanoid#430]
snapshots do not get pruned, when only using systemd files, because there is no timer file for sanoid-prune.service

**Comment by segler-alex** [comment]
maybe daily would be fine

**Comment by phreaker0** [comment]
@segler-alex 
sanoid-prune.service is triggered after sanoid.service, so there is no need for an dedicated timer. But this only works if the sanoid-prune.service is enabled like it's stated in the install instructions:
```
# Enable sanoid-prune.service to allow it to be triggered by sanoid.service
sudo systemctl enable sanoid-prune.service
```

It was missing for a period of time in the install instructions, you may missed it therefore.
