### ISSUE TITLE
pruning huge amout of snapshots is slow

### ISSUE THREAD

**Issue by segler-alex** [jimsalterjrs/sanoid#431]
i overlooked that pruning on my computer did not work for some time, so the snapshots got to over 7000. after manually starting the pruning, it takes about 4 seconds for every snapshot to delete. maybe you do get the list of snapshots in the loop ? is it normal for one snapshot remove to take that long? most interestingly it seems to get faster over time, when snapshot count decreases. it started with 5 seconds each

**Comment by phreaker0** [comment]
Nop. snapshots get deleted with the zfs destroy command in a loop without any other time consuming task (except if you are using pruning scripts).

If your pool is on rust (no ssd's) 4 seconds with a big list of snapshots is nothing out of the ordinary with zfs (unfortunately). Nothing sanoid can fix :-)
