### ISSUE TITLE
Frequently and Hourly are being created and we don't know why. 

### ISSUE THREAD

**Issue by JayStarrco** [jimsalterjrs/sanoid#432]
For tank/VDS I am using template backup. Backup is set to not make Hourly and Frequently but I am still getting them. This issued was first noticed in June but the hourly and frequently only seem to be retained for about 9 days. The oldest ones we have now are from 9/11. 

[template_backup]
        autoprune = yes
        frequently = 0
        hourly = 0
        daily = 14
        monthly = 12
        yearly = 0

        ### don't take new snapshots - snapshots on backup
        ### datasets are replicated in from source, not
        ### generated locally
        autosnap = no

        ### monitor hourlies and dailies, but don't warn or
        ### crit until they're over 48h old, since replication
        ### is typically daily only
        hourly_warn = 2880
        hourly_crit = 3600
        daily_warn = 48
        daily_crit = 60

These are how many hourlies and frequentlies were made yesterday

zfs list -t all -r tank/VDS|egrep "hour|freq" |egrep "2019-09-19"| wc -l
1432

tank/VDS/www3.example.net-13@autosnap_2019-09-20_00:00:02_hourly                         2.00K      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_01:00:01_hourly                         1.08M      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_02:00:01_hourly                         1.21M      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_02:30:02_frequently                     1.21M      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_02:45:01_frequently                     2.00K      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_03:00:01_hourly                         2.00K      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_03:00:01_frequently                     2.00K      -  7.58G  -
tank/VDS/www3.example.net-13@autosnap_2019-09-20_03:15:01_frequently                         0      -  7.58G  -

tank/VDS/vmexampledata@autosnap_2019-09-20_00:00:01_hourly                               2.00K      -   126G  -
tank/VDS/vmexampledata@autosnap_2019-09-20_01:00:01_hourly                               2.00K      -   126G  -
tank/VDS/vmexampledata@autosnap_2019-09-20_02:00:02_hourly                               2.00K      -   126G  -
tank/VDS/vmexampledata@autosnap_2019-09-20_03:00:01_hourly                               2.00K      -   126G  -
tank/VDS/vmexampledata@autosnap_2019-09-20_04:00:01_hourly                                   0      -   126G  -

 cat /etc/sanoid/sanoid.conf
######################################
######################################

### name your backup modules with the path to their ZFS dataset - no leading slash.
[tank/VDS]
        ### pick one or more templates - they're defined (and editable) below. Comma separated, processed in order.
        ### in this example, template_demo's daily value overrides template_production's daily value.
        use_template = backup

        ### if you want to, you can override settings in the template directly inside module definitions like this.
        ### in this example, we override the template to only keep 12 hourly and 1 monthly snapshot for this dataset.
        ###hourly = 12
        ###monthly = 1

###tank/home is backed up from dc1 to stor2 and stor1.cgn.stlgeek.net !!!!!!!!!!!!!!!!!!

[tank/macservers]
        use_template = macserver

[db]
        use_template = monitoring
        recursive = yes
        process_children_only = yes

###you can also handle datasets recursively.
###[zpoolname/parent]
###
### you can selectively override settings for child datasets which already fall under a recursive definition.
#[zpoolname/parent/child]
### only override the values already set by the parent template, not replace it completely.
###use_template = demo

#############################
###templates below this line #
#############################

###name your templates template_templatename. you can create your own, and use them in your module definitions above.

[template_demo]
        daily = 60

[template_monitoring]
        frequently = 0
        hourly = 6
        daily = 10
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes

[template_production]
        frequently = 0
        hourly = 36
        daily = 30
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes

[template_macserver]
        autoprune = yes
        frequently = 0
        hourly = 0
        daily = 45
        monthly = 12
        yearly = 0
        autosnap = yes

[template_backup]
        autoprune = yes
        frequently = 0
        hourly = 0
        daily = 14
        monthly = 12
        yearly = 0

        ### don't take new snapshots - snapshots on backup
        ### datasets are replicated in from source, not
        ### generated locally
        autosnap = no

        ### monitor hourlies and dailies, but don't warn or
        ### crit until they're over 48h old, since replication
        ### is typically daily only
        hourly_warn = 2880
        hourly_crit = 3600
        daily_warn = 48
        daily_crit = 60

[template_scripts]
        ### dataset and snapshot name will be supplied as environment variables
        ### for all pre/post/prune scripts ($SANOID_TARGET, $SANOID_SNAPNAME)
        ### run script before snapshot
        pre_snapshot_script = /path/to/script.sh
        ### run script after snapshot
        post_snapshot_script = /path/to/script.sh
        ### run script after pruning snapshot
        pruning_script = /path/to/script.sh
        ### don't take an inconsistent snapshot (skip if pre script fails)
        #no_inconsistent_snapshot = yes
        ### run post_snapshot_script when pre_snapshot_script is failing
        #force_post_snapshot_script = yes
        ### limit allowed execution time of scripts before continuing (<= 0: infinite)
        script_timeout = 5

[template_ignore]
        autoprune = no
        autosnap = no
        monitor = no

**Comment by JayStarrco** [comment]
We are running version 2.0.0
cat /cbin/sanoid/VERSION
2.0.0

**Comment by JayStarrco** [comment]
1 0-23 * * *       TZ=UTC /cbin/sanoid/sanoid --cron ; RC=$?; if [[ $RC -ne 0 ]]; then echo "Sanoid failed to run with return code $RC"|mail -s "[stor1] Sanoid failure" monitoring@example.com; fi

**Comment by jimsalterjrs** [comment]
Where is tank/VDS being replicated in from? That backup template isn't taking *any* snapshots unless something's desperately wrong; any new snapshots will be taken at wherever the source for tank/VDS is, along with the hourlies and dailies you're showing.

**Comment by JayStarrco** [comment]
tank/VDS is our VM servers. We are running KVM and the VMs are all Ubuntu 18.04.3 LTS. 
I am a little new to ZFS but are you saying that ZFS is creating the hourlies and frequentlies on the VMS and that sanoid is just copying the snapshots?

**Comment by fryfrog** [comment]
More likely sanoid on the VM server and syncoid is bringing them over?

**Comment by jimsalterjrs** [comment]
The sanoid.conf you're showing me doesn't create **any** snapshots at all on tank/VDS. It's a stock or fairly stock copy of the provided [template_backup], which has `autosnap=no` explicitly set, as you can see in your own paste.

You're taking the snapshots on some other server, and replicating them in to that server. All Sanoid is doing to tank/VDS on that server is _removing_ snapshots as they become stale according to the policy defined in `[template_backup]`.

**Comment by phreaker0** [comment]
@JayStarrco like the others already said. Your config doesn't create those snapshots but they are probably received from some other server. If you provide more information we can reopen the ticket and help with further debugging.
