### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by fryfrog** [jimsalterjrs/sanoid#433]
It has been ~9 months and 130+ commits since the last release. Could you guys do one? :)

**Comment by jimsalterjrs** [comment]
Fastest way to get that done is submit a PR that increments version number to a new minor, and updates the CHANGELIST to document the commits. =)

**Comment by fryfrog** [comment]
:o

**Comment by jimsalterjrs** [comment]
Dead serious here, yes we're overdue for a new release but the time to document the CHANGELIST is the biggest barrier right now. You Can Contribute! =)

**Comment by fryfrog** [comment]
https://github.com/jimsalterjrs/sanoid/pull/434

**Comment by jimsalterjrs** [comment]
Thank you! 2.0.2 is now a thing.
