### ISSUE TITLE
Please update the packaging to correspond with latest version numbering

### ISSUE THREAD

**Issue by felimwhiteley** [jimsalterjrs/sanoid#436]
Hi There,

Using the DEB build instructions it's unable to upgrade the v2.0.0 package on systems as the 

https://github.com/jimsalterjrs/sanoid/blob/master/packages/debian/changelog

The log is still on version 2.0.0, the fix would be to add new version with

dch -v 2.0.1
dch -v 2.0.2

Thanks

**Comment by jimsalterjrs** [comment]
Thanks Felim!

**Comment by felimwhiteley** [comment]
Cheers Jim, talk about service :-)

**Comment by jimsalterjrs** [comment]
Honestly credit goes to @phreaker0 , I sadly don't know bollocks about deb packaging :)

**Comment by felimwhiteley** [comment]
LOL alright so, redirecting thanks :)
