### ISSUE TITLE
syncoid occational errors: could not find any snapshots to destroy; check snapshot names

### ISSUE THREAD

**Issue by magore** [jimsalterjrs/sanoid#44]
I am seeing the following happen occasionally when I am running syncoid  manually to replicate to a remote host  - note: rerunning always fixes it.
I think that because sanoid is running in a cron task that syncoid is seeing an unexpected state change ? 

Sending incremental disk-pool/opt@autosnap_2016-08-15_03:00:02_hourly ... syncoid_media_2016-08-15:12:34:52 (~ 100.2 MB):
 100MiB 0:00:01 [61.3MiB/s] [================================>] 100%            
could not find any snapshots to destroy; check snapshot names.
CRITICAL ERROR: /usr/bin/ssh -c chacha20-poly1305@openssh.com,arcfour -p 22 -S /tmp/syncoid-root-root@backup-1471278891 root@backup " /sbin/zfs destroy disk-pool/opt@syncoid_media_2016-08-15:12:21:39;  /sbin/zfs destroy disk-pool/opt@syncoid_media_2016-08-15:03:30:58" failed: 256 at /usr/local/bin/syncoid line 666.

**Comment by jimsalterjrs** [comment]
Correct, Mike - if you update to the most recent version of Syncoid, it'll WARN instead of CRIT'ing (and failing) when it encounters this condition.
