### ISSUE TITLE
Missing documentation on zfs_recursion for atomic snapshots

### ISSUE THREAD

**Issue by danielewood** [jimsalterjrs/sanoid#442]
In regards to #320, I didnt see any updates in sanoid.conf or sanoid.defaults.conf.

I tried adding zfs_recursion = 1 to my template, but that didnt work.

What is the proper method for enabling atomic recursive snapshots?

Thanks!

**Comment by 0xFelix** [comment]
From the code it looks like you have to add `recursive = zfs`

**Comment by phreaker0** [comment]
@0xFelix this is correct
