### ISSUE TITLE
Continuous Replication with Syncoid

### ISSUE THREAD

**Issue by chrismcv** [jimsalterjrs/sanoid#444]
Hi, New here, sorry if this is a silly question.

I want to send my snapshots to a remote host continuously, I'm wondering what the best way to achieve this with Syncoid is? Is there a daemon like the `sanoid.timer`? Or do I just cron (and will it clash detect with itself?)

Thanks, 
chris

**Comment by jimsalterjrs** [comment]
Cron works well. Syncoid can handle detection of simultaneously running 
processes just fine.

**Comment by chrismcv** [comment]
perfect - thanks!

**Comment by fryfrog** [comment]
Just create your own `syncoid.service` and `syncoid.timer`, you're already using systemd so why mix in old cron?
