### ISSUE TITLE
syncoid dst end error

### ISSUE THREAD

**Issue by timkgh** [jimsalterjrs/sanoid#448]
Not critical, but letting you know there's still an issue with the end of DST:

```
cannot create snapshot 'rpool@syncoid_xxx_2019-11-03:01:05:01': dataset already exists
CRITICAL ERROR:   zfs snapshot 'rpool'@syncoid_xxx_2019-11-03:01:05:01
 failed: 256 at xxx/zfs/sanoid/syncoid line 1377.
```

**Comment by gdevenyi** [comment]
Fix already proposed at #409

**Comment by phreaker0** [comment]
@timkgh v2.0.3 only fixes DST stuff in sanoid not syncoid

**Comment by timkgh** [comment]
It's the end of DST, errors from both `sanoid` and `syncoid`, it doesn't seem it's fixed in syncoid either per previous comment.

**Comment by redmop** [comment]
I'm not sure the fix made it to release. It has been 1 year today since the last one.

**Comment by timkgh** [comment]
The project does not appear to be active like it used to be.

**Comment by jimsalterjrs** [comment]
I've been just STUPID busy since going full time at Ars Technica. The project itself has been pretty active, it's me that's been inactive. =\
