### ISSUE TITLE
batch snapshots together

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#455]
Hi. 
I currently have my own cobbled together snapshot bash scripts.  Separate scripts for snapshot, replicate and pruning.   One of the things I do is pause one (or more) VM(s), then I will snapshot all of their disks, then resume the VM(s).  That gives me the atomicity when a VM has multiple disks or across a couple of VMs that work together.  

My snapshot format looks like this: tank/data/client@2019-11-04_23-00-00__daily__batch1

Where daily would be the frequency
batch1 is a batch/grouping name 

Does anyone see a way that this can work without using any of my scripts?  Can I group datasets together and have a single pre snapshot command?

If not, can I manually trigger a sanoid snapshot from inside my scripts?  

Last resort would be to format the snapshot to match what sanoid does.  I have not quite figured out how you differentiate between different frequencies with the format.  

thanks,
Geoff

**Comment by phreaker0** [comment]
@gnordli yes you can instruct sanoid to take a recursive atomic snapshot of a dataset with all subdatasets. In this case a specified pre_snapshot command will only be executed once for the top level dataset:

```
[tank/data/client]
    ....
    recursive = zfs
    ....
```

**Comment by phreaker0** [comment]
you could also do a snapshot for all datasets:

```
[tank]
    ....
    recursive = zfs
    ....
```

and define custom prune policies for the sub datasets so the unneeded snapshots are removed after.

**Comment by gnordli** [comment]
That is a good idea, but won't work as I can only pause a machine for a few seconds or clients will notice the server absence and start to disconnect.  Once you pause 3 or 4 machines at the same time it starts to hit the limit.  

I think there is some value with being able to list multiple datasets under a single section.  A lot of times virtual machines will have multiple disks attached to it and you want to treat them as a single unit.

**Comment by phreaker0** [comment]
okay so currently you would need to organize all disk zvols for an vm under a root vm dataset. Then you can use the recursive=zfs stuff per vm.

```
[tank/data/client/vm1]
    ....
    recursive = zfs
    ....

# tank/data/client/vm1/disk1
# tank/data/client/vm1/disk2
# tank/data/client/vm1/disk3
```

I thought about a feature to group snapshoting taking together but hadn't the time to implement it yet (also because of recursive=zfs I don't need to if I'm organzing the datasets the right way)

**Comment by gnordli** [comment]
I would totally do that.  In fact when you mentioned it I thought, why didn't I think of that.   It was because you can't do that with a zvol, only filesystem datasets have a hierarchy.

**Comment by phreaker0** [comment]
I would do it with a dummy filesystem dataset parent which isn't mounted:

```
zfs create tmp/vm1 -o canmount=off
zfs create -V 1M tmp/vm1/disk1
zfs create -V 1M tmp/vm1/disk2
zfs create -V 1M tmp/vm1/disk3
```

or better, use the filesystem dataset as storage for the xml description of the vm and stuff like that.

**Comment by gnordli** [comment]
BTW, this isn't a huge deal, I have scripts already in place to do the snapshots.   
I just need to nail down the format.  It seems I may already have a decent enough format.  

tank/data/client@2019-11-04_23-00-00__daily__batch1

If that was my daily frequency would I need any changes to make it managed by sanoid for pruning?

**Comment by phreaker0** [comment]
Sanoid format for dailies is:

`autosnap_2019-11-04_21:01:39_daily`

**Comment by gnordli** [comment]
@phreaker0 That is brilliant, I didn't know you could nest them,but it makes sense.  I will think about that layout instead.

**Comment by phreaker0** [comment]
glad I could help. I think the question in answered :-)
