### ISSUE TITLE
multi-master replication or master/slave

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#456]
Hi again. 

I work with small businesses.  My design goal is to build a two-node cluster on-site plus an offsite backup all ready to be able to be used.  In the event there is a failure.  I have that going now, but there is a lot of manual intervention/configuration required which is not ideal.  

Any thoughts on two or three nodes being able to replicate to each other and marking one the "master". 

thanks,
Geoff

**Comment by phreaker0** [comment]
multi-master isn't possible.
master/slave with manual intervention can be done, I myself have a setup running like this:

storage pool "storage" on both nodes, two parent datasets for the two nodes:

- storage/primary
- storage/secondary

in my case the slave/secondary node is used as a backup server and writes to datasets in the storage/secondary group.

syncoid is used to pull storage/primary from the primary to the backup and vice versa. In both cases the --no-rollback option is used, so in the case I do a failover I don't risk losing any data by accident an need to intervene manually to resolve the conflict. In any case you will need some external scripting.

**Comment by gnordli** [comment]
Hi.   I just finished up my supporting scripts now.  I broke things down into three parts:  snapshot, replication, and pruning.  

I created a conf.d folder, where I then put one configuration folder per vm/dataset.  I then created different group folders with symbolic links to the configurations.  The scripts will loop through all the configurations in specific group folder for snapshots.   This will allow for different scheduling for each group.  You can have different groups for pruning/snapshots/replication

In the configuration folder I put source and target information in files in the configuration folder.  When doing the replication I look in the folder to find the source/target information.  One file for source and one file for target.  The target file can have multiple lines with different targets. 

To make changes I only need to add/remove the symbolic link in group.   For replication I would need to change the source/target files.    

The only thing I am missing is just some extra stats with replication.  See https://github.com/jimsalterjrs/sanoid/issues/493.  

thanks for all your help!!
Geoff
