### ISSUE TITLE
Syncoid 2.0.2 and 2.0.3 using --no-privilege-elevation can't find zfs

### ISSUE THREAD

**Issue by HunnyPuns** [jimsalterjrs/sanoid#457]
I have a number of servers replicating to an off-site server. The latest source server that was setup was unable to replicate to the destination server. It was giving the error "bash: zfs: command not found"

I checked the user on the destination server, su - to the user, and sure 'nuff, I couldn't just run zfs. But I checked another user that was working, they couldn't just run zfs either. I added /sbin/zfs to the path anyway, and it still failed with the same message, even though as the user I could run just zfs at that point.

This was initially done on Syncoid 2.0.2. I updated to 2.0.3, and had the same issue. I reverted to 2.0.1, and was able to start syncing without issue.

Here is a list of the flags I use on the source side:
--sshciper chacha20-poly1305@openssh.com
--sshkey ed25519 key
--sshport some high port or another
--no-resume
--no-sync-snap
--no-privilege-elevation
--recursive

On the destination side, I use ZFS delegation and grant these permissions:
create,diff,mount,readonly,receive,release,send,userprop

Also, we are replicating zvols, if that makes a difference.

Attaching a somewhat sanitized debug log of one of the zvols failing to replicate.
[SyncoidDebug.txt](https://github.com/jimsalterjrs/sanoid/files/3828093/SyncoidDebug.txt)

**Comment by phreaker0** [comment]
@HunnyPuns your remote system PATH is not configured correctly (for the specified user), therefore zfs binary can't be found. Since 2.0.2 syncoid uses the PATH for command lookup instead of using fixed command locations to support more command locations on different systems. I tried to find a way to make it backward compatible for systems which doesn't set the PATH correctly but for ssh connection this was to tricky and there doesn't seem to be an reliable way. So the only solution for you is to fix the PATH initialization on your remote server.

**Comment by HunnyPuns** [comment]
@phreaker0 That's what I thought, too. But I changed the remote path to include I think it's /sbin where zfs is. I am able to ssh into the remote server now as that user, and do things like zfs list and such. Maybe I set it in the wrong place? Since all of my other dedicated users a working, I just applied this new path to the one user who was not working.

After applying the new path, and verifying that I could run the zfs command as that user, I had Syncoid 2.0.2 take another attempt at replicating. It failed with the same message. That's when I upgraded to 2.0.3, which also failed, and then I downgraded to 2.0.1, and it works.

I'm game to try other things, but this really strikes me as a Syncoid problem.

**Comment by phreaker0** [comment]
@HunnyPuns have you tried with a shell or direct command invocation? Please try:

`ssh user@remote-server zfs --version`

**Comment by HunnyPuns** [comment]
It was a shell. I'll try command invocation tonight.

**Comment by HunnyPuns** [comment]
Invocation failed. I updated the path in .profile, instead of .bashrc. Updated the path in .bashrc and I can invoke a command via ssh. Thank you!

**Comment by mdPlusPlus** [comment]
@HunnyPuns Sorry to bother you, but I seem to be running into the same problem. Could you please elaborate how exactly you fixed this? For me, neither adding `export PATH="$PATH:/usr/sbin/"` in `~/.bashrc` nor in `/etc/bash.bashrc` does work.
