### ISSUE TITLE
Adjust monitoring messages to allow copy/paste of filesystem names

### ISSUE THREAD

**Issue by dlangille** [jimsalterjrs/sanoid#461]
When monitoring the snapshots, a message like this might arrive:

```
CRIT: tank_fast/poudriere/jails/120amd64's newest daily snapshot is 6d 4h 48m 2s old (should be  
1d 8h 0m 0s), CRIT: tank_fast/poudriere/jails/120amd64s newest hourly snapshot is 5d 8h 48m 
4s old (should be  6h 0m 0s)
```

When copy/pasting that filesystem name (`tank_fast/poudriere/jails/120amd64`) care must be exercised not to include the trailing `s`.  It would be easier if there was no trailing `s`.

I went to patch the code but found there is intent to have `'s`, not just `s`.  

`push @msgs, "CRIT: $path\'s newest $type snapshot is $dispelapsed old (should be < $dispcrit)";`

re https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L161

Somewhere, somehow, that single quote is getting dropped.

**Comment by redmop** [comment]
Let's drop the 's altogether. Makes scripting easier.
