### ISSUE TITLE
Syncoid "invalid option 't'" on latest Solaris 11.4

### ISSUE THREAD

**Issue by Will-Moshe** [jimsalterjrs/sanoid#464]
Same issue as #172 .

Suggested fix is to use latest Solaris, but it still fails. 

Would love to see a `--solaris` flag implemented if possible.

**Comment by Will-Moshe** [comment]
Oddly, `sanoid 1.4.8` doesn't have this issue.

**Comment by fryfrog** [comment]
I would suggest re-opening or asking them to re-open the old one, no real reason to split it. The original issue was wrong about the fix.

**Comment by phreaker0** [comment]
Solved with #476 which is in master now and will end up in the next release
