### ISSUE TITLE
CentOS 8 package dependencies

### ISSUE THREAD

**Issue by srcc-chekh** [jimsalterjrs/sanoid#466]
Seems perl-Config-IniFiles and perl-Capture-Tiny are not available in base or epel on CentOS 8.

> [root@reg sanoid]# dnf install perl-Capture-Tiny
> Last metadata expiration check: 0:00:57 ago on Mon 09 Dec 2019 10:58:11 AM PST.
> No match for argument: perl-Capture-Tiny
> Error: Unable to find a match
> 
> [root@reg sanoid]# dnf install perl-Config-IniFiles
> Last metadata expiration check: 0:02:22 ago on Mon 09 Dec 2019 10:58:11 AM PST.
> Error:
>  Problem: conflicting requests
>   - nothing provides perl(IO::Scalar) >= 2.109 needed by perl-Config-IniFiles-3.000002-3.el8.noarch
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
>

**Comment by srcc-chekh** [comment]
workaround for now:
dnf install perl-CPAN
cpan
install Capture::Tiny
install Config::IniFiles

**Comment by mddeff** [comment]
@srcc-chekh

Ran into the same issue (google search lead me here).  `perl-Capture-Tiny` and `perl-IO-stringy` (dependency of `perl-Config-IniFiles` coming from EPEL) is actually available in CentOS 8's 'Power Tools' repo:

```
dnf config-manager --set-enabled PowerTools
```

After enabling this repo I was able to install all required perl modules.

**Comment by Topslakr** [comment]
PR #584 addresses this more cleanly. As mddeff says, installing the PowerTools repo is the correct method.

I posted the PR yesterday and thought I might look to see if others had found other workarounds.

**Comment by echo-devnull** [comment]
2023 and people are still finding this ;-)

Anyway, I'm on RHEL8, no access to the internet (company policy) and only the RHEL8 and epel repo's are available via locally hosted repo server.

So I guess I'm out of luck?

**Comment by mailinglists35** [comment]
note for Oracle Linux (OL), the `perl-Capture-Tiny` package[ is in repo](https://forums.oracle.com/ords/apexds/post/powertools-and-pgadmin-4-on-oracle-linux-8-8360) `ol8_codeready_builder` 

`dnf --enablerepo=ol8_developer_EPEL,ol8_codeready_builder install perl-Capture-Tiny`

**Comment by mailinglists35** [comment]
> Anyway, I'm on RHEL8, no access to the internet (company policy) and only the RHEL8 and epel repo's are available via locally hosted repo server.
> 
> So I guess I'm out of luck?

usb flashdrive with the rpm?
