### ISSUE TITLE
Lots of errors during ZFS scrub

### ISSUE THREAD

**Issue by olegblecher** [jimsalterjrs/sanoid#467]
Hi there,

I'm running Sanoid 2.0.0 on Ubuntu 16.04. 

In the last few months, the ZFS scrubs have started to take more and more time on one particular production server. Normally, I don't mind, I let it take its time.

However, during the last few scrubs which last 50-70 hours, I get a lot of the following errors from Sanoid (which runs as a cronjob every 5 minutes):

```
could not find any snapshots to destroy; check snapshot names.
could not remove tank/container...... : 256 at /usr/bin/sanoid line 326.
```

As well as:

```
ERROR: No valid lockfile found - Did a rogue process or user update or delete it?
```

Does anyone else recognize this? Should I configure Sanoid to be working in another way when ZFS is performing its monthly scrub?

Here's my `sanoid.conf`:

[tank/container]
        use_template = backup
        recursive = yes
        process_children_only = yes

# backup of all regular data and containers without any particular needs
[template_backup]
        hourly = 48
        daily = 90
        monthly = 6
        yearly = 3

Thanks in advance!

**Comment by phreaker0** [comment]
During scrub the zfs commands take much longer and then you are running multiple sanoid processes at once. For further details and solutions look here: https://github.com/jimsalterjrs/sanoid/issues/459#issuecomment-554657389
