### ISSUE TITLE
sanoid on openmediavault - how to setup nagios 

### ISSUE THREAD

**Issue by comsyspro** [jimsalterjrs/sanoid#470]
Hi,

I've setup an openmediavault server (debian linux) and have configured nagios on it. Now I want to tryout nagios but don't know how you can monitor the sanoid logs (--monitor-snapshots etc.). The command `sanoid --monitor-snapshots` gives following output: 

> OK: all monitored datasets (pool1/data) have fresh snapshots

but how I can collect these logs to nagios? Do I need here a nagios plugin or can I do something with `/usr/local/nagios/libexec/check_log` command?

Thanks.

Here is a screenshot of nagios but I don't know how this should work with sanoid together:
![image](https://user-images.githubusercontent.com/13809377/71521686-0d4ae500-28c2-11ea-8c82-10b703143ddc.png)

**Comment by phreaker0** [comment]
@comsyspro 
you instruct nagios/icinga to run the sanoid command as check plugin, the output is already in the correct format.
`sanoid --monitor-snapshots`
`sanoid --monitor-health`

**Comment by comsyspro** [comment]
Thanks to your hint I've found an article about writing check plugins for nagios:

[https://www.howtoforge.com/tutorial/write-a-custom-nagios-check-plugin/](url)
