### ISSUE TITLE
What commands does syncoid try to run using sudo?

### ISSUE THREAD

**Issue by UntouchedWagons** [jimsalterjrs/sanoid#471]
I'm trying to get syncoid to replicate snapshots using as few permissions as possible. I set up a dedicated replication user on my desktop and on my server (the source and destination respectively) with (hopefully) the appropriate zfs permissions for replication but syncoid invokes sudo somewhere. Hopefully what I'm getting at makes sense but what does syncoid need to run as sudo?

**Comment by phreaker0** [comment]
There is a flag for this use case:
`      --no-privilege-elevation  Bypass the root check, for use with ZFS permission delegation`
