### ISSUE TITLE
syncoid: snapshot pruning on target for 1:1 replication?

### ISSUE THREAD

**Issue by gdevenyi** [jimsalterjrs/sanoid#477]
I have been using syncoid to replicate an active pool to offsite disaster recovery and discovered yesterday that my disaster target is out of space. This appears to be due to snapshots (zfs-auto-snapshot based) which have been pruned on the source still being present in the target.

I thought --force-delete might be the option to enable this but I realize now it just removes datasets that are no longer present on source.

So unless I'm missing something in the options, I'd like to request such a feature.

**Comment by phreaker0** [comment]
I think there were already requests to prune on the target too in the past, but this shouldn't be done by syncoid was the decision as far as I know @jimsalterjrs  please correct me here if this is wrong and we can reopen the ticket if so.

In you case you should run zfs-auto-snapshot --destroy-only on the target server to cleanup there. I'm doing the same with sanoid.

**Comment by gdevenyi** [comment]
> In you case you should run zfs-auto-snapshot --destroy-only on the target server to cleanup there. I'm doing the same with sanoid.

That's exactly what I needed. Cheers.

**Comment by mat813** [comment]
Mmmm, the thing is, different machines being backuped through syncoid could have different policies regarding snapshots, and using different tools for managing the snapshots automatically.

How could the server where all the data is sync'ed could possibly know which to expire and when?

While I agree that syncoid deciding to remove remote snapshots would not be most people's cup of tea, making an informed decision of "yes, I want you to remove snapshots that I removed" would be great.

**Comment by gdevenyi** [comment]
@mat813 thats a really good point, for me, this wasn't an issue since this is an identical off-site replication, but this may not be the case for some users.

I don't have the bandwidth to work on this right now, but perhaps someone can sort out a PR to address this.
