### ISSUE TITLE
syntax error at /usr/sbin/sanoid line 1406, near "unlink"

### ISSUE THREAD

**Issue by florian-obradovic** [jimsalterjrs/sanoid#479]
Hey,
i just installed sanoid on Ubuntu 18.04 but i get this error on execution
`sanoid
syntax error at /usr/sbin/sanoid line 1406, near "unlink"
Execution of /usr/sbin/sanoid aborted due to compilation errors.`

any hints what I am missing?
Regards, Flo

**Comment by phreaker0** [comment]
this #478 fixes it

**Comment by florian-obradovic** [comment]
Hey @phreaker0 thx a lot - the fix is not in current release right?

**Comment by jimsalterjrs** [comment]
@florian-obradovic I merged the fix for this into master just now.

Neither this bug nor the patch that introduced it are in the most recent release. Only in master.

**Comment by florian-obradovic** [comment]
@jimsalterjrs thx a lot!
