### ISSUE TITLE
ZFS deduplication

### ISSUE THREAD

**Issue by Nicolas-V13** [jimsalterjrs/sanoid#484]
Hi all,

This is my first post on this website so please be kind with me :)

On Centos 7, using ZFS deduplication in the past on a storage pool, I moved all file-systems that dedup was on to another storage pool.

But, doing a "zpool status -D " I can see that deduplication is still in use on this pool.

I think that, if deduplication was ON on a file-system in the past, then changed to off, but in meantime some snapshot were taken, the deduplication is there, and there are no possibility to know exactly where it is coming from....

Am I right? is there any possibility to know if deduplication is in use on snapshots ?

Thanks for your help and sorry in advance if this is not the best place to post this issue...

Regards, Nicolas

**Comment by fryfrog** [comment]
You'd probably be better off asking this on a more general ZFS forum, maybe reddit's /r/zfs?

But I think you're right, any snapshots from when deduplication was *on* will be holding those blocks. I think your only real choice is to remove all snapshots from *before* deduplication was turned off or wipe and re-create the pool. You should be able to figure out how much memory your DDT is consuming, if you've re-written most of your data after turning it off, it might not be very big.

**Comment by phreaker0** [comment]
@Nicolas-V13 fryfrog already pointed you in the right direction.
