### ISSUE TITLE
Installation on Ubuntu 19.10 failing

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#489]
Hi.
I followed the instructions on the install guide for installation of Debian/Ubuntu by creating a package. 
I am running on Ubuntu 19.10.
When I try to install the package it errors out. 
Setting up sanoid (2.0.3) ...
dpkg: error processing package sanoid (--configure):
 installed sanoid package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 sanoid

any ideas?
thanks,
Geoff

**Comment by gnordli** [comment]
I just went into the /var/lib/dpkg/info/sanoid.postinst file and commented out:
##[ -f /var/cache/sanoidsnapshots.txt ] && rm /var/cache/sanoidsnapshots.txt

and configured again:
dpkg --configure -a

**Comment by phreaker0** [comment]
@gnordli did it work after commenting out that line? The only way this line would fail is if the cache file can't be deleted, but I don't see how because the package manager has root permission as far as I know.

**Comment by gnordli** [comment]
yes it worked when I commented out that line.  It also works if I create the file first, then do the install.

**Comment by phreaker0** [comment]
@gnordli thx, could reproduce it
