### ISSUE TITLE
syncoid feature request: notice clones on source and re-create them as clones on target

### ISSUE THREAD

**Issue by fmyhr** [jimsalterjrs/sanoid#49]
First, thank you very much for syncoid! It's making my life much better.

Don't know if this is in scope, but:
Today upon completion of a recursive syncoid to an empty target dataset I noticed that the target was using 9GB, while the source was using only 5GB. This turned out to be because a 4GB dataset on the source was actually a clone of a snapshot. It would be great if syncoid could notice that a source dataset is a clone (with origin property) and instead of doing a full send/receive, instead clone the appropriate snapshot on the target.

**Comment by ewwhite** [comment]
I was also looking at this issue. 

I think ZFS send/receive is clone-aware and can recreate the clone on the target if the snapshot is present. Is this possible in syncoid?

**Comment by mailinglists35** [comment]
I'd pretty much wish this will be supported - I have hundreds of clones of a snapshot (lxd when used with zfs backend creates clones from snapshots)

**Comment by mailinglists35** [comment]
@fmyhr if you read comments by mail this is just a kind observation that i've further improved my previous comment while you might get on the email only the original form

**Comment by mailinglists35** [comment]
@jimsalterjrs if you read comments by mail this is just a kind observation that i've further improved my previous comment while you might get on the email only the original form

**Comment by jimsalterjrs** [comment]
@mailinglists35 can you give me an example of doing this clone-aware replication from the command line?  I am following what you want, but not sure I'm following how it could be handled in practice.

**Comment by zrav** [comment]
I'm very much looking forward to this feature. Atm one has to manually transfer the first clone dataset snapshot before being able to use syncoid.

Programmatically you could proceed like this:
- When getting the list of datasets to sync, also read the origin property to determine which are clones and which aren't. 
- Sync all the non-clone datasets first. 
- When syncing clones, if it is a new dataset, send it like an incremental send, like "zfs send -i originDS@clonebaseSnap cloneDS@firstSnap" and "zfs receive cloneDS". This will recreate the clone on the target.
- Once the clone exists on the target, it can be treated like a regular dataset regarding further incremental sends.
