### ISSUE TITLE
Little glitch on startup of sanoid 2.0.3

### ISSUE THREAD

**Issue by gbonazzoli** [jimsalterjrs/sanoid#490]
Sanoid has to prune 200.000 snapshots that were created by a failing script.

Every time I start it, I get these warnings:
```
root@rsm-dr1:/# /usr/local/bin/sanoid --cron
Use of uninitialized value $checkmutex in scalar chomp at /usr/local/bin/sanoid line 1421.
Use of uninitialized value $checkmutex in string eq at /usr/local/bin/sanoid line 1423.
```
Working on pruning the 200.000 sanoid starts fasts with a pace of 80 snapshots destroyed every 3 minutes and after a day of working it has slowed down to 50 snapshots every 4 minutes.

If you relaunch it, sanoid will return to the original pace of 80 snapshots destroyed every 3 minutes

**Comment by phreaker0** [comment]
This is probably fixed by #473 which is in master. The speed shouldn't have anything to do with sanoid but zfs itself. Stopping and starting sanoid again for pruning will probably give zfs some time to clear up some succeeding async stuff and this will be the reason why initial speed is higher again.

**Comment by phreaker0** [comment]
@gbonazzoli did you try the master?

**Comment by gbonazzoli** [comment]
You are right, the master hasn't the little defect.

Well done!

Now I'm running it for purging the last 130.000 snapshots.

**Comment by dlangille** [comment]
This just happened for me with sanoid 2.0.3 on FreeBSD 12.1 but much fewer snapshots:

```
[dan@zuul:~] $ zfs list -r -t snapshot | wc -l
    2314
```

**Comment by ovizii** [comment]
> @gbonazzoli did you try the master?

Can you give me a pointer what needs to be changed from the default instructions to run a stable version of sanoid? Sounds like 2.0.3 as instructed here is not the latest stable release? https://github.com/jimsalterjrs/sanoid/blob/master/INSTALL.md#debianubuntu

**Comment by gbonazzoli** [comment]
Yes I did.

It is working without problems since 1 month ago.

Regards,

**Comment by phreaker0** [comment]
@ovizii 2.0.3 is the latest stable, but the fix is in master and not any release version yet If you leave out the "git checkout $(git tag | grep "^v" | tail -n 1)" step from the instruction you will get the latest master version.

**Comment by phreaker0** [comment]
#601
