### ISSUE TITLE
how to control TZ of snapshots

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#492]
I see in the docs you can control the TZ selection by using TZ=UTC in the cron file. 
If you aren't using that cron file how is the TZ determined.  For some reason when I first started taking snapshots it was using my local time (Pacific) and then after I rebooted it started using GMT as the snapshot time.  

Any thoughts?  

thanks,
Geoff

**Comment by phreaker0** [comment]
The systemwide configured timezone in /etc/localtime should be used, you can check with a one liner:

`perl -e 'use POSIX;print strftime("%Z", localtime()), "\n";'`

Using the TZ env variable once can override the systemwide default timezone.
