### ISSUE TITLE
syncoid replication stats

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#493]
Hi.
I have been writing some scripts to manage the replication process.  I like to direct all output to a log file, then e-mail the log file after the replication is done.  Then I can look at the stats of replication to see if anything doesn't look right. 

Right now it looks like this when you are doing a replication:
 /usr/sbin/syncoid --recursive --no-sync-snap --skip-parent tank/vm/oi-exch1 backup/vm/oi-exch1
2.74KiB 0:00:00 [33.0KiB/s] [==============================>                ] 68%            
5.96KiB 0:00:00 [74.0KiB/s] [==================================>            ] 76%            
 277MiB 0:00:01 [ 199MiB/s] [=============================================> ] 99%           

In my script I am piping that to a log file with the > $LOG at the end. 
I get something like this in my log file:
NEWEST SNAPSHOT: autosnap_2020-02-07_13:03:17_hourly
Sending incremental tank/vm/oi-exch1/data@autosnap_2020-02-06_20:51:59_hourly ... autosnap_2020-02-07_13:03:17_hourly (~ 4 KB):
NEWEST SNAPSHOT: autosnap_2020-02-07_13:03:17_hourly
Sending incremental tank/vm/oi-exch1/data/oi-exch1-data@autosnap_2020-02-06_20:51:59_hourly ... autosnap_2020-02-07_13:03:17_hourly (~ 7 KB):
NEWEST SNAPSHOT: autosnap_2020-02-07_13:03:17_hourly
Sending incremental tank/vm/oi-exch1/data/oi-exch1-root@autosnap_2020-02-06_20:51:59_hourly ... autosnap_2020-02-07_13:03:17_hourly (~ 277.8 MB):
NEWEST SNAPSHOT: syncoid_oi-stor1_2020-02-06:09:17:24

Is it possible to get some more stats on the output.  I would like to see the MB/s and time it took for each dataset something like the zfs send like below:  

sudo /usr/sbin/zfs send -pv -I tank/si-dmz1-root@2020-01-23_23-00-00__daily__batch1 tank/si-dmz1-root@2020-01-24_23-00-00__weekly__batch1 sudo /usr/sbin/zfs recv -vu backup/si-dmz1-root
receiving incremental stream of tank/si-dmz1-root@2020-01-24_23-00-00__weekly__batch1 into backup/si-dmz1-root@2020-01-24_23-00-00__weekly__batch1
**received 3.38GB stream in 26 seconds (133MB/sec)** 

thanks,
Geoff

**Comment by phreaker0** [comment]
@gnordli this is already supported via the recvoptions setting, use:
`syncoid --recvoptions="v" ...`

**Comment by gnordli** [comment]
Perfect, thank you.  
I don't think I saw that in any syncoid documentation, unless I missed it.
