### ISSUE TITLE
two cronjobs: snapshot & prune

### ISSUE THREAD

**Issue by dlangille** [jimsalterjrs/sanoid#496]
I now run this:

`*/5 * * * * root /usr/bin/lockf -t 0 /tmp/.sanoid-cron /usr/local/bin/sanoid --cron`

That `lockf` avoids multiple concurrent instances.

When things get busy, that job can take some time to run, perhaps 10 minutes.  I suspect it is the pruning which is taking time.

I plan to change my approach to this:

```
*/5 * * * * root /usr/bin/lockf -t 0 /tmp/.sanoid-cron-snapshot /usr/local/bin/sanoid --take-snapshots
*/5 * * * * root /usr/bin/lockf -t 0 /tmp/.sanoid-cron-prune    /usr/local/bin/sanoid --prune-snapshots
```

Is this an unwise approach? I think it makes sense because pruning can take some time, but snapshots are much faster.

I don't mind snapshots which linger longer than planned. I would rather have snapshots taken every time and on time.

Thank you.

**Comment by dlangille** [comment]
While researching this, I found #13 but concluded it was too out-dated to consider.

**Comment by phreaker0** [comment]
In my opinion it's the better approach as it doesn't delay the snapshot taking. If you use a systemd based distro it's also documented as the default way to setup sanoid: https://github.com/jimsalterjrs/sanoid/blob/master/INSTALL.md

**Comment by redmop** [comment]
I run my prunes daily. Usually about 5-15 after I take the daily snapshot.
Uses more disk space, but controls when the disk io for cleanup happens.

**Comment by jdrch** [comment]
> I run my prunes daily

Yes, from my personal experience with `zfsnap`/`zfsnap2` as well as `restic` pruning on POSIX fileystems is more computationally expensive than creation, and you always want to do it as a regularly scheduled batch job as opposed to something you run after each creation.

Someone should really ask the NTFS & ReFS devs how they implemented low-cost snapshot pruning as seen on Windows. It's the only local, on-disk snapshot system I've encountered that does not have this issue.
