### ISSUE TITLE
Can the syncoid SSH port be specified on the command line?

### ISSUE THREAD

**Issue by ewwhite** [jimsalterjrs/sanoid#51]
A customer uses SSH port 2223 for the source server I'll be replicating from in syncoid. I have entries in /etc/ssh/ssh_config  for the hostname to force port 2223:

    Host *ancaste*
        Port 2223

I don't think syncoid honors this, so I'm looking for the cleanest way to be able to modify the SSH port on the fly without hardcoding the script.

**Comment by pferland** [comment]
Looking at the code for the syncoid script, on line 40, it has a check to see if $args{'sshport'} is set. So I am getting if you do -sshport=2223 it would take it.

**Comment by jimsalterjrs** [comment]
This is correct; sshport was a recently merged pull. It works as described.

--------

**Comment by jimsalterjrs** [comment]
Syncoid *should* honor nearly anything set in ssh_config, including port 
numbers, actually.

--------

**Comment by ewwhite** [comment]
Yes, the `-sshport=2223` works for me. Thank you.
