### ISSUE TITLE
critical error no datasets found  -- seems to be a permissions issue

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#514]
Hi. 
I am trying to use a regular user account with zfs delegated permissions.  

It is working fine if just use the defaults
` /usr/sbin/syncoid  tank/data/client backup/data/client`
Sending incremental tank/data/client@syncoid_oi-stor1_2020-02-24:14:53:46 ... syncoid_oi-stor1_2020-02-24:15:09:26 (~ 4 KB):

When I add all of the options I want to use it fails.
`/usr/sbin/syncoid --recursive --no-sync-snap --no-rollback --skip-parent  --debug --no-privilege-elevation '--recvoptions="v"' tank/data/client backup/data/client`
DEBUG: SSHCMD: ssh    
DEBUG: checking availability of lzop on source...
DEBUG: checking availability of lzop on target...
DEBUG: checking availability of lzop on local machine...
DEBUG: checking availability of mbuffer on source...
DEBUG: checking availability of mbuffer on target...
DEBUG: checking availability of pv on local machine...
DEBUG: checking availability of zfs resume feature on source...
DEBUG: checking availability of zfs resume feature on target...
DEBUG: recursive sync of tank/data/client.
DEBUG: getting list of child datasets on tank/data/client using   zfs list -o name,origin -t filesystem,volume -Hr 'tank/data/client' |...
CRITICAL ERROR: no datasets found at /usr/sbin/syncoid line 145.

If I just execute the zfs command that is failing it works OK. 

`test@oi-stor1:/etc/sanoid$ zfs list -o name,origin -t filesystem,volume -Hr 'tank/data/client'`
tank/data/client        -

Here are my zfs permissions.
test@oi-stor1:/etc/sanoid$ zfs allow tank
---- Permissions on tank ---------------------------------------------
Permission sets:
        @adminrole clone,create,destroy,hold,mount,promote,quota,receive,rename,reservation,rollback,send,snapshot,userprop
Local+Descendent permissions:
        user test @adminrole
test@oi-stor1:/etc/sanoid$ zfs allow backup
---- Permissions on backup -------------------------------------------
Permission sets:
        @adminrole clone,create,destroy,hold,mount,promote,quota,receive,rename,reservation,rollback,send,snapshot,userprop
Local+Descendent permissions:
        user test @adminrole

I must be missing something else.
thanks,
Geoff

**Comment by gnordli** [comment]
Interesting there are some datasets it seems work fine on.  Not sure what the difference is.  They are all filesystems.

**Comment by phreaker0** [comment]
@gnordli I don't see any issue here. Your are telling syncoid to skip the parent dataset of a recursive call for tank/data/client, but this dataset doesn't have any childrens and the dataset itself is excluded like you specified, so there are no datasets for replication.

**Comment by gnordli** [comment]
Of course, that makes total sense.  LOL totally missed that one.  Thank you @phreaker0.
