### ISSUE TITLE
Feature request: syncoid "sync all" command

### ISSUE THREAD

**Issue by darkpixel** [jimsalterjrs/sanoid#515]
I understand this might take a bit of effort, but I would love to be able to configure syncoid options in a config file like (maybe even in) ```/etc/sanoid/sanoid.conf```.

Coming from zrep, you had the ability to ```zrep init``` one or more filesystems to do the initial replication to a remote machine.  Once that was done, you just had to run ```zrep sync all```.

zrep stores some of that config info using dataset properties, so a ```sync all``` would just look at the properties to see what datasets should be synced.

If syncoid had options in the sanoid config file for things like ```--no-stream```, ```--sendoptions="raw"```, etc... it would be really easy to handle machines with different configurations.

For example, I manage 23 NAS boxes.  Every single one has a ```tank/virt``` dataset, but only a small handful of them have a ```tank/images``` dataset that needs backing up.

I currently take manual backups of the boxes using ```clusterssh``` and am able to issue the exact same command to every single one of them: ```zrep sync all```.  Using syncoid, I would have to sync ```tank/virt``` and then figure out which ones needed ```tank/images``` and issue them separate commands.  It will get more painful when I bring on another 15 machines in the next 2 months. :)

**Comment by phreaker0** [comment]
@darkpixel This can easily be done with a shell script, for example:

**/usr/local/bin/sync_all.sh**
```
#!/bin/bash
code=0

syncoid --no-rollback --quiet root@192.168.1.1:ssd/stuff storage/primary/stuff || code=$?
syncoid --no-rollback -r --quiet root@192.168.1.1:ssd/mysql storage/primary/mysql || code=$?
syncoid --no-rollback -r --quiet --exclude=".*mysql.*" --exclude=".*stuff" root@192.168.1.1:storage/primary storage/primary || code=$?

exit $code
```

On each host you can have different syncoid calls and issue them all at once with the same command over clusterssh.

**Comment by darkpixel** [comment]
That's what I ended up doing.  I'm used to being able to pass environment variables in to adjust things like speed of the backups, so I wrapped the commands with some bash magic and pushed it out from my config management server.
