### ISSUE TITLE
Skip Hourly Snapshots

### ISSUE THREAD

**Issue by asmartin** [jimsalterjrs/sanoid#52]
I only need to take daily snapshots (skipping hourly), and at a particular time of day, so I have my `sanoid.conf` as follows:

```
[mypool/mydataset]
use_template = my_template
recursive = yes


#############################
# templates below this line #
#############################

[my_template]
hourly = 0
daily = 33
monthly = 3
yearly = 0
autosnap = yes
autoprune = yes
```

I then have sanoid configured to run daily at the specific time that I need it to run at:

```
0 6 * * * /usr/local/bin/sanoid --cron
```

However,  an hourly snapshot is still being taken every day:

```
mypool/mydataset@autosnap_2016-10-01_06:00:02_hourly       0      -   736G  -
mypool/mydataset@autosnap_2016-10-02_06:00:02_daily        0      -   735G  -
mypool/mydataset@autosnap_2016-10-02_06:00:02_hourly       0      -   735G  -
mypool/mydataset@autosnap_2016-10-03_06:00:02_hourly       0      -   735G  -
mypool/mydataset@autosnap_2016-10-03_06:00:02_daily        0      -   735G  -
```

How can I prevent this and only take daily snapshots?

Thanks!

**Comment by jimsalterjrs** [comment]
Woah. That's odd.

Can you confirm installed version of sanoid please? sanoid --version from 
the CLI will do the trick.


----------------

(Sent from my tablet - please blame any weird errors on autocorrect)

**Comment by jimsalterjrs** [comment]
Also please post the rest of your conf. I see that your dailies are 
happening at 6am, so I know there's more to the conf than what's posted 
here. :-)


----------------

(Sent from my tablet - please blame any weird errors on autocorrect)

**Comment by asmartin** [comment]
Sanoid version is 1.4.7. That is my whole config - the way I'm making daily snapshots happen is by running the sanoid cron only on the 6th hour of the day (see crontab output in first post)

**Comment by jimsalterjrs** [comment]
Ahhhh, interesting.  OK, I'll have to take a closer look at that.

**Comment by foafron** [comment]
Just curious if is this being caused by the misnaming of the template?  What happens if you change your template name from

`[my_template]`
to
`[template_my_template]`

**Comment by asmartin** [comment]
That name for the template was just my example; the actual template name was `[template_thing]` and then I referenced it by calling `use_template = thing`. In any case, I just checked this server again and the duplicate hourly snapshots are no longer being created. I'm not sure what changed, but since I can no longer reproduce it, I'll consider this resolved.
