### ISSUE TITLE
Feature Request: Add other transports besides ssh

### ISSUE THREAD

**Issue by devZer0** [jimsalterjrs/sanoid#520]
could you consider adding other transports to syncoid?

see https://zrepl.github.io/configuration/transports.html as an example

I need to switch to different tool because with syncoid & ssh transport, data volume has grown too big to get handled properly

**Comment by phreaker0** [comment]
I guess you mean like a direct TCP connection without ssh overhead, if so I made a PR for that #513

**Comment by devZer0** [comment]
duplicate of https://github.com/jimsalterjrs/sanoid/issues/371
