### ISSUE TITLE
Running synoid as a regular user

### ISSUE THREAD

**Issue by mat813** [jimsalterjrs/sanoid#522]
Because of security concerns, I (well, the security people in my company) would like to be able to run syncoid as a regular user, locally and remotely.

All the zfs operations can be delegated with `zfs allow`, so this should not be a problem.

My question is, is there a list of the zfs operations that are run locally, and remotely, that I could use, or do I have to either go through the source code to list them, or do trial and error, adding allowed operations until it all works.

Also, being able to use a forced command script on the remote server to filter what is allowed to run would be great, so, is there a list of commands that syncoid runs on the remote server?

**Comment by click0** [comment]
>  is there a list of commands that syncoid runs on the remote server?

My file for sudoers:
```
# Syncoid commands
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs get *
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs snapshot *
#zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs send *
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs receive *
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs rollback *@syncoid_cdn*
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs rollback *tank/video*@*
# We only want to destroy snapshots
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs destroy *@syncoid_cdn*
zfs-replication ALL=(ALL) NOPASSWD:/sbin/zfs destroy *tank/video*@*
```
Where:
- `tank / video` - the name of the pool and partition that are being synchronized
- `cdn` - the beginning of the name `hostname` master server.

**Comment by mat813** [comment]
Thanks, with that, and a few try and errors, I got to:

```
zfs allow -u backup-user compression,create,destroy,mount,mountpoint,receive,rollback,send,snapshot
```

Next step is restricting the shell with a forced command.

**Comment by jimsalterjrs** [comment]
Note: syncoid already supports running as a non root user, but attempts to 
elevate with sudo if not running as root. You'll need to nerf that behavior 
if you want the whole thing running unprivileged from the system standpoint 
and relying on zfs allow rather than sudo.

Patches accepted if cleanly written, particularly if they include 
documentation. Ideally, with detection of working zfs delegation rather 
than simply yanking out the sudo functionality entirely.

**Comment by phreaker0** [comment]
@jimsalterjrs there is already an option to prevent privilege elevation:
`      --no-privilege-elevation  Bypass the root check, for use with ZFS permission delegation`

**Comment by jimsalterjrs** [comment]
Thank you @phreaker0 .

It's really weird—and humbling—seeing your own project get so much community investment that you can't even remember all of the great features other people have added in without needing reference or reminders sometimes.

If I don't already say it enough, I _greatly_ appreciate all of the community contributions and effort, very much including yours. <3

**Comment by phreaker0** [comment]
Running synoid as a regular user is possible already :-)

**Comment by Igortorrente** [comment]
> Thanks, with that, and a few try and errors, I got to:
> 
> ```
> zfs allow -u backup-user compression,create,destroy,mount,mountpoint,receive,rollback,send,snapshot
> ```

For people like me trying to make it work, in the Sanoid 2.0.3-4(And probably beyond) is necessary to allow 'bookmark' and 'hold' aside the other permissions.

`zfs allow -u backup-user compression,create,destroy,mount,mountpoint,receive,rollback,send,snapshot,bookmark,hold`

> 
> Next step is restricting the shell with a forced command.

And I had to add this lines to my sshd_config

```
Match User backup-user
        ForceCommand export PATH=$PATH:/usr/zfs-bin; bash -c "$SSH_ORIGINAL_COMMAND"
Match all
```
