### ISSUE TITLE
CRITCAL ERROR when syncing to rsync.net

### ISSUE THREAD

**Issue by tgunr** [jimsalterjrs/sanoid#524]
rsyncz.polymicro.net is a CNAME to my zfs account 3712.zfs.rsync.net.

gamma/tv was a non-existing dataset on the target.

`[pro]/Users/davec/Sources/GitHub/sanoid (local): syncoid -debug  gamma/tv root@rsyncz.polymicro.net:/data1/tv
DEBUG: SSHCMD: ssh
DEBUG: checking availability of lzop on source...
DEBUG: checking availability of lzop on target...
DEBUG: checking availability of lzop on local machine...
DEBUG: checking availability of mbuffer on source...
DEBUG: checking availability of mbuffer on target...
DEBUG: checking availability of pv on local machine...
DEBUG: checking availability of zfs resume feature on source...
DEBUG: checking availability of zfs resume feature on target...
WARN: ZFS resume feature not available on target machine - sync will continue without resume support.
DEBUG: syncing source gamma/tv to target /data1/tv.
DEBUG: getting current value of syncoid:sync on gamma/tv...
 sudo zfs get -H syncoid:sync 'gamma/tv'
DEBUG: checking to see if /data1/tv on ssh     -S /tmp/syncoid-root-root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net is already in zfs receive using ssh     -S /tmp/syncoid-root-root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "ssh     -S /tmp/syncoid-root-root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net  zfs get -H name ''"'"'/data1/tv'"'"'' 2>&1 |"...
DEBUG: getting list of snapshots on gamma/tv using  sudo zfs get -Hpd 1 -t snapshot guid,creation 'gamma/tv' |...
DEBUG: creating sync snapshot using " sudo zfs snapshot 'gamma/tv'@syncoid_pro.home_2020-03-18:06:50:31
"...
DEBUG: target /data1/tv does not exist.  Finding oldest available snapshot on source gamma/tv ...

DEBUG: getting estimated transfer size from source  using " sudo zfs send  -nP 'gamma/tv@syncoid_pve_2019-09-15:08:23:21' 2>&1 |"...

DEBUG: sendsize = 41584

INFO: Sending oldest full snapshot gamma/tv@syncoid_pve_2019-09-15:08:23:21 (~ 40 KB) to new target filesystem:

DEBUG: sudo zfs send  'gamma/tv'@'syncoid_pve_2019-09-15:08:23:21' | pv -s 41584 | lzop  | mbuffer  -q -s 128k -m 16M 2>/dev/null | ssh     -S /tmp/syncoid-root-root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net ' mbuffer  -q -s 128k -m 16M 2>/dev/null | lzop -dfc |  zfs receive   -F '"'"'/data1/tv'"'"''

DEBUG: checking to see if /data1/tv on ssh     -S /tmp/syncoid-root-root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net is already in zfs receive using ssh     -S /tmp/syncoid-root-root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net ps -Ao args= ...

45.1KiB 0:00:00 [1.21MiB/s] [========================================================================] 111%

Ambiguous output redirect.

CRITICAL ERROR: sudo zfs send  'gamma/tv'@'syncoid_pve_2019-09-15:08:23:21' | pv -s 41584 | lzop  | mbuffer  -q -s 128k -m 16M 2>/dev/null | ssh     -S /tmp/syncoid-root-
root@rsyncz.polymicro.net-1584539430 root@rsyncz.polymicro.net ' mbuffer  -q -s 128k -m 16M 2>/dev/null | lzop -dfc |  zfs receive   -F '"'"'/data1/tv'"'"'' failed: 256 at /Users/davec/bin/syncoid line 464.`

**Comment by phreaker0** [comment]
Because of the error message I guess you are using FreeBSD with an sh incompatible default shell. See: https://github.com/jimsalterjrs/sanoid/blob/master/FREEBSD.readme for a solution

**Comment by tgunr** [comment]
This was on MacOS 10.15.3

**Comment by phreaker0** [comment]
@tgunr can you check the default remote shell used?

**Comment by phreaker0** [comment]
@tgunr I'm talking about the remote target if it wasn't obvious. https://www.rsync.net/products/platform.html#zfs doesn't specify the OS used but I don't think it's mac :-)

**Comment by tgunr** [comment]
I did change the shebang locally to the brew installed perl /usr/local/bin/perl and checked the remote which is freebsd and it is also using /usr/local/bin/perl according to `which perl` on both machines.

`sshrsz unman -a
FreeBSD 3712.zfs.rsync.net 12.0-STABLE FreeBSD 12.0-STABLE r351060 GENERIC  amd64`

**Comment by tgunr** [comment]
Also, using /bin/bash on both.

**Comment by phreaker0** [comment]
@tgunr are you sure about the shell? The remote execute shell can be different from the login shell.

try:
ssh root@rsyncz.polymicro.net env | grep SHELL

**Comment by tgunr** [comment]
bingo, it is using csh

**Comment by phreaker0** [comment]
try changing it with
chsh -s /bin/sh
or
chsh -s /bin/bash

**Comment by tgunr** [comment]
I tried changing to sh as there is no bash on that remote machine. I verified my login shell is now sh but still same critical error.

**Comment by tgunr** [comment]
My bad, finally noticed the leading slash on the target dataset, removed it and off we go.

Thanks heaps!
