### ISSUE TITLE
Syncoid should create a hold before send

### ISSUE THREAD

**Issue by zhimsel** [jimsalterjrs/sanoid#525]
When using the `--no-sync-snap` option, if a syncoid send fails for whatever reason, it can't be resumed if the source snapshot no longer exists. This is a non-zero possibility when using Sanoid, since the source snapshot will likely have been pruned.

If a snapshot hold is created first, the snapshot won't be pruned and the send can be resumed.

Just ran into this halfway into a 36TB send when a connection issue occurred.

**Comment by phreaker0** [comment]
Should be fixed by #510
