### ISSUE TITLE
Sanoid generating multiple monthly/daily snapshots of the same zpools

### ISSUE THREAD

**Issue by doug-w** [jimsalterjrs/sanoid#526]
sanoid --version
/usr/sbin/sanoid version 2.0.2
(Getopt::Long::GetOptions version 2.50; Perl version 5.28.1)

I'm seeing the case where I'm getting multiple of the same types of snapshots.  I've looked and confirmed it's not related to #328.  
Every few days I clean them up but new ones keep getting created.

zfs list -t all -r rpool | grep month
rpool@autosnap_2020-04-01_00:00:13_monthly                0B      -       96K  -
rpool@autosnap_2020-04-10_09:04:41_monthly                0B      -       96K  -
rpool@autosnap_2020-04-10_15:30:10_monthly                0B      -       96K  -
rpool@autosnap_2020-04-12_19:33:27_monthly                0B      -       96K  -
rpool@autosnap_2020-04-12_21:30:10_monthly                0B      -       96K  -
rpool@autosnap_2020-04-13_00:45:10_monthly                0B      -       96K  -
rpool@autosnap_2020-04-13_02:00:10_monthly                0B      -       96K  -
rpool@autosnap_2020-04-13_04:45:11_monthly                0B      -       96K  -
rpool@autosnap_2020-04-13_09:30:09_monthly                0B      -       96K  -
rpool@autosnap_2020-04-13_16:45:06_monthly                0B      -       96K  -

zfs list -t all -r rpool | grep dail
rpool@autosnap_2020-04-06_15:30:10_daily                  0B      -       96K  -
rpool@autosnap_2020-04-07_00:05:20_daily                  0B      -       96K  -
rpool@autosnap_2020-04-08_00:00:12_daily                  0B      -       96K  -
rpool@autosnap_2020-04-09_00:00:10_daily                  0B      -       96K  -
rpool@autosnap_2020-04-10_00:18:54_daily                  0B      -       96K  -
rpool@autosnap_2020-04-10_09:04:41_daily                  0B      -       96K  -
rpool@autosnap_2020-04-10_15:30:10_daily                  0B      -       96K  -
rpool@autosnap_2020-04-11_00:42:29_daily                  0B      -       96K  -
rpool@autosnap_2020-04-12_00:00:11_daily                  0B      -       96K  -
rpool@autosnap_2020-04-12_19:33:27_daily                  0B      -       96K  -
rpool@autosnap_2020-04-12_21:30:10_daily                  0B      -       96K  -
rpool@autosnap_2020-04-13_00:02:13_daily                  0B      -       96K  -
rpool@autosnap_2020-04-13_00:45:10_daily                  0B      -       96K  -
rpool@autosnap_2020-04-13_02:00:10_daily                  0B      -       96K  -
rpool@autosnap_2020-04-13_04:45:11_daily                  0B      -       96K  -
rpool@autosnap_2020-04-13_09:30:09_daily                  0B      -       96K  -
rpool@autosnap_2020-04-13_16:45:06_daily                  0B      -       96K  -

I last cleaned them up on 4-10, and this is happening for other zpools but just showing this one as it's the simpliest case.

sanoid.conf:
[rpool]
        use_template = prod
        recursive = yes

[template_prod]
        frequently = 0
        hourly = 36
        daily = 30
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes

I'm running on Proxmox which is a Debian system with systemd, there's no cron jobs related to sanoid, and I'm using the sanoid.timer and sanoid.service entries from https://github.com/jimsalterjrs/sanoid/blob/master/INSTALL.md to configure it.

**Comment by phreaker0** [comment]
@doug-w Can you run sanoid two times with the "--debug" option and check if for those two runs to many snapshots are created

**Comment by doug-w** [comment]
I had turned back on the systemd scheduler after not having any issues from doing multiple runs with --debug, and while I can't reproducer it with running it manually I do see 2 days of 2x dailies:

rpool@autosnap_2020-04-22_00:00:06_daily                  0B      -       96K  -
rpool@autosnap_2020-04-22_10:55:41_daily                  0B      -       96K  -
rpool@autosnap_2020-04-23_00:00:06_daily                  0B      -       96K  -
rpool@autosnap_2020-04-23_11:06:44_daily                  0B      -       96K  -

**Comment by phreaker0** [comment]
@doug-w can you let all systemd activated sanoid runs use the "--debug" flag an log each run. After there are multiple dailys again, please provide the logs around those times.

**Comment by doug-w** [comment]
It's been over two weeks and I haven't been able to reproduce this.  And I can't identify anything in my local settings that would have changed but I'm fine with closing it.  I'll watch the snapshot creation and try to comment or open a new bug if I get more information.

Thanks!
