### ISSUE TITLE
zfs resume check fails for Debian target

### ISSUE THREAD

**Issue by isundaylee** [jimsalterjrs/sanoid#527]
Hi, first thanks for making sanoid, it's been really useful for me!

I noticed that `syncoid` is complaining about resume feature not available on the target system, whereas I confirmed manually that it is supported. I did some digging, and it's because of this line:

```perl
my $resumechkcmd = "$zpoolcmd get -o value -H feature\@extensible_dataset";
```

Here the check command runs as non-sudo, and calls `zpool` without path. On Debian, `zpool` is not in the `PATH` of non-root users -- hence the failure.

**Comment by phreaker0** [comment]
thanks for reporting, i pushed a PR with the fix

**Comment by isundaylee** [comment]
awesome, thanks for the quick fix! :)

**Comment by asche77** [comment]
See also my #554 - is the grep regex perhaps not working under debian too? (Not sudo related)
