### ISSUE TITLE
Automatic --no-resume when "incremental source ... no longer exists" 

### ISSUE THREAD

**Issue by realcarbonneau** [jimsalterjrs/sanoid#528]
Failed sync with resume, incremental source deleted, subsequent sync fail and does not correct itself.  As mentioned in other issues, this can be common with frequent snapshots and --no-sync-snap option.  As a side note, option --sendoption=w is also used and the dataset is encrypted. 

Strangely, this should have been fixed by #304, but the error below occurred (even after multiple retries) on version 2.0.3 which should include the fix.  
```
syncoid -v
/usr/sbin/syncoid version 2.0.3
(Getopt::Long::GetOptions version 2.50; Perl version 5.28.1)
```
Error:
```
cannot resume send: incremental source ... no longer exists
cannot receive: failed to read from stream
CRITICAL ERROR: ...
```

Forcing a sync with --no-sync-snap --no-resume correctly synced, but syncoid should be able to do this automatically.

**Comment by phreaker0** [comment]
@realcarbonneau I already made an PR for this #510

**Comment by phreaker0** [comment]
fix was merged
