### ISSUE TITLE
--no-stream not recognised in v2.0.3

### ISSUE THREAD

**Issue by Filmtangent** [jimsalterjrs/sanoid#539]
Hi there, 

I seem to be having an issue where my install of 2.0.3 doesnt seem to be accepting the arguments --no-stream and --no-sync-snap

This is a first time sync to a new pool on an Ubuntu 18.04 system. I havent used these commands before and am hoping that I am just passing them wrong:

``` 
/opt/sanoid/syncoid --no-stream --compress=lz4 --target-bwlimit=40m --no-sync-snap root@<server>:<share>/VFX Production/vfx 
ERROR: don't understand argument --no-stream.
```

Help is much appreciated

**Comment by phreaker0** [comment]
run and post the output of both here:
```
/opt/sanoid/syncoid
/opt/sanoid/syncoid --version
```

**Comment by Filmtangent** [comment]
output of `/opt/sanoid/syncoid`
```
Use of uninitialized value $fs in regexp compilation at /opt/sanoid/syncoid line 508.

Use of uninitialized value $targetfs in concatenation (.) or string at /opt/sanoid/syncoid line 125.

Cannot sync now:  is already target of a zfs receive process.
```

Output of `opt/sanoid/syncoid --version`
```Syncoid version: 1.4.7```

**Comment by phreaker0** [comment]
@Filmtangent Look at the last line, you have version 1.4.7 installed (which probably didn't have the --no-stream option), not the 2.0.3 version as you said. Install the latest version and it should work as expected.
