### ISSUE TITLE
Syncoid should give usage guide when invoked with no arguments

### ISSUE THREAD

**Issue by rriley** [jimsalterjrs/sanoid#54]
In the latest (b4bed0374) version running on Ubuntu 16.04 server, running Syncoid gives me the following:

```
Use of uninitialized value $fs in pattern match (m//) at ./syncoid line 752.
Use of uninitialized value $fs in pattern match (m//) at ./syncoid line 752.
Use of uninitialized value $fs in regexp compilation at ./syncoid line 508.
Use of uninitialized value $fs in regexp compilation at ./syncoid line 508.
...
```

Some quick testing with git bisect indicates that the first bad commit is 287663765582f36551ba352af9c029b1933ff032

Reverting that commit on HEAD fixes the error for me.

**Comment by jimsalterjrs** [comment]
I don't see how you could be getting that error - iszfsbusy() (where line 508 is) is only called 5 times in the code, and $fs is explictly specified in its callout each time.

Similar problem with line 752, in getssh() - it's only called twice, and $fs is explicitly passed in both calls there as well.

Actually, hold the phone -  (b4bed0374) isn't the latest version. (7eb772f) is.  Can you please update to (7eb772f) and see if that resolves your issue?

**Comment by jimsalterjrs** [comment]
> Some quick testing with git bisect indicates that the first bad commit is 2876637

That's the commit where I turned warnings on in the first place, not a commit where a bug was introduced. :)

**Comment by jimsalterjrs** [comment]
If you're absolutely certain you're on the latest version of syncoid, you might try an if (!defined $rawsourcefs) { $rawsourcefs = ''; } towards the top of the file (and another for $rawtargetfs) to see if that resolves the issue - I can't really test that on my end because I'm not getting the warnings you're seeing.

It might help to see the exact command line you're using with syncoid when you get the warning.

**Comment by rriley** [comment]
I'm running it with no arguments at all, and I'm expecting to see the usage instructions.  Instead, I get...

```
Use of uninitialized value $fs in regexp compilation at ./syncoid line 508.
...
Use of uninitialized value $fs in concatenation (.) or string at ./syncoid line 734.
Use of uninitialized value $fs in regexp compilation at ./syncoid line 740.
Use of uninitialized value $fs in concatenation (.) or string at ./syncoid line 785.
Use of uninitialized value $fs in regexp compilation at ./syncoid line 793.
...
Use of uninitialized value $fs in concatenation (.) or string at ./syncoid line 785.
...
Use of uninitialized value $fs in regexp compilation at ./syncoid line 793.
Use of uninitialized value $fs in concatenation (.) or string at ./syncoid line 723.
cannot open '': invalid dataset name
usage:
	snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR:  /usr/bin/sudo /sbin/zfs snapshot @syncoid_router_2016-10-14:18:14:13
 failed: 512 at ./syncoid line 724.
```

If I were a betting man, I would assume I'm getting all the warnings and weird messages because I don't have arguments.  Maybe syncoid just shouldn't be run without arguments?

Results of more testing based on your recommendations:
- I just cloned a fresh copy, no change.  
- I added the code you recommended for $rawsourcefs and $rawtargetfs, no change.
- It looks like the warnings get printed because of the addition of `use warnings;` in 287663765582f:

**Comment by jimsalterjrs** [comment]
... yeah you're not supposed to run it without arguments.

There's certainly a great argument to be made that running with no arguments should result in a brief usage guide, but it would have been _really_ nice if you'd specified that that's what you were doing in the first place...

**Comment by fajarnugraha** [comment]
Are you accepting PR for this? This simple change should help new users:

```
# diff -Naru a b
diff -Naru a/syncoid b/syncoid
--- a/syncoid   2016-12-28 22:04:53.534349873 +0700
+++ b/syncoid   2016-12-28 22:04:57.470383906 +0700
@@ -19,6 +19,11 @@
        exit 0;
 }

+if (!(defined $args{'source'} && defined $args{'target'})) {
+       print 'usage: syncoid [src_user@src_host:]src_pool/src_fs [dst_user@dst_host:]dst_pool/dst_fs'."\n";
+       exit 127;
+}
+
 my $rawsourcefs = $args{'source'};
 my $rawtargetfs = $args{'target'};
 my $debug = $args{'debug'};
 ```

```
# ./b/syncoid
usage: syncoid [src_user@src_host:]src_pool/src_fs [dst_user@dst_host:]dst_pool/dst_fs
```

Of course the ideal solution would be to add `--usage`, and add all relevant args to its output as well.

**Comment by jimsalterjrs** [comment]
Done. Closing for now (feel free to open a new enhancement request asking for --help, as it is a good idea.)
