### ISSUE TITLE
Question/feature request: provide pv with send size for bookmark sends

### ISSUE THREAD

**Issue by zhimsel** [jimsalterjrs/sanoid#540]
When using a bookmark as the source for a send (e.g. with `--no-sync-snap` and `--create-bookmark` set, syncoid does not provide `pv` with the total send size. This means the progress bar just shows speed and how much has been sent, not how much there is remaining to send.

Is this a limitation of ZFS (e.g. ZFS can't know the send size)? or is this something missing from syncoid?

**Comment by phreaker0** [comment]
This is a limitation in ZFS.

**Comment by zhimsel** [comment]
Ah, I figured it might be. Thanks!
