### ISSUE TITLE
warm up the cache? 

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#543]
Quick ask:  Is there a way to just warm up the cache besides a full blown sanoid --force-update?  

Details: 

I am not sure if it is a caching issue or not, but occasionally when i take a snapshot (no pruning) it takes a long time to complete.    This is on a lightly used system with very few snapshots, and plenty of disk space.  It is a brand new server.  

I have a snapshot script that goes through and does a filesystem freeze and suspends the vm, takes a snapshot, thaws fs, and resumes vm. Normally a snapshot only takes a second or so and having the machine frozen during that time is totally fine, clients doesn't notice any interruption. 

I put a timer in the script to try to track down where the delay happens.  After the VM suspend, the timer is still at 0, then it goes to 27 seconds after the snapshot.   This is a problem because the vm is paused for 27 seconds.  

As a temporary measure I am planning on putting a "sanoid --force-update" at the beginning of the script to make sure the cache is good.  

Here is a log:

Date:   2020-05-14_15-03-44
Configuration pc-pfs1 is listed
preparing to snapshot the folowing configurations:  pc-pfs1
pc-pfs1 is type KVM need to prepare virtual machine
pc-pfs1 is running, prepare freezing
Timer after filesystem freeze:  0
pc-pfs1 is frozen, prepare vm suspend
Timer after vm suspend:  0
pc-pfs1 file systems are frozen and VM is suspended, time to snapshot
sanoid --configdir=/etc/sanoid/conf.d/pc-pfs1 --take-snapshots  --verbose
INFO: cache expired - updating from zfs list.
INFO: taking snapshots...
taking snapshot tank/vm/pc-pfs1/data@autosnap_2020-05-14_15:04:10_weekly (zfs recursive)
taking snapshot tank/vm/pc-pfs1/data@autosnap_2020-05-14_15:04:10_daily (zfs recursive)
INFO: cache expired - updating from zfs list.
Timer after snapshots:  27
pc-pfs1 resumed
pc-pfs1 filesystem thawed

thanks,
Geoff

**Comment by jimsalterjrs** [comment]
Are you using before-snapshot hooks in sanoid for this, or are you
taking the snapshots with a completely separate script?

**Comment by gnordli** [comment]
I rolled my own script.   I am not a bash expert, but hacked it together. 

#!/bin/bash
##set -x
GROUP_DIR=/etc/sanoid/group
CONTACT=""
SENDER=""
VSH=/usr/bin/virsh
CONF_DIR=/etc/sanoid/conf.d
LOG=/var/log/sanoid/snapshot_`date +%Y-%m-%d_%H-%M-%S`.log
START=$(date +%s)
SANOID=/usr/sbin/sanoid
## define array to hold configurations that need to get snapshots
a_conf=()
echo "Date:  " `date +%Y-%m-%d_%H-%M-%S` >> $LOG

# Usage info
usage() {
cat <<EOT
usage: snapshot.sh [group] 
        eg. snapshot.sh vm
Groups are defined in the /etc/sanoid/group folder.  They are symbolic
links to configurations in the /etc/sanoid/conf.d folder
Groups allow different schedules for configurations.
EOT
}

if [ $# -ne 1 ]; then
  echo "1 arguments required, $# provided"
  usage
  mailx -r $SENDER -s "ERROR: Incorrect number of arguments provided" $CONTACT < $LOG
  exit 1
fi
GROUP=$1

### check to make sure the group is listed in the group directory
if (ls -1 ${GROUP_DIR} | grep -w $GROUP >/dev/null )
then
    echo "Configuration $GROUP is listed" >> $LOG
else
   echo "Configuration $GROUP is not defined" >> $LOG
   mailx -r $SENDER -s "ERROR: Configuration $GROUP is not defined" $CONTACT < $LOG
   exit 1
fi


## Update sanoid's cache
$SANOID --force-update --verbose >> $LOG

a_conf=(`ls -1 $GROUP_DIR/$GROUP`)
### LOOP through the configurations to snapshot

echo "preparing to snapshot the folowing configurations: " ${a_conf[*]} >> $LOG
for (( i = 0 ; i < ${#a_conf[@]} ; i++))
do
   ## What type of configuration is it:  kvm or filesystem
   case $(cat /etc/sanoid/conf.d/${a_conf[$i]}/type) in
   "kvm" ) 
      echo "${a_conf[$i]} is type KVM need to prepare virtual machine" >> $LOG
      if [[ `$VSH domstate ${a_conf[$i]}` == 'running' ]]
      then
         echo "Drop cache" >> $LOG
         $VSH send-key ${a_conf[$i]} KEY_LEFTALT KEY_SYSRQ KEY_S
         echo "${a_conf[$i]} is running, prepare freezing" >> $LOG
         if [[ `$VSH domfsfreeze ${a_conf[$i]} | grep -i -v error` ]]
         then 
           
            echo "Timer after filesystem freeze: " $(( $(date +%s) - $START )) >> $LOG
            echo "${a_conf[$i]} is frozen, prepare vm suspend" >> $LOG
            if [[ `$VSH suspend ${a_conf[$i]} | grep -i -v error` ]]
            then
               echo "Timer after vm suspend: " $(( $(date +%s) - $START )) >> $LOG
               echo "${a_conf[$i]} file systems are frozen and VM is suspended, time to snapshot" >> $LOG
               echo "sanoid --configdir=$CONF_DIR/${a_conf[$i]} --take-snapshots  --verbose" >> $LOG
               $SANOID --configdir=$CONF_DIR/${a_conf[$i]} --take-snapshots  --verbose >> $LOG
               echo "Timer after snapshots: " $(( $(date +%s) - $START )) >> $LOG
            else
               echo "error suspending vm" >> $LOG
               mailx -r $SENDER -s "ERROR:  ${a_conf[$i]} suspending vm" $CONTACT < $LOG
               exit 1
            fi    
         else
            echo "error freezing vm" >> $LOG
            mailx -r $SENDER -s "ERROR:  ${a_conf[$i]} freezing vm" $CONTACT < $LOG
            exit 1
         fi
         ### VM is currently suspended and filesystem frozen
         ### VM needs to be resumed
         if [[ `$VSH resume ${a_conf[$i]} | grep -i -v error` ]]
         then
            echo "${a_conf[$i]} resumed" >> $LOG
            ### VM is currently resumed
            ### VM filesystem needs to get thawed
            if [[ `$VSH domfsthaw ${a_conf[$i]} | grep -i -v error` ]]
            then
               echo "${a_conf[$i]} filesystem thawed" >> $LOG
            else
               echo "error thawing filesystem"  >> $LOG
               mailx -r $SENDER -s "ERROR:  ${a_conf[$i]} thawing filesystem" $CONTACT < $LOG
               exit 1
            fi
         else
            echo "error resuming vm"  >> $LOG
            mailx -r $SENDER -s "ERROR:  ${a_conf[$i]} resuming vm" $CONTACT < $LOG
            exit 1
         fi
      else
         echo "${a_conf[$i]} is not running just taking a snapshot" >> $LOG
         $SANOID --configdir=$CONF_DIR/${a_conf[$i]} --take-snapshots --verbose --run-dir=/tmp >> $LOG
      fi
      ;;
   "filesystem" ) 
            echo a_conf[$i] " is type filesystem take a snapshot" >> $LOG
            $SANOID --configdir=$CONF_DIR/${a_conf[$i]} --take-snapshots --verbose --run-dir=/tmp >> $LOG
            ;;
   esac
done 

END=$(date +%s)
DIFF=$(( $END - $START ))

mailx -r $SENDER -s "Snapshot ${a_conf[*]} successful in $DIFF seconds"  $CONTACT < $LOG

**Comment by jimsalterjrs** [comment]
You need to head to
https://github.com/jimsalterjrs/sanoid/blob/master/sanoid.defaults.conf 
and look at available options: specifically, pre_snapshot_script =
and post_snapshot_script =. 

If you perform your logic from _within _Sanoid by using the hooks
provided (which will run an external script before taking a snapshot,
and after taking a snapshot), you won't end up _competing_ with Sanoid
occasionally the way you seem to be now. 

Note: you're just looking at defaults.conf because it shows you all
possible directives. Don't try to _modify_ defaults.conf!

**Comment by gnordli** [comment]
You are right, I guess I will have to look at changing up the code again. 
thanks!!
Geoff
