### ISSUE TITLE
Bookmarks piling up on syncoid source

### ISSUE THREAD

**Issue by yanky83** [jimsalterjrs/sanoid#544]
Hi,

we run incremental backups with syncoid and bookmarks.

I noticed the bookmarks seem to never get deleted on the source and keep piling up.

Is there an option to cull them at some point? Have I missed something? Or even worse, am I missing sth fundamental?

Thanks in advance!

**Comment by phreaker0** [comment]
There isn't an option to clean them up, you need to do it yourself. Bookmarks shouldn't use too much data though.
