### ISSUE TITLE
KVM Migration with Sanoid

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#545]
Hi.  
Not really a syncoid issue -- other than the management of the configuration files and making sure the correct server is the master data replicator.  

I work with small businesses to build out a backup and disaster recovery systems.  I just migrated my toolset from illumos+vbox+zfs+homemade_replication_scripts to linux+kvm+zfs+sanoid.  It works pretty well, but there is a lot of manual work to make it happen.   I am hoping to get a bit more automation.  Nothing fancy like Proxmox.   I am actually thinking something like ansible or just bash scripts.  

Before i go down the path, does anyone have any suggestions?  I can share some of my design thoughts.  

thanks,
Geoff

**Comment by tonymmm1** [comment]
You could probably just make a script to copy over libvirt xml and then just use virsh to import files and then replicate over or use shared zfs storage using syncoid.

**Comment by gnordli** [comment]
Hi @tonymmm1.

I am using qemu raw files and structure the zfs datasets like:
/tank/vm/vmname/vmname-root
/tank/vm/vmname/vmname-data
etc....

I dump the xml into the /tank/vm/vmname folder.

I do a recursive snapshot of tank/vm/vmname, and replicate that out. 

The host that wants to run the VM can import the xml.
