### ISSUE TITLE
syncoid with encrypted dataset

### ISSUE THREAD

**Issue by versus167** [jimsalterjrs/sanoid#548]
Hello,

I'm not sure if this is a syncoid problem or a zfs problem.

I send an encrypted record with Syncoid to a new destination -> Syncoid creates the new record without encryption, but still the snapshots are transferred and can be read without encryption!

I think the default behavior should be to encrypt the destionation dataset as well

Steps to reproduce this:

`root@vs-2018:/# time syncoid zfshome/testenc vs3/bk/target
INFO: Sending oldest full snapshot zfshome/testenc@zfsnappy_2020-03-25T15:24:01.966604 (~ 14.5 MB) to new target filesystem:
14,4MiB 0:00:01 [10,0MiB/s] [=================================================================================================> ] 99%            
INFO: Updating new target filesystem with incremental zfshome/testenc@zfsnappy_2020-03-25T15:24:01.966604 ... syncoid_vs-2018_2020-05-19:14:05:20 (~ 1.1 GB):
1,06GiB 0:00:28 [38,2MiB/s] [=================================================================================================>] 100%            

real	0m46,198s
user	0m0,220s
sys	0m2,798s
root@vs-2018:/# syncoid --version
/usr/sbin/syncoid version 2.0.3
(Getopt::Long::GetOptions version 2.50; Perl version 5.30.0)
root@vs-2018:/# zpool version
zfs-0.8.3-1ubuntu12
zfs-kmod-0.8.3-1ubuntu12
root@vs-2018:/# zfs list -o space,quota,lused,compressratio,mountpoint,rdonly,mounted,encryption zfshome/testenc
NAME             AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD  QUOTA  LUSED  RATIO  MOUNTPOINT    RDONLY  MOUNTED   ENCRYPTION
zfshome/testenc  63,6M   960M     2,67M    958M             0B         0B     1G  1,07G  1.15x  /mnt/testenc     off       no  aes-256-ccm
root@vs-2018:/# zfs list -o space,quota,lused,compressratio,mountpoint,rdonly,mounted,encryption vs3/bk/target
NAME           AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD  QUOTA  LUSED  RATIO  MOUNTPOINT  RDONLY  MOUNTED   ENCRYPTION
vs3/bk/target   409G   971M     1,80M    970M             0B         0B   none  1,08G  1.14x  none            on       no          off

root@vs-2018:/# zfs get encryption,keylocation,keyformat vs3/bk/target
NAME           PROPERTY     VALUE        SOURCE
vs3/bk/target  encryption   off          default
vs3/bk/target  keylocation  none         default
vs3/bk/target  keyformat    none         default

`

**Comment by secabeen** [comment]
That is the default behavior of zfs.  If you want to send encrypted streams, you must pass --sendoptions="w" to syncoid to tell zfs to send a raw stream.

**Comment by versus167** [comment]
This is kind of unexpected for me, but okay. Thanks for the information.
