### ISSUE TITLE
Specify config section for a complete pool as source

### ISSUE THREAD

**Issue by perburn** [jimsalterjrs/sanoid#55]
I'm trying to do a recursive backup of a whole pool, hence specifying only the poolname as source.

It works great when calling syncoid manually with -r, but it will not pick up options from the config file where a specified a section called

[mypoolname]
...options...

How to specify a config section that gets picked up if the source is the whole pool (no /, no dataset)?

**Comment by jimsalterjrs** [comment]
Syncoid does not have a config file. The config file affects sanoid only.


----------------

(Sent from my tablet - please blame any weird errors on autocorrect)

**Comment by perburn** [comment]
Sorry, had some misunderstandings in the Readme.
Still not sure how to reach me goal setup, but will open another question for that. Thanks for reply!
