### ISSUE TITLE
Syncoid: No way to replicate a whole pool

### ISSUE THREAD

**Issue by JamesSwift** [jimsalterjrs/sanoid#550]
If I try to replicate a whole encrypted pool, syncoid refuses because the new "dataset" already exists. But there is no way to create a "root dsataset", you need to create the pool first. Example command:

syncoid -r old new

**Comment by jimsalterjrs** [comment]
Not quite: you can replicate the whole pool just fine, you just can't do it onto a root dataset. For example, `syncoid -r old new/old` will work just fine.

This isn't a syncoid thing, this is a ZFS replication itself thing. It's one reason most experienced ZFS admins recommend that you not store data you care about directly in the pool root.

**Comment by JamesSwift** [comment]
Thanks for the quick reply! I also see people recommend not encrypting the root dataset, so perhaps I will sync it across as a sub dataset of an un-encrypted pool..

If I use the following command, where `old` is already encrypted and `new` is un-encrypted, will `new/old` be encrypted with the same key as `old`?

`syncoid -r old new/old`

P.S. I'm going to miss you on tech snap

**Comment by secabeen** [comment]
Yeah, and if you have a pool with a unmounted and empty root dataset, the "--recursive --skip-parent" arguments allow you to send the whole thing to a new pool easily.

**Comment by JamesSwift** [comment]
Sorry, I'm not quick sure what you mean by that.

**Comment by secabeen** [comment]
Say you wanted to do what you had originally.  `syncoid --recursive old new`  doesn't work because the root pool in new already exists.  Jim posted the suggestion `syncoid --recursive old new/old` which works even with an in-use root pool, but puts the datasets one level down in the tree.  If the root dataset in old is empty, and unused, you can then do `syncoid --recursive --skip-parent old new` and it will work, copying everything from the old pool to the new, in the same exact spots, except the (empty) root pool, which is skipped.

**Comment by jimsalterjrs** [comment]
Yup. Let's say you start out with:

````
old
  |--one
  |     |---two
  |
  |--three

new
````

If you `syncoid -r --skip-parent old new`, you end up with:

````
old
  |--one
  |     |---two
  |
  |--three

new
  |--one
  |     |---two
  |
  |--three
````

**Comment by secabeen** [comment]
Now to answer your encryption question.  If you want to transfer a dataset or pool of datasets with encryption, you almost always use the `--raw` argument.  Without that, the data will be decrypted, sent over, then re-encrypted on the far side.  (You can set an encryption key on the far end with `--recvoptions`, but that's probably not what you want).  When you send encrypted datasets this way, they arrive on the far side without any encryption key at all, unless you set one with `--recvoptions`.  Once they're on the far side, you can set the encryption key on each dataset, and even restore the inheritance with `zfs change-key -i`.

**Comment by JamesSwift** [comment]
Ah ha. That's really good. Thanks so much.

It's a bit of shame that zfs doesn't just support a straight root replication.

**Comment by jimsalterjrs** [comment]
@JamesSwift also be aware that right now I think you need to use `--sendoptions -w` to get an encrypted send. We don't have an argument directly in syncoid itself for raw send at the moment, so if you only do `syncoid old new/old` you'll end up with an **un**encrypted dataset on the remote side.

PS: I'm going to miss TechSNAP too... but you can still find me at https://2.5admins.com/ with Joe Ressington and Allan Jude. :)

**Comment by JamesSwift** [comment]
> Now to answer your encryption question. If you want to transfer a dataset or pool of datasets with encryption, you almost always use the `--raw` argument. Without that, the data will be decrypted, sent over, then re-encrypted on the far side. (You can set an encryption key on the far end with `--recvoptions`, but the decrypt/reencrypte probably not what you want). When you send encrypted datasets this way, they arrive on the far side without any encryption key at all. Once they're on the far side, you can set the encryption key on each dataset, and even restore the inheritance with `zfs change-key -i`.

Oh wait, so are you saying that the command I mentioned earlier `syncoid -r old new/old` will decrypt the data when it is stored inthe `new` pool?

**Comment by JamesSwift** [comment]
> @JamesSwift also be aware that right now I think you need to use `--sendoptions -w` to get an encrypted send. We don't have an argument directly in syncoid itself for raw send at the moment, so if you only do `syncoid old new/old` you'll end up with an **un**encrypted dataset on the remote side.

Ah. So, just to be clear, I should use:

`syncoid -sendoptions -w -r old new/old`

Is that right?

**Comment by jimsalterjrs** [comment]
Well, it would be, if I hadn't bobbled the syntax myself (I have not actually used the --sendoptions flag in anger personally yet).

Looks like it should be:

````
syncoid -r --sendoptions="w" old new/old
````

**Comment by JamesSwift** [comment]
Thanks for all your help. Out of interest, the `--sendoptions` flag is not mentioned in the wiki. What exactly is it doing here?

**Comment by secabeen** [comment]
Yep, you have it right.  And the reason for this is that there is zero communication back from the recipient back to the sender.  There is no way for the receiver to indicate to the sender what options or features it supports, so for maximum compatibility, zfs by default sends streams that use as few features as possible unless you pass the necessary arguments to require specific features.

(It might make sense to put a feature request into the ZoL team to add a per-dataset/zvol flag that tags that dataset to only be sent raw/encrypted.)

**Comment by jimsalterjrs** [comment]
passing along options to `zfs send` directly. There's a matching `--recvoptions` argument that does the same for `zfs receive` on the other side.

I don't think I knew there **was** a wiki, lol. You can see all of the available arguments by just typing `syncoid` with no arguments; you can do the same for `sanoid` using `sanoid --help`. You can't really add an argument **without** documenting it that way due to the design of the argument handler!

**Comment by JamesSwift** [comment]
> I don't think I knew there **was** a wiki, lol.

Yup, https://github.com/jimsalterjrs/sanoid/wiki/Syncoid

Thanks again for being so helpful. I find that zfs send/recv is something of a black box where encryption is concerned. There's very little helpful real world examples.
