### ISSUE TITLE
two snapshots

### ISSUE THREAD

**Issue by felixn-dk** [jimsalterjrs/sanoid#553]
Hi

I have a crontab job running syncoid everyda 18:00 -> 

        hourly = 0
        daily = 7
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes
        daily_hour = 18;
        daily_min = 00;

But when I list snapshots it take two snapshots with a minute apart any clues?

saspool/shares/dump@autosnap_2020-05-30_18:00:01_daily       0B      -     1.24T  -
saspool/shares/dump@autosnap_2020-05-30_18:00:00_daily       0B      -     1.24T  -
saspool/shares/dump@autosnap_2020-05-31_18:00:01_daily       0B      -     1.24T  -
saspool/shares/dump@autosnap_2020-05-31_18:15:00_daily       0B      -     1.24T  -
saspool/shares/dump@autosnap_2020-06-01_00:00:00_monthly     0B      -     1.24T  -
saspool/shares/dump@autosnap_2020-06-01_18:00:01_daily       0B      -     1.24T  -
saspool/shares/dump@autosnap_2020-06-01_18:00:00_daily       0B      -     1.24T  -

Thanks
Felix

**Comment by phreaker0** [comment]
@felixn-dk I guess you mean sanoid not syncoid, can you show your crontab entries? I guess you are running two sanoid instances at the same time.

**Comment by felixn-dk** [comment]
Yes sorry sanoid :)

cron:

0 18 * * * /usr/sbin/sanoid --cron


conf:

[ssdpool]
        use_template = production
	recursive = yes
	process_children_only = yes

[saspool]
        use_template = production
        recursive = yes
        process_children_only = yes

[rpool/ROOT/pve-1]
        use_template = production
        recursive = no

[p4pool/nobackup/vm-122-disk-0]
        use_template = production
        recursive = no

[p4pool/nobackup/vm-122-disk-1]
        use_template = production
        recursive = no

[p4pool/subvol-114-disk-0]
        use_template = production
        recursive = no
#	pre_snapshot_script = /usr/bin/ssh -t 192.168.183.9 /opt/perforce/sbin/helix-p4d-maintenance.sh --all

[p4pool/subvol-114-disk-1]
        use_template = production
        recursive = no

[p4pool/subvol-114-disk-2]
        use_template = production
        recursive = no

[p4pool/subvol-114-disk-3]
        use_template = production
        recursive = no

[template_production]
        hourly = 0
        daily = 7
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes
        daily_hour = 18;
        daily_min = 00;

**Comment by phreaker0** [comment]
can you check your cron logs with something like:
`cat /var/log/syslog | grep CRON`

**Comment by felixn-dk** [comment]
Yes of course, it only runs sanoid ones it looks like

Jun  1 10:17:01 mother CRON[23652]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 11:17:01 mother CRON[6172]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 12:17:01 mother CRON[26215]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 13:17:01 mother CRON[6640]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 14:17:01 mother CRON[13938]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 15:17:01 mother CRON[8207]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 16:17:01 mother CRON[13293]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 17:17:01 mother CRON[7667]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 18:00:01 mother CRON[11174]: (root) CMD (/usr/sbin/sanoid --cron)
Jun  1 18:17:01 mother CRON[26872]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 18:30:01 mother CRON[19917]: (root) CMD (/root/replicate.sh >> /var/log/replicate.log)
Jun  1 19:17:01 mother CRON[23106]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 20:17:01 mother CRON[20459]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 21:17:01 mother CRON[7263]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 22:17:01 mother CRON[23363]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun  1 22:30:01 mother CRON[18803]: (root) CMD (#vzdump 104 105 106 108 110 111 124 122 --mode snapshot --compress lzo --quiet 1 --storage QNAP --mailto felix@playdeadgames.com --mailnotification always)
Jun  1 23:17:01 mother CRON[11041]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by phreaker0** [comment]
just to verifiy that there is no systemd timer which is executing sanoid at the same time:
`systemctl list-timers`

Can you add "--debug" to you cron line, and if scheduled at 18:00 check the output and post it here.

**Comment by felixn-dk** [comment]
there is actually a timer! - from old version / installation I guess

Tue 2020-06-02 11:15:00 CEST  9min left    Tue 2020-06-02 11:00:00 CEST  5min ago     sanoid.timer                 sanoid.service

I will stop it and disable time, thanks!

**Comment by phreaker0** [comment]
:-)

**Comment by felixn-dk** [comment]
and great response and help :)
