### ISSUE TITLE
ERROR: /var/run/sanoid_cacheupdate.lock is invalid.

### ISSUE THREAD

**Issue by darrenfreeman** [jimsalterjrs/sanoid#555]
I just suffered some corruption, and went to roll back to the last good snapshot. They should have been taken every five minutes, however the most recent was over two weeks old.

This is the recurring error that I see in `journalctl -b 1 | sanoid` :

```
Jun 06 19:00:01 host CRON[3623661]: (root) CMD ([ -f /etc/sanoid/sanoid.conf ] && if [ ! -d /run/systemd/system ]; then TZ=UTC /usr/sbin/sanoid --cron --quiet; fi)
Jun 06 19:00:01 host sanoid[3623662]: ERROR: /var/run/sanoid_cacheupdate.lock is invalid.
Jun 06 19:00:01 host systemd[1]: sanoid.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 06 19:00:01 host systemd[1]: sanoid.service: Failed with result 'exit-code'.
Jun 06 19:00:01 host sanoid[3623679]: ERROR: /var/run/sanoid_cacheupdate.lock is invalid.
Jun 06 19:00:01 host systemd[1]: sanoid-prune.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 06 19:00:01 host systemd[1]: sanoid-prune.service: Failed with result 'exit-code'.
```

I don't know why it is being run from `cron`, as the sanoid systemd service is also running. I am not sure if that's relevant.

Looking in `journalctl -b 0`, I see that it appears to be running fine. The snapshots are appearing again.

**Comment by phreaker0** [comment]
This should be fixed with #601
