### ISSUE TITLE
Question concerning sanoid running on syncoid target system

### ISSUE THREAD

**Issue by perburn** [jimsalterjrs/sanoid#56]
I want to implement the following setup:

- No sanoid/syncoid running on the source system, no periodic snapshotting running on the source.
- Syncoid is periodically pulling in remote datasets (recursively of the whole remote pool).
- Sanoid snapshots these datasets on the target system, creating a hierarchy of hourly, weekly.. etc

I got this working to the point where datasets are pulled in by syncoid and sanoid is creating the additional snapshots (based on the backup template from the default config).

However when running syncoid on the target again it destroys the snapshots created by sanoid. From reading the debug log I suppose it does this not explicitly  but by performing some rollback operations when pulling in the next round of datasets.

Is the desired setup even possible with syncoid/sanoid? Or is it required that snapshots are created on the source systems?

**Comment by jimsalterjrs** [comment]
Required. That's how zfs replication works.

--------
