### ISSUE TITLE
default config file missing after installation

### ISSUE THREAD

**Issue by hallamjeff** [jimsalterjrs/sanoid#561]
I installed sanoid from the Ubuntu 20.04 default repos. Subsequently following the project wiki, I could not find an `/etc/sanoid` directory or a default configuration file as currently documented.

I am unsure if this means the wiki is incorrect, or there was an error in the installation.

`sanoid --version`
/usr/sbin/sanoid version 2.0.3
(Getopt::Long::GetOptions version 2.50; Perl version 5.30.0)

**Comment by phreaker0** [comment]
This package is not from us but I checked and you are right, no /etc/sanoid is created after the package creation. You can open a bug with the package maintainer for Ubuntu here:
https://launchpad.net/ubuntu/+source/sanoid

**Comment by secabeen** [comment]
Ubuntu/Debian packages put their documentation in 
/usr/share/doc/<pkgname>.  If you look in there, you'll find a 
README.Debian file with the following contents:

 > To start, copy the example config file in 
/usr/share/doc/sanoid/examples/ to /etc/sanoid/sanoid.conf.

That's all you need to do.

--Ted

**Comment by hallamjeff** [comment]
I see, thank you. That doesn't necessarily align with my idea of obvious behaviour for the user but it doesn't sound like this is a bug. I will close my issue.

**Comment by secabeen** [comment]
Yeah, it's slightly weird behavior, but I don't know if I could write a generic config file to put in /etc/sanoid, and they don't want to put a sample file in /etc/sanoid for you, for whatever reason.
