### ISSUE TITLE
Syncoid crash: Broken pipe / mbuffer: fatal: unknown option "2"

### ISSUE THREAD

**Issue by StewLG** [jimsalterjrs/sanoid#563]
I'm trying to pull backup from a FreeNAS ZFS share to a little Ubuntu box running on a Raspberry pi. It's apparently no simple task to get Syncoid running working on FreeNAS without resorting to a Jail, so I'm hoping I don't need to in my use case. I see people doing exactly what I want to, for example:

https://www.reddit.com/user/kaihp/comments/fyhxdj/howto_setting_up_a_raspberry_pi_4_to_pull_backups/

Anyhow. I'm running 

`# syncoid purplebackup@scarfolk.doodle.local:ScarVol/ProxmoxBackups doodlebackup/vmbackup`

Scarfolk is the FreeNAS box. I'm trying to snapshot/backup the dataset ScarVol/ProxmoxBackups on Scarfolk to the local dataset on the Ubuntu Pi ("purplepi"), doodlebackup/vmbackup.

With debug, here's the error output:

`
root@ubuntu:~# syncoid purplebackup@scarfolk.doodle.local:ScarVol/ProxmoxBackups doodlebackup/vmbackup --debug
DEBUG: SSHCMD: ssh    
[Error Output.txt](https://github.com/jimsalterjrs/sanoid/files/4874197/Error.Output.txt)

DEBUG: checking availability of lzop on source...
DEBUG: checking availability of lzop on target...
DEBUG: checking availability of lzop on local machine...
WARN: lzop not available on source ssh:-S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local- sync will continue without compression.
DEBUG: checking availability of mbuffer on source...
DEBUG: checking availability of mbuffer on target...
DEBUG: checking availability of pv on local machine...
DEBUG: checking availability of zfs resume feature on source...
DEBUG: checking availability of zfs resume feature on target...
DEBUG: syncing source ScarVol/ProxmoxBackups to target doodlebackup/vmbackup.
DEBUG: getting current value of syncoid:sync on ScarVol/ProxmoxBackups...
ssh     -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local sudo zfs get -H syncoid:sync ''"'"'ScarVol/ProxmoxBackups'"'"''
DEBUG: checking to see if doodlebackup/vmbackup on  is already in zfs receive using  ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "  zfs get -H name 'doodlebackup/vmbackup' 2>&1 |"...
DEBUG: getting list of snapshots on ScarVol/ProxmoxBackups using ssh     -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local sudo zfs get -Hpd 1 -t snapshot guid,creation ''"'"'ScarVol/ProxmoxBackups'"'"'' |...
DEBUG: creating sync snapshot using "ssh     -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local sudo zfs snapshot ''"'"'ScarVol/ProxmoxBackups'"'"''@syncoid_ubuntu_2020-07-04:23:47:44
"...
DEBUG: target doodlebackup/vmbackup does not exist.  Finding oldest available snapshot on source ScarVol/ProxmoxBackups ...
DEBUG: getting estimated transfer size from source -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local using "ssh     -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local sudo zfs send  -nP ''"'"'ScarVol/ProxmoxBackups@manual-2020-07-03_17-22'"'"'' 2>&1 |"...
DEBUG: sendsize = 26178918504
INFO: Sending oldest full snapshot ScarVol/ProxmoxBackups@manual-2020-07-03_17-22 (~ 24.4 GB) to new target filesystem:
DEBUG: ssh     -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local 'sudo zfs send  '"'"'ScarVol/ProxmoxBackups'"'"'@'"'"'manual-2020-07-03_17-22'"'"' | mbuffer  -q -s 128k -m 16M 2>/dev/null' | mbuffer  -q -s 128k -m 16M 2>/dev/null | pv -s 26178918504 |  zfs receive  -s -F 'doodlebackup/vmbackup'
DEBUG: checking to see if doodlebackup/vmbackup on  is already in zfs receive using  ps -Ao args= ...
mbuffer: fatal: unknown option "2"
warning: cannot send 'ScarVol/ProxmoxBackups@manual-2020-07-03_17-22': Broken pipe
0.00 B 0:00:00 [0.00 B/s] [>                                                                                              ]  0%            
cannot receive: failed to read from stream
CRITICAL ERROR: ssh     -S /tmp/syncoid-purplebackup-purplebackup@scarfolk.doodle.local-1593906463 purplebackup@scarfolk.doodle.local 'sudo zfs send  '"'"'ScarVol/ProxmoxBackups'"'"'@'"'"'manual-2020-07-03_17-22'"'"' | mbuffer  -q -s 128k -m 16M 2>/dev/null' | mbuffer  -q -s 128k -m 16M 2>/dev/null | pv -s 26178918504 |  zfs receive  -s -F 'doodlebackup/vmbackup' failed: 256 at /usr/sbin/syncoid line 464.
root@ubuntu:~# 
`
Error output attached, I've struggled trying to get the formatting above right, failed.

My guess is something wrong with escaping since the "2>/dev/null" is the first appearance of the character 2 after the invocation of mbuffer, but I'm just guessing.

I'd appreciate any help anyone can give.

**Comment by phreaker0** [comment]
@StewLG you need to use a compatible shell, the default on FreeBSD doesn't work. See https://github.com/jimsalterjrs/sanoid/blob/master/FREEBSD.readme
