### ISSUE TITLE
Update Documentation about systemctl timers

### ISSUE THREAD

**Issue by FireDrunk** [jimsalterjrs/sanoid#566]
I've just installed Sanoid, and it works fine, but after a while I was getting errors regarding sanoid being unable to create snapshots.
Apparantly they already existed, so the command fails.

Turns out, that when installing the Debian package, a systemd timer is installed, so you no longer need to setup cron.
This was not very obvious from the start. So I had enabled Cron and the Systemd timer simultaniously.

That's not a good idea :)

Some extra explanation in the README regarding this issue, might be useful.

**Comment by jim-perkins** [comment]
I noticed Ubuntu sets up a cron but it doesnt run if systemd is installed
*/15 * * * * root [ -f /etc/sanoid/sanoid.conf ] && if [ ! -d /run/systemd/system ]; then TZ=UTC /usr/sbin/sanoid --cron --quiet; fi

had me confused for  bit .

**Comment by phreaker0** [comment]
Closing as this apparently is distribution specific.
