### ISSUE TITLE
syncoid makes script exit

### ISSUE THREAD

**Issue by devZer0** [jimsalterjrs/sanoid#569]
i'm trying to sync a list of datasets on commandline like this:

`[root@tmbackup02` timemachinepool]# ls -1|grep -v "tm1$" |egrep -v "backup|pve" | while read line;do echo $line ; syncoid --compress=lz4 timemachinepool/$line root@172.16.37.101:timemachinepool/$line;done
tm10
Sending incremental timemachinepool/tm10@syncoid_tmbackup02_2020-07-21:12:13:43 ... syncoid_tmbackup02_2020-07-21:12:14:43 (~ 4 KB):
1,52kiB 0:00:00 [6,87kiB/s] [===============================================================>                                                                                                           ] 38%
[root@tmbackup02 timemachinepool]#
`

for my surprise, that command exists after the first syncoid run, i.e. there seems something in syncoid which is causing that.

any clue, why?  i have never seen such behaviour, i'm unsing while read;do....;done  a lot for loops...

**Comment by phreaker0** [comment]
@devZer0 works for me:
```
POOL_IMAGE="/tmp/syncoid-test.zpool"
POOL_SIZE="1000M"
POOL_NAME="syncoid-test"

truncate -s "${POOL_SIZE}" "${POOL_IMAGE}"

zpool create -m none -f "${POOL_NAME}" "${POOL_IMAGE}"

function cleanUp {
  zpool export "${POOL_NAME}"
}

# export pool in any case
trap cleanUp EXIT

zfs create "${POOL_NAME}"/src
zfs create -o recordsize=16k "${POOL_NAME}"/src/16
zfs create -o recordsize=32k "${POOL_NAME}"/src/32
zfs create -o recordsize=128k "${POOL_NAME}"/src/128

syncoid --preserve-recordsize --debug --compress=none "${POOL_NAME}"/src "${POOL_NAME}"/dst
echo -e "16\n32\n128" | while read line; do echo $line ; syncoid "${POOL_NAME}"/src/$line "${POOL_NAME}"/dst/$line; done
```
