### ISSUE TITLE
Syncoid doesn't purge foreign syncoid snapshots

### ISSUE THREAD

**Issue by tpetersen572** [jimsalterjrs/sanoid#57]
Hello, 

We have a issue where old Syncoid snapshots are not being purged. Our environment is setup as the following:

Host1: VM Host
Host2: VM Host

Host1 --> Syncoid to Host2
Host2 --> Syncoid to Host1

This way we have a copy of the VM disk on each host for any fail over needs. 

Then we also have a system for saving the VM disks long term. 

Backup preforms  a Syncoid pull from Host1
Backup preforms  a Syncoid pull from Host2

Correct me if I am wrong but when Syncoid runs, it creates 2 snapshots. One on the source and one on the dest. 

On our backup box we see:
(ZFS Dataset)@syncoid_Host1_2016-10-17:11:00:56

And on the VMHost we see:
(ZFS Dataset)@syncoid_Backup_2016-10-17:11:00:56

But there are snapshots from several weeks ago. It does not appear that when Syncoid is running it purges the old snapshots it created. 

Are we missing something?

Thanks!

**Comment by jimsalterjrs** [comment]
Syncoid can only remove snapshots that were created by the host running the syncoid process. It has no way of knowing whether foreign syncoid snapshots are still needed in order to maintain incremental replication validity between the source host and the foreign host.

So when you run syncoid host1/source backup/target, host Backup cannot get rid of @syncoid_host2 snapshots, since it has no way of knowing whether they're still needed or not.

This is a pretty thorny problem; at first blush you might think you could just have any syncoid run automatically nuke any foreign syncoid snapshot older than the most recent one.  Problem is, it's entirely possible for a syncoid snapshot to be created at the beginning of a replication, have the replication be interrupted, but then the syncoid snapshot is still there.  So now the _necessary_ syncoid snapshot for that host _isn't_ the most recent one - it's just a _sorta_ recent one.

I will try to tackle this in a near future update, probably by having in-progress syncoid use a different name for its in-progress syncoid snapshot, then rename it on both ends once the replication has successfully completed.  But like I said, it's a relatively thorny problem, so for right now, syncoid just plain refuses to touch foreign syncoid snapshots.

You could consider a cron job that deletes any syncoid snapshots more than, say, a month old as a temporary workaround for your situation.

**Comment by devZer0** [comment]
i have a question here. i tried syncoid and it seems to work well, but i wondered why syncoid does not purge any snapshot on remote when it was purged by zfs-auto-snapshot on the source. 

i will run into diskspace issues on remote with this sooner or later, so i`m curious why syncoid does not create an exacty replica of the zfs from source to  destination but leaves snapshots on remote which do not exist anmyore on source. 

i`m not sure if i got this correct, as what i read above seems to be about syncoid-initiated snapshots!?

**Comment by redmop** [comment]
That really is a different issue. I would suggest creating a new issue for this question.

**Comment by Biktorgj** [comment]
I just got hit by this today, and I noticed something that doesn't seem to be mentioned by the OP.

My replication scheme is this:
Server1:
  Dataset1 (normally in use by Server1)
  Dataset2 (normally in use by Server2)
Server2:
  Dataset1 (normally in use by Server1)
  Dataset2 (normally in use by Server2)
Server3:
  Dataset1 (normally in use by Server1)
  Dataset2 (normally in use by Server2)

Server1 uses syncoid to replicate Dataset2 from Server2
Server2 uses syncoid to replicate Dataset1 from Server1
Server3 uses syncoid to replicate Dataset1 from Server1 and Dataset2 from server2. 

What I'm seeing is stale snapshots, from Server3 task, of the datasets which are *not* being replicated. Take a look at zfs list output:
root@Server1:/etc/monit/conf.d# zfs list -t snapshot
NAME                                                       USED  AVAIL  REFER  MOUNTPOINT
rpool/Dataset1@syncoid_Server1_2017-06-21:22:35:50    5.05G      -  1.66T  -
rpool/Dataset1@syncoid_Server2_2017-06-22:07:05:41   2.03M      -  1.66T  -
rpool/Dataset1@syncoid_Server3_2017-06-22:07:05:48      869K      -  1.66T  -
rpool/Dataset2@syncoid_Server2_2017-06-21:23:10:12  1.82G      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:57:03    5.16M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:57:48    1.59M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:58:03     815K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:58:18     727K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:58:33     754K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:58:48     485K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:59:03     700K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:59:18    1.01M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:59:33     714K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:06:59:48    1.04M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:00:06    1.75M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:00:18    1.12M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:00:33    1.20M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:00:48    2.66M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:01:03    2.31M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:01:18    1.78M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:01:33    1.51M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:01:48    1024K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:02:03     310K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:02:18     673K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:02:33     902K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:02:48     714K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:03:03    1017K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:03:19     734K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:03:33     162K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:03:48     855K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:04:04    1.24M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:04:18    1003K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:04:34     855K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:04:49     997K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:05:04    1017K      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:05:19    2.53M      -   169G  -
rpool/Dataset2@syncoid_Server3_2017-06-22:07:05:34    1.45M      -   169G  -
rpool/Dataset2@syncoid_Server1_2017-06-22:07:05:48       0      -   169G  -

I can still use a cronjob to remove these snapshots, but it seems syncoid shouldn't be even touching a dataset which is not on its list to replicate on that server (but might be getting confused by the fact that there is a dataset with the same name being replicated from another server and with the same machine as a target...)

Hope it helps!

**Comment by jimsalterjrs** [comment]
You're getting confused. Syncoid absolutely, 100% does not touch datasets that it isn't replicating. The only snapshots it does or even *can* create are those on the source host. They are tagged with the hostname of the machine creating the snapshot. In a pull replication, the target machine is creating the sync snapshot on the host machine. In a push replication, the source host is creating the sync snapshot on the host machine.

You might want to consider --no-sync-snapshot for your use case. If you're content with only replicating the most recent snapshots created by policy, this avoids the confusion of dealing with multiple sync snapshots from different hosts.

**Comment by redmop** [comment]
On Thu, Jun 22, 2017 at 5:18 AM, Jim Salter <notifications@github.com>
wrote:

> --no-sync-snapshot


The reason I'm migrating back to syncoid/sanoid.



Shawn T Perry
Red Mop Computing Services
phone: 303-881-2623
email: shawn@redmop.com

**Comment by jimsalterjrs** [comment]
Closing; you can now use --no-sync-snapshot to avoid issues with foreign syncoid snapshots piling up in multi-target replication schemes.

**Comment by ser** [comment]
I do not think it should be closed, there should be a regexp to avoid syncing snapshots from other syncoided hosts

**Comment by phreaker0** [comment]
@ser There is already an issue requesting the exclude feature here #153
