### ISSUE TITLE
Syncoid monitoring

### ISSUE THREAD

**Issue by ser** [jimsalterjrs/sanoid#573]
Hi, as I can see that monitoring parameters to syncoid are still empty, I wonder how do you monitor if syncoid works? Monitoring is really important in backups, is not it?

**Comment by jim-perkins** [comment]
Hi
I set syncoid up thru a cron job.  passed the --quiet option to syncoid so it only prints errors.  Have the server running syncoid setup to email cron errors to an email account that is monitored

**Comment by click0** [comment]
I've made some scripts for [monit](https://mmonit.com/monit/).
If there is a strong discrepancy in time, I receive an alert by mail.

**Comment by ewwhite** [comment]
@click0 I'd like to see your Monit scripts. I have some as well since I run and [manage syncoid processes](https://serverfault.com/a/842740/13325) with Monit.

**Comment by click0** [comment]
@ewwhite I have posted [some scripts](https://gist.github.com/click0/dad761f16cc03e8376bf693cf9dd8d6e).

**Comment by stoivo** [comment]
At our company we run icinga. I copied the base from you script and build some more features on top of it. You can find it [here](https://gist.github.com/stoivo/fe217d3c543a63673a20fe157b8d7dd9)

**Comment by jimsalterjrs** [comment]
You monitor whether syncoid is working by checking the target for snapshot freshness using `sanoid --monitor-snapshots`.

If the target has fresh snapshots, replication is working. If the target stops receiving fresh snapshots, `--monitor-snapshots` will throw a fit, and you know your replication has stopped working and can troubleshoot why.

**Comment by stoivo** [comment]
I was thinking of doing that. It is a perfect solution if you have access to both servers. I our case we are bying backupservice so we don't have access. I posted it here in case a someone else has the same case, maybe this isn't common at all. 

BTW. This project sped up our daily backup from 6-9hour  to 20 minutes. Totaly awsome.

**Comment by gnordli** [comment]
I am using monit to execute/control the replication, snapshot, and monitoring checks.   It gives a nice dashboard of all the current replication and snapshot health status.

**Comment by click0** [comment]
> 
> I am using monit to execute/control the replication, snapshot, and monitoring checks. It gives a nice dashboard of all the current replication and snapshot health status.

Could you post the monit settings and the accompanying scripts themselves?

**Comment by gnordli** [comment]
Part of it is here where I go through setting up the replication and snapshot piece.  #589 

The check_replication.conf file is symlinked into the /etc/monit/conf.d folder.  

check_replication.conf 
```
check program monit_check_replication with path "/etc/sanoid/check_replication.sh"
        as uid sanoid and gid sanoid
        with timeout 3600 seconds
        every 30 cycles
        if status != 0 then alert
```
check_replication.sh 
```
#!/bin/bash

flock -n /var/run/sanoid/check_snapshots_lock /usr/sbin/sanoid --configdir=/etc/sanoid/monitor --monitor-snapshots

exit $?
```
