### ISSUE TITLE
Syncoid "Cannot sync now" when simultaneously sending similarly named but different datasets

### ISSUE THREAD

**Issue by fmoledina** [jimsalterjrs/sanoid#579]
For better or worse, I have a few datasets that are similarly-named that differ only in the last character (i.e. `archive` and `archive2`). When using syncoid to send these datasets simultaneously to the same parent, syncoid presents the following error:

```bash
Cannot sync now: tank1/dest/archive is already target of a zfs receive process.
```

Steps to reproduce are below. First, create some test datasets and sample data:

```bash
$ zfs create tank1/source && zfs set mountpoint=/tmp/source tank1/source
$ zfs create tank1/dest && zfs set mountpoint=/tmp/dest tank1/dest
$ zfs create tank1/source/dataset
$ zfs create tank1/source/dataset2
$ dd if=/dev/urandom of=/tmp/source/dataset/file1.txt bs=1048576 count=10000
10000+0 records in
10000+0 records out
$ dd if=/dev/urandom of=/tmp/source/dataset2/file2.txt bs=1048576 count=10000
10000+0 records in
10000+0 records out
$ zfs snapshot tank1/source/dataset@oldestsnap
$ zfs snapshot tank1/source/dataset2@oldestsnap
```

Next, start two syncoid instances in two separate terminal windows.

```bash
# in one terminal window
$ syncoid -r tank1/source/dataset tank1/dest/dataset
INFO: Sending oldest full snapshot tank1/source/dataset@oldestsnap (~ 9.8 GB) 
 to new target filesystem:
 765MiB 0:00:08 [27.4MiB/s] [========>                                                    ]  7% ETA 0:01:36
```

```bash
# in another terminal window
$ syncoid -r tank1/source/dataset2 tank1/dest/dataset2
INFO: Sending oldest full snapshot tank1/source/dataset2@oldestsnap (~ 9.8 GB) 
 to new target filesystem:
21.0MiB 0:00:27 [1.06MiB/s] [>                                                            ]  0% ETA 3:34:12
```

In the first terminal window, syncoid errors out after sending the oldest snapshot of `dataset`, while `dataset2@oldestsnap` is still in progress in the other terminal window.

```bash
# back in the first terminal window
syncoid -r tank1/source/dataset tank1/dest/dataset
INFO: Sending oldest full snapshot tank1/source/dataset@oldestsnap (~ 9.8 GB)
 to new target filesystem:
9.79GiB 0:02:11 [76.5MiB/s] [============================================================>] 100%
Cannot sync now: tank1/dest/dataset is already target of a zfs receive process.
```

For datasets with multiple snapshots, this error prevents the subsequent sending of later snapshots. I realize the dataset names are similar, but they're not identical and shouldn't present a conflict. Simultaneous transfers of either of these datasets to the same parent dataset with a completely different dataset names, i.e. sending `tank1/source/home` and `tank1/source/dataset` to `tank1/dest/home` and `tank1/dest/dataset`, respectively, do not result in this error.

I'm wondering whether this is intended behaviour to prevent other edge cases or if this is a bug. Thanks.

**Comment by jimsalterjrs** [comment]
That's a ZFS error, not a syncoid error. You'd need to look for a fix upstream—although I wonder if there's not something else going on to tie the dataset up that we're not seeing here.

**Comment by fmoledina** [comment]
Thanks for the response. I can confirm that the target datasets are not mounted and no other processes were using them. Just want to confirm, were you able to reproduce the error with the example I gave? Thanks.

**Comment by jimsalterjrs** [comment]
Nope, cannot confirm.

**Comment by fmoledina** [comment]
Hmm, that's a bit disingenuous, then, given that I provided a full example. I'll test it out with raw send/recv to see if it's rooted in ZFS and continue to report findings here for posterity even though the issue is closed. Thanks.

**Comment by jimsalterjrs** [comment]
Disingenuous? You realize that means you're saying I'm a liar, right...? Seems pretty rude and uncalled for.

**Process one:**
```
root@banshee:/tmp# date ; syncoid tank1/source/dataset1 tank1/dest/dataset1
Sun 01 Nov 2020 08:21:41 PM EST
INFO: Sending oldest full snapshot tank1/source/dataset1@syncoid_banshee_2020-11-01:20:21:24 (~ 128.2 MB) to new target filesystem:
 128MiB 0:00:00 [ 132MiB/s] [================================>] 100%            
INFO: Updating new target filesystem with incremental tank1/source/dataset1@syncoid_banshee_2020-11-01:20:21:24 ... syncoid_banshee_2020-11-01:20:21:41 (~ 4 KB):
1.52KiB 0:00:00 [6.64KiB/s] [===========>                      ] 38%            

```
**Process two:**
```
root@banshee:/tmp# date ; syncoid tank1/source/dataset2 tank1/dest/dataset2
Sun 01 Nov 2020 08:21:41 PM EST
INFO: Sending oldest full snapshot tank1/source/dataset2@syncoid_banshee_2020-11-01:20:21:24 (~ 128.2 MB) to new target filesystem:
 128MiB 0:00:01 [88.7MiB/s] [================================>] 100%            
INFO: Updating new target filesystem with incremental tank1/source/dataset2@syncoid_banshee_2020-11-01:20:21:24 ... syncoid_banshee_2020-11-01:20:21:42 (~ 4 KB):
1.52KiB 0:00:00 [66.6KiB/s] [===========>                      ] 38%            

```

**Comment by fmoledina** [comment]
Thanks for testing. It wasn't clear at first whether you had run that test. Please try again using `dataset` instead of `dataset1`. I think that since `dataset` is wholly contained in `dataset2`, it ends up matching the conditional in L1125, which to me is a false positive if that's what's happening.
