### ISSUE TITLE
Parallel zfs send

### ISSUE THREAD

**Issue by stuartthebruce** [jimsalterjrs/sanoid#582]
Request for enhancement for syncoid to support parallel zfs send streams.

The use case is to reduce time to completion when replicating a large pool with a lot of datasets that can be transferred in parallel if additional CPU, storage and network resources are available.

**Comment by stuartthebruce** [comment]
I found that parallel --delay=1 -P# 'syncoid --recursive' on independent branches in my snapshot tree does a good job. Note, --delay avoids triggering problems with starting too many ssh connections between the same endpoints in too short of a time interval.

**Comment by phreaker0** [comment]
@stuartthebruce this won't be possible with the current architecture of syncoid, multiple invocations is the way to go here. The problem with the ssh collisions will be handled in the future #535
