### ISSUE TITLE
Syncoid failing after update to Openzfs 2.0.0-rc1

### ISSUE THREAD

**Issue by Nopel2020** [jimsalterjrs/sanoid#583]
I have several servers with zpools (running gentoo and debian) and one backup server (running debian) that runs a very simple weekly script to do a syncoid -r to a backuppool. This has worked perfectly for months, years, but now suddenly I am getting: cannot receive incremental stream: most recent snapshot does not match incremental source

I am not doing any pruning of snapshots on the backuppool. I've checked that there are matching snapshots on the source and backup. In fact, whenever I run the syncoid command, it starts correctly and manages to send one single snapshot over, and then fails. So if I rerun the syncoid command multiple times, eventually all the snapshots do end up on the backuppool.

The only thing that's changed is that I upgraded to 2.0.0-rc1 (from 0.8.4) on all pools. Maybe syncoid needs to be updated because something's changed in the send-recv logic?

**Comment by phreaker0** [comment]
@Nopel2020 can you post a full --debug run? I just tried 2.0.0-rc1 in a debian buster vm and the test runs from "tests/syncoid" all work. Are you doing send/recv between 2.0.0-rc1 and lower versions?

**Comment by Nopel2020** [comment]
@phreaker0 Thanks for looking into this!

All servers are on 2.0.0-rc1. I've done a --debug run now between two identical servers, both on debian.

[syncoid.txt](https://github.com/jimsalterjrs/sanoid/files/5151972/syncoid.txt)

**Comment by phreaker0** [comment]
@Nopel2020 can you make sure that the servers have the matching kernel and userspace tools with:
```zfs -V```

**Comment by Nopel2020** [comment]
Hi @phreaker0 

You're right, that was the problem! On the backup system the userspace tools got stuck on 0.8.4. I feel stupid that I didn't catch that!

Thanks for helping and sorry to waste your time! ;) Will close the ticket.

**Comment by phreaker0** [comment]
no problem :-)
