### ISSUE TITLE
Autosnap only for monthly and yearly?

### ISSUE THREAD

**Issue by apiening** [jimsalterjrs/sanoid#585]
I have a production system configured to create 15 daily snapshots (**autosnap = True**, **autoprune = True**).
I copy the snapshots with **--no-sync-snap** over to a backup pool on another system.

What I want in addition to that, is to keep monthly and yearly snapshots in the backup pool. These don't exist, since they have not been created on the source and I have sanoid configured with **autosnap = False**, **autoprune = True** on the backup system.
Ideally, one of the daily snapshots would be renamed to **weekly** instead of being pruned.
Another option I can think of is to set **autosnap = True** for only weekly and yearly snapshots, which from my understanding is not possible.

Is there a way to do a setup like this?
If so: What would be the best option?

**Comment by phreaker0** [comment]
@apiening Making snapshots on the backup pool as you stated is not possible if you want to keep the replication, this is just how zfs and other COW filesystems work. Renaming snapshots is the way to go in your use case but this out of scope for syncoid so you will have to create some post script which will do it for you.

**Comment by apiening** [comment]
Thanks @phreaker0,

that's of course correct: Additional snapshots on the target would break the synchronization. Haven't thought about this.

Do you know of an example script floating around where somebody else did something similar?
Renaming the snapshots should be easy, but there is some logic implied on when a specific snapshot should be renamed to weekly, monthly or yearly based on the date.
I think I should be able to figure that out, but I would prefer to start with a solution that has already proven to work.
