### ISSUE TITLE
Syncoid dies on initial large dataset sync

### ISSUE THREAD

**Issue by adman-c** [jimsalterjrs/sanoid#586]
Hi. I'm having difficulty syncing my primary storage pool (4x 8TB, raid10) to my backup server (4x 2TB, raidz1). Syncoid dies consistently on my media dataset, which is by far the largest dataset (~1.9TB full snapshot; the next largest dataset's full snapshot is ~400GB). The remaining datasets, totaling around 1.2TB, are able to complete normally. I am able to complete the sync on my media dataset by repeating the Syncoid command until it doesn't die. Once the initial sync is completed, any subsequent incremental syncs complete without issue, with the caveat that those incremental syncs are never anywhere near the size of the initial sync that causes problems.
Both servers are running Proxmox 6.2 with Sanoid/Syncoid version 2.0.3. All drives involved are SATA rust. The servers are connected via switched 10GBE and have a separate direct 40GBE connection. I see the problem over both connections. ZFS version: 0.8.4-pve1; srcversion: E9712003D310D2B54A51C97; vermagic: 5.4.44-2-pve SMP mod_unload modversions. Below are two examples of the error I'm seeing.
Thanks for any assistance you can provide, and please let me know if any additional info would be helpful.
Initial error (`syncoid -r --no-sync-snap --exclude=temp Pool/Media root@mmx40:Pool/Media`):
```
INFO: Sending oldest full snapshot Pool/Media@autosnap_2020-01-02_00:00:14_yearly (~ 1909.6 GB) to new target filesystem:
mbuffer: error: outputThread: error writing to <stdout> at offset 0x120e6680000: Broken pipe===> ] 62% ETA 1:14:09
mbuffer: warning: error during output to <stdout>: Broken pipe
1.16TiB 2:01:54 [ 166MiB/s] [==================================================================> ] 62%
CRITICAL ERROR: zfs send 'Pool/Media'@'autosnap_2020-01-02_00:00:14_yearly' | pv -s 2050437261536 | lzop | mbuffer -q -s 128k -m 16M 2>/dev/null | ssh -S /tmp/syncoid-root-root@mmx40-1599629065 root@mmx40 ' mbuffer -q -s 128k -m 16M 2>/dev/null | lzop -dfc | zfs receive -s -F '"'"'Pool/Media'"'"'' failed: 65280 at /usr/sbin/syncoid line 464.
```
Second error (`syncoid -r --exclude=temp Pool/Media root@mmx40:Pool/Media`):
```
Resuming interrupted zfs send/receive from Pool/Media to Pool/Media (~ 722.1 GB remaining):
mbuffer: error: outputThread: error writing to <stdout> at offset 0x9089680000: Broken pipe========================> ] 80% ETA 0:13:19
mbuffer: warning: error during output to <stdout>: Broken pipe
580GiB 0:54:26 [ 181MiB/s] [======================================================================================> ] 80%
CRITICAL ERROR: zfs send -t 1-e69eb8e52-d8-789c636064000310a500c4ec50360710e72765a5269730305c3a005184219f96569c5a02923180cbb321c9275596a41603e9026ba9fb1a8c98fa4bf2d34b33531818ba42f7707ef8b2a3dd03499e132c9f97989bcac010909f9fa3ef9b9a9299e890585a925f9c9758106f646064a06b60a86b60146f606005448626f195a98945399510ff000093bd2428 | pv -s 775383903600 | lzop | mbuffer -q -s 128k -m 16M 2>/dev/null | ssh -S /tmp/syncoid-root-root@mmx40-1599651745 root@mmx40 ' mbuffer -q -s 128k -m 16M 2>/dev/null | lzop -dfc | zfs receive -s -F '"'"'Pool/Media'"'"' 2>&1' failed: 65280 at /usr/sbin/syncoid line 549.
```

**Comment by phreaker0** [comment]
@adman-c the return code needs to be shifted by 8 bits to get the command exits code: 65280 >> 8 = 255
255 exit code indicates an error with ssh, from the manpage: 

`ssh exits with the exit status of the remote command or with 255 if an error occurred.`

So you should check the ssh server logs around the time the connection is terminated.

**Comment by adman-c** [comment]
@phreaker0 thanks for the pointer. I looked in the auth log and sure enough, right around the time that the sync died, here's what was happening in sshd land:
```
Sep  9 02:26:20 sshd[4551]: Corrupted MAC on input.
Sep  9 02:26:20 sshd[4551]: ssh_dispatch_run_fatal: Connection from user root 10.20.30.3 port 37378: message authentication code incorrect
Sep  9 02:26:20 sshd[4551]: pam_unix(sshd:session): session closed for user root
```
I'm now troubleshooting what would cause ssh to die like that, but it looks like it's probably not syncoid.

Thanks again.

**Comment by adman-c** [comment]
So for further testing, I swapped motherboards while keeping drives and NICs the same. Result: flawless sync of ~4TiB with no drops. So it's either the motherboard (the SATA ports maybe?), the processor, or the memory. In any case, this issue is pretty clearly not related to Syncoid. I'm closing this.
