### ISSUE TITLE
Cleaning up overabundance of sanoid snapshots

### ISSUE THREAD

**Issue by wkorfhage** [jimsalterjrs/sanoid#587]
I'm not sure what went wrong, but at some point, sanoid started making too many snapshots, such as yearly snapshots every minute over some time periods. I ended up with 10's of thousands of snapshots. The standard --prune-snapshots won't delete excessive newer ones because they are too new to age out. I have, for instance, 1553 yearly snapshots when it knows it wants just 1, but the excess won't get destroyed for a long time because they are less than a year old. I know I could just delete all but N snapshots, but I wondered if there is any script that would leave it in a state similar to what it should have been, e.g. 1 monthly snapshot per month.

**Comment by darkpixel** [comment]
Your monthly snapshots are probably on a specific day of the month--like the 1st.  You could trim the list a bit using something like ```zfs list -o name -s creation -rt snapshot | grep autosnap | grep monthly | grep -v 01_```

That would give you a list of all the snapshots with 'autosnap' and 'monthly' in the name, then filter out every snapshot with '01_' which is the date of the month followed by the separator between the date and time fields.

Based on what you described, you might still have a month of 'monthly' snapshots at various times on the first, but it might pair down the list if you need to do some manual deleting. :)
