### ISSUE TITLE
replicating multiple datasets concurrently 

### ISSUE THREAD

**Issue by gnordli** [jimsalterjrs/sanoid#589]
Hi. 
Right now I am generally focused on taking daily snapshots and replicating them offsite.  I have a few helper scripts making that happen.  It rolls through a configuration for each VM, which may have a couple of datasets per VM.  I separate out the snapshot and replication into different times.  For what it is, this is working really well.

I am looking at increasing my replication interval to maybe 15 mins, instead of daily.    

The snapshot piece looks pretty easy with basically no change, just run it in 15 minute intervals. 

The part I am not sure about is the replication piece.  I am not sure if I want to spawn a bunch of background syncoid processes.  If it were 1 per VM, that would make it about 12 at the same time.  Can I assume that it will reliably detect if another sync is happening on the current dataset and fail properly?  

How are other people handling it to get good concurrent sends of multiple datasets?
thanks,
Geoff

**Comment by gnordli** [comment]
I decided to go down the route with having monit control the replication, snapshot and pruning processes.  One of the challenges with monit is everything seems to start at the same time.  Unless you use different timer values it triggers the scripts simultaneously.  Here are some things I did to get around that limitation.  

I was getting some errors about the control socket

`ControlSocket /tmp/syncoid-user-user@pc-offsite1-1601943679 already exists, disabling multiplexing`
  
I changed syncoid to add a random number.  time() wasn't enough to create a unique socket.  

` $socket = "/tmp/syncoid-$remoteuser-$rhost-" . time() . rand(1000);`

In the script to trigger replication I added a sleep command to defer the replication up to 60 seconds.   

`sleep $((RANDOM % 60))`

I have three different targets that the replication goes to.   
```
cat targets
backup/vm
user@pc-offsite1:backup/vm
user@pc-back1:tank/vm
```
I pipe them through a "sort -R" to get a random listing.  When the replication starts the order of the hosts changes.  

monit configuration looks like this for each virtual machine
```
check program monit_sync_pc-security1 with path "/etc/sanoid/replicate.sh pc-security1 monit" 
        as uid user and gid user
        with timeout 3600 seconds
        every 4 cycles
        if status != 0 then alert
```

In my script for pruning and snapshots.  I take a lock

```
flock -n /var/run/sanoid/cron-take.lock /usr/sbin/sanoid --configdir=/etc/sanoid --take-snapshots --verbose | tee -a $LOG
flock -n /var/run/sanoid/cron-prune.lock   /usr/sbin/sanoid --configdir=$MONITOR_DIR --prune-snapshots --verbose >> $LOG
```
It looks like that is necessary because in my logs I see

`monit_prune_2020-10-07.log:INFO: deferring cache update (snapshot removal) - valid cache update lock held by another sanoid process.`

Sanoid is smart enough to detect when other activity is happening on a dataset

`/var/log/sanoid/monit_prune_2020-10-07.log:INFO: deferring pruning of backup/vm/pc-monitor1@autosnap_2020-10-07_01:53:00_frequently - backup/vm/pc-monitor1 is currently in zfs send or receive.`

Things seem to be going OK.

The only issue I am having right now is something is causing a modification on a remote dataset which breaks the receive process.  I don't like forcing a rollback in case there are issues with scripts and it goes sideways.  This is strange because the remote datasets are not even mounted.  

Geoff

**Comment by jimsalterjrs** [comment]
> Can I assume that [syncoid] will reliably detect if another sync is happening on the current dataset and fail properly?

Yes; syncoid looks for busy datasets. Beyond that, ZFS itself will refuse to allow more than one process to replicate to the same target at the same time, so running multiple syncoid processes is safe.

**Comment by griznog** [comment]
I just hit this issue running `syncoid` in parallel (Gnu parallel) using

```
cat list-of-fs | parallel -j 4 syncoid --quiet {} otherhost:{}
```

Testing now with the change from @gnordli above:

```
$socket = "/tmp/syncoid-$remoteuser-$rhost-" . time() . rand(1000);
```

and that seems to be working (so far). Any chance that change could get put into syncoid permanently? 

griznog
