### ISSUE TITLE
Ignoring/Including dataset based on ZFS user-property

### ISSUE THREAD

**Issue by TheHolm** [jimsalterjrs/sanoid#591]
I guess it would be nice to able to enable/disable autosnapshoting based on "com.sun:auto-snapshot" user-property as it done in
https://github.com/zfsonlinux/zfs-auto-snapshot.

It is very useful when new datasets are created automatically.

Happy to write code if author consider this feature worth of implementing.  It is bit unclear how to handle conflicts with config. What should get priority?  
P.S actually whole sanoid.conf can be moved to  user-property-es.

**Comment by phreaker0** [comment]
This is already possible: https://github.com/jimsalterjrs/sanoid#syncoid-dataset-properties

**Comment by wengole** [comment]
I too am looking for this functionality, but the documentation you've linked @phreaker0 is for Syncoid, I believe (and if I'm wrong I'm happy to open another issue) @TheHolm is asking for Sanoid to read ZFS user properties to determine if snapshots should be created.

**Comment by glueckself** [comment]
My current solution is to use a pre_snapshot_script, that fails if the property 'sanoid:disabled' is set to true. If the property is not present or set to false, sanoid works as usual. Syncoid is not affected by this.
Thus, it works "like before" for any dataset but my "special" ones.

Having it in sanoid itself would be better of course.
