### ISSUE TITLE
Syncoid with Zsys

### ISSUE THREAD

**Issue by spiral27** [jimsalterjrs/sanoid#596]
Hello,

Ubuntu 20.04 now has its own snapshot management tool called Zsys (see https://didrocks.fr and https://github.com/ubuntu/zsys). I am satisfied with this tool so I would prefer not to add sanoid on top.

I am trying to use syncoid to pull the snapshots from a central backup server with the command:

`syncoid --recursive --no-sync-snap <user>@<ip>:rpool backupspool/mycomputer/rpool`

but I can't get it to recognize the snapshots created by Zsys:

`WARN: --no-sync-snap is set, and getnewestsnapshot() could not find any snapshots on source for current dataset. Continuing.
CRITICAL: no snapshots exist on source rpool, and you asked for --no-sync-snap.`

Is there any way I can pull Zsys snapshots without having sanoid/syncoid to create its own snapshots on the source?

Thanks for any help!

**Comment by jimsalterjrs** [comment]
Syncoid recognizes all snapshots regardless of source. The issue is that you're asking for recursive replication beginning with a dataset--the root dataset of `rpool`--that does not have any snapshots, and you asked for `--no-sync-snap`.

Either manually create a snapshot in the `rpool` root yourself, or replicate once without using `--no-sync-snap` (which will create a snapshot for you). After that it will work fine.

**Comment by redmop** [comment]
FYI, you will need to expire your own snapshots on the remote if you are using zsys, as it does not expire them for you.

**Comment by spiral27** [comment]
Hello and thank you very much for your clarifications!

> Syncoid recognizes all snapshots regardless of source. The issue is that you're asking for recursive replication beginning with a dataset--the root dataset of `rpool`--that does not have any snapshots, and you asked for `--no-sync-snap`.
>
> Either manually create a snapshot in the `rpool` root yourself, or replicate once without using `--no-sync-snap` (which will create a snapshot for you). After that it will work fine.

I got a bit confused because I thought ZFS could only snapshot a dataset and not a pool. By reading the terminology at https://www.freebsd.org/doc/handbook/zfs-term.html I just realized "The root of the pool is technically a dataset as well". I'll just let syncoid create a snapshot on the source then, which is very convenient.

> FYI, you will need to expire your own snapshots on the remote if you are using zsys, as it does not expire them for you.

It is exactly why I didn't want syncoid to create many snapshots on the source (it uses space that Zsys pruning policy can't use)

**Question1**
What if my backup script (on the target):

1- connect to the source via SSH and destroys the syncoid snapshot(s) generated by the previous backup(s)

2- run the syncoid command which automatically creates a new snapshot on the source and sends it to the target

?

Or is it a bad idea because syncoid wouldn't find its previous snapshot to calculate the incremental ? Should I always use the --recursive flag?

**Question2**
The target pool has a bigger capacity. So my ultimate goal is to keep more snapshots on the target (even if they are pruned on the source). Zsys would prune the source and Sanoid would prune the target. I imagine Sanoid should not prune any snapshot still present on the source or it would be sent again on next backup. What is the best way to achieve that?

**Question3**
I used this very simple guide https://linsomniac.gitlab.io/post/2020-04-09-ubuntu-2004-encrypted-zfs/ to encrypt the rpool on the source. I can see it is encrypted on the source but not on the target. Is it because I use syncoid in "pull mode"?

Thanks for any help!

**Comment by lciti** [comment]
Technically, you don't need to create a snapshot on the source. You just need to manually create target filesystems (BOOT, ROOT, USERDATA) before starting syncoid the first time. Then you can sync your zsys backed up system with:

    zsysctl save -s
    syncoid --recursive --skip-parent --no-sync-snap --sendoptions=raw bpool/BOOT $BACKUP_BPOOL/BOOT
    syncoid --recursive --skip-parent --no-sync-snap --sendoptions=raw rpool/ROOT $BACKUP_RPOOL/ROOT
    syncoid --recursive --skip-parent --no-sync-snap --sendoptions=raw rpool/USERDATA $BACKUP_RPOOL/USERDATA

Regarding your "Question 3", the `--sendoptions=raw` switch also has the effect of sending encrypted filesystems as they are.

**Comment by spiral27** [comment]
@lciti thank you very much, it works wonderfully!!

Do you think it's really necessary to execute a "zsysctl save -s" on the backed up PC before syncoid? I understand Zsys snapshots:

- /rpool/USERDATA every hour

- bpool/BOOT and /rpool/ROOT only when necessary (when installing a new package for example)

So I am wondering if frequent "zsysctl save -s" snapshots created by my backup script wouldn't mess with Zsys garbage collection (snapshots pruning) policy.

**Comment by lciti** [comment]
@spiral27 No, I don't think it's necessary, I added it just in case I edit a file in "/etc", "/usr/local/bin" (or sth like that) and want to mare sure that everything is saved even if I have not updated a package recently. On the other hand, I don't think extra snapshots are a problem, the garbage collection should clean up as needed.
On a different note, if you want to restore more than just the files, you may use `--sendoptions="raw p"` so that the properties that zsys uses to link snapshots are preserved.

**Comment by spiral27** [comment]
Thanks again, you are really helpful!

I didn't think about the files edited in non-USERDATA directories but you are right on this, so I'll just "zsysctl save -s" before syncoid (it won't use much disk space anyway). And the "raw p" is definitely a very good tip that I will use too.

I am using a pull backup method (Syncoid installed on a server connects to the clients and retrieve the data). I am happy with the standard Zsys pruning policy (see https://didrocks.fr/2020/06/04/zfs-focus-on-ubuntu-20.04-lts-zsys-state-collection/) so my initial idea was to mirror the clients and the server (a snapshot destroyed on the client would be destroyed on the server). But then I thought it wouldn't be a good idea as a virus could delete snapshots on the client, which would be deleted on the server too...

I am now thinking about replicating the Zsys policy on Syncoid server but with 1 extra snapshot for security. So for example:
- if Zsys keeps 7 dailies, Syncoid will keep 8 dailies
- if Zsys keeps 4 weeklies, Syncoid will keep 5 weeklies
- etc...

But I think it would tricky to "translate" the Zsys policy into a Syncoid policy and I pretty sure there is a better solution.

Do you have any recommendation?

PS: I hope I am not using too much of your time. I feel like you achieved exactly what I am trying to do so I am trying to learn from your experience...

**Comment by spiral27** [comment]
Hello and thanks again for all the information.

My goal is simpler than yours as I don't need to boot from backup. But I just discovered a problem: the data used on the target is doubled if the source reverted to a previous state. Let me explain:

## On a fresh ubuntu 20.4 machine installed on ZFS: ##

1- the USED value of source/rpool is 400G

2- I send everything with syncoid from source/rpool to backup/rpool

3- the USED value of backup/rpool is 400G


## On a the same machine after it was reverted to a previous Zsys state: ##

1- new datasets are created on the source (because of the revert) but the USED value of source/rpool is still 400G

2- I send everything with syncoid from source/rpool to backup/rpool

3- the USED value of backup/rpool is now 800G (for the exact same data which represents 400G on the source)


For example, the output of "zsysctl show" on https://didrocks.fr/2020/06/02/zfs-focus-on-ubuntu-20.04-lts-zsys-commands-for-state-management makes me think that this system was reverted at least once. In pure ZFS terms it means there is now a /rpool/USERDATA/didrocks_fsmk5b dataset and another /rpool/USERDATA/didrocks_e2jj0s dataset. After syncoid sends the new didrocks_e2jj0s datasets, the USED value rpool on the target is doubled.

If I "reset the target" by destroying backup/rpool and re-send everything (including the "before revert" datasets and "after revert" datasets) with syncoid, the used value is now 400G (just like on the source). But this is annoying as all the data must be sent again on every revert.

Do you understand what is happening?
