### ISSUE TITLE
Issue with syncoid at initial sync: `cannot receive incremental stream: dataset is busy`

### ISSUE THREAD

**Issue by kobuki** [jimsalterjrs/sanoid#598]
As the title says. For any inital sync, I always get the error. Example below. Any incremental updates are running without errors.

```
root@backup:~# syncoid --compress=zstd-fast --source-bwlimit=5m -no-sync-snap --sendoptions 'c' backup@sourcehost:rpool/data/subvol-101-disk-1 backup/hostgroup/hostname/subvol-101-disk-1
NEWEST SNAPSHOT: autosnap_2020-11-15_00:00:00_daily
INFO: Sending oldest full snapshot rpool/data/subvol-101-disk-1@syncoid_hostname_2020-11-14:14:34:02-GMT01:00 (~ 575.5 MB) to new target filesystem:
 617MiB 0:01:20 [7.70MiB/s] [=========================================================================================================================================================] 107%
INFO: Updating new target filesystem with incremental rpool/data/subvol-101-disk-1@syncoid_hostname_2020-11-14:14:34:02-GMT01:00 ... autosnap_2020-11-15_00:00:00_daily (~ 513 KB):
 835KiB 0:00:00 [10.0MiB/s] [=========================================================================================================================================================] 162%
cannot receive incremental stream: dataset is busy
CRITICAL ERROR: ssh     -S /tmp/syncoid-backup@sourcehost-1605440450 backup@sourcehost 'sudo zfs send -c  -I '"'"'rpool/data/subvol-101-disk-1'"'"'@'"'"'syncoid_hostname_2020-11-14:14:34:02-GMT01:00'"'"' '"'"'rpool/data/subvol-101-disk-1'"'"'@'"'"'autosnap_2020-11-15_00:00:00_daily'"'"' | zstd -3 | mbuffer -R 5m -q -s 128k -m 16M 2>/dev/null' | mbuffer  -q -s 128k -m 16M 2>/dev/null | zstd -dc | pv -p -t -e -r -b -s 526168 |  zfs receive  -s -F 'backup/hostgroup/hostname/subvol-101-disk-1' failed: 256 at /usr/sbin/syncoid line 528.
```

sanoid version: master@50cf9c9

Source
OS: Debian 10.6 (Proxmox 6.2)
ZoL: 0.8.4-pve2

Target
OS: Ubuntu 20.04.1 LTS
ZoL; 0.8.3-1ubuntu12.4

Note that the target is encrypted.

**Comment by phreaker0** [comment]
@kobuki this is a zfs problem, syncoid does the right thing here

**Comment by kobuki** [comment]
@phreaker0 can you please point me to where it's detailed? ZoL must have an issue# or something about this. My own old scripts that I'm planning to replace with your solutions (or some other) never produce this kind of error.

**Comment by phreaker0** [comment]
@kobuki I don't know if this problem is known and already reported to the zfs developers, I only judged from the command which is executed that syncoid did the right thing here, like I would do if I do it by hand.
If I had to guess I would say that the sendoption flag "c" (send compressed blocks as is) maybe has something to do with it. I would suggest to try without and see whats happens.
You can also run syncoid with "--debug" so all commands which are executed by syncoid are shown.
