### ISSUE TITLE
target exists but has no matching snapshots!

### ISSUE THREAD

**Issue by 0xFate** [jimsalterjrs/sanoid#6]
SInce i did git pull yesterday all my datasets run in an error that there are no matching snapshots, even on an freshly synced dataset (with current version) it fails after the first run, if source or target is remote.i cant sync on local fs, it fails with "failed to read from stream".
im sorry i dit not pull any changes since my last additions  so i just cant tell wich one broke. my latest working syncoid was "1.0.13" with my changes to getsnaps.

my OS
Linux zfscas02 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

**Comment by jimsalterjrs** [comment]
Please try your sync with the --debug flag, and post the output here.

**Comment by jimsalterjrs** [comment]
Any update, @0xFate ?

**Comment by 0xFate** [comment]
sorry i actually encounterd that while in an reabuild process while encountering it so i had to focus on my servers firt before debugging it. i found old syncoid snapshits which may have caused that problem. ill come back on that later when finished ans cleaned up messy snapshots

**Comment by 0xFate** [comment]
Yeah indeed it was the messy snapshots after an cleanup it worked lik a charm again. i may spend some time in writing some exception handling for that this weekend.

**Comment by jimsalterjrs** [comment]
Don't know if you noticed, btw, but a lot of that new code I added was adding sudo support to syncoid.  It will now automatically detect if it should use sudo (example syncoid syncoid@remotebox:pool/dataset localpool/dataset), so as long as the user on the remote end has `NOPASSWD` available for /sbin/zfs, everything works great.

**Comment by 0xFate** [comment]
yeah thats why o opened this in the first place b/c i supposed that changes to be the issue in some way but i read the code and it rules out sudo when @root.

**Comment by jimsalterjrs** [comment]
Yup.  Coming up pretty soon on the roadmap will be the ability to communicate directly with a remote sanoid, to minimize the SSH traffic and also the amount of privilege needed to grant to a remote machine.  IE have a wrapper syncoid-send that calls syncoid --send [arguments], which can obligingly cough up all of the necessary information about snapshots and capabilities in one go, can be given privileges to handle only certain datasets but not others, etc.

**Comment by 0xFate** [comment]
great to hear that, i already wrapped my head around that a bit either. when you want to do the caching of snap/vol list on FS please consider a cfg file and an option to set cache dir and sync data source. that way you could easily adapt caching on clusterFS (glusterfs,ocfs) for accessing remote cache directly, or ramdisk for faster access.
if you go upstream w/ the feature you planned ill definitivly spaer some time in working on that :)
