### ISSUE TITLE
syncoid deletes snapshots on the target

### ISSUE THREAD

**Issue by marzah** [jimsalterjrs/sanoid#60]
I cant tell what I am doing wrong

I run
syncoid -r root@192.168.1.73:zfsstorage zfsbackups/debian8
and I end up with 
zfsbackups                                                        1.29M  19.3G    96K  /zfsbackups
zfsbackups/debian8                                                 288K  19.3G    96K  /zfsbackups/debian8
zfsbackups/debian8@syncoid_debian8-zfs2_2016-11-05:16:18:14           0      -    96K  -
zfsbackups/debian8/dir1                                             96K  19.3G    96K  /zfsbackups/debian8/dir1
zfsbackups/debian8/dir1@syncoid_debian8-zfs2_2016-11-05:16:18:14      0      -    96K  -
zfsbackups/debian8/dir2                                             96K  19.3G    96K  /zfsbackups/debian8/dir2
zfsbackups/debian8/dir2@syncoid_debian8-zfs2_2016-11-05:16:18:14      0      -    96K  -
Which is fine
I then run 
sanoid --cron
and zfs list -t all gives me this
zfsbackups                                                        1.34M  19.3G    96K  /zfsbackups
zfsbackups/debian8                                                 288K  19.3G    96K  /zfsbackups/debian8
zfsbackups/debian8@syncoid_debian8-zfs2_2016-11-05:16:18:14           0      -    96K  -
zfsbackups/debian8@autosnap_2016-11-05_16:20:56_monthly               0      -    96K  -
zfsbackups/debian8@autosnap_2016-11-05_16:20:56_daily                 0      -    96K  -
zfsbackups/debian8@autosnap_2016-11-05_16:20:56_hourly                0      -    96K  -
zfsbackups/debian8/dir1                                             96K  19.3G    96K  /zfsbackups/debian8/dir1
zfsbackups/debian8/dir1@syncoid_debian8-zfs2_2016-11-05:16:18:14      0      -    96K  -
zfsbackups/debian8/dir1@autosnap_2016-11-05_16:20:56_daily            0      -    96K  -
zfsbackups/debian8/dir1@autosnap_2016-11-05_16:20:56_monthly          0      -    96K  -
zfsbackups/debian8/dir1@autosnap_2016-11-05_16:20:56_hourly           0      -    96K  -
zfsbackups/debian8/dir2                                             96K  19.3G    96K  /zfsbackups/debian8/dir2
zfsbackups/debian8/dir2@syncoid_debian8-zfs2_2016-11-05:16:18:14      0      -    96K  -
zfsbackups/debian8/dir2@autosnap_2016-11-05_16:20:56_hourly           0      -    96K  -
zfsbackups/debian8/dir2@autosnap_2016-11-05_16:20:56_monthly          0      -    96K  -
zfsbackups/debian8/dir2@autosnap_2016-11-05_16:20:56_daily            0      -    96K  -
Which I guess is also fine
I then run 
syncoid -r root@192.168.1.73:zfsstorage zfsbackups/debian8
And I am back to this. The dailies monthlies etc.. are gone
zfsbackups                                                        1.30M  19.3G    96K  /zfsbackups
zfsbackups/debian8                                                 288K  19.3G    96K  /zfsbackups/debian8
zfsbackups/debian8@syncoid_debian8-zfs2_2016-11-05:16:22:58           0      -    96K  -
zfsbackups/debian8/dir1                                             96K  19.3G    96K  /zfsbackups/debian8/dir1
zfsbackups/debian8/dir1@syncoid_debian8-zfs2_2016-11-05:16:22:58      0      -    96K  -
zfsbackups/debian8/dir2                                             96K  19.3G    96K  /zfsbackups/debian8/dir2
zfsbackups/debian8/dir2@syncoid_debian8-zfs2_2016-11-05:16:22:58      0      -    96K  -

Here is my sanoid.conf
[zfsbackups/debian8]       
        use_template = backup
        recursive = yes
#############################
# templates below this line #
#############################

# name your templates template_templatename. you can create your own, and use them in your module definitions above.

[template_demo]
        daily = 60

[template_production]
        hourly = 36
        daily = 30
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes

[template_backup]
        autoprune = yes
        hourly = 10
        daily = 90
        monthly = 12
        yearly = 0

        ### don't take new snapshots - snapshots on backup
        ### datasets are replicated in from source, not
        ### generated locally
        autosnap = no

        ### monitor hourlies and dailies, but don't warn or
        ### crit until they're over 48h old, since replication
        ### is typically daily only
        hourly_warn = 2880
        hourly_crit = 3600
        daily_warn = 48
        daily_crit = 60

Reading the instructions and various groups tells me that syncoid is not supposed to clobber the destination but it does.
My goal is to snapshot machine A to B and have sanoid on B  manage the snapshots.
I don’t want to keep many snapshots on the production server
This is Debian 8 fresh installation
Syncoid version: 1.4.7
What am I doing wrong.
Any help would be appreciated

**Comment by jimsalterjrs** [comment]
You can't take snapshots on a target and expect them to persist.  Incremental ZFS replication has to start from a commonly held snapshot - so anything you do on the target that changes data since the last replication will be wiped out when the next replication happens.

1. syncoid pool/source pool/target
2. newest snapshot on pool/source and pool/target are now both @syncoid_timestamp
3. you take zfs snapshot pool/target@whatever
4. syncoid pool/source pool/target
5. syncoid sees most recent common snapshot between pool/source and pool/target is @syncoid_timestamp
6. syncoid rolls back pool/target to @syncoid_timestamp so replication can begin
7. replication happens

**Comment by marzah** [comment]
Hello Jim

Thank you for responding.
I think you misunderstand.
I have 2 servers A the source and B the target.
On A I would like 1 or 2 snapshots.
On B I would like many snapshots of A.
Everything I posted was from the perspective of B.
From what I could glean from the the instructions I assume sanoid and syncoid can work together.
I did the following.
1)Run syncoid from B to get a current snapshot of A
2)Run sanoid on B to hopefully manage the snapshots as defined in the policy
3)Run syncoid again from B and get a current snapshot of A
4)Observer that all of the sanoid stuff is gone.
I never touch the snaphots created by syncoid.

Perhaps I misunderstand the use case. I have written my own scripts that do the above correctly but yours looked better.

**Comment by jimsalterjrs** [comment]
I didn't misunderstand.

Sanoid and syncoid do work together.

A and B are confusing, so please let's speak only of host "source" and host "target".

Host "source" is where you create your data.  On host "source", sanoid must be configured with the "production" template - or a similar one, with both autosnap=yes and autoprune=yes.

Host "target" receives replication from host "source". Host "target" must use a sanoid configuration with autosnap=**no** and autoprune=yes.

Host "target" should not attempt to take snapshots of its own.  They will merely be rolled back the next time replication happens.  Host "target" merely prunes expired snapshots according to policy.  That policy may be very different from the policy on host "source" - for example, "target" might keep 12 monthlies around where "source" only kept three.

**Comment by marzah** [comment]
Hello Jim

You are correct. I went through your code and had already come to understand how it works.
I am testing it now.
Any ideas on getting 1 minutes snapshots. I have a case requiring finer granularity.
Also I occasionally need 2 snapshots a day not 2 hours but 1 at noon and 1 at 12

**Comment by pgiblock** [comment]
This is an old issue, but it is one of the first results when searching for a solution to @marzah's requirement, so I hope this helps someone else. One can use syncoid to sync from source to target machines while only leaving one one "@syncoid_XXX" snapshot persisted, and also use sanoid on the target to main a snapshot history("@autosnap_"). 

syncoid's `--no-rollback` can be used to omit the `-F` flag from `zfs receive`. However, for this to work reliably, you need to make the target dataset readonly (or never mount it, but readonly seems to make more sense). `--no-rollback` may have not existed 4 years ago, but the solution is easy-peasy!

Cheers.
