### ISSUE TITLE
2.1.0 release schedule

### ISSUE THREAD

**Issue by stuartthebruce** [jimsalterjrs/sanoid#600]
Is there a timeline for a 2.1.0 release given that all of the milestone issues are closed?

**Comment by mabod** [comment]
Is there any progress?

**Comment by redmop** [comment]
It can't be done yet. I am in the middle of deploying 2.0.3. It can be released after I finish. :P

**Comment by redmop** [comment]
Damn. Missed it by 1 day. I was going to finish tomorrow.

Seriously, thanks so much for maintaining this.

**Comment by jimsalterjrs** [comment]
@phreaker0 deserves the lion's share of the credit.

**Comment by redmop** [comment]
Thank you specifically then, @phreaker0. ;)
