### ISSUE TITLE
resumechkcmd not scoped

### ISSUE THREAD

**Issue by stuartthebruce** [jimsalterjrs/sanoid#603]
The following should check the particular pool in question rather than assuming that all pools on a system have the same features enabled,
```
my $resumechkcmd = "$zpoolcmd get -o value -H feature\@extensible_dataset";
```

**Comment by phreaker0** [comment]
syncoid checks the src and target pool for resume support, the line you copied is the base command for building the pool check commands. See lines https://github.com/jimsalterjrs/sanoid/blob/50cf9c9cc5d82ebb17b1c3d9808f14a3c6942515/syncoid#L1093 and https://github.com/jimsalterjrs/sanoid/blob/50cf9c9cc5d82ebb17b1c3d9808f14a3c6942515/syncoid#L1097.
