### ISSUE TITLE
Configuration does not deal well with duplicate lines

### ISSUE THREAD

**Issue by dspindler** [jimsalterjrs/sanoid#604]
If a boolean in a configuration is defined it does not behave as expected. For example if the line "autosnap = no" is in a template it behaves as expected, however if it is in the template twice then it enables autosnap.

This is a problem because people often copy/paste between configs and in a line by line review everything is correct as both lines set the same value.

**Comment by phreaker0** [comment]
@dspindler can you post an example? I don't really grasp what you mean.

**Comment by dspindler** [comment]
See below. Basically it works fine with the autosnap=no line, but if I add the line in a second time it inverts it like a 'toggle'
`
[root@storage11 ~]# cat /etc/sanoid/sanoid.conf
[zpool38]
        use_template=productionr
        recursive=yes
        process_children_only=yes

[zpool38/emergency]
        use_template=none


[template_productionr]
        frequently = 0
        hourly = 36
        daily = 14
        weekly = 8
        monthly = 4
        yearly = 0
        autosnap = no
        autoprune = yes
        hourly_warn = 240m
        hourly_crit = 360m
        daily_warn = 30h
        daily_crit = 34h
        weekly_warn = 8d
        weekly_crit = 9d
        monthly_warn = 33d
        monthly_crit = 34d
[root@storage11 ~]# sanoid
INFO: cache expired - updating from zfs list.
INFO: taking snapshots...
INFO: pruning snapshots...
[root@storage11 ~]# echo 'autosnap = no' >> /etc/sanoid/sanoid.conf
[root@storage11 ~]# sanoid
INFO: taking snapshots...
taking snapshot zpool38/persad_research@autosnap_2020-12-07_16:33:32_hourly
taking snapshot zpool38/climate_data@autosnap_2020-12-07_16:33:32_hourly
taking snapshot zpool38/potvin@autosnap_2020-12-07_16:33:32_hourly
taking snapshot zpool38/climate_yang@autosnap_2020-12-07_16:33:32_hourly
taking snapshot zpool38/potvin_users@autosnap_2020-12-07_16:33:32_hourly
taking snapshot zpool38/climate@autosnap_2020-12-07_16:33:32_hourly
taking snapshot zpool38/emergency@autosnap_2020-12-07_16:33:32_monthly
taking snapshot zpool38/emergency@autosnap_2020-12-07_16:33:32_weekly
taking snapshot zpool38/emergency@autosnap_2020-12-07_16:33:32_daily
taking snapshot zpool38/emergency@autosnap_2020-12-07_16:33:32_hourly
INFO: cache expired - updating from zfs list.
INFO: pruning snapshots...
[root@storage11 ~]# cat /etc/sanoid/sanoid.conf
[zpool38]
        use_template=productionr
        recursive=yes
        process_children_only=yes

[zpool38/emergency]
        use_template=none


[template_productionr]
        frequently = 0
        hourly = 36
        daily = 14
        weekly = 8
        monthly = 4
        yearly = 0
        autosnap = no
        autoprune = yes
        hourly_warn = 240m
        hourly_crit = 360m
        daily_warn = 30h
        daily_crit = 34h
        weekly_warn = 8d
        weekly_crit = 9d
        monthly_warn = 33d
        monthly_crit = 34d
autosnap = no
[root@storage11 ~]#
`

**Comment by phreaker0** [comment]
@dspindler thanks, found the issue. In this case the configuration parser will provide an array with all the values specified which isn't handled correctly by sanoid. Fixed in the linked PR.
