### ISSUE TITLE
sanoid seems to ignore template

### ISSUE THREAD

**Issue by marzah** [jimsalterjrs/sanoid#61]
I have a basic debian install

Here is my  sanoid.conf

######################################
# This is a sample sanoid.conf file. #
# It should go in /etc/sanoid.       #
######################################

# name your backup modules with the path to their ZFS dataset - no leading slash.
[zfsstorage]
	use_template = marcus 
	recursive = yes
	

#############################
# templates below this line #
#############################

# name your templates template_templatename. you can create your own, and use them in your module definitions above.

[template_marcus]
	hourly = 4
	daily = 0
	monthly = 0
	yearly = 0
	autosnap = yes
        autoprune = yes

[template_production]
	hourly = 36
	daily = 30
	monthly = 3
	yearly = 0
	autosnap = yes
	autoprune = yes

[template_backup]
	autoprune = yes
	hourly = 30
	daily = 90
	monthly = 12
	yearly = 0

	### don't take new snapshots - snapshots on backup 
	### datasets are replicated in from source, not
	### generated locally
	autosnap = no

	### monitor hourlies and dailies, but don't warn or 
	### crit until they're over 48h old, since replication 
	### is typically daily only
	hourly_warn = 2880
	hourly_crit = 3600
	daily_warn = 48
	daily_crit = 60

After 20 hours I have this.
Basically many more snapshots than my template specifies.

root@debian8-zfs1:~# zfs list -t all
NAME                                                       USED  AVAIL  REFER  MOUNTPOINT
zfsstorage                                                3.67M  9.62G    96K  /zfsstorage
zfsstorage@autosnap_2016-11-06_05:32:23_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_06:32:23_monthly               0      -    96K  -
zfsstorage@autosnap_2016-11-06_06:32:23_daily                 0      -    96K  -
zfsstorage@syncoid_debian8-zfs2_2016-11-06:06:33:48           0      -    96K  -
zfsstorage@autosnap_2016-11-06_07:01:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_08:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_09:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_10:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_11:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_12:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_13:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_14:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_15:00:01_hourly                0      -    96K  -
zfsstorage@autosnap_2016-11-06_16:00:01_hourly                0      -    96K  -
zfsstorage/dir1                                             96K  9.62G    96K  /zfsstorage/dir1
zfsstorage/dir1@autosnap_2016-11-06_06:32:23_daily            0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_06:32:23_monthly          0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_05:32:23_hourly           0      -    96K  -
zfsstorage/dir1@syncoid_debian8-zfs2_2016-11-06:06:33:49      0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_07:01:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_08:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_09:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_10:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_11:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_12:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_13:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_14:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_15:00:01_hourly           0      -    96K  -
zfsstorage/dir1@autosnap_2016-11-06_16:00:01_hourly           0      -    96K  -
zfsstorage/dir2                                             96K  9.62G    96K  /zfsstorage/dir2
zfsstorage/dir2@autosnap_2016-11-06_06:32:23_daily            0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_06:32:23_monthly          0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_05:32:23_hourly           0      -    96K  -
zfsstorage/dir2@syncoid_debian8-zfs2_2016-11-06:06:33:49      0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_07:01:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_08:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_09:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_10:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_11:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_12:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_13:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_14:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_15:00:01_hourly           0      -    96K  -
zfsstorage/dir2@autosnap_2016-11-06_16:00:01_hourly           0      -    96K  -
zfsstorage/dir3                                             96K  9.62G    96K  /zfsstorage/dir3
zfsstorage/dir3@autosnap_2016-11-06_05:32:23_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_06:32:23_daily            0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_06:32:23_monthly          0      -    96K  -
zfsstorage/dir3@syncoid_debian8-zfs2_2016-11-06:06:33:50      0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_07:01:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_08:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_09:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_10:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_11:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_12:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_13:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_14:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_15:00:01_hourly           0      -    96K  -
zfsstorage/dir3@autosnap_2016-11-06_16:00:01_hourly           0      -    96K  -

So I run
sanoid --debug
Which produces this

DEBUG: initializing $config{zfsstorage} with default values from /etc/sanoid/sanoid.defaults.conf.
DEBUG: getting list of child datasets on zfsstorage using  /sbin/zfs list -o name -Hr zfsstorage |...
DEBUG: recursively setting monthly_crit from zfsstorage to zfsstorage.
DEBUG: recursively setting min_percent_free from zfsstorage to zfsstorage.
DEBUG: recursively setting monitor_dont_crit from zfsstorage to zfsstorage.
DEBUG: recursively setting autosnap from zfsstorage to zfsstorage.
DEBUG: recursively setting path from zfsstorage to zfsstorage.
DEBUG: recursively setting hourly_warn from zfsstorage to zfsstorage.
DEBUG: recursively setting monthly_mday from zfsstorage to zfsstorage.
DEBUG: recursively setting hourly from zfsstorage to zfsstorage.
DEBUG: recursively setting autoprune from zfsstorage to zfsstorage.
DEBUG: recursively setting daily_warn from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_hour from zfsstorage to zfsstorage.
DEBUG: recursively setting daily_hour from zfsstorage to zfsstorage.
DEBUG: recursively setting daily_min from zfsstorage to zfsstorage.
DEBUG: recursively setting monthly_warn from zfsstorage to zfsstorage.
DEBUG: recursively setting daily from zfsstorage to zfsstorage.
DEBUG: recursively setting monthly_min from zfsstorage to zfsstorage.
DEBUG: recursively setting monthly from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_crit from zfsstorage to zfsstorage.
DEBUG: recursively setting monitor from zfsstorage to zfsstorage.
DEBUG: recursively setting monitor_dont_warn from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_warn from zfsstorage to zfsstorage.
DEBUG: recursively setting hourly_min from zfsstorage to zfsstorage.
DEBUG: recursively setting daily_crit from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_min from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_mon from zfsstorage to zfsstorage.
DEBUG: recursively setting monthly_hour from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_mday from zfsstorage to zfsstorage.
DEBUG: recursively setting hourly_crit from zfsstorage to zfsstorage.
DEBUG: recursively setting yearly_mday from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monthly_hour from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting hourly_crit from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly_min from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting daily_crit from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly_mon from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting hourly_min from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly_warn from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monthly_warn from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting daily from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monthly_min from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monthly from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monitor_dont_warn from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly_crit from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monitor from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting daily_warn from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly_hour from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting daily_hour from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting daily_min from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting autoprune from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting initialized from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting path from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting hourly_warn from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting autosnap from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monthly_mday from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting hourly from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monthly_crit from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting min_percent_free from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting monitor_dont_crit from zfsstorage to zfsstorage/dir1.
DEBUG: recursively setting yearly_mday from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monthly_hour from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting hourly_crit from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly_min from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting daily_crit from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly_mon from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting hourly_min from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly_warn from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monthly_warn from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting daily from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monthly_min from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monthly from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monitor_dont_warn from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly_crit from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monitor from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting daily_warn from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly_hour from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting daily_hour from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting daily_min from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting autoprune from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting initialized from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting path from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting hourly_warn from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting autosnap from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monthly_mday from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting hourly from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monthly_crit from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting min_percent_free from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting monitor_dont_crit from zfsstorage to zfsstorage/dir2.
DEBUG: recursively setting yearly_mday from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monthly_hour from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting hourly_crit from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting yearly_min from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting daily_crit from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting yearly_mon from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting yearly from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting hourly_min from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting yearly_warn from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monthly_warn from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting daily from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monthly_min from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monthly from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monitor_dont_warn from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting yearly_crit from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monitor from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting daily_warn from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting yearly_hour from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting daily_hour from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting daily_min from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting autoprune from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting initialized from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting path from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting hourly_warn from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting autosnap from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monthly_mday from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting hourly from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monthly_crit from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting min_percent_free from zfsstorage to zfsstorage/dir3.
DEBUG: recursively setting monitor_dont_crit from zfsstorage to zfsstorage/dir3.
****** CONFIGS ******
$VAR1 = {
          'zfsstorage' => {
                            'autoprune' => 1,
                            'autosnap' => '1;',
                            'daily' => '90',
                            'daily_crit' => '32',
                            'daily_hour' => '23;',
                            'daily_min' => '59;',
                            'daily_warn' => '28',
                            'hourly' => '48',
                            'hourly_crit' => '360 ',
                            'hourly_min' => '0;',
                            'hourly_warn' => '90',
                            'initialized' => 1,
                            'min_percent_free' => '10',
                            'monitor' => 1,
                            'monitor_dont_crit' => 0,
                            'monitor_dont_warn' => 0,
                            'monthly' => '6',
                            'monthly_crit' => '35',
                            'monthly_hour' => '0;',
                            'monthly_mday' => '1;',
                            'monthly_min' => '0;',
                            'monthly_warn' => '32',
                            'path' => 'zfsstorage',
                            'yearly' => '0',
                            'yearly_crit' => '0',
                            'yearly_hour' => '0;',
                            'yearly_mday' => '1;',
                            'yearly_min' => '0;',
                            'yearly_mon' => '1;',
                            'yearly_warn' => '0'
                          },
          'zfsstorage/dir1' => {
                                 'autoprune' => 1,
                                 'autosnap' => '1;',
                                 'daily' => '90',
                                 'daily_crit' => '32',
                                 'daily_hour' => '23;',
                                 'daily_min' => '59;',
                                 'daily_warn' => '28',
                                 'hourly' => '48',
                                 'hourly_crit' => '360 ',
                                 'hourly_min' => '0;',
                                 'hourly_warn' => '90',
                                 'initialized' => 1,
                                 'min_percent_free' => '10',
                                 'monitor' => 1,
                                 'monitor_dont_crit' => 0,
                                 'monitor_dont_warn' => 0,
                                 'monthly' => '6',
                                 'monthly_crit' => '35',
                                 'monthly_hour' => '0;',
                                 'monthly_mday' => '1;',
                                 'monthly_min' => '0;',
                                 'monthly_warn' => '32',
                                 'path' => 'zfsstorage/dir1',
                                 'yearly' => '0',
                                 'yearly_crit' => '0',
                                 'yearly_hour' => '0;',
                                 'yearly_mday' => '1;',
                                 'yearly_min' => '0;',
                                 'yearly_mon' => '1;',
                                 'yearly_warn' => '0'
                               },
          'zfsstorage/dir2' => {
                                 'autoprune' => 1,
                                 'autosnap' => '1;',
                                 'daily' => '90',
                                 'daily_crit' => '32',
                                 'daily_hour' => '23;',
                                 'daily_min' => '59;',
                                 'daily_warn' => '28',
                                 'hourly' => '48',
                                 'hourly_crit' => '360 ',
                                 'hourly_min' => '0;',
                                 'hourly_warn' => '90',
                                 'initialized' => 1,
                                 'min_percent_free' => '10',
                                 'monitor' => 1,
                                 'monitor_dont_crit' => 0,
                                 'monitor_dont_warn' => 0,
                                 'monthly' => '6',
                                 'monthly_crit' => '35',
                                 'monthly_hour' => '0;',
                                 'monthly_mday' => '1;',
                                 'monthly_min' => '0;',
                                 'monthly_warn' => '32',
                                 'path' => 'zfsstorage/dir2',
                                 'yearly' => '0',
                                 'yearly_crit' => '0',
                                 'yearly_hour' => '0;',
                                 'yearly_mday' => '1;',
                                 'yearly_min' => '0;',
                                 'yearly_mon' => '1;',
                                 'yearly_warn' => '0'
                               },
          'zfsstorage/dir3' => {
                                 'autoprune' => 1,
                                 'autosnap' => '1;',
                                 'daily' => '90',
                                 'daily_crit' => '32',
                                 'daily_hour' => '23;',
                                 'daily_min' => '59;',
                                 'daily_warn' => '28',
                                 'hourly' => '48',
                                 'hourly_crit' => '360 ',
                                 'hourly_min' => '0;',
                                 'hourly_warn' => '90',
                                 'initialized' => 1,
                                 'min_percent_free' => '10',
                                 'monitor' => 1,
                                 'monitor_dont_crit' => 0,
                                 'monitor_dont_warn' => 0,
                                 'monthly' => '6',
                                 'monthly_crit' => '35',
                                 'monthly_hour' => '0;',
                                 'monthly_mday' => '1;',
                                 'monthly_min' => '0;',
                                 'monthly_warn' => '32',
                                 'path' => 'zfsstorage/dir3',
                                 'yearly' => '0',
                                 'yearly_crit' => '0',
                                 'yearly_hour' => '0;',
                                 'yearly_mday' => '1;',
                                 'yearly_min' => '0;',
                                 'yearly_mon' => '1;',
                                 'yearly_warn' => '0'
                               }
        };

Filesystem zfsstorage/dir3 has:
     24 total snapshots (newest: 0.8 hours old)
          21 hourly
              desired: 48
              newest: 0.8 hours old, named autosnap_2016-11-07_02:00:01_hourly
          1 monthly
              desired: 6
              newest: 20.3 hours old, named autosnap_2016-11-06_06:32:23_monthly
          2 daily
              desired: 90
              newest: 2.9 hours old, named autosnap_2016-11-06_23:59:01_daily

Filesystem zfsstorage/dir1 has:
     24 total snapshots (newest: 0.8 hours old)
          2 daily
              desired: 90
              newest: 2.9 hours old, named autosnap_2016-11-06_23:59:01_daily
          1 monthly
              desired: 6
              newest: 20.3 hours old, named autosnap_2016-11-06_06:32:23_monthly
          21 hourly
              desired: 48
              newest: 0.8 hours old, named autosnap_2016-11-07_02:00:01_hourly

Filesystem zfsstorage/dir2 has:
     24 total snapshots (newest: 0.8 hours old)
          2 daily
              desired: 90
              newest: 2.9 hours old, named autosnap_2016-11-06_23:59:01_daily
          1 monthly
              desired: 6
              newest: 20.3 hours old, named autosnap_2016-11-06_06:32:23_monthly
          21 hourly
              desired: 48
              newest: 0.8 hours old, named autosnap_2016-11-07_02:00:01_hourly

Filesystem zfsstorage has:
     24 total snapshots (newest: 0.8 hours old)
          21 hourly
              desired: 48
              newest: 0.8 hours old, named autosnap_2016-11-07_02:00:01_hourly
          2 daily
              desired: 90
              newest: 2.9 hours old, named autosnap_2016-11-06_23:59:01_daily
          1 monthly
              desired: 6
              newest: 20.3 hours old, named autosnap_2016-11-06_06:32:23_monthly

So it is completely ignoring my template

I tried deleting the cache etc.. and it did the same thing.

I found that if I override all of my template settings like this in my sanoid.conf

[zfsstorage]
	use_template = marcus 
	recursive = yes
	hourly = 4
        daily = 0
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes

It now works.

**Comment by marzah** [comment]
I have found the problem
It seems that sanoid is prone to errors caused by a trailing whitespaces in sanoid.conf
In the function named init
I found that my use_template value had a trailing space which caused the array search on line 580 to not find a match for any keys
I inserted the following
$rawtemplate =~ s/^\s+|\s+$//g; ##insert at line 580

So this if statement
# override with values from user-defined templates applied to this module,
                # in the order they were specified (ie use_template = default,production,mytemplate)
                if (defined $ini{$section}{'use_template'}) {
                        my @templates = split (' *, *',$ini{$section}{'use_template'});
                        foreach my $rawtemplate (@templates) {
                                my $template = 'template_'.$rawtemplate;
                                foreach my $key (keys %{$ini{$template}}) {
                                        if (! ($key =~ /template|recursive/)) {
                                                if ($args{'debug'}) { print "DEBUG: overriding $key on $section with value from user-defined template $template.\n"; }
                                                $config{$section}{$key} = $ini{$template}{$key};
                                        }
                                }
                        }
                }

became this one
# override with values from user-defined templates applied to this module,
                # in the order they were specified (ie use_template = default,production,mytemplate)
                if (defined $ini{$section}{'use_template'}) {
                        my @templates = split (' *, *',$ini{$section}{'use_template'});
                        foreach my $rawtemplate (@templates) {
                                $rawtemplate =~ s/^\s+|\s+$//g;
                                my $template = 'template_'.$rawtemplate;
                                foreach my $key (keys %{$ini{$template}}) {
                                        if (! ($key =~ /template|recursive/)) {
                                                if ($args{'debug'}) { print "DEBUG: overriding $key on $section with value from user-defined template $template.\n"; }
                                                $config{$section}{$key} = $ini{$template}{$key};
                                        }
                                }
                        }
                }

This white space problem has probably tripped up a lot of people. All of the values in sanoid.conf should probably be checked for whitespace.

**Comment by jimsalterjrs** [comment]
Can you please issue a pull request so I can review your proposed change?

**Comment by jimsalterjrs** [comment]
Reviewed. Changed regex to strip trailing whitespace only (leading whitespace is already not processed), implemented in 1.4.12 in master.

Thank you very much for the report - this fix would have gone in _much_ sooner with a more readable report, though. It was very hard to make heads or tails of this.
