### ISSUE TITLE
Should Properties be Copied when using Syncoid?

### ISSUE THREAD

**Issue by stellarpower** [jimsalterjrs/sanoid#610]
I've performed a basic clone to an empty pool using (from memory)

`syncoid --no-syncsnap -r Source/Root Dest/Root`

however the mountpoints on the destination filesystems are all missing. Does/should syncoid copy all filesystem properties over when it is performing a copy? I can provide proper information for a report later (🎄) but before I do wanted to check if this is a mis-assumption on my part and not a bug or feature request.

Thanks :)

**Comment by phreaker0** [comment]
Not by default, but you can pass send options to include properties, see the zfs documentation: [https://openzfs.github.io/openzfs-docs/man/8/zfs-send.8.html#p,](https://openzfs.github.io/openzfs-docs/man/8/zfs-send.8.html#p,)

so in your example: 
`syncoid --no-sync-snap -r --sendoptions=p Source/Root Dest/Root`

**Comment by stellarpower** [comment]
Ah brilliant, cheers!
