### ISSUE TITLE
Support Encrypted Datasets

### ISSUE THREAD

**Issue by Ratief** [jimsalterjrs/sanoid#612]
Please add a flag to syncoid to support syncing encrypted datasets. I believe that this would be the --raw option for ZFS send.

**Comment by phreaker0** [comment]
This is already possible by passing the flag with the send options like:

     syncoid --sendoptions="w" src dst

**Comment by Ratief** [comment]
Thanks for the answer! Maybe this option should be documented. I don't see it listed anywhere.
