### ISSUE TITLE
UTC with Monthly and Yearly Snapshots

### ISSUE THREAD

**Issue by reefland** [jimsalterjrs/sanoid#617]
I have sanoid version 2.0.3 running on Ubuntu 20.04.2 with the following conf:

```

[tank/docker]
    use_template = docker

[tank/docker_projects]
    use_template = docker_projects
    recursive = yes

#############################
# templates below this line #
#############################


[template_docker]
    frequently = 0
    hourly = 36
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes

[template_docker_projects]
    frequently = 4
    hourly = 36
    daily = 30
    monthly = 15
    yearly = 1
    autosnap = yes
    autoprune = yes
```
This part is working fine.   

ISSUE:  I have a TrueNAS 12.0-U2 system doing a "PULL" replication (using TrueNAS's build in replication task to pull snapshots created by Sanoid).  This is working fine for `Hourly` and `Daily` snapshots.  However all of the `Monthly` and `Yearly` snapshots fail in the initial replication with a message like:

```
warning: cannot send 'tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly': not an earlier snapshot from the same fs
Replication cannot continue because existing snapshot
autosnap_2021-01-28_00:00:00_daily is newer than
'tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly', but has an older date
in the snapshot name. To resolve the error, rename
'tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly' with a date that is older than
autosnap_2021-01-28_00:00:00_daily or delete snapshot
'tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly' from both the source and destination.
```

To get around this, I had to rename the snapshot to be the previous day.

`sudo zfs rename tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly autosnap_2021-01-27_00:00:00_monthly`

Then that snapshot was able to be replicated.  I had to do this for all `monthly` and `yearly` snapshots.

I'm assuming, this is the source of the issue:
```
$ zfs get creation tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly
NAME                                                               PROPERTY  VALUE                  SOURCE
tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly  creation  Wed Jan 27 19:00 2021  -
```

Are snapshots being created with UTC enabled causing the problem?   It's clearly documented how sanoid uses UTC with cron.  But I can't figure out how sanoid uses UTC with systemd timers to try and disable that to use local time instead.

**Comment by gdevenyi** [comment]
#410

**Comment by phreaker0** [comment]
@reefland to run sanoid in UTC mode with systmed, look at the service file provided with the debian package: https://github.com/jimsalterjrs/sanoid/blob/master/packages/debian/sanoid.service

```
autosnap_2021-01-28_00:00:00_daily is newer than
'tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_monthly', but has an older date
in the snapshot name. To resolve the error, rename
```
can you also run, i guess it has the same creation value as the monthly snapshot, and the error message is incorrect: 
zfs get creation tank/docker_projects/certbot@autosnap_2021-01-28_00:00:00_daily

you can use syncoid for replication, which uses the creation date of the snapshots for ordering, so it will work regardless of snapshot names.

**Comment by reefland** [comment]
@phreaker0 - thanks for the reference, that helped. I'll try that.

**Comment by reefland** [comment]
It was slightly wonky for 5 hours until the previous UTC passed, once local time caught up to previous UTC time everything got back in sync and replication pulls resumed without issue.  Hopefully I don't have the error at the end of the month.

**Comment by reefland** [comment]
Switching to UTC greatly improved this issue, still fails if the snapshot name is even 1 second newer than creation time but that is more related to #552 ... would love to drop the seconds from the name.
