### ISSUE TITLE
syncoid: Bookmarks not destroyed

### ISSUE THREAD

**Issue by rbike** [jimsalterjrs/sanoid#618]
When using the "create-bookmark" option of syncoid, I would be good to destroy the old bookmark when a new bookmark is create similar to the semi-ephemeral syncoid snapshots.

**Comment by preussal** [comment]
ich lass das einfach per Cron machen.
So werden nur die Bookmarks von gestern gelöscht

`zfs list -rt bookmark POOL |grep $(date -d "yesterday" '+%Y-%m-%d') |awk '{system("zfs destroy " $1)}'`

**Comment by rbike** [comment]
I use bookmarks for a backup target that is not always available and therefore might not be updated each day, even for weeks. Destroying each day yesterdays bookmarks doesn't work for that. Anyway as bookmarks don't consume space it is not an important topic.

**Comment by beren12** [comment]
yeah you want bookmarks to hang around mostly

**Comment by phreaker0** [comment]
Bookmarks are very cheap, so it's good to keep many of them around to guarantee a successful replication. If you want to clean them up, currently you need to do this on your own, @preussal provided an example
