### ISSUE TITLE
Sanoid 2.0.3 monitor commands ignore ini settings?

### ISSUE THREAD

**Issue by darkpixel** [jimsalterjrs/sanoid#621]
In my sanoid.ini file, I have the following relevant sections:
```
[template_ignore]
autoprune = no
autosnap = no
monitor = no

[rpool]
use_template = ignore

[tank]
recursive = zfs
```

If I run ```--monitor-health``` or ```--monitor-capacity``` I will get an error about 'rpool' not existing (```--monitor-snapshots``` works fine).  It doesn't exist on the box at the moment, but I would think the ```monitor = no``` command would tell it to not try to query information about rpool.

```
root@uswuxsdbkp00:~# sanoid --monitor-health
cannot open 'rpool': no such pool
CRITICAL ZPOOL {rpool} does not exist and/or is not responding!
root@uswuxsdbkp00:~# sanoid --monitor-capacity
cannot open 'rpool': no such pool
Use of uninitialized value $line in scalar chomp at /usr/sbin/sanoid line 1270.
Use of uninitialized value $line in split at /usr/sbin/sanoid line 1271.
Use of uninitialized value $cap in pattern match (m//) at /usr/sbin/sanoid line 1275.
CRITICAL ZPOOL {rpool} does not exist and/or is not responding!
root@uswuxsdbkp00:~# 
```

**Comment by jimsalterjrs** [comment]
Do you mean sanoid.conf? Sanoid.ini isn't a thing.

**Comment by jimsalterjrs** [comment]
I don't think you can actually tell it to ignore the fact that you defined a pool that doesn't exist. Monitor-health as written pulls health data for ANY pool with a defined module; it doesn't care whether you told it to monitor that pool or not.

**Comment by darkpixel** [comment]
Yes.  I meant .conf.  I spent half the day dealing with Windows and I think I've suffered brain damage. ;)

So it sounds like it's not a bug, but an intended result.  Thanks!
