### ISSUE TITLE
Does 'sanoid --monitor-snapshots' check lack of pruning?

### ISSUE THREAD

**Issue by dlangille** [jimsalterjrs/sanoid#628]
Does `sanoid --monitor-snapshots` check lack of pruning? I think it does not.

This seems to confirm that:

```
# pruning can be skipped based on the used capacity of the pool
# (0: always prune, 1-100: only prune if used capacity is greater than this value)
prune_defer = 0
```

I monitor `zpool` capacity already. Just checking.

**Comment by jimsalterjrs** [comment]
No, `--monitor-snapshots` merely checks to make sure there are 1. fresh snapshots, as defined by policy and 2. *enough* snapshots, as defined by policy. It doesn't mind if there are "more than enough."
