### ISSUE TITLE
mbuffer on FreeBSD

### ISSUE THREAD

**Issue by lckarssen** [jimsalterjrs/sanoid#63]
I noticed that the [INSTALL file](https://github.com/jimsalterjrs/sanoid/blob/master/INSTALL) mentions that `mbuffer` has oddities. So far, the only one I have found is that it only listens on IPv6 by default. You could force it to also listen on IPv4 by adding the `-4` command line option. I guess this won't hurt other operating systems, or maybe add `-4 -6` to have both protocols (note: I didn't test that). 

Is this the only oddity or are there others?

**Comment by jimsalterjrs** [comment]
I couldn't get syncoid to work at all if it used mbuffer on FreeBSD when I tested it.

I have a very few legacy systems on FreeBSD, so it's possible that mbuffer and syncoid get along fine on 10.x or 11.x and I just don't know about it.  The issue I was encountering was that syncoid would not successfully replicate at all, whatsoever, if mbuffer was put into use.

Can @lckarssen or another FreeBSD user please clarify if syncoid is working as expected with mbuffer installed on modern FreeBSD systems?

**Comment by phryneas** [comment]
I'm currently running FreeNAS 11 and it runs fine with mbuffer present. Before that it worked with FreeNAS 9.10 as well.
In my current installation, mbuffer version is 20151002.

**Comment by jimsalterjrs** [comment]
Thank you!  I'll remove that caveat then, and close this issue. I appreciate the feedback!
