### ISSUE TITLE
Syncoid failes initial send: CRITICAL ERROR

### ISSUE THREAD

**Issue by s-a-p-i-e-n-s** [jimsalterjrs/sanoid#630]
I receive the following error trying to sync a dataset to a remote destination:
> CRITICAL ERROR:  zfs send  'array/array'@'syncoid_computer_2021-03-28:17:06:29' | pv -s 9581987901968 | lzop  | ssh   -p 22 -i /ssh/id_rsa -S /tmp/syncoid-user-user@target-1616945519 user@target ' mbuffer  -q -s 128k -m 16M 2>/dev/null | lzop -dfc | sudo zfs receive  -s -F '"'"'array/array'"'"'' failed: 256 at /usr/bin/syncoid line 464.

Host:
> /usr/bin/syncoid version 2.0.3
(Getopt::Long::GetOptions version 2.51; Perl version 5.32.1)

> zfs-2.0.4-1
zfs-kmod-2.0.4-1

Remote:
> zfs-0.8.3-1ubuntu12.7
zfs-kmod-0.8.3-1ubuntu12.6

If more information is required, please let me know what you need!

**Comment by jimsalterjrs** [comment]
Going to need to see your original syncoid command that threw that error, along with a less-mangled version of the error output (and any more lines before or after the error line shown). The critical error you're showing doesn't make any sense; that might be due to you mangling it for privacy reasons or due to the original syncoid command not making sense.

As shown, it looks like an error that would arise from `syncoid array/array array/array`... which not only makes no sense, but would have thrown a different error anyway (cowardly refusing to proceed; target exists but has no matching snapshots).

**Comment by s-a-p-i-e-n-s** [comment]
The command I executed was:
`sudo syncoid -r --sshport 22 --sshkey /ssh/id_rsa array/array user@target:array/array`

Here is the complete output I receive:
> sudo syncoid -r --sshport 22 --sshkey /ssh/id_rsa array/array user@target:array/array
[sudo] password for user: 
Enter passphrase for key '/ssh/id_rsa': 
WARN: mbuffer not available on source [local machine] - sync will continue without source buffering.
INFO: Sending oldest full snapshot array/array@syncoid_computer_2021-03-28:18:29:03 (~ 8923.9 GB) to new target filesystem:
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
1,31MiB 0:00:00 [74,9MiB/s] [>                                 ]  0%            
CRITICAL ERROR:  zfs send  'array/array'@'syncoid_computer_2021-03-28:18:29:03' | pv -s 9581987901968 | lzop  | ssh   -p 22 -i /home/user/.ssh/id_rsa -S /tmp/syncoid-user-user@target-1616948927 user@target ' mbuffer  -q -s 128k -m 16M 2>/dev/null | lzop -dfc | sudo zfs receive  -s -F '"'"'array/array'"'"'' failed: 256 at /usr/bin/syncoid line 464.
The pool as well as the dataset on the host and remote location are named `array`. This is indeed setup this way.

**Comment by jimsalterjrs** [comment]
> sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

There's your answer. Your sudo check is failing on the remote host. You'll need to use NOPASSWD in your /etc/sudoers on that host, or work around the issue in some other way, so that the `sudo zfs receive` command on that end will actually function rather than bouncing you for lack of permission.

**Comment by s-a-p-i-e-n-s** [comment]
Thank you for the explanation. I was able to resolve the issue!

**Comment by kd8bny** [comment]
I'm tracking this is dead, but in case anyone else finds their way here this totally fixed my issue. I didn't realize it was failing at the prompt.

Now that being said adding `NOPASSWD` to a user's sudo is generally ill-advised as its an easy method of privileged escalation. I would recommend to folks to have a single user account for sync and to add the privilege to the `zfs` binary alone as such

```
/etc/sudoers through visudo
...
<user> ALL=NOPASSWD: /usr/local/sbin/zfs
...
```

This way the only time that user doesn't have to enter a password on executing sudo is when using the `zfs` command

**Comment by s-a-p-i-e-n-s** [comment]
@kd8bny I resorted to giving specific permissions to my user on a per dataset basis using the `zfs allow` command.

**Comment by adam-stamand** [comment]
Looks like ghost has since deleted his account; I wonder if there's a way around elevating privileges with `zfs allow`.

In the meantime, I updated the PR @kd8bny posted since it looks like it got stalled out waiting on a typo fix: https://github.com/jimsalterjrs/sanoid/pull/670
