### ISSUE TITLE
syncoid complains about existing pool on destination uselessly because it continue with the process

### ISSUE THREAD

**Issue by slrslr** [jimsalterjrs/sanoid#642]
Hello, following is weird, it says that there is critical error, yet it continue with a note that replication MUST be on non existent dataset, yet it again continue and start transferring data without issue (that critical error at line 492 is possibly just a result of me doing Ctrl+C interrupt - i think this should also not happen and script should stop without error or say for example,  you may be able to resume the process by running same command again). It is confusing.

```
CRITICAL ERROR: Target poolb exists but has no snapshots matching with pool!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

          NOTE: Target poolb dataset is < 64MB used - did you mistakenly run
                `zfs create poolb` on the target? ZFS initial
                replication must be to a NON EXISTENT DATASET, which will
                then be CREATED BY the initial replication process.

INFO: Sending oldest full snapshot pool/dd@syncoid_hn_2021-04-23:10:52:14-GMT02:00 (~ 5906.3 GB) to new target filesystem:
^C10,4GiB 0:00:39 [ 224MiB/s] [>                                                                                                                                               ]  0% ETA 6:10:14
CRITICAL ERROR: sudo zfs send  'pool/dd'@'syncoid_hn_2021-04-23:10:52:14-GMT02:00' | pv -p -t -e -r -b -s 6341843775152 | sudo zfs receive  -s -F 'poolb/dd' failed: 2 at ./syncoid line 492.
INFO: Sending oldest full snapshot pool/ee@syncoid_hn_2021-04-23:10:53:12-GMT02:00 (~ 2662.3 GB) to new target filesystem:
^C,4GiB 0:01:40 [ 212MiB/s] [>                                                                                                                                               ]  0% ETA 3:26:06
CRITICAL ERROR: sudo zfs send  'pool/ee'@'syncoid_hn_2021-04-23:10:53:12-GMT02:00' | pv -p -t -e -r -b -s 2858654988144 | sudo zfs receive  -s -F 'poolb/ee' failed: 2 at ./syncoid line 492.
```

**Comment by jimsalterjrs** [comment]
You can't replicate directly to a pool's root dataset, so `syncoid pool poolb` fails.

But you called `syncoid` *recursively*, so although it critically fails replicating `pool` to `poolb`, it does fine replicating `pool/dd` to `poolb/dd` and so forth.

What you would typically want to do here is replicate like `syncoid -r pool poolb/pool`, resulting in `poolb/pool`, `poolb/pool/dd`, `poolb/pool/ee` and so on.

**Comment by slrslr** [comment]
Indeed, thanks, my point here was that the script output was not enough friendly to a ZFS newbie user like me or was a bit confusing.
