### ISSUE TITLE
Permissions Errors

### ISSUE THREAD

**Issue by joshaspinall** [jimsalterjrs/sanoid#653]
Hello,
I am new to Sanoid, so apologies if I've missed some previous guidance.  I cannot run a cycle of snapshot/prune due to various permission errors seen.  I am using a minimal sanoid.conf file before expanding once I am comfortable with using it.

The server I am running the commands on is running an up-to-date Ubuntu 20.04, with Sanoid installed from the repos.  The sanoid.conf below was added as described.

Assistance is appreciated!

`
[storage/docker-data]
	use_template = production
	recursive = zfs

#############################
# templates below this line #
#############################

[template_production]
	hourly = 48
	daily = 30
	monthly = 3
	autosnap = yes
	autoprune = yes
`

Errors are as follows:
`
joshua@serv-01 ~> sanoid
INFO: taking snapshots...
taking snapshot bat1/docker-data@autosnap_2021-07-07_22:56:43_monthly (zfs recursive)
cannot create snapshots : permission denied
no snapshots were created
CRITICAL ERROR: /sbin/zfs snapshot -r bat1/docker-data@autosnap_2021-07-07_22:56:43_monthly failed, 256 at /usr/sbin/sanoid line 598.
taking snapshot bat1/docker-data@autosnap_2021-07-07_22:56:43_daily (zfs recursive)
cannot create snapshots : permission denied
no snapshots were created
CRITICAL ERROR: /sbin/zfs snapshot -r bat1/docker-data@autosnap_2021-07-07_22:56:43_daily failed, 256 at /usr/sbin/sanoid line 598.
taking snapshot bat1/docker-data@autosnap_2021-07-07_22:56:43_hourly (zfs recursive)
cannot create snapshots : permission denied
no snapshots were created
CRITICAL ERROR: /sbin/zfs snapshot -r bat1/docker-data@autosnap_2021-07-07_22:56:43_hourly failed, 256 at /usr/sbin/sanoid line 598.
print() on closed filehandle FH at /usr/sbin/sanoid line 1476.
print() on closed filehandle FH at /usr/sbin/sanoid line 1477.
INFO: cache expired - updating from zfs list.
Could not write to $cache!\n at /usr/sbin/sanoid line 773.
`

**Comment by jimsalterjrs** [comment]
You need to either run Sanoid as root, or use ZFS delegation to allow your `joshua` user sufficient privileges to use `zfs snapshot` and `zfs destroy`.
