### ISSUE TITLE
"sanoid --monitor-snapshots" reports critical errors, when it shouldn't

### ISSUE THREAD

**Issue by Pajkastare** [jimsalterjrs/sanoid#654]
I have a primary zpool with hourly, daily, weekly, monthly and yearly snapshots taken automatically by sanoid, according to the `/etc/sanoid/sanoid.conf` definitions. This works as it should.

But: On a secondary system, with a backup zpool, I have defined some of these to zero. E.g.: A template that contains `hourly = 0`. In this case, sanoid prunes all the hourly snapshots as it should, but `sanoid --monitor-snapshots` still reports "CRIT: pool/path/to/dataset has no hourly snapshots at all!, CRIT: ......", and returns code 2. This is obviously not what I want, since I use Nagios to monitor this backup system.

Of course, the minimum-effort fix in my case is to replace all "= 0" with "= 1" (except frequently) in the template definitions, but I still think this is a bug.

(Not that it matters, but that dataset contains stuff I don't need to be able to restore with a high granularity, and I (ironically) thought that setting "hourly = 0" in the template would make the snapshot list in Nagios much shorter.)

**Comment by jimsalterjrs** [comment]
Take a closer look at the default backup template. The settings you didn't find are `hourly_warn` and `hourly_crit`, which control how old the most current snapshot can be before Sanoid gets worried about it.

**Comment by Pajkastare** [comment]
Excellent, thanks. I no longer think this is a bug, just a bit unintuitive, but that can be OK. :-)
