### ISSUE TITLE
Why do I have ~ 17179869183.6 GB remaining on a syncoid backup on a 12Tb pool?

### ISSUE THREAD

**Issue by malibu1966** [jimsalterjrs/sanoid#655]
I have 7.27 pool and backing up a zfs filesystem to a 12Tb pool and I recently removed a lot of files from the primary side.  when I run the syncoid backup, it tells me that I have ~ 17179869183.6 GB remaining to back up and it ran for 4 hours last night until I stopped it.  Clearly there is some problem, can anyone tell me if it is possible to fix this or must I delete the whole backup volume and start over?  I would like to avoid this since the copy will take a couple days.

The OS is arch linux, with zfs-dkms 2.0.2-1, and sanoid 2.0.3-2.

**Comment by phreaker0** [comment]
@malibu1966 this has nothing to do with sanoid/syncoid, this is more of a ZFS question. A better place for this will be https://www.reddit.com/r/zfs/. I guess you are sending all incremental snapshots so you also will transfer the deleted files and so on. Furthermore you most likely use compression. zfs send/recv will send the replication stream uncompressed by default.

syncoid will use compression by default (lzo) if available on both systems. ZFS also supports to send compressed blocks as is (see: https://openzfs.github.io/openzfs-docs/man/8/zfs-send.8.html#c) . So for example if you only want send the latest snapshot to the backup destination and keep the on disk compression you can use syncoid like (-L is for large block support):

```syncoid --sendoptions="cL" zpool zfs-recv@aaaa:zpool/backups/bbbb```

**Comment by malibu1966** [comment]
I don't understand what compression has to do with the issue.  I run syncoid with lz4 compression.

**Comment by phreaker0** [comment]
@malibu1966 The send size **estimation** of zfs will tell you the amount of data which will be transferred (before the syncoid compression takes place). If the data is compressed on zfs and you didn't instruct zfs to send the data as is (-e flag or --raw or similiar), zfs will give you the estimated uncompressed zfs send stream size.

**Comment by malibu1966** [comment]
There is no way I have 17179869183.6 GB uncompressed though.

**Comment by phreaker0** [comment]
@malibu1966 if you are sure you can submit a ticket to the openzfs project about the send estimate being wrong by a huge factor.

**Comment by malibu1966** [comment]
Let me ask one more question.. is it possible that this syncoid backup is still valid and it is just taking a long time?

**Comment by phreaker0** [comment]
@malibu1966 if syncoid finished without an error, yes. And the zfs send stream will only be as big as it needs to be.
