### ISSUE TITLE
template autosnap=no does not seem to apply recursively to children

### ISSUE THREAD

**Issue by timkgh** [jimsalterjrs/sanoid#663]
Config (based on the included examples):

```
[nas]
        use_template = nas
        recursive = yes
        process_children_only = yes

[nas/rpool_backup]
        use_template = zfsreceive
        recursive = yes
        
...

[template_nas]
        hourly = 48
        daily = 30
        monthly = 12
        yearly = 0
        autosnap = yes
        autoprune = yes

[template_zfsreceive]
        autoprune = yes
        hourly = 48
        daily = 90
        monthly = 12
        yearly = 0

        ### don't take new snapshots - snapshots on backup
        ### datasets are replicated in from source, not
        ### generated locally
        autosnap = no

        ### monitor hourlies and dailies, but don't warn or
        ### crit until they're over 48h old, since replication
        ### is typically daily only
        hourly_warn = 2880
        hourly_crit = 3600
        daily_warn = 48
        daily_crit = 60
```

`nas/rpool_backup` is used by `syncoid` to back up child datasets, e.g. target `nas/rpool_backup/home` from source `rpool/home`

The child datasets, e.g. `nas/rpool_backup/home` get snapshotted when running `sanoid --cron`. I would expect they don't get snapshots because `autosnap = no` in the template.

Is this a bug or do I need to adjust the config somehow?

**Comment by xpufx** [comment]
I am new user myself but your [nas] config is recursive and rpool_backup is a child dataset of it. I think that's what's taking the snapshots not the specific [nas/rpool_backup] settings.  Try to specify the datasets you want snapshot explicitly instaed of providing the topmost dataset/zvol.

**Comment by timkgh** [comment]
The most specific config should be honored and the most specific one has `autosnap = no` in the template so it shouldn't be snapshotted, otherwise the entire system of configuration gets very confusing.
@jimsalterjrs any thoughts here?

**Comment by timkgh** [comment]
Fixed by https://github.com/jimsalterjrs/sanoid/pull/837
