### ISSUE TITLE
syncoid: how to maintain an identical clone?

### ISSUE THREAD

**Issue by timkgh** [jimsalterjrs/sanoid#664]
Source has a pool with various datasets with their own autosnap/autoprune policies. I would like to maintain a target via syncoid that is an identical clone but without redefining the same autoprune policies on the target and manually keeping the config in sync with the source. In other words, similar to `rsync --delete`, when snapshots get pruned from the source they should also get pruned from the target next time syncoid runs.

Is this possible?

Is it a good idea or dangerous in case source snapshots are accidentally deleted?

**Comment by timkgh** [comment]
@phreaker0 do any of the new features in v2.2.0 make this easier?

**Comment by phreaker0** [comment]
@timkgh @geerlingguy this is in the latest v2.2.0 release (https://github.com/jimsalterjrs/sanoid/releases/tag/v2.2.0)
