### ISSUE TITLE
syncoid fails in Ubuntu 20.04.2 LTS kernel 5.11.0-25 due to zfs receive -s issue

### ISSUE THREAD

**Issue by timkgh** [jimsalterjrs/sanoid#665]
Ubuntu 20.04.2 LTS
Kernel: 5.11.0-25-generic #27~20.04.1-Ubuntu
zfs-0.8.3-1ubuntu12.12
zfs-kmod-2.0.2-1ubuntu5

https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1939177

`syncoid --no-resume` might work.

**Comment by phreaker0** [comment]
You are using incompatible versions of zfs user space tools and the zfs kernel module, this won't work and has nothing to do with syncoid. You need to fix you zfs installation
