### ISSUE TITLE
feature request for syncoid: detect and create deleted snapshots from target if they exist on source

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#67]
if a snapshot older than @syncoid_host_date is accidentally deleted from target but still present on source, it would be nice if syncoid could detect this and recreate it, behavind like a rsync operating on datasets instead of files.

**Comment by jimsalterjrs** [comment]
I'm not entirely sure I understand what you're asking for here.  Is this the behavior you're looking for:

~~~~
root@source:~# zfs list -rt snap test
test@1
test@2
test@3
test@4

root@target:~# zfs list -rt snap test
test@1
test@3

root@source:~# syncoid test root@target:test

root@target:~# zfs list -rt snap test
test@1
test@2
test@3
test@4
~~~~

If it is, it's highly impractical unfortunately.  ZFS cannot insert snapshots interstitially into a dataset; for the above example to work, you'd first need to roll the target all the way BACK to test@1, then let syncoid behave as it normally does to add on @2, @3, and @4 incrementally.  You can't just sort of slide @2 in between an existing @1 and @3.

It gets even worse if the source has @1-@4, and the target only has @3 - you'd have to destroy the target dataset ENTIRELY and first send a full of @1, then a stream to incrementally update with @2, @3, and @4.  Ugly, ugly, ugly.

There are also quite a few common use cases _depending_ on the ability to destroy snapshots on the source while leaving them on the target, or vice versa - you may have considerably more storage available on one end than the other and wish to keep deeper archives, etc.

**Comment by mailinglists35** [comment]
>  Is this the behavior you're looking for

Yes, that was what I was thinking. I don't know why I was under impression I could send individual snapshots as long as the source and destination are the same filesystems. I'll give it a try to be sure! :)

**Comment by mailinglists35** [comment]
ps: could you suggest an way to do the opposite? to delete snapshots on target that are no longer existing on source? I'm thinking a manual diff between `zfs list -t snapshot` run on target / source, and delete what diff says that shows only on target. Maybe could this eventually become an option in syncoid?

**Comment by jimsalterjrs** [comment]
This may not be the answer you're looking for... but if you're using sanoid on the source, just use sanoid on the target, also, with whatever retention policy you desire.  Use the built in "backup" template on the target rather than the built-in "production" template - or create your own template, just make sure to set autoprune=yes and autosnap=no, so that it WILL prune snapshots but WON'T take new ones (since new ones will be replicated in from the source).
