### ISSUE TITLE
Trouble with Initial Sync

### ISSUE THREAD

**Issue by tadr0** [jimsalterjrs/sanoid#673]
I've been using syncoid for years and like it but recently ran into trouble. Now I'm looking for help debugging an issue.

Context:
remote host: dubious
local host: spaz (where I'm running syncoid)

syncoid version: 2.0.3

perl version:
spaz:      5.30.0-9ubuntu0.2
dubious: 5.30.0-9ubuntu0.2

zfs version:
spaz:      libzfs2linux and  zfsutils-linux 0.8.3-1ubuntu12.12
dubious: libzfs2linux and  zfsutils-linux 0.8.3-1ubuntu12.12

I created a new filesystem (test of course) on dubious and tried to sync it to spaz. Then after a few tries to simplify things:
```
root@spaz:~# zfs destroy -rRf storage/dubious-replica/test; rm log.txt
root@spaz:~# /usr/sbin/syncoid --debug root@dubious:pool0/test storage/dubious-replica/test > log.txt
```
produces an output including:
cannot receive: failed to read from stream
cannot receive new filesystem stream: dataset does not exist

[log.txt](https://github.com/jimsalterjrs/sanoid/files/7079473/log.txt)

The transfer completes and the new dataset appears on spaz but it is not mounted. It can be manually mounted and looks like the right data.

Can anyone suggest anything to probe further into this?

**Comment by mhov** [comment]
I just started getting the same problem yesterday on a machine that's otherwise been running syncoid 2.0.1 like a champ for months.

**Comment by ewwhite** [comment]
> I just started getting the same problem yesterday on a machine that's otherwise been running syncoid 2.0.1 like a champ for months.

Do you have an accounting of what changed on the system?

**Comment by mhov** [comment]
> Do you have an accounting of what changed on the system?

Hey Ed! 
A reboot (due to yesterdays AWS us-west2 networking fire) was the only difference between syncoid working and not working.  My syncoid source and target are on the same local machine (ephemeral nvme -> EBS mounted volume). I've destroyed/recreated the target pool. I get the same problem doing syncoid from/to the same primary nvme zfs pool.

**Comment by mhov** [comment]
Found a core issue and a workaround.  

Per this issue https://github.com/openzfs/zfs/issues/12462 it seems the automatic ubuntu update from kernel 5.8 to 5.11 may have caused the zfs compatibility issue.  This is not a sanoid/syncoid problem.

Following the link to the ubuntu version of that bug https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1939177 they recommended adding `--no-resume` to the `syncoid` call in order to bypass the issue until there's a proper workaround.

**Comment by tadr0** [comment]
> Found a core issue and a workaround.
> 
> Per this issue [openzfs/zfs#12462](https://github.com/openzfs/zfs/issues/12462) it seems the automatic ubuntu update from kernel 5.8 to 5.11 may have caused the zfs compatibility issue. (try `uname -r` to confirm your version) This is not a sanoid/syncoid problem.
> 
> Following the link to the ubuntu version of that bug https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1939177 they recommended adding `--no-resume` to the `syncoid` call in order to bypass the issue until there's a proper workaround.

Thanks for this info and thanks to the sanoid/syncoid team for the --no-resume option. This work-around worked for me.

**Comment by Darkyere** [comment]
Plz. go to this page and vote this is a problem for you too if u read this post.

[When using HWE, zfs-kmod and zfs user tools versions must match](https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1939210)

**Comment by callumgare** [comment]
I'm also getting this issue but I'm running Proxmox (which I believe is downstream of debian or something like that). The kernel of the server I'm sending from is `5.11.22-7-pve` and the receiving server is `5.4.128-1-pve`.

**Comment by jimsalterjrs** [comment]
I can personally confirm that out-of-sync libraries and utilities will cause zfs resume to be broken, and specifically, any `zfs receive -s` to fail (while `zfs receive` without `-s` works).

You can mitigate with --no-resume, but you'll still have a pretty broken system and there's no guarantee you won't encounter further problems. It's better to make sure your libraries and utilities aren't out of sync in the first place. On the machine I personally encountered this issue on, `apt-update ; apt install zfsutils-linux` was sufficient to get the job done; the issue I believe related to either the kernel or the utilities being flagged as a security upgrade while the other half was not so flagged, resulting in `automatic-updates` patching one side without patching the other.
