### ISSUE TITLE
syncoid doesn't remove snapshots on remote

### ISSUE THREAD

**Issue by alchemyx** [jimsalterjrs/sanoid#677]
Hi,

I am not sure if it is my misunderstanding of --force-delete command or there is missing functionality. When syncoid sends over snapshots it never tries to remove the ones that are no longer on source but still present on remote. How to achieve that? To have same set of snapshots on local and remote?

Kind regards,
Michał

**Comment by toby11** [comment]
@alchemyx  did you work out an answer to this?

**Comment by danboid** [comment]
I'm a new sanoid user and I was wondering about this. I expected the pruning of deleted snapshots to happen automatically so it would be cool if this could be fixed in the future so that the user doesn't need to configure sanoid too, just for this.

**Comment by jimsalterjrs** [comment]
Nope. Syncoid is not for deleting snapshots, it's for replicating them. It is not and never will be a pruning tool. "Use sanoid on both ends" (or some other tool which prunes snapshots) is the correct answer.

**Comment by heeplr** [comment]
> Nope. Syncoid is not for deleting snapshots, it's for replicating them. It is not and never will be a pruning tool. 

Admittedly I had the same misconception of "sync" implying to maintain the same state at both ends which would include removing datasets that don't exist on the other side (similar to `rsync --delete ...`)

> "Use sanoid on both ends" (or some other tool which prunes snapshots) is the correct answer.

I added a [section to the syncoid wiki page](https://github.com/jimsalterjrs/sanoid/wiki/Syncoid#pruning) to spare future confusion for anyone finding this.

**Comment by danboid** [comment]
> > Nope. Syncoid is not for deleting snapshots, it's for replicating them. It is not and never will be a pruning tool.
> 
> Admittedly I had the same misconception of "sync" implying to maintain the same state at both ends which would include removing datasets that don't exist on the other side (similar to `rsync --delete ...`)
> 
> > "Use sanoid on both ends" (or some other tool which prunes snapshots) is the correct answer.
> 
> I added a [section to the syncoid wiki page](https://github.com/jimsalterjrs/sanoid/wiki/Syncoid#pruning) to spare future confusion for anyone finding this.

Thanks but it still doesn't address the question "can syncoid prune snapshots not made with sanoid?" eg if you're using zfs-auto-snapshot or LXD to create the snapshots, for example. My experience says no, you have to use something like zfs-prune-snapshots instead if they don't conform to sanoids snapshot naming format but hopefully @jimsalterjrs  will correct me if I'm wrong about that.

**Comment by heeplr** [comment]
> Thanks but it still doesn't address the question "can syncoid prune snapshots not made with sanoid?"

True, but that's not necessarily within the scope of the sanoid documentation.

> if they don't conform to sanoids snapshot naming format

iirc the naming scheme can be altered but I'm not familiar enough with sanoid to tell or document. I also wouldn't expect syncoid/sanoid to prune 3rd party snapshots. If you find a way, it would be nice if you added it to the wiki.

**Comment by danboid** [comment]
> True, but that's not necessarily within the scope of the sanoid documentation.

I strongly disagree. This is one of the few things the user needs to know about sanoids autoprune feature. It can be answered in a sentence with a link to [zfs-prune-snapshots](https://github.com/bahamas10/zfs-prune-snapshots) if the answer is definitely no.
