### ISSUE TITLE
Remove local snapshots after syncing to remote machine

### ISSUE THREAD

**Issue by Alexandero89** [jimsalterjrs/sanoid#687]
I dont think this is possible, but i still wanted to ask.

Lets assume i have 20 hourly snapshots and 3 monthly snapshots kept by sanoid.
I sync everything via syncoid to a remote ssh machine.

Now i would like to keep all snapshots on the remote machine, but delete all or most of them locally after syncing (so i have more free space available).

Would this be possible?
Thanks.

**Comment by redmop** [comment]
Run sanoid on the remote host, set autosnap = off and autoprune=on and set the prune schedule you would prefer.

**Comment by jimsalterjrs** [comment]
@redmop gave the correct answer. Note that you can look at the included "backup" and "hotspare" templates as examples of the sort of policy you'd typically set for a backup target.
