### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by timkgh** [jimsalterjrs/sanoid#692]
It doesn't appear to have any significant recent commits and issues are not getting answers.

Is it still safe to use or should we look for alternatives?

I appreciate @jimsalterjrs' articles on Ars Technica :)

**Comment by jimsalterjrs** [comment]
It's active, it's just mature. We generally do bursts of commit approvals two or three times a year.

Folks who desperately need proposed features earlier than that sometimes run off of forks sitting in the originator's github repo, and that's fine too. =) At this point my biggest goal by far is not "adding more features as quickly as I can" it's "making sure this continues to be a stable and reliable tool," which I feel is better served with a less-frequent update schedule.
