### ISSUE TITLE
Problems sending new filesystem: cannot receive: invalid stream (bad snapshot name)

### ISSUE THREAD

**Issue by pquan** [jimsalterjrs/sanoid#704]
I'm trying to initialize a new backup on a remote server. 
The initial sync fails with an error of "cannot receive: invalid stream (bad snapshot name)"
The ` '"'"'tank/vm/vm-134-disk-0'"'"' ` escapes look suspicious.
If I manually send the filesystems once, then syncoid is able to replicate after the fact.

The error I get is here: 

```
NEWEST SNAPSHOT: autosnap_2021-12-15_14:51:51_hourly
INFO: Sending oldest full snapshot tank/vm/vm-134-disk-0@autosnap_2021-12-15_14:51:51_monthly (~ 4.9 GB) to new target filesystem:
cannot receive: invalid stream (bad snapshot name)
 256KiB 0:00:00 [13.8MiB/s] [>                                                                                                                                          ]  0%
mbuffer: error: outputThread: error writing to <stdout> at offset 0x14000: Broken pipe
mbuffer: warning: error during output to <stdout>: Broken pipe
CRITICAL ERROR: ssh     -S /tmp/syncoid-root@s20-1639576431 root@s20 ' zfs send  '"'"'tank/vm/vm-134-disk-0'"'"'@'"'"'autosnap_2021-12-15_14:51:51_monthly'"'"' | lzop  | mbuffer  -q -s 128k -m 512M 2>/dev/null' | mbuffer  -q -s 128k -m 512M 2>/dev/null | lzop -dfc | pv -p -t -e -r -b -s 5210760480 |  zfs receive   -F 'backup6/enc/local/s20/tank/vm/vm-134-disk-0' failed: 256 at /usr/sbin/syncoid line 492.
```

And the command I run is

` syncoid --no-resume --recursive --skip-parent --no-sync-snap --mbuffer-size=512M remote:<poo> local/pool `

This is using debian buster (proxmox) and both syncoid 2.0.3 and 2.1.0 compiled from source.

Any ideas?

**Comment by jimsalterjrs** [comment]
Nope, this is a new one on me.

I doubt the escapes are the problem. But you can confirm whether they are or are not the problem by running the command manually WITHOUT the escapes. That entire command line shown is exactly what syncoid is actually doing, so you can troubleshoot by copying the command and running it directly, without benefit of syncoid.

> remote:<poo> local/pool

I assume "remote:<poo>" is some sort of obfuscation?

**Comment by pquan** [comment]
Jim your answer was really quick. 

It's new to me as I've been using syncoid for years. The remote: is the remote server and the local/pool is the local filesystem where I want the backup to appear (the backup server is connecting to the remote server).

I was tricked this time. A plain zfs send/receive was working but piped trough pv/mbuffer/lzop etc I was getting the error. 

I've been fighting this issue most of today and it turned out to be something very silly. One of the servers had an unaligned shared library. I got suspicious when zpool status was complaining of a different data structure size (!).

So the issue was mine and nothing wrong with syncoid !

Thank you, and sorry for the inconvenience.
