### ISSUE TITLE
syncoid defunct processes

### ISSUE THREAD

**Issue by vphan13** [jimsalterjrs/sanoid#71]
I'm running zfs on CentOS 7.2 (3.10.0-327.28.2.el7.x86_64)
The source zfs server is running zfs version 0.6.5.8
The destination host is running zfs zfs-0.7.0-rc3
I'm able to use syncoid to push my snapshots from the source to the destination host.  However the syncoid process does not seem to exit properly, it leaves socket files in /tmp directory and ends up in a defunct state, after 24 hours I have lots of defunct syncoid processes and socket files in the /tmp directory

My sanoid.conf (source)

[zfs_source/archdata]
        use_template = template_source_archdata
        recursive = yes
        hourly = 24
        daily = 14
        monthly = 3
        yearly = 1
        autosnap = yes
        autoprune = yes

The sanoid.conf on the target server is identical, except autosnap is turned off

My syncoid command (run from cron), I'm only testing a child dataset for replication at the moment

1 * * * *       /opt/software/sanoid/syncoid zfs_source/projdata/0716 root@target_server:zfs_target/projdata/0716

[root@source_server ~]# ps -ef |grep defunct
root      4682  4680  0 10:01 ?        00:00:00 [syncoid] <defunct>

[root@source_server ~]# ls -tlra /tmp/ | grep syncoid
srw-------   1 root root      0 Feb 28 10:01 syncoid-root-root@target_server-1488304861

The snapshots are replicated, but this seems to be a bug, perhaps it is caused by the different versions of zfs?

**Comment by jay-lark** [comment]
I'm seeing the same issue as well and it seems to greatly slow down the replication as these leftover processes build up.  Once I clear them all out my transfer return to full speed again.

**Comment by ewwhite** [comment]
I modify the syncoid script to set SSH ControlMaster not to persist these connections:

Changing:

```open FH, "$sshcmd -M -S $socket -o ControlPersist=yes $sshport $rhost exit |";```

to

```open FH, "$sshcmd -M -S $socket -o ControlPersist=no $sshport $rhost exit |";```

**Comment by jay-lark** [comment]
Thanks!  That definitely got rid of the old sessions staying around.  Unfortunately it didn't solve our problem of the replication slowing down over time.

**Comment by jimsalterjrs** [comment]
Updating this to ControlPersist=1m to cause the master session to die after the initial flurry of ssh commands.
