### ISSUE TITLE
Feature Request - Be able to run a seperate sanoid.timer and sanoid.service

### ISSUE THREAD

**Issue by Darkyere** [jimsalterjrs/sanoid#711]
I would like to ask for the enhancement to be able to make a custom `sanoid.timer` and `sanoid.service` that would point to another `/etc/sanoid/sanoid.conf` file.

Etc.

```
sanoid-custom.timer
sanoid-custom.service
/etc/sanoid/sanoid-custom.conf
```

In a way where it would be possible to take a template of `sanoid.timer` and `sanoid.service` and name it what ever one would want.

With the possibility in the sanoid-custom1.timer to choose a desired timer function.
And sanoid-custom1.service to point to a custom `/etc/sanoid/sanoid-custom1.conf`

----

The reason for this is I have a server where i got a WD My Book 8TB connected.

What's great about that HDD is that it power off the device after 1 hour.

But the problem is every 15 minutes `sanoid.timer` and `sanoid.service` actually keeps the drive awake by checking the latest snapshots.

I had to edit `sanoid.timer` to only do it once at 00:00. To keep the drive from spinning.

I all so got another Drive where i have Docker containers on and that one i would like to work as normal checking for snapshots to create/cleanup.

But since there is only one `sanoid.timer` and `sanoid.service` and thatit cant point to another `sanoid.conf` file.
I cant make a separate `sanoid-custom.timer` and `sanoid-custom.service` that would read its separate `/etc/sanoid/sanoid-custom.timer`

----

I really hope u would make this feature.
I would guess for other reasons than mine, that people could make use of separate `services` and `sanoid.conf` files.

Ty for listening and best ragards,
Darkyere

**Comment by ezr** [comment]
I haven't tested it, but there is a `--configdir` option that let's you specify a different location for the config file. 

So your config file could have this path: `/etc/sanoid/custom/sanoid.conf`

Then sanoid-custom.service would look like:
```[Unit]
Description=Snapshot ZFS Pool
Requires=zfs.target
After=zfs.target
Wants=sanoid-prune.service
Before=sanoid-prune.service
ConditionFileNotEmpty=/etc/sanoid/custom/sanoid.conf

[Service]
Environment=TZ=UTC
Type=oneshot
ExecStart=/usr/sbin/sanoid --configdir=/etc/sanoid/custom/ --take-snapshots --verbose
```
sanoid-prune.service would need a similar change.

This would allow you to make a custom sanoid.timer and sanoid.service that would point to different sanoid.conf file.

**Comment by phreaker0** [comment]
Like @ezr already said, this is already possible by specifying different "configdir", "cache-dir" and "run-dir" arguments.

**Comment by Darkyere** [comment]
Could i maybe ask for some more documentation on how to set it up proberly in the WiKi.

The thing is i have one ZFS pool where i need hourly snapshots and so on.

And i got another drive specifically bought be cause the drive will shutdown completely when it hasn't been used for 30 minutes. But every hour it spins up the drive to make snapshots.

I have done my best to set it up with the before mentioned command but i would like to make sure it only snapshots once every day so the drive never spins up more than once a day.

To keep it alive for longer.

So very basically the idea is the drive never makes a snapshot, prune or anything similar until it is 00:00 or 12AM preventing the drive spinning up unnecessarily.

Best regards,
Darkyere

**Comment by phreaker0** [comment]
@Darkyere unfortunately this will only help your use case if you export your idle pool. Because right now sanoid will list all existing snapshots over all pools if invoked. So even if you don't specify you "idle" pool in the sanoid config, it will get queried and therefore will wake up.

**Comment by brevilo** [comment]
You could run `sanoid` only if, say, `hdparm -C <dev>` returns `active/idle` in your customized service (just modify `ExecStart`). If you keep it triggered each 15 mins (the default) it'll create snapshots only when you actually used the drive anyway. Just make sure that your spin-down threshold is longer than your minimum snapshot interval.
