### ISSUE TITLE
sanoid --monitor-snapshots exit code

### ISSUE THREAD

**Issue by frainz-de** [jimsalterjrs/sanoid#715]
Hi,

I'm sorry if this is already documented somewhere but in any case I couldn't find it. I'm in the process of setting up a very simple monitoring for my NAS using healthchecks.io using a cron job:

`/usr/sbin/sanoid --monitor-snapshots && curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/[...] `

This only works if sanoid returns a non-zero exit code when it isn't happy. I expect it does but could not confirm it using the documentation

**Comment by Pajkastare** [comment]
From the `sanoid --help` output, it says "`in a Nagios compatible format`".
So you should look at the Nagios documentation, for example [here](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html).

In short: Return code 0 means that all is OK.

**Comment by jimsalterjrs** [comment]
yep. sanoid --monitor-snapshots and sanoid --monitor-health both exit 0 for OK, 1 for WARN, 2 for CRIT, 3 for ERROR.
