### ISSUE TITLE
Add --quiet to sanoid as well

### ISSUE THREAD

**Issue by secabeen** [jimsalterjrs/sanoid#72]
We should have a --quiet for sanoid as well as syncoid.  With the recommended run of every minute, sanoid creates cron output every run.  I can create a pull request for this if you like.  The main logic change is this one, to line 49:
`if (!$args{'quiet'}) { $args{'verbose'} = 1; }`
plus the usual addition of --quiet to the list of valid args.

**Comment by secabeen** [comment]
I created a pull request.  Let me know if it shows any issues.

**Comment by jimsalterjrs** [comment]
merged.
