### ISSUE TITLE
Timestamps wrong?

### ISSUE THREAD

**Issue by hyperbart** [jimsalterjrs/sanoid#720]
Running Ubuntu 20.04.3 LTS
Sanoid 2.1.0 (installed yesterday)

sanoid.conf
`
[MyPool/MySet]
        use_template = shorthigh

#############################
# templates below this line #
#############################

[template_shorthigh]
        frequently = 12
        frequent_period = 5
        hourly = 72
        daily = 31
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes
`

/etc/timezone
`Europe/Brussels`

Results in snapshots as defined, however the time stamps are 1 hour off.
This makes for a "broken" chain since syncoid snapshots are correctly timestamped (an autosnap 08:00 is in fact created at 09:00)

`root@nas:~# zfs list -t snapshot
NAME                                                                        USED  AVAIL     REFER  MOUNTPOINT
MyPool/MySet@autosnap_2022-02-16_19:09:43_daily                          0B      -     30.8G  -
MyPool/MySet@autosnap_2022-02-16_19:09:43_hourly                         0B      -     30.8G  -
MyPool/MySet@autosnap_2022-02-16_20:00:25_hourly                      55.1M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-16_21:00:32_hourly                      77.6M      -     30.8G  -
MyPool/MySet@autosnap_2022-02-16_22:00:11_hourly                      64.9M      -     30.8G  -
MyPool/MySet@autosnap_2022-02-16_23:00:08_hourly                      29.4M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_00:00:15_daily                          0B      -     30.8G  -
MyPool/MySet@autosnap_2022-02-17_00:00:15_hourly                         0B      -     30.8G  -
MyPool/MySet@autosnap_2022-02-17_01:00:10_hourly                      46.0M      -     30.8G  -
MyPool/MySet@autosnap_2022-02-17_02:00:22_hourly                      42.5M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_03:00:07_hourly                      50.4M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_04:00:04_hourly                      44.0M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_05:00:20_hourly                      48.8M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_06:00:37_hourly                      48.7M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_07:00:15_hourly                      48.5M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_07:45:10_frequently                  40.0M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_08:00:26_hourly                         0B      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_08:00:26_frequently                     0B      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_08:15:15_frequently                  12.5M      -     30.7G  -
MyPool/MySet@syncoid_backupper_2022-02-17:09:16:24-GMT01:00           15.4M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_08:30:23_frequently                  23.8M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_08:45:20_frequently                  55.1M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_09:00:05_hourly                         0B      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_09:00:05_frequently                     0B      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_09:15:31_frequently                  54.5M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_09:30:13_frequently                  48.5M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_09:45:10_frequently                  42.7M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_10:00:03_hourly                         0B      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_10:00:03_frequently                     0B      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_10:15:02_frequently                  33.2M      -     30.7G  -
MyPool/MySet@autosnap_2022-02-17_10:30:35_frequently                  25.4M      -     30.7G  -`

What is causing this? Am I doing something wrong?

**Comment by phreaker0** [comment]
you are using UTC as timezone most likely. Look at the systemd/cron timer command.

**Comment by hyperbart** [comment]
timedatctl shows the following:

```
root@nas:~# timedatectl
               Local time: Thu 2022-02-17 12:36:38 CET
           Universal time: Thu 2022-02-17 11:36:38 UTC
                 RTC time: Thu 2022-02-17 11:36:38
                Time zone: Europe/Brussels (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by phreaker0** [comment]
@hyperbart doesn't matter. I guess it's overridden. If you use systemd show your unit files with:

`systemctl cat sanoid.service`

I guess you will see a line like "Environment=TZ=UTC"

**Comment by hyperbart** [comment]
Ah, thanks for explaining/pointing me to that. I am not familiar with that aspect.
Documentation recommends UTC to prevent problems with DST, what can one expect as type of problems? At DST time change a snapshot which is "same hour" but in reality differs 1h?

**Comment by phreaker0** [comment]
@hyperbart DST is handled, at least in our timezone it works as expected. You can drop the TZ=UTC line if you want local time snapshots (I for example use it for a user facing file server where the local time is needed to be user friendly)

**Comment by hyperbart** [comment]
Ok, @phreaker0 , thanks
After dropping the line (just do a systemctl vi sanoid.service?) I'll have to do the following?
systemctl enable sanoid.timer

Or will it pick it up transparantly after editing the sanoid.service file?

**Comment by Germano0** [comment]
@hyperbart after you complete the edit, run
```
# systemctl daemon-reload
```
