### ISSUE TITLE
Sanoid no longer runs cron verbose if called without arguments

### ISSUE THREAD

**Issue by Hooloovoo** [jimsalterjrs/sanoid#721]
Hello,

It looks to me as though 
https://github.com/jimsalterjrs/sanoid/pull/463
inadvertently stopped sanoid from running in `--cron` `--verbose` mode if called without arguments.

There is a section in the code:
```
# If only config directory (or nothing) has been specified, default to --cron --verbose
if (keys %args < 2) {
	$args{'cron'} = 1;
	$args{'verbose'} = 1;
}
```

Two additional elements were added into %args by the PR before this block, so now %args is always at least 3 by the time it reaches this code.

**Comment by phreaker0** [comment]
Fixed with #819
