### ISSUE TITLE
`syncoid -r` doesn't use `zfs snapshot -r` to get consistent snapshots

### ISSUE THREAD

**Issue by Dieken** [jimsalterjrs/sanoid#725]
According to output of `syncoid -r SRC DST --debug`,  syncoid doesn't use `zfs snapshot -r` to get consistent snapshots across zfs dataset hierarchy.

```
$ syncoid --version
/usr/bin/syncoid version 2.1.0
(Getopt::Long::GetOptions version 2.52; Perl version 5.34.0)
```

**Comment by jimsalterjrs** [comment]
It does if you use recursive=zfs instead of recursive=yes in your policy definitions. Check the sample sanoid.conf in this repo for example and discussion of why that's not the default.

**Comment by Dieken** [comment]
@jimsalterjrs   This issue is about `syncoid`, not `sanoid`.

https://github.com/jimsalterjrs/sanoid/blob/master/syncoid#L24

Option `recursive` doesn't accept a value, its pod also says no value for `--recursive`.
