### ISSUE TITLE
Feature Request:  prune snapshots more agressively if free diskspace is too low 

### ISSUE THREAD

**Issue by devZer0** [jimsalterjrs/sanoid#726]
hello, 

i'm using saniod + syncoid with proxmox for local snapshots and replication. 

I have applied this settings to sanoid:

	frequently = 16
	hourly = 24
	daily = 1
	monthly = 0
	yearly = 0
	autosnap = yes
 	autoprune = yes
 	

on the replicated dataset, i have different snapshot policy, which keeps snapshots for much longer, as there is much more diskspace available.

sometimes, when there is heavy activity in one of the VMs (build system / CI) , the diskspace is filling up quickly on the proxmox server and we had out of diskspace conditions for at least two times.

what about some option in sanoid to make sure disk fillup is avoided, i.e. sanoid could prune more agressively (i.e. delete oldest snapshots) to make sure there always is enough diskspace, i.e. "free space of %x" should be considered more important than having local snapshots ( as they are replicated anyway...)

**Comment by phreaker0** [comment]
@devZer0 such an option already exists: https://github.com/jimsalterjrs/sanoid/blob/d863c35cac808bc79162f9b4233be54141642d89/sanoid.defaults.conf#L55-L56

**Comment by devZer0** [comment]
doesn't that mean no snapshots will be pruned unless the specified limit is reached and if it's being reached, then only all snapshots which are NOT in the retention policy will be destroyed (but no more) ?

what i need is that it should prune even more snapshots, i.e. if policy tells "keep 100 frequent snapshots" it should prune some more (if not all of them) until %freespace is being reached. i.e. %free should be more important then keeping a snapshot....

**Comment by jimsalterjrs** [comment]
> %free should be more important then keeping a snapshot

Sanoid's primary mission is preservation of data, not destruction of it. If we did what you're asking for, you could wake up one morning with a catastrophic loss of data and no snapshots to recover from--for example, if you got nailed with ransomware that encrypted all the data on your drive, thereby eating all your free space, but then "helpfully" your proposed system nukes all the snapshots that you could otherwise have recovered from in order to make more room for the ransomware.

Sorry, this one just plain isn't going to happen. Too dangerous.

**Comment by devZer0** [comment]
i'd like to give a comment on this, regarding dangerous.

if you have replication with syncoid and have a different prune policy on the target, i don't see the point why pruning more agressively on the source is too dangerous.

you could define some "minimum and maximum snapshot cound" and sanoid could prune appropriately to have a good weight between snapshot cound and diskspace usage

i need to reduce to one snapshot/day on all source datasets for security reason and have 31 days of snapshots on the replication target - i would like to have as much daily snapshots on the source datasets, too, but it's too dangerous that some heavy disk activity for some days will eat up all diskspace. 

i think this "feature" could need some more investigation, i don't find it too dump. i respect your considerations, but also get my point....
