### ISSUE TITLE
Add configuration validation

### ISSUE THREAD

**Issue by giomf** [jimsalterjrs/sanoid#730]
I would like sanoid to run only if the configuration is valid.

I have just noticed an error in the transfer of syncoid and looked frightened on my backup server. As it happened sanoid created snapshots on the backup server which in the end caused syncoid to fail.
After a first look into my sanoid.conf I couldn't see anything wrong.
After using `sanoid --debug` I noticed that` autosnap = 'no '` was set. It looks like I put a space after the value and sanoid read the setting and created snapshots without warning. I don't know what value sanoid actually uses but I see that sanoid creates snapshots.
After I removed the space `autosnap = 0` was set and no more snapshots were created.

I think sanoid should at least warn that a setting could not be read properly. But I would much rather that sanoid does not start at all.

**Comment by datenheim** [comment]
I would second that. Especially for binary options checking the validity of values is straight forward.

**Comment by phreaker0** [comment]
Fixed with #837
