### ISSUE TITLE
syncoid: progress bar frequently reaches 101% to 103%

### ISSUE THREAD

**Issue by danboid** [jimsalterjrs/sanoid#731]
When syncing a large number of datasets using syncoid under Ubuntu 20.04, I have seen the progress bar reach 101%, 102% and 103% several times.

**Comment by jimsalterjrs** [comment]
Yep, that's going to happen. Syncoid uses the zfs send "dry run" feature to get an estimate of what the total send size will be, and that's not entirely accurate. When doing replication with very small amounts of change, you can get considerably wilder results than that--sometimes 200% or more (but the whole thing is over in two or three seconds, so it's not exactly a problem).

You can try filing an upstream bug in OpenZFS about zfs send dry run not reporting 100% accurate numbers if you like, but there's nothing we can do about it here.

**Comment by danboid** [comment]
OK, thanks for explaining Jim!
