### ISSUE TITLE
syncoid breaks bash while read loops

### ISSUE THREAD

**Issue by toddjames** [jimsalterjrs/sanoid#74]
[This is a pretty good explanation](http://stackoverflow.com/questions/13800225/shell-script-while-read-line-loop-stops-after-the-first-line) of an issue that I'm experiencing with syncoid.

Consider the bash script:

```
#!/bin/bash
# dummy function - the actual logic is more complex with dataset selection.
get_disks() {
    echo "pool01/vm-100-disk-1"
    echo "pool01/vm-101-disk-1"
    echo "pool01/vm-102-disk-1"
}
while read -r line; do
    syncoid "--quiet" "${line}" "root@10.0.0.2:pool01/backups/${line}"
done <<< "$(get_disks)"
```

Only the first iteration will execute, and thus only one dataset is replicated. SSH within Syncoid will consume all other input from STDIN (which is used to iterate over the loop).

After some research, I was able to fix this on my side by appending `</dev/null` to the end of the Syncoid command.

However, I did not expect this behavior. From my perspective, I should be able to call Syncoid without worrying about its internal operations affecting my script. No worries if you can't fix it - I have a workaround.

I don't know that this is a trivial fix for you, either. The StackOverflow posts suggest using -n with SSH to ignore STDIN, but if you're piping `zfs send` to SSH, that's probably not a good idea.

**Comment by jimsalterjrs** [comment]
I don't think I see a pressing need for `syncoid` in bash loops since syncoid can already be used recursively.

I'm willing to accept PRs if you or somebody else wants to tackle this, but I'm #wontfix-ing it for now.  Thank you for the report though!
