### ISSUE TITLE
Wront percentage calculation

### ISSUE THREAD

**Issue by quotengrote** [jimsalterjrs/sanoid#750]
Hi, 

i am moving all my Datasets between two Pools and the percentage caculation for syncoid seems wrong.

```
root@pve2:~# syncoid hdd_data_raidz hdd_data_raidz_neu --skip-parent --recursive
INFO: Sending oldest full snapshot hdd_data_raidz/amd@autosnap_2022-04-01_00:00:02_monthly (~ 123.7 GB) to new target filesystem:
 123GiB 0:14:18 [ 147MiB/s] [===[...]=====>] 100%            INFO: Updating new target filesystem with incremental hdd_data_raidz/amd@autosnap_2022-04-01_00:00:02_monthly ... syncoid_pve2_2022-06-14:12:35:11 (~ 299.4 MB):
 453MiB 0:00:28 [16.0MiB/s] [===[...]=====>] 151%            INFO: Sending oldest full snapshot hdd_data_raidz/archiv@autosnap_2022-06-01_00:00:01_daily (~ 45.4 GB) to new target filesystem:
45.5GiB 0:13:57 [55.6MiB/s] [===[...]=====>] 100%            INFO: Updating new target filesystem with incremental hdd_data_raidz/archiv@autosnap_2022-06-01_00:00:01_daily ... syncoid_pve2_2022-06-14:12:50:04 (~ 280.7 MB):
 545MiB 0:01:09 [7.84MiB/s] [===[...]=====>] 194%            INFO: Sending oldest full snapshot hdd_data_raidz/backup@autosnap_2022-04-01_00:00:03_monthly (~ 38.4 GB) to new target filesystem:
```

How can syncoid send more than 100%? Or does certain Blocks get resend?

Cheers
mg

**Comment by oddlama** [comment]
Sanoid takes a size estimate from `zfs send --dryrun`. These estimates are only rough estimates (often a lower bound) which is why you frequently see values >100%. This is expected.

**Comment by quotengrote** [comment]
Ah, i get it, sounds reasonable.

**Comment by fallingcats** [comment]
There is a still a bug lingering here: If replication was interrupted after the 100% mark a subsequent sync will underflow and calculate a completely wrong number, ```~ 17179869183.5 GB remaining``` in my case instead while being ~26GB over the original estimation. 
Using v2.0.3
(If you want me to open a new bug report instead I can do that)
