### ISSUE TITLE
Add exit codes to Syncoid, in case of different errors

### ISSUE THREAD

**Issue by Darkyere** [jimsalterjrs/sanoid#754]
I am trying to create a `Python3` script that uses `Pexpect` to execute a list of DataSet's to be send/received.

The thing is i can get an exit code from the command spawned with `Pexpect.`

But `Syncoid` doesnt seems to give a exit code in certain examples.

I tried for an instance to force an error by using `Syncoid` to send/receive a dataset that doesnt exit.

```
Enter passphrase for key '/dest/to/keyfile':

WARN Skipping dataset (dataset no longer exists): Storage/dontexist...
----
This is the Syncoid Exit status   :    0 This is the SynCoid signal Status    :    None
----
```

It would be helpfull if `Syncoid` would give different exit codes in case of errors.
So one could now something went wrong in a gived `Syncoid` Send/Receive case.

And then one could look through any given self created logs for the error.

Ty for reading and hope u can implement it,
Darkyere

**Comment by phreaker0** [comment]
syncoid will return exit code 1 on warning level errors and exit code 2 if there are serious errors.

In this case there is a bug which will be fixed by the linked PR. In case of recursive replications, vanished datasets will be skipped but this also affected the specified dataset which is wrong.
