### ISSUE TITLE
[Feature request] New prefix for sanoid temporary files

### ISSUE THREAD

**Issue by Jeroen0494** [jimsalterjrs/sanoid#758]
Hi,

Would it be possible to change the prefix of the temporary files created by sanoid? Right now the name is completely random, which creates an issue with my AppArmor profiles:
```
ALLOWED zfs file_inherit /tmp/ovCBaP5lW2 comm=zfs requested_mask=wr denied_mask=wr
ALLOWED zfs file_inherit /tmp/cry4oLKKlT comm=zfs requested_mask=wr denied_mask=wr
ALLOWED zfs file_inherit /tmp/a9NLgjEPMt comm=zfs requested_mask=wr denied_mask=wr
ALLOWED zfs file_inherit /tmp/ySXge1j_Qt comm=zfs requested_mask=wr denied_mask=wr
ALLOWED zfs file_inherit /tmp/Bes9P8a8MI comm=zfs requested_mask=wr denied_mask=wr
ALLOWED zfs file_inherit /tmp/xbzGn5MIAQ comm=zfs requested_mask=wr denied_mask=wr
```

In order for ZFS to read these files, I would have to create a rule like the following which allowed reading of all files directly under the `/tmp/` directory:
```
/tmp/* rw,
```

If sanoid were to use a prefix like so:
```
/tmp/sanoid_ovCBaP5lW2
/tmp/sanoid_a9NLgjEPMt
```

I would be able to create a more specific AppArmor rule:
```
/tmp/sanoid_* rw,
```

**Comment by Jeroen0494** [comment]
@jimsalter any change you could take a look at this issue? Should be a simple enough fix.

**Comment by phreaker0** [comment]
@Jeroen0494 according to your provided log output, sanoid doesn't create those files but zfs does.

**Comment by Jeroen0494** [comment]
Huh, how'd you come to that conclusion? The log you see is from AppArmor, where ZFS is trying to read these temp files because is creates the snapshots. The temp files are created by Sanoid, your conclusion is wrong.

**Comment by phreaker0** [comment]
@Jeroen0494 sanoid doesn't create temporary files in /tmp/, at least I couldn't find it in the source code. And furthermore doens't call the zfs binary with such files as arguments. I also don't see those files on my systems with sanoid.

**Comment by jimsalterjrs** [comment]
Sanoid does not create files in /tmp. Only the cache files, which by default live under /var (and don't use randomly generated names either).

Those might possibly be SSH socket files created by syncoid, though. I'd have to check the source to be certain.

**Comment by jimsalterjrs** [comment]
Nope. Not syncoid SSH sockets either; those are created in tmp but already use prefixes:

~~~~
		$socket = "/tmp/syncoid-$rhost-" . time() . "-" . int(rand(10000));

		open FH, "$sshcmd -M -S $socket -o ControlPersist=1m $args{'sshport'} $rhost exit |";
~~~~

Sorry friend, you appear to be barking up the wrong tree in terms of those tmp files.

**Comment by Jeroen0494** [comment]
Hmm, that's very strange. I'll experiment with the audit daemon to find out which program exactly is creating these files.
My apologies if I came across a bit crass.

**Comment by jimsalterjrs** [comment]
Thanks, and good luck!
