### ISSUE TITLE
RFE: pass params for post/pre/prune scripts ?

### ISSUE THREAD

**Issue by devZer0** [jimsalterjrs/sanoid#776]
would it make sense to have passing params to those post/pre/prune scripts or have support for generic envvars in sanoid.conf , which could be read by the script ?

i'm implementing  bookmark pruning script and thought about passing number of days to prune to that script, so i could configure the values in sanoid.conf instead of configuring it in the script itself.

it would look like this:

```
[rpool/vms-files-zstd]
        use_template = prod
        pruning_script = /root/prune-bookmarks.sh 30

[ssdpool2/vms-files-zstd]
        use_template = prod
        pruning_script = /root/prune-bookmarks.sh 15

[template_prod]
        frequently = 16
        hourly = 24
        daily = 1
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes

**Comment by devZer0** [comment]
this is the preliminary version of the pruning script for bookmarks, otherwise thousands of them would pile up....

maybe someone wants to review/comment....

```
# cat /root/prune-bookmarks.sh
#!/bin/sh

# derived from https://www.jan0sch.de/post/deleting-old-zfs-snapshots/

# Get EPOCH timestamp from $DAYS ago.
DAYS=30
DATE=$(echo "$(date +"%s") - $DAYS * 24 * 60 * 60" | bc)

echo "Deleting bookmarks older than $DAYS days..." >>/tmp/prune-bookmarks.log

echo "target:" $SANOID_TARGET >>/tmp/prune-bookmarks.log

zfs list -p -S creation -o name,creation -t bookmark $SANOID_TARGET | awk -v DATE=$DATE '$2<DATE {print $1}' | while read bookmark;do echo $bookmark;zfs destroy -vp $bookmark;done >>/tmp/prune-bookmarks.log

**Comment by phreaker0** [comment]
@devZer0 this already works like you did it in your example

**Comment by devZer0** [comment]
weird, i'm sure i tested that and it failed.  now, when retesting it works. thanks for making clear that it works!
