### ISSUE TITLE
Two syncoid runs one with minimum disk heads movement, other more noisy (--force-delete)

### ISSUE THREAD

**Issue by slrslr** [jimsalterjrs/sanoid#780]
Hello,

/usr/sbin/syncoid version 2.0.3
(Getopt::Long::GetOptions version 2.51; Perl version 5.32.1)
Debian 11, 5.10.0-18-amd64
zfs-2.1.5-1~bpo11+1
zfs-kmod-2.1.5-1~bpo11+1

one HDD was connected in two ways.
A) SATA to USB adaptor
B) [SATA USB dock station](https://bin.disroot.org/?8aeddee5aa5e4e7e#HUf5cuqN7pEa3FotfdqGfkzmT2fP8FDXd9iocTgofQs6)

I remember that the first syncoid run was silent like i heard nearly no noise
But currently i hear quite often heads movement and often speed drops from 180MB/s down to hundreds of kB/s for the time of couple of second.

First run possibly:
Destroy pool, create new one (without datasets)
syncoid --skip--parent -r --force-delete src dest

Second run:
Pool not deleted, exist, including same datasets i wanted to copy
syncoid -r --skip-parent --no-stream --force-delete pool poolbackup

Third run
same as second run, only I have destroyed destination pool and recreated it with no datasets and ran without  --force-delete
result is no speed drops and total estimated time being nearly half of the second run! UPDATE: second dataset syncing is more noisy than first, i have many small files there, maybe it can play some role. Speed is at only 100MB/s.

Any idea please what may be wrong and how to proceed? Or if possible to optimize force delete somehow not to drop speed and not to increase heads movement & noise?

**Comment by phreaker0** [comment]
this is more a zfs question and I don't think there is anything which can be done.
