### ISSUE TITLE
SSH socket name collisions

### ISSUE THREAD

**Issue by stuartthebruce** [jimsalterjrs/sanoid#782]
To avoid an SSH socket filename race condition (/tmp/syncoid-*) please consider changing,
```
$socket = "/tmp/syncoid-$rhost-" . time();
```
to also include the current pid ($$) or switch to using File::Temp.

**Comment by phreaker0** [comment]
@stuartthebruce current master already contains a random number at the end:
https://github.com/jimsalterjrs/sanoid/blob/ef601eb96b016786af63ea5d7e30c8ad1b5de689/syncoid#L1474

**Comment by stuartthebruce** [comment]
Do you have an estimate for when the next release will be?

P.S. wouldn't using `$$` be more robust than `rand()`?

**Comment by phreaker0** [comment]
This is up to @jimsalterjrs 

And yes, $$ would be better as rand() has a low probability of collisions too.
