### ISSUE TITLE
Syncoid: Resilience against broken, nice-to-have commands like mbuffer, pv and lzop

### ISSUE THREAD

**Issue by koraa** [jimsalterjrs/sanoid#783]
Hi there,

syncoid kept throwing errors (cannot receive stream), upon investigation it turned out my mbuffer is broken:

    mbuffer: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

The fix is obvious. To find the issue I had to activate syncoid debug output, manually paste the command:

    ssh <CENSORED…> ' zfs send -L -e -c -p -w  -I <CENSORED…>' \
      | mbuffer  -q -s 128k -m 16M 2>/dev/null \
      | pv -p -t -e -r -b -s 82992 \
      |  zfs receive  -s -F <CENSORED> 2>&1

I disabled mbuffer silencing and added verbosity flags to zfs send, zfs recv. Disabling mbuffer slencing did the trick.

There are two potential improvements conceivable to improve usability:

* [ ] Perform end-to-end testing of optional tools on both hosts; only activate them if end to end testing passes
* [ ] Use `grep` based silencing of known-harmless log output from tools instead of blanket silencing using `2>/dev/null`.

**Comment by jimsalterjrs** [comment]
This one's going to be a #wontfix, at least for the moment. If you'd like to contribute improved error checking code yourself, we'll be happy to review it! :)
