### ISSUE TITLE
sanoid --cron mode should not write to stdout

### ISSUE THREAD

**Issue by rwarren** [jimsalterjrs/sanoid#79]
When run with `sanoid --cron`, sanoid is outputting to stdout. See below...

```bash
$ sudo sanoid --cron 2>/dev/null
INFO: taking snapshots...
taking snapshot data/images/foo@autosnap_2017-04-27_18:58:18_monthly
taking snapshot data/images/foo@autosnap_2017-04-27_18:58:18_daily
taking snapshot data/images/foo@autosnap_2017-04-27_18:58:18_hourly
INFO: cache expired - updating from zfs list.
INFO: pruning snapshots...
```
With sanoid typically being run very frequently by cron, this results in cron spamming you with mails, or barking at you in syslog if you have "no MTA installed".

In `--cron` mode, sanoid should probably remain silent unless there is an actual error worth notifying the sysadmin about.

Suppressing email/syslog spam with `sanoid --cron >/dev/null 2>&1` in your crontab is obviously possible, but this would suppress actual errors resulting in email-worthy notifications.

**Comment by tl-t3cms** [comment]
Hi. Great software but yeah as rwarren says, correct stdout/stderr usage is critical to avoid alarm fatigue.

**Comment by crocket** [comment]
I think it is an issue of documentation. If verbosity of output was lowered, this issue would be solved.
To lower verbosity, one has to know what options sanoid has.
Currently, sanoid options are not documented, and sanoid doesn't accept '--help' option.

**Comment by redmop** [comment]
I have some documentation for the readme. I'll put in a pr.

**Comment by crocket** [comment]
`sanoid --cron --quiet` does what you want.

**Comment by rwarren** [comment]
@jimsalterjrs this can probably be closed. The new `--quiet` does prevent the "no MTA" problems. I'm not 100% sure that it doesn't suppress all errors, though.

**Comment by jimsalterjrs** [comment]
If you come across something that --quiet isn't suppressing but should, please open another issue.
