### ISSUE TITLE
[Questions] Installation and documentation.

### ISSUE THREAD

**Issue by Synt3x** [jimsalterjrs/sanoid#792]
Hello,

I am trying to setup and learn how to use sanoid and have a few questions about the installation process and documentation. 

* The installation instruction for Ubuntu is saying that I should apt install a few package and the clone this project. I later found a youtube talk of you JIm, telling the audience, that sanoid now is available in apt for Ubuntu. So I was just wondering if there is any reason (except time) why this isn't mention in the installation instructions. 
* ~Instead of following the installation instruction, I downloaded sanoid with apt. But after it got installed I notice that `/etc/sanoid` didn't exist and was wondering if I should copy over `sanoid.default.conf` or that configuration file is hidden on another location. This might not be a question for you, maybe I should ask Ubuntu this instead, since it's their package.~ [Found it](https://packages.ubuntu.com/focal/all/sanoid/filelist)
* In the `sanoid.conf` there is a [line](https://github.com/jimsalterjrs/sanoid/blob/ef601eb96b016786af63ea5d7e30c8ad1b5de689/sanoid.conf#L34) saying `recursive = zfs`. Shouldn't this say yes or no? I didn't find anything on this in the wiki section. 

Thanks in advance.

/R

**Comment by backupandforkacc** [comment]
Many thanks, I have the same questions. 

So you have to do `mkdir /etc/sanoid/ ` yourself and create a configuration there, right?

There are some hints here:
/usr/share/doc/sanoid/examples/sanoid.conf

Can you also put a complete pool in your template? Or do you need to define single datasets?

**Comment by lckarssen** [comment]
> So you have to do mkdir /etc/sanoid/ yourself and create a configuration there, right?

That's correct. And then create `sanoid.conf` in that directory (or copy the example). As for snapshotting a whole pool: IIRC that is not supported.

**Comment by backupandforkacc** [comment]
Thanks!

For snapshotting the whole pool: I will try, but[ I read that](https://www.ulrichivens.de/index.php/2020/08/30/datensicherung-mit-zfs-und-syncoid/?unapproved=165&moderation-hash=2ac077a992a58a6a286606b58fa5f968#comment-165)
`syncoid -r ssdpool backupssd`
works. So at least sanoid is able to make backups of all datasets. 
I have a lot of datasets as docker creates dozens of them per container. So for the backups to work, I need sanoid to backup the whole pool.

**Comment by jimsalterjrs** [comment]
Snapshotting the whole pool is supported just fine.

~~~~
[poolname]
    use_template=production
    recursive=yes
~~~~

**Comment by backupandforkacc** [comment]
And what does

```
[poolname]
    use_template=production
    recursive=zfs
```
from the demo file mean? Its from:
 /usr/share/doc/sanoid/examples/sanoid.conf

**Comment by Synt3x** [comment]
I am not sure, I just replaced it with yes. Maybe @jimsalterjrs can give us a quick answer. :)

**Comment by phreaker0** [comment]
@backupandforkacc @Synt3x 

With `recursive=zfs` sanoid will invoke zfs with the recursive (-r) flag to create the snapshots in an atomic way. This also means that you can't exclude child datasets as opposed to `recursive=yes` in which case sanoid iterates over the child datasets and takes one snapshot at a time.

**Comment by Synt3x** [comment]
@phreaker0 thanks this detail! Do you mind sharing where I can find this information and read more about all options? I looked at the wiki section but couldn't find it. Is there another place?

Thanks in advance.
