### ISSUE TITLE
Syncoid send all datasets

### ISSUE THREAD

**Issue by backupandforkacc** [jimsalterjrs/sanoid#794]
In sandroid, its possible to specify a whole pool with all datasets to be backuped. 
No I would like to send all the datasets and backups of the pool to an external drive. How can I do this with syncoid? 
I have a huge amount of datasets as I use docker and it creates a lot of them.

**Comment by phreaker0** [comment]
It's in the readme: https://github.com/jimsalterjrs/sanoid#syncoid
