### ISSUE TITLE
no syncoid usage

### ISSUE THREAD

**Issue by kforner** [jimsalterjrs/sanoid#81]
syncoid should print a usage page when called without args or with --help. 
I had to read the source code to discover all the options.

Thank you for this software !

**Comment by tomposmiko** [comment]
This would fix it:

https://github.com/jimsalterjrs/sanoid/pull/97/commits/dcc69207b6f773a7ff05c21a136aa54104f8f353

**Comment by jimsalterjrs** [comment]
root@banshee:~/git/sanoid# syncoid
usage: syncoid [src_user@src_host:]src_pool/src_dataset [dst_user@dst_host:]dst_pool/dst_dataset

If somebody wants to provide a more detailed version, I'm more than willing to accept a PR - especially if it's written with an eye to easy maintenance as new features are added or changed.
