### ISSUE TITLE
RFE: please add option for send+recv pipe like zfs_autobackup

### ISSUE THREAD

**Issue by devZer0** [jimsalterjrs/sanoid#810]
see  https://pypi.org/project/zfs-autobackup/
  
  It's also possible to add custom send or receive pipes with --send-pipe and --recv-pipe.
  
--send-pipe COMMAND   pipe zfs send output through COMMAND (can be used
                        multiple times)
  --recv-pipe COMMAND   pipe zfs recv input through COMMAND (can be used
                        multiple times)
                        
                        
https://github-wiki-see.page/m/psy0rz/zfs_autobackup/wiki/Performance

Direct TCP network transfer
If ssh-encryption performance is too slow for your use-case, you can do a direct unencrypted transfer via tcp ip:

Use something like this:

zfs-autobackup ... --send-pipe "nc server_name 8023" --recv-pipe "nc -l -p 8023"

This will pipe the data through netcat on the specified port.

**Comment by redmop** [comment]
For --send-pipe and --recv-pipe, what do you plan to use this for?

**Comment by devZer0** [comment]
using some different transport besides ssh, which is slow

**Comment by jimsalterjrs** [comment]
Fixed in v2.2.0, with @phreaker0 's new argument `--insecure-direct-connection=IP:PORT[,IP:PORT,[TIMEOUT,[mbuffer]]]`
