### ISSUE TITLE
Killing Syncoid early during send of initial resumable snapshot to remote may hang remote `zfs receive` preventing dataset deletion until killed.

### ISSUE THREAD

**Issue by ipaqmaster** [jimsalterjrs/sanoid#814]
Hey all,

I got some new Arch Linux servers (zfs 2.1.9 & Kernel 6.2.7) onto sanoid yesterday for an automated snapshot scheme and tried sending the datasets to a remote with `syncoid localZpool remoteMachine:remoteZpool/localZpool --recursive --no-sync-snap --sendoptions="pw"'` (send options = props & raw send for even unencrypted datasets. To avoid reprocessing on the remote.)

Overall the process is flawless and I'm glad to finally be on the sanoid/syncoid side of things. I'm glad I was also able to send the top level zpool-dataset to the remote alone, then `zfs rename` the child datasets already present on the remote to _under_ the zpool dataset so I didn't have to re-send a few terabytes anew. Great software and snapshot handling.

I ended up Ctrl+C'ing the command mid-transfer a few times as I continued to tweak arguments, tweak sudoers.d files and schedule the actual transfer and what not. While the datasets were recursively present on the remote machine as expected and desired in their partially-received states with a `receive_resume_token` property set - I was unable to delete or rename the datasets even after deleting their snaps nor could I export the zpool, desperately trying to get a 'fresh state' to try and delete them again. All attempts said that the dataset was busy.

After a while of wondering what else I could do without a forced reboot I felt a little silly finally realizing that `ps aux|grep zfs receive` revealed the zfs receive process on this remote machine still sitting there presumably waiting more data to stream in from the source machine - unknowing that the source machine terminated the transfer a while ago and has re-tried a few times since that. I did a `pkill -f -9 zfs` and that nabbed the receive processes left behind.

Between debugging and realizing what was really going on I tried the syncoid command as above on the source machine a few times and it refused to touch those datasets as well, acknowledging they're already in the middle of something. (I should've noted down all of this command output).

------------

At this point, I'm wondering if this is even something Syncoid should care about? Or is it on the user to realize the stuck state the remote `zfs receive` process has experienced?

Could Syncoid check a remote for stale `zfs receive`'s and promptly hit them with a kill signal? I presume this could theoretically happen if a sending source machine loses power for example as well.

Also, at the time these machines didn't have `mbuffer` nor `lzop` installed (in case they may alter the outcome). I tried reproducing this a few times yesterday evening but had trouble doing so with a recursive test dataset which is.. great. I'll keep trying to make a reproducible command list so this can actually be reproducible.

**Comment by phreaker0** [comment]
AFAIK this can only happen if the zfs receive hangs for some reasons.

In the ordinary case if the ssh process is closed the read channel of zfs receive will be close which will lead to the termination of zfs receive. 

so there is nothing syncoid should do.
