### ISSUE TITLE
Issue with --delete-target-snapshots and --insecure-direct-connection

### ISSUE THREAD

**Issue by revilo951** [jimsalterjrs/sanoid#822]
Using `--delete-target-snapshots --insecure-direct-connection` on a fresh install from Master results in:

```
Unknown option: delete-target-snapshots
Unknown option: insecure-direct-connection
```

**Comment by ipaqmaster** [comment]
Fresh install of what distribution? And what version of the package?

**Comment by revilo951** [comment]
Great question. 

Debian 11 Bullseye (Proxmox v7)

syncoid version 2.1.0 (Installed 2 or 3 days ago via instructions on INSTALL.md)

**Comment by jimsalterjrs** [comment]
Actually not v2.1.0--installed from master, after the last round of merges. What's in master right now technically doesn't *have* a version number yet. It doesn't get a version number until it's packaged up as the next release.

**Comment by revilo951** [comment]
Ah, that makes sense. Would you like me to have a go at a PR updating the docs to reflect that?

If I understand correctly, for those features, someone would need to clone the repo and build themselves, as they aren't built into packaged releases yet?

**Comment by joelishness** [comment]
Is there a workaround to --delete-target-snapshots issue?
Like, is there a zfs receive option that could be specified in --recvoptions= ?

**Comment by crpb** [comment]
I just tried the current git-version it with a [self-built package](https://salsa.debian.org/cb/sanoid) and i'm very happy about those new features.

`--delete-target-snapshots` works in my cases with no issues so far

I was about to tinker in the code to disable the cache-update for the whole system as my targets are only dataset-children with `zfs allow ...` for the specific users.
Luckily i skimmed the commits :see_no_evil: 

Now i can remove my Target-Side $Users cpan and $HOME/bin setup again :+1: 


Just fyi, what works for me
```
#!/bin/bash
if [ "$1" = "-d" ]; then DEBUG="--debug"; fi
SOURCEPOOL=rpool
SSHUSER=USERNAME
SSHHOST=HOSTNAME.DOMAIN.TLD
SSHPORT=REMOTEPORT
SSHKEY=~/.ssh/id_ed25519
TARGETPOOL=POOLNAME
TARGETDATASET=USERNAME/BACKS/HOSTNAME
EXCLUDES='rpool/(tmp|usr|var/(cache|lib|mail|spool|tmp))'
SYNCOIDOPTS=( --compress=zstd-fast
              --delete-target-snapshots
              --exclude="${EXCLUDES}"
              --force-delete
              --no-privilege-elevation
              --no-sync-snap
              --recursive
              --sshkey="${SSHKEY}"
              --sshport="${SSHPORT}" )
/usr/sbin/syncoid ${DEBUG} \
                  ${SYNCOIDOPTS[@]} \
                  ${SOURCEPOOL} \
                  ${SSHUSER}@${SSHHOST}:${TARGETPOOL}/${TARGETDATASET} \
                  | systemd-cat -t SYNCOID
```

**Comment by nickcmaynard** [comment]
@jimsalterjrs I hate to ask directly, but it would be super helpful if these features from master could make it into a release (and thus distro packages). What plans do you have for a sanoid/syncoid minor release?

**Comment by phreaker0** [comment]
https://github.com/jimsalterjrs/sanoid/releases/tag/v2.2.0
