### ISSUE TITLE
Syncoid always thinks it's not root.

### ISSUE THREAD

**Issue by MikeBellerue** [jimsalterjrs/sanoid#83]
The getsnaps subroutine has a check to see if it needs to add `/usr/bin/sudo` to the beginning of the command for getting snapshots. But getsnaps is called at lines 138 and 141 without the $sourceisroot and $targetisroot variables, so getsnaps always thinks it's not root.

Not gonna lie, I don't know how to submit my change, and it's almost 4am so I'm not going to figure it out any time soon. Here's my suggested change. Enjoy.

138 should be
`%snaps = getsnaps('source',$sourcehost,$sourcefs,$sourceisroot);`

141 should be
`my %targetsnaps = getsnaps('target',$targethost,$targetfs,$targetisroot);`

**Comment by jimsalterjrs** [comment]
Looks like I must have fixed this at some point - the code in master reads like your suggestions here, and a couple trial runs in `--debug` both as root and as a user with `NOPASSWD:/sbin/zfs` in `sudoers` worked as expected.  Yay? =)
