### ISSUE TITLE
syncoid --quiet via cron seems to incurr errors, when leaving it out does not

### ISSUE THREAD

**Issue by papamoose** [jimsalterjrs/sanoid#830]
I have a user that runs something like this via cron:

`* */4 * * * /path/to/pulldataset.sh quiet` 

If no data needs to be transferred, which is pretty normal, a run takes ~70 seconds. 

```
#!/bin/bash
from="<hostname>"
user="<zfs user>"
options=""

if [ "$1" == "quiet" ]; then
  options+="--quiet"
fi

options="--sshkey=~/.ssh/zfsreplicate
  --keep-sync-snap
  --no-sync-snap
  --no-privilege-elevation
  --preserve-recordsize
  --sendoptions='-w'
  ${options}"

# a couple syncoid commands, like the below, for a few other datasets. No errors reported, these do not have child datasets.

# The below dataset is four datasets deep
# pool/child/grandchild/greatgrandchild

/usr/sbin/syncoid \
  $options \
  --recursive \
  --exclude=downloads \
  --exclude=archive \
  ${connuser}@${from}:pool/child \
  pool/child
```

In this configuration I get errors like this in my email on every run:

```
Cannot sync now: pool/child/grandchild/greatgrandchild is already target of a zfs receive process.
```

```
cannot receive incremental stream: most recent snapshot of pool/child/grandchild/greatgrandchild does not match incremental source
CRITICAL ERROR: ssh    -i path/to/sshkey -S /tmp/syncoid-user@ip-1689098436 [user@ip](mailto:user@ip) ' zfs send -w  -I '"'"'pool/child/grandchild/greatgrandchild'"'"'@'"'"'autosnap_2023-07-11_14:00:03_hourly'"'"' '"'"'pool/child/grandchild/greatgrandchild'"'"'@'"'"'autosnap_2023-07-11_18:00:08_hourly'"'"' | lzop  | mbuffer  -q -s 128k -m 16M 2>/dev/null' | mbuffer  -q -s 128k -m 16M 2>/dev/null | lzop -dfc |  zfs receive  -s -F 'pool/child/grandchild/greatgrandchild' 2>&1 failed: 256 at /usr/sbin/syncoid line 817.
```

The datasets referenced between these two errors messages may or may not be the same. There could be multiple datasets.

I get messages like this on every single run (every four hours).

Now if I change the cronjob to not include the `--quiet` option and redirect STDOUT to /dev/null I no longer receive these errors. 

```
* */4 * * *  /path/to/pulldataset.sh > /dev/null
```

I've verified that I should still get the `warn()` messages if they occur by working with the above.

```
#!/usr/bin/perl
use warnings;
warn "Hello World! This is a warning";
```
```
* * * * * /path/to/p.pl > /dev/null
```
The above will email me all stderr messages.

Running `pulldatasets.sh quiet` as a normal user and outside of cron and also inside crons environment does NOT report an error. `./run-as-cron ./pulldatasets.sh quiet`

The behavior of `--quiet` doesn't seem intentional. Did I miss something?

**Comment by papamoose** [comment]
It's possible I just need to wrap `pulldatasets.sh` in `flock`. Will report back when done.

**Comment by phreaker0** [comment]
@papamoose quiet argument doesn't affect the busy message. You probably run the same replication in parallel .
