### ISSUE TITLE
Syncoid's documentation: missing docs for prunning

### ISSUE THREAD

**Issue by rsysadmin-com** [jimsalterjrs/sanoid#839]
Hi! 

First, go to https://github.com/jimsalterjrs/sanoid/wiki/Syncoid

![image](https://github.com/jimsalterjrs/sanoid/assets/20558552/9c8979e7-2073-4657-bb82-60ded9659b8f)

Click on option #3 ... https://github.com/jimsalterjrs/sanoid/wiki/Syncoid#pruning and it leads to nowhere

TIA!

**Comment by jimsalterjrs** [comment]
The wiki is an ENTIRELY community project at this time. If you don't like it, *edit* it. :)
