### ISSUE TITLE
Critical error - failed: 2 at /usr/sbin/syncoid line 1415.

### ISSUE THREAD

**Issue by ovizii** [jimsalterjrs/sanoid#842]
I have used syncoid once or twice with success and today I decided to update some data so I ran this command:

` syncoid --recursive --compress lz4 --sendoption=w root@100.71.xxx.xxx:sixer/Music rpool/Music `

nothing happened for quite a while so I hit CTRL+C and then I saw this error:

```
CRITICAL ERROR: ssh     -S /tmp/syncoid-root@100.71.xxx.xxx-1690976355 root@100.71.xxx.xxx  zfs snapshot ''"'"'sixer/Music'"'"''@syncoid_target_host_2023-08-02:13:39:21-GMT02:00
 failed: 2 at /usr/sbin/syncoid line 1415.
```

Any idea what all this means? Nothing major has changed except the source server is slowly running out of space, hence me trying to sync data, so I can manually delete datasets from the source. Anyway, the free space is bigger than the dataset sixer/Music

**Comment by phreaker0** [comment]
With "CTRL+C" you aborted the underlying ssh process for the replication, so the replication failed.
I don't think nothing happend, i guess zfs ist just slow for you for some reason (many metadata updates, ...). You can check with `zpool iostat` for activitiy
