### ISSUE TITLE
More interactive support channels

### ISSUE THREAD

**Issue by rsysadmin-com** [jimsalterjrs/sanoid#844]
Hi all!

Besides raising issues here, which seems to be a rather slow way of getting support, is there any alternative? such as an IRC or Discord channel? I searched but didn't find anything... 

This way, more experienced users could help newcomers, share experiences etc... you get the drill :-)

TIA!

**Comment by jimsalterjrs** [comment]
@lckarssen nailed it. This is the appropriate place to raise bug reports; regular usage stuff is better handled at https://discourse.practicalzfs.com/ -- time was, I would have said r/zfs on Reddit, but, well, yanno. :)
