### ISSUE TITLE
Unclear syncoid edge case from documentation

### ISSUE THREAD

**Issue by gordan-bobic** [jimsalterjrs/sanoid#847]
Maybe I am missing something, but there is a potentially important edge case that I cannot find explicitly mentioned in the documentation.

1) Take some snapshots on the source, e.g. 1,2,3,4,5
2) syncoid them across
3) rollback to a snapshot somewhere in the middle of the snapshot list on source, e.g. zfs rollback data@3
4) take new snapshot 6
5) re-syncoid

From what I can tell, syncoid with --no-sync-snap option seems to rollback to 3 on the target and syncs up to 6.
This seems dangerous / undesirable. If source is maliciously rolled back, then that will propagate to the backup target.
Will --no-rollback prevent that behaviour? Is there a way to specifically limit rollback to only the latest snapshot on the target?

**Comment by phreaker0** [comment]
yes --no-rollback will prevent this and error out in this case. Just keep in mind that any modification on the target will break the sync (a rw mount is enough to change the target).

Rolling back to the latest snapshot on the target won't work, as the source can't be replicated to the target in this case.
