### ISSUE TITLE
Feature request: New options to run the "sanoid --monitor-*" commands as non-root without updating the snapshot cache file

### ISSUE THREAD

**Issue by Pajkastare** [jimsalterjrs/sanoid#851]
I use `sanoid` and `syncoid` for all my backup needs (and a bit of `rsync` from non-ZFS filesystems to ZFS), and I use `nagios` to monitor my local and remote ZFS status. All of this works great.

But: I'd like the ability to run `sanoid` as non-root for the `--monitor-snapshots`, `--monitor-capacity` and `--monitor-health` cases, **without** updating the snapshot cache file (`/var/cache/sanoid/snapshots.txt`, which by default times out after 15 minutes) even if it were to be too old. Suggested new option names are `--monitor-snapshots-no-update`, `--monitor-capacity-no-update` and `--monitor-health-no-update` for the new behaviour.

Well, to be precise, these commands _can_ be run as non-root today, but in case the snapshot cache file is too old, the commands will fail because `sanoid` automatically attempts to refresh the cache. (Perhaps it makes the most sense to return an "UNKNOWN" status code if it cannot be concluded if the snapshots are OK/WARN/CRIT, but the capacity and health commands should not need a cache file update.)

Why do I think this is a good idea? Not only because of the "too-old-snapshot-file issue" I described above, but also because the updating of the cache file causes unnecessary peaks in disk utilization, and unnecessary wear on mechanical HDDs. 
For example: A zpool of large HDD[s] only used for backup purposes, with snapshots sent a couple of times per day, doesn't need all snapshots indexed all the time.

What is the current behaviour? Just having Nagios look after the zpools by using the monitor commands above will result in "flapping services" (as it's called in Nagios), depending on how long after a systemd-timer-invoked `sanoid` execution as root occurs.
(My workaround is to add this to `/etc/crontab`: `*/14 * * * * root /usr/sbin/sanoid --force-update >/dev/null 2>&1`, which never gives me flapping Nagios services, but it also definitely causes unnecessary disk usage.) I guess I could, but I prefer not to, allow Nagios/NRPE to run `sanoid` as root. Or I could write a wrapper script that doesn't run the command if the snapshot file is too old. But I don't think I'm the only one who has this usecase.

I don't speak perl at all, so I don't think I should attempt to create a pull request for it.

**Comment by jimsalterjrs** [comment]
I'm actually good with just disabling cache updates when one of the monitoring arguments is invoked; I don't think creating new arguments is necessary. You raise a good point that this could result in false WARN or CRIT on monitor-snapshots due to stale cache, but I think we can actually dispense with that concern; if someone isn't running with --cron at least once per hour, they can start doing so!

I am EXTREMELY buried in client work this week, though. If you don't see this issue cleared this week, remind me next week, would you?

**Comment by Pajkastare** [comment]
Thanks, I will start to nag if I need to. :-)

**Comment by Pajkastare** [comment]
> I am EXTREMELY buried in client work this week, though. If you don't see this issue cleared this week, remind me next week, would you?

I guess this is the "next week" reminder, @jimsalterjrs? :-)

**Comment by Pajkastare** [comment]
Hi @jimsalterjrs, any news on this front?

**Comment by Pajkastare** [comment]
As I wrote, I don't speak perl, but I do speak bash, so I gave it a go... And I haven't been able to find problems with the code in the pull request.
