### ISSUE TITLE
Syncoid Replication how exactly works Question

### ISSUE THREAD

**Issue by madmax01** [jimsalterjrs/sanoid#853]
Hi,

this is more an Question rather an Issue.

is the Replication just working on File-level if any File is new?  or does is also recognize changes inside a File (like a VM disk).

if so does it replicate whole File > or just the Blocks required?

thx

**Comment by phreaker0** [comment]
@madmax01 you should look into how ZFS works. ZFS will split up files in multiple blocks. Only the changed blocks will sent on replication. So if you replicate a dataset with a vm disk image only the changes will be replicated instead of the whole file.

**Comment by madmax01** [comment]
gracias. got it..... what i love is > its direct syncing the files. so i see the files in the dataset backup. thats cool. many thx for this
