### ISSUE TITLE
feature request: `--force-delete` option to "cowardly destroy destination" if no common snapshot is found

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#86]
````
CRITICAL ERROR: Target exists but has no matching snapshots!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.
````

^ please, for the above case, add a `--force-delete` command line option.
because in the end I would manually have to delete the destination anyway :)

**Comment by phreaker0** [comment]
I actually need something like that :-) I use docker with ZFS, and it recreates datasets which makes replication hard, because I need to destroy the replicated datasets on the target manually right now.
