### ISSUE TITLE
--exclude=REGEX question

### ISSUE THREAD

**Issue by madmax01** [jimsalterjrs/sanoid#867]
Hi team,

i done with syncoid --exclude=pool1/backup

but when doing replica i get exit code 2

NEWEST SNAPSHOT: autosnap_2023-11-30_20:35:31_daily

CRITICAL ERROR: Target pool1/backup exists but has no snapshots matching with pool1!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

NEWEST SNAPSHOT: autosnap_2023-11-30_20:35:31_daily
INFO: no snapshots on source newer than autosnap_2023-11-30_20:35:31_daily on target. Nothing to do, not syncing.
NEWEST SNAPSHOT: autosnap_2023-11-30_20:35:31_daily
INFO: no snapshots on source newer than autosnap_2023-11-30_20:35:31_daily on target. Nothing to do, not syncing.
NEWEST SNAPSHOT: autosnap_2023-11-30_20:35:31_daily
INFO: no snapshots on source newer than autosnap_2023-11-30_20:35:31_daily on target. Nothing to do, not syncing.
syncoid command failed with exit code 2

do i need to do anything else to exclude ?

**Comment by jimsalterjrs** [comment]
what does the rest of your syncoid command look like?

**Comment by madmax01** [comment]
syncoid  root@test:pool1:/pool1 pool1/backup --no-resume --no-stream --no-privilege-elevation  --recursive --no-sync-snap --source-bwlimit 10G --target-bwlimit 10G

then its creating inside backup additional sets (syncoid seems doing that)

pool1/backup/local_files
pool1/backup/local_system
pool1/backup/local_images

i just created the init pool1/backup so i can use above

just was not sure why its trying to make an snapshot (don't have that dataset configured).

**Comment by madmax01** [comment]
in the sanoid config i only added the pool1/local_files pool1/local_system  (but didn't added the backup to snapshot itself)

**Comment by madmax01** [comment]
thx for advice. may i have an logical issue in understanding

**Comment by madmax01** [comment]
i just deleted pool1/backup and it created it itself (seems had trouble when manual created)
