### ISSUE TITLE
syncoid delete option

### ISSUE THREAD

**Issue by madmax01** [jimsalterjrs/sanoid#869]
Hi Team,

In Case source don't have Data X anymore > can you please add an feature so its deleting it on the target

syncoid root@host:pool1 pool1/backup --no-resume --no-stream --no-privilege-elevation --recursive --no-sync-snap --source-bwlimit 100g --target-bwlimit 100g --compress none

when vm moved to other host then data not valid anymore on first host. thx

**Comment by Derkades** [comment]
If the VM images are in zvols, `--force-delete` should delete them on the destination.

**Comment by madmax01** [comment]
ah i didn't used the --force-delete

seems with above sync cares already about data.... it delete and create. all good thx ;)
