### ISSUE TITLE
How do I install sanoid on gentoo?

### ISSUE THREAD

**Issue by crocket** [jimsalterjrs/sanoid#87]
I want to package sanoid for gentoo, but I don't know how to handle perl programs.
I can package C programs and python programs, but not perl programs.

Can you provide installation instructions?

**Comment by crocket** [comment]
It seems `sanoid.spec` contains installation instructions for an RPM package.
I think I can use this.

**Comment by jimsalterjrs** [comment]
It boils down to "dump sanoid and syncoid in /usr/local/bin (or other place you'd like executables to be in your PATH), then install pv, lzop, mbuffer, and Perl's Config::IniFiles CPAN module (this is libconfig-inifiles-perl on Ubuntu; not sure on Gentoo), then create /etc/sanoid, and put sanoid.conf and sanoid.conf.defaults in there."

**Comment by crocket** [comment]
What about findoid and sleepymutex?

**Comment by jimsalterjrs** [comment]
Findoid is probably not useful to anybody at this point; it's a half-built tool to search through VM images that never got finished.  Sleepymutex is, as it says on the tin, just a dev tool - it's handy for troubleshooting locks that depend on looking for mutexes, but nothing else.  No use at all to a consumer or admin, only to a dev.

**Comment by redmop** [comment]
I actually do use findoid from time to time.

**Comment by jimsalterjrs** [comment]
Oh, awesome!  Had no idea anybody was actually using it in the wild. =)

**Comment by kenny-evitt** [comment]
@jimsalterjrs Any reason not to just add to *INSTALL* something like [your earlier comment in this issue](https://github.com/jimsalterjrs/sanoid/issues/87#issuecomment-308458584):

> dump sanoid and syncoid in /usr/local/bin (or other place you'd like executables to be in your PATH), then install pv, lzop, mbuffer, and Perl's Config::IniFiles CPAN module (this is libconfig-inifiles-perl on Ubuntu; not sure on Gentoo), then create /etc/sanoid, and put sanoid.conf and sanoid.conf.defaults in there.

I can submit a PR with that change if you'd like.

**Comment by jimsalterjrs** [comment]
I'd love for you to submit a PR, thank you! If you'd like to break out any distro-specific bits and bobs into their own subheadings, that would be fabulous also; I do almost all of my own work in Ubuntu these days so I'm not going to be immediately familiar with things specific to Arch, Gentoo, what have you.
