### ISSUE TITLE
[Documentation] Install.md mentions mbuffer in FreeBSD.readme which does not exist.

### ISSUE THREAD

**Issue by xpufx** [jimsalterjrs/sanoid#870]
"See note about mbuffer and other things in FREEBSD.readme"

There's no mention of mbuffer in that file.

**Comment by jimsalterjrs** [comment]
updated to read "tcsh unpleasantness," which is the actual issue causing FreeBSD usage of mbuffer to fail. If the user's shell is sh, everything works with or without mbuffer.
