### ISSUE TITLE
feature request for syncoid: use bookmark feature as fallback method

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#88]
I hope [this reddit discussion](https://www.reddit.com/r/zfs/comments/5op68q/can_anyone_here_explain_zfs_bookmarks/) makes it clear that the main advantage to `bookmark` in relation with `zfs send` is that you can afford to lose the source snapshot yet still be able to bring the destination in sync with the source.

It would be very useful if you can add the ability use bookmarks as a fallback mechanism:
when syncoid finds a common snapshot between source and destination, it should automatically bookmark the matching source snapshot.
if syncoid does not find a common snapshot, try to find a bookmark created by syncoid and that fails too, try to find newest bookmark and attempt to send incrementally from that bookmark to latest snapshot.
if that fails, try again with the second newest bookmark it finds, and repeat until oldest bookmark. only then fail if the incremental from oldest bookmark to latest snapshot still fails.

beware that when sending bookmarks you cannot have `-v` and [cannot estimate the size](https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSBookmarksMechanism) of the sending stream

also pay attention to the fact that -I and -R [do not work with sending bookmarks](https://web.archive.org/web/20160618005021/http://comments.gmane.org:80/gmane.comp.file-systems.openzfs.devel/514), only -i

all in all the use of bookmarks may seem to complicate things but in the end you will have more happy users by not having to re-send datasets after accidental snapshot deletions. and syncoid will be the first serious replication tool that fully takes advantage of the bookmarks feature :) (I only know about [zap](https://github.com/Jehops/zap) but it seems kind of immature)

**Comment by jimsalterjrs** [comment]
Note for future: most relevant discussion is here --> https://www.reddit.com/r/zfs/comments/5op68q/can_anyone_here_explain_zfs_bookmarks/

**Comment by jimsalterjrs** [comment]
Have bookmarks made it into mainstream openzfs yet? In particular, Ubuntu 16.04 repo openzfs?

**Comment by mailinglists35** [comment]
I believe yes, Ubuntu has 0.6.5.x version while the bookmarks feature has been introduced in [0.6.4 ](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.4)

**Comment by mailinglists35** [comment]
PS: You might want to pay attention to two fixes related to bookmarks, commited after the release of 0.6.5.6 that Ubuntu originally shipped with:

https://github.com/zfsonlinux/zfs/search?q=bookmark&type=Commits&utf8=%E2%9C%93

1. [Allow bookmark short name in 'zfs bookmark'](https://github.com/zfsonlinux/zfs/commit/587e228a6fcc03aa1135fda368666841dcb0e4c8)
````
This lets users create a bookmark from the command line by its name
only, without the need to specify the dataset path which is extacted
from the snapshot parameter.

These commands are now equivalent:

   zfs bookmark poolname/fs@snap poolname/fs#bookmark
   zfs bookmark @snap poolname/fs#bookmark
   zfs bookmark poolname/fs@snap \#bookmark_
````

2. [Documentation fixes for zfs(8) and 'zfs' binary](https://github.com/zfsonlinux/zfs/commit/038091fd4f8d24f308708987192065e55574bbe9)
````
* bookmarks are not supported when sending all intermediary snaps (-I)
* add missing compressed (-c) option to the 'zfs' help and manpage
````

**Comment by mailinglists35** [comment]
[one more note](https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSBookmarksWhatFor):

> Using bookmarks does require you to keep the previous snapshot on the destination (aka backup) filesystem, although the manpage only tells you this by implication. I believe that this implies that while you're receiving a new incremental, you may need extra space over and above what the current snapshot requires for space, since you won't be able to delete previous and recover its space until the incremental receive finishes. The relevant bit from the manpage is:
> 
> If an incremental stream is received, then the destination file system must already exist, and its most recent snapshot must match the incremental stream's source. [...]
> 
> This means that the destination filesystem must have a snapshot. This snapshot will and must match a bookmark made from it, since otherwise incremental send streams from bookmarks wouldn't work.

**Comment by mailinglists35** [comment]
on #68 you say
>  I'm blocking on this until bookmarks / resumable send and receive make it into mainstream ZoL (to wit, Ubuntu 16.04 Ubuntu repos)

centos already has packages for 0.7 release which includes bookmarks. why wait until ubuntu, and even unsure if ubuntu will have 0.7?
https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1734172?comments=all

**Comment by mailinglists35** [comment]
hi
next ubuntu LTS appears to include 0.7
https://launchpad.net/zfs

````
zfs-linux source package in Bionic
Version 0.7.5-1ubuntu13 uploaded on 2018-03-29
````

it would be awesome to be able to use bookmarks with syncoid.

**Comment by jimsalterjrs** [comment]
Correct, looks like 16.04 will never get it.  We are already in april of 18, so shortly after 18.04 actually releases I'll begin work on this. =)

**Comment by mailinglists35** [comment]
heh, better late than never.

I'm so anxious to see the first free public tool that makes use of bookmarks :)

**Comment by mailinglists35** [comment]
Hi, any news on this? 
Thanks

**Comment by mailinglists35** [comment]
@phreaker0 with bookmarks you can still sync two datasets even if you lost the common snapshot

**Comment by phreaker0** [comment]
@mailinglists35 
yeah, the main bookmark usage was clear to me. But I didn't know what you mean by syncoid should create bookmarks.  It makes no sense for the created/destroy "syncoid_..." snapshots, but maybe for all other intermediate snapshots (if there are replicated).

**Comment by mailinglists35** [comment]
@phreaker0 heh, I forgot for a moment that sanoid and other tools (zfs-auto-snapshot etc) are the ones responsible for point-in-time management, and that syncoid is just the synchronization tool. so the wish originally was to do both bookmark creation and bookmark fallback.

apparently the role of creating bookmarks should be done by the snapshot management tool, not by the synchronization tool.

nonetheless, the synchronization tool still does a temporary snapshot; what I had in mind when I filed this was that I thought syncoid could create harmless bookmarks (and leave them alone, as they are really harmless) for each automatic snapshot it creates in order to synchronize the datasets.
