### ISSUE TITLE
How to tell sanoid not to take snapshot while syncoid is running?

### ISSUE THREAD

**Issue by hth2** [jimsalterjrs/sanoid#897]
I am setting up a backup server as follows:
- run syncoid to replicate desired zvols from several hosts to the backup server
- run sanoid on the backup server to implement retention

The issue I am facing is that if sanoid takes a snapshot of a zvol being received by syncoid, then that zvol is broken. What would be  the recommended way to solve this? I am thinking of using the pre_snapshot_script to check and return 1 if syncoid is running.

**Comment by phreaker0** [comment]
If I understand correctly you want to create snapshots of your zvols on the receiving side, but those will be rolled back/deleted on the next replication. So what you want to do is not possible with ZFS.

Futhermore, the issues section is not for general questions but for issues regarding sanoid/syncoid. For other requests I suggest using:

- https://www.reddit.com/r/zfs/
- https://github.com/jimsalterjrs/sanoid/discussions

**Comment by hth2** [comment]
thanks for the answer, I find it helpful

**Comment by jimsalterjrs** [comment]
If anyone wants to look for answers on Reddit, they can, but I would **strongly** recommend https://discourse.practicalzfs.com/ (which I created, and operate) instead, either for generic ZFS questions and discussion or sanoid specific questions and discussion.
