### ISSUE TITLE
[question] Is syncoid inital offline sync possible?

### ISSUE THREAD

**Issue by cheretbe** [jimsalterjrs/sanoid#900]
Hi
I'm going to sync a huge dataset over the internet. Sending daily increments is going to be fine, but initial sync will take days. 
Is it possible somehow do initial sync using a file? Dump everything to a portable hard drive, move it to destination and restore there or something like that.

**Comment by phreaker0** [comment]
no, not with syncoid. For the initial sync you need to directly use zfs send for generating the initial replication stream and save it to a disk for later zfs receive at the target location.
