### ISSUE TITLE
Recursive setting cannot be enabled if trailing space present

### ISSUE THREAD

**Issue by nlflint** [jimsalterjrs/sanoid#901]
Problem:
My sanoid runs on a backup pool, with a backup template, but it's not pruning old snapshots.

My config:
```
[backup]
	use_template = backup
	recursive = yes 

[template_backup]
	autoprune = yes
	frequently = 0
	hourly = 6 
	daily = 7
	monthly = 6
	yearly = 0

	### don't take new snapshots - snapshots on backup
	### datasets are replicated in from source, not
	### generated locally
	autosnap = no

	### monitor hourlies and dailies, but don't warn or
	### crit until they're over 48h old, since replication
	### is typically daily only
	hourly_warn = 2880
	hourly_crit = 3600
	daily_warn = 48
	daily_crit = 60
```

Cause: **An extra "space" at the end of `recursive = yes `.** This extra space left the setting in its default value, so recursive wasn't set. A few things made this difficult for me to debug:

1. Debug output should explicitly show the value of the recursive flag but it does not. I had never used the debug output before and I looked for this flag at one point in my debugging, but it's not in the output. Someone more experienced could have noticed only 1 config and inferred the flag wasn't set, since the configs weren't unrolled. I had never used `--debug` before so I just saw 1 config and it matched what I wrote in the `sanoid.conf`, so it looked good.

2.  An unreadable value from the config should be a halting error. It should not be silently ignored.

**Comment by phreaker0** [comment]
@nlflint this is already fixed in master https://github.com/jimsalterjrs/sanoid/commit/7ab0ac0cf6bdc112b2b0a5a93f464892af66ca8a
