### ISSUE TITLE
My sanoid.conf is not being recognized.

### ISSUE THREAD

**Issue by d-tork** [jimsalterjrs/sanoid#908]
I created my config file to be much less active than the defaults: 
```
[cistern/backup]
        use_template = daily

[cistern/iso]
        use_template = rare

[cistern/media]
        use_template = daily

#############################
# templates below this line #
#############################
[template_daily]
        daily = 7
        monthly = 1
        autosnap = yes
        autoprune = yes

[template_rare]
        monthly = 1
        autosnap = yes
        autoprune = yes
```
But I still have about 40 hourly snapshots of each dataset, and 250 in total, which indicates that sanoid is still running the default config. The permissions on `/etc/sanoid/sanoid.conf` are the same as the defaults:
```
-rw-r--r-- 1 root root  584 Apr 15 13:10 sanoid.conf
-rw-r--r-- 1 root root 4685 Jul 18  2023 sanoid.defaults.conf
```
I am also using the systemd timer. It just occurred to me as I was writing this to try restarting the sanoid.service, but I don't think I will know if it worked until 15 minutes from now. I never saw anything about it in the documentation, so I doubt this will solve the problem. Any other ideas?

**Comment by phreaker0** [comment]
Not a sanoid issue. You didn't specify and hourly value therefore the defaults are uses from the default file.
