### ISSUE TITLE
[feature request / question] Auto-mount last snapshot done by sanoid

### ISSUE THREAD

**Issue by pbek** [jimsalterjrs/sanoid#917]
@jimsalterjrs, thank you for Sanoid and 2.5 Admins! 😉
I'm using Sanoid on NixOS to create ZFS auto-snapshots, which works great!

Is there by chance an easy way to automatically keep the last created Snapshot mounted to some directory to create consistent backups from that snapshot with e.g. rsync, restic (in my case), borg, ...?

**Comment by phreaker0** [comment]
@pbek yes, you can use the post_snapshot_script hook (https://github.com/jimsalterjrs/sanoid?tab=readme-ov-file#post_snapshot_script) for this.

**Comment by phreaker0** [comment]
yes. But you should also filter for SANOID_TARGETS if you snapshot more than one dataset to "select" the dataset for the mountpoint.

**Comment by pbek** [comment]
Thank you, that was something I wanted to ask... Is `post_snapshot_script` called for each target individually, each time with a different `SANOID_TARGETS` (that currently holds only one item)?

**Comment by phreaker0** [comment]
yes post_snapshot_script is called for each filesystem/volume individually.
I planned to implemented grouping of datasets for atomic snapshoting and in this case SANOID_TARGETS can have multiple datasets but currently only one item is possible.

**Comment by pbek** [comment]
Thank you very much!
