### ISSUE TITLE
--force-delete does not seem to delete datasets

### ISSUE THREAD

**Issue by Derkades** [jimsalterjrs/sanoid#932]
My command is:
```
syncoid --no-privilege-elevation --recursive --no-sync-snap --no-rollback --force-delete "root@host:pool" "backup/<local_dataset>"
```

For each snapshot, it prints a success message for each child dataset, and no warnings. However, datasets that have been deleted on the source, remain on the destination. This triggers warnings in my monitoring system, which checks the recency of snapshots on the target.

I have tested this using the latest master and 2.1.0.

**Comment by phreaker0** [comment]
"--force-delete" won't delete datasets which are not synced, from the readme:

> --force-delete
> 
> Remove target datasets recursively (WARNING: this will also affect child datasets with matching snapshots/bookmarks), if there are no matching snapshots/bookmarks. Also removes conflicting snapshots if the replication would fail because of a snapshot which has the same name between source and target but different contents.

**Comment by Derkades** [comment]
Thanks for the response, so I don't understand the wording in the readme. Does that mean datasets on the target are deleted only when the dataset exists on the source but has no matching snapshots? So not if the dataset is deleted at the source?

Is there any way to accomplish such a recursive sync using sanoid and syncoid, where datasets deleted on the source are also (eventually) deleted on the target?
