### ISSUE TITLE
Syncoid hangs on snapshot sync when using `pv`

### ISSUE THREAD

**Issue by djmixman** [jimsalterjrs/sanoid#943]
**Environment:**
- **OS:** FreeBSD 13.3
- **Sanoid Version:** 2.2.0
- **`pv` Version:** 1.8.10

**Description:**
When creating a new snapshot with Sanoid, attempting to sync that new snapshot with Syncoid causes the process to hang indefinitely. There are no error messages, and the process remains stalled without proceeding. I noticed this issue start within the last month or so.

**Steps to Reproduce:**
1. Create a new snapshot using Sanoid.
2. Attempt to sync the new snapshot using Syncoid with `pv` installed.

**Expected Behavior:**
Syncoid should successfully sync the new snapshot without hanging.

**Actual Behavior:**
Syncoid hangs indefinitely when it gets to the zfs send | recv stage when `pv` is used.

**Workaround:**
Renaming the `pv` executable to disable its use within Syncoid allows the sync process to complete successfully.

**Additional Information:**
- No error messages are provided during the hanging state.
- Disabling `pv` resolves the issue.
- I am unsure what else to check but wanted to report this so if others are having a similar issue they can chime in.

**Comment by phreaker0** [comment]
@djmixman seems to be a bug in pv 1.8.10 on FreeBSD, see https://codeberg.org/a-j-wood/pv/pulls/92 . It's fixed in 1.8.12.

**Comment by ryannathans** [comment]
Holy shit, I have been trying to work out why my snapshots (from dedup datasets only) hang while sending for weeks!

I fucked pv off for now, works!
