### ISSUE TITLE
syncoid deletes snapshots created by sanoid on the target

### ISSUE THREAD

**Issue by sonologic** [jimsalterjrs/sanoid#965]
I am using syncoid to backup a number of datasets from source to target. On the source, I have set up sanoid with the following config:

```
[zroot/var/spool/jails]
        use_template = production
        process_children_only = yes
        recursive = yes

[template_production]
        frequently = 4
        frequent_period = 15
        hourly = 6
        daily = 5
        monthly = 2
        yearly = 0
        autosnap = yes
        autoprune = yes
```

On the target I have sanoid configured as:

```
[extra/backup]
        use_template = backups
        process_children_only = yes
        recursive = yes

[template_backups]
        frequently = 0
        hourly = 0
        daily = 14
        monthly = 12
        yearly = 4
        autosnap = yes
        autoprune = yes
```

As can be seen, on the source I don't want to keep too many snapshots around, whereas on the target I'd like to keep a lot more.

However, each time I run syncoid as follows:

```
${syncoid} \
        --sshport ${remote_port} \
        -r --skip-parent --source-bwlimit=300m --compress=lz4 \
        root@${remote_host}:${source_dataset} ${target_dataset}
```

The snapshots created by sanoid on the target are destroyed.

Is there a way to set up things so that I can use different policies for auto snapshots on source and target?

I thought of setting `autosnap = no` on the target, and rely on snapshots from the source to be transferred over by syncoid, then have sanoid on the target prune them according to the policy, but then I would not get any yearly snapshots, or would I and would they just not have 'yearly' in the name?

**Comment by phreaker0** [comment]
@sonologic the behaviour you want is not possible with ZFS. In order for the replication (zfs send | zfs recv) to work, all changes on the target muss be rolled back. So you can't create snapshots on the target and keep them.

So this is the intended behaviour of syncoid (there is the --no-rollback option which would just abort in this case).

**Comment by sonologic** [comment]
Thanks for clarifying, this makes sense.

So is there no way to to keep snapshots around for longer on the target than they are kept on the source?

**Comment by phreaker0** [comment]
@sonologic sure. You can have a different pruning policy on the target/backup server. But the snapshots need to be created on the source.

**Comment by secabeen** [comment]
Note that there is no way to convert or change a snapshot type, so you need the source to take at least one of each type of snapshot you want to preserve.  In your example, you'll want to set `yearly = 1` on the source, and set `autosnap = no` on the target.  That should do what you want.  

Note that syncoid will transfer the frequently and hourly snapshots over to the target unless you explicitly exclude them, but they will be deleted on the next target sanoid run, so it's not that big a deal.

**Comment by sonologic** [comment]
@secabeen thanks, so if I want any yearly snapshots on the target, I will need to have a yearly snapshot on the source. Understood. Thanks both for your clarifications, much appreciated!
