### ISSUE TITLE
sanoid on Debian (Buster) requires zfs-dkms

### ISSUE THREAD

**Issue by HankB** [jimsalterjrs/sanoid#975]
When ZFS is installed directly from the OpenZFS repo, I can bypass DKMS. Installing `sanoid` pulls in `zfs-dkms` from the repo and conflicts with the other installation.

Is this really necessary? At present my desire is to run ZFS 0.8.6 on Debian Buster and with `sanoid` (though not necessarily the latest release)

I'm, open to suggestions on how best to do this. At present my thought is to fork `sanoid` and tweak the Debian build to eliminate that dependency. I will probably need to repeat the install a number of times so I'd like to streamline it as much as possible.

Thanks!

**Comment by jimsalterjrs** [comment]
There's no need to "build" it at all. It's a couple of Perl scripts.

Download the literal files sanoid and syncoid, drop them in /usr/local/bin, 
and Bob's your uncle. Then, `apt install pv mbuffer lzop 
libcapture-perl-tiny libconfig-inifiles-perl` and that should take care of 
all your dependencies.

There used to be hints in the comments at the head of each file on 
fulfilling dependencies manually, but those seem to have disappeared in 
some misguided "cleanup" or another. I'll have to see about putting those back.

**Comment by HankB** [comment]
Thank you, particularly for listing the other required packages.

**Comment by HankB** [comment]
Just a quick followup. I forked and deleted a single line to eliminate the ZFS requirements and the Debian package I build installs without conflicting with a non-DKMS/non packaged install. In addition to getting the scripts and all dependencies installed, it configures the Systemd timer and may do other things that Mr. Salter programmed to make the install frictionless. In the long run, this is going to be easier for me because I expect to do multiple installs during testing.

[fork](https://github.com/HankB/sanoid)
